### ISSUE TITLE
Editor - Exercise plugin does not display existing exercise text

### ISSUE THREAD

**Issue by edwoodward** [Connexions/webview#1005]
I derived OSC Sociology and dervied the 3rd Page, "What is Sociology?".  The Exercises are detectyed by the editor in the sense the plugin is there, but no text is displayed in the plugin.

Original Exercises
![screenshot from 2015-03-30 07 51 56](https://cloud.githubusercontent.com/assets/1394695/6896505/af0b98a2-d6b1-11e4-9bc5-9da4dfd423ac.png)

Exercises in Editor
![screenshot from 2015-03-30 07 52 41](https://cloud.githubusercontent.com/assets/1394695/6896516/c8224624-d6b1-11e4-8c82-5f523fd44ff7.png)

**Comment by amberwebb** [comment]
The text is not showing because the editor is looking for classes of 'problem' and 'solution', which are missing.

**Comment by edwoodward** [comment]
I'll create an issue on the transform.

**Comment by edwoodward** [comment]
Moved to https://github.com/Connexions/rhaptos.cnxmlutils/issues/126
