### ISSUE TITLE
Editor - Note Plugin not detecting Note Title

### ISSUE THREAD

**Issue by edwoodward** [Connexions/webview#1006]
I dervied OSC Sociology and then derived the 3rd Page, "What is Sociology?". The Note in the misddle of the Page is detected by the Plugin, but the title is in Plain text at the top of the Note.  it should be in the Title field of the Plugin.

Original Note
![screenshot from 2015-03-30 07 55 48](https://cloud.githubusercontent.com/assets/1394695/6896557/40c9951e-d6b2-11e4-86e0-f62049b6bd49.png)

Note in Editor
![screenshot from 2015-03-30 07 56 06](https://cloud.githubusercontent.com/assets/1394695/6896561/48a529f6-d6b2-11e4-8752-46a7322265f2.png)

**Comment by amberwebb** [comment]
This is missing the class 'title' but is also nested within the body of the note. The html that is returned for this plugin is not what the editor expects.

**Comment by edwoodward** [comment]
Can you document what is expected?

**Comment by amberwebb** [comment]
**Here is an example of a note that I added into the editor:**

https://gist.githubusercontent.com/amberwebb/f8128373b8c9de211371/raw/6251b9a545ef7e1bda2a812f4093191db2630a2e/gistfile1.html

**Here is what's being returned in the derived copy:**

https://gist.githubusercontent.com/amberwebb/3266d0e55924ddd09146/raw/25940e902dbfefea51f7e7c6ffc33a246b4ef8f3/gistfile1.html

The title div needs to be moved out of the main body of the note and class="title" added to the div. The title dropdown HTML is not in the derived note, although I'm not sure if that is a problem with the plugin or the transform.

**Comment by edwoodward** [comment]
Moved to https://github.com/Connexions/rhaptos.cnxmlutils/issues/127
