### ISSUE TITLE
Search is not searching by title unless explicitly using 'title' in search

### ISSUE THREAD

**Issue by amberwebb** [Connexions/webview#1021]
I searched for the book 'Understanding Basic Music Theory' in the search bar, not Advanced Search. No results were found. I had to search by 'title: "Understanding Basic Music Theory"' for the results to show. A user will not know to do that.

**Comment by dak** [comment]
@pumazi @reedstrm Is this an issue with archive/authoring?

**Comment by amberwebb** [comment]
I can search just by keywords though.

**Comment by amberwebb** [comment]
This is working on production.
