### ISSUE TITLE
Attribution - version is being added twice to attribution links

### ISSUE THREAD

**Issue by edwoodward** [Connexions/webview#1026]
The attribution links have the version twice which gives a 500 error

http://cnx.org/contents/031da8d3-b525-429c-80cf-6c8ed997733a@8.34@8.34

**Comment by amberwebb** [comment]
This is fixed in dev and beta.

**Comment by edwoodward** [comment]
I see that, but when you toggle between book and page, the URL stays the 
same.  it should change from the Book URL to the Page URL.
