### ISSUE TITLE
Searching by keywords and key phrases

### ISSUE THREAD

**Issue by amberwebb** [Connexions/webview#1029]
In Advanced Search, I searched with the following keywords: 'flats, fifths'. I removed 'fifths' and no results were returned for 'flats,' because of the comma. Shouldn't search ignore the comma?

I also searched with the key phrase 'key signature' and search treated them like separate keywords. Maybe we should allow users to enter comma separated keywords and key phrases. So as an example a user could search with 'flats, fifths, key signature'. That way of searching keywords/phrases is more intuitive and could return a more accurate search result.

**Comment by RoyEJohnson** [comment]
Search now finds occurrences of "flat" when searching for "flats," so I think the bug portion of this is addressed.
