### ISSUE TITLE
Should return message if there are too many search results

### ISSUE THREAD

**Issue by amberwebb** [Connexions/webview#1032]
On cnx.org, I did an advanced search by subject Humanities and type Page. After the results were returned, I removed the subject and webview started a new search based on pages. I killed the search after 1.7 minutes. Nothing was returned. There are too many pages to return results in a sane amount of time. We should return a message for narrowing down search results in a case like this.

**Comment by RoyEJohnson** [comment]
http://archive.cnx.org/search?q=type:page
runs for minutes and eventually returns Service Unavailable. We've got several options:
- The back end can return a "too many results" message
- The back end can return a partial list after it finds a reasonable number or has spent a reasonable time
- We can pass a time limit or result number limit to the back end (requires change in API)
- We can require "sensible" parameters, meaning at least something besides Type

**Comment by edwoodward** [comment]
I vote for requiring additional parameters.

**Comment by edwoodward** [comment]
With the new index, this is no longer an issue. Closing
