### ISSUE TITLE
Print styles should be listed server-side?

### ISSUE THREAD

**Issue by pumazi** [Connexions/webview#1045]
I noticed that the print-styles are hardcoded into the metadata.coffee I also recently noticed a PR that included a change to them in a one of the legacy products. So these probably need to be stored and retrieved server-side, yeah?

**Comment by amberwebb** [comment]
I don't know. @edwoodward @reedstrm  what do you think?

**Comment by reedstrm** [comment]
Yes, they should. In fact, they should be probably be part of '/extras'. I think the existing 'tags' table could handle them, with a new 'schema' name.
