### ISSUE TITLE
Table Title Styling Request

### ISSUE THREAD

**Issue by openstaxalina** [Connexions/webview#1070]
W&N has requested that the "Section Key Terms" table title display above the table in web view for High School Physics.  The Section Key Terms tables have the following classes on them: 

unnumbered
key-­terms
ost-­reading-­discard

Here is a screenshot of how the table/title currently display: 
![screen shot 2015-05-12 at 9 26 31 am](https://cloud.githubusercontent.com/assets/7863733/7589581/0bfe86de-f889-11e4-9c7d-464f6ed7c77f.png)

If you need more information or would like to discuss, please contact me or Alana.  Thank you!

**Comment by edwoodward** [comment]
We generally do not do specific book styling. The main reason is that 
the content can be used in a different book (derived or just used in a 
user created book) and the styling would be inconsistent in that book.

**Comment by edwoodward** [comment]
Closing since this has not gone into further discussion in 2 years
