### ISSUE TITLE
Indent and Outdent do not work

### ISSUE THREAD

**Issue by amberwebb** [Connexions/webview#1075]
Indent and outdent icons do nothing.

**Comment by edwoodward** [comment]
Is this on beta? Is it an install issue or they just don't work?

**Comment by amberwebb** [comment]
This is on beta.

**Comment by amberwebb** [comment]
@ew2 I can confirm that indent and outdent do work in the editor on beta. I've tested it with unordered and ordered lists. Closing this issue.
