### ISSUE TITLE
Problem with Images on Rewrite Web View

### ISSUE THREAD

**Issue by nyxer95** [Connexions/webview#1087]
We have a problem with legacy web view. In Chemistry, nest images do not have any size constraints so they are being cut off on rewrite.

![image](https://cloud.githubusercontent.com/assets/6640738/7964089/a598ea60-09db-11e5-8f65-68ac8b9bf5b5.png)

**Rewrite:**
https://cnx.org/contents/85abf193-2bd2-4908-8563-90b8a7ac8df6@9.49:86/Chemistry
![image](https://cloud.githubusercontent.com/assets/6640738/7963863/717a7f4c-09da-11e5-99f1-0142d3f777a4.png)

**Legacy:**
https://legacy.cnx.org/content/m51118/1.4/?collection=col11760/1.9&legacy=true
![image](https://cloud.githubusercontent.com/assets/6640738/7963924/cd355dac-09da-11e5-959e-9e8512fa9367.png)

**Comment by dak** [comment]
Adding a `max-width: 100%;` to all images would probably be safe and would fix this issue.

**Comment by reedstrm** [comment]
@Dak - we've got a @max-wdith in there, just for some reason it's not applying in some contexts (nested inside an example, in this case) Need to see what's overriding it.

**Comment by dak** [comment]
@reedstrm It looks like the `max-width` is only being applied to an `img` inside a `figure` tag, whereas the above images are in a `span[data-type="media"]`.

**Comment by reedstrm** [comment]
Ah that makes sense - @alana and @alina has said something about it having to do non-figure images

**Comment by oscryan** [comment]
still looks pretty big on textbook-qa at http://legacy-textbook-qa.cnx.org/content/m51057/1.4/?collection=col11760/latest

You can scroll right and see the whole image, but it is still much bigger than the browser window

![screen shot 2015-06-04 at 10 50 44 am](https://cloud.githubusercontent.com/assets/1895432/7988155/88d11782-0aa7-11e5-908a-946059a76281.png)

**Comment by amberwebb** [comment]
@reedstrm The image style change needs to be added to legacy as well to fix the issue @oscryan mentioned. Who can update that?

**Comment by reedstrm** [comment]
@oscryan that needs to be a diff issue, against something in rhaptos. It's less urgent, since the content is there.
