### ISSUE TITLE
Author names are not in the same order as on Legacy

### ISSUE THREAD

**Issue by edwoodward** [Connexions/webview#1096]
This was reported by user in [Trac ticket 13213](https://trac.cnx.org/ticket/13213)

The order of the authors is different between legacy and rewrite. it could be a display issue or a data issue.

legacy: https://legacy.cnx.org/content/col11569/latest/

Rewrite: http://cnx.org/contents/db89c8f8-a27c-4685-ad2a-19d11a2a7e2e@21.1:1/Principles_of_Biology

**Comment by amberwebb** [comment]
Webview is displaying the authors in the order they are returned in the JSON.

**Comment by amberwebb** [comment]
Moved issue to archive. https://github.com/Connexions/cnx-archive/issues/335
