### ISSUE TITLE
New Feature => Hint Function (Duplication of "Click to Reveal")

### ISSUE THREAD

**Issue by nyxer95** [Connexions/webview#1097]
W&N has requested a new feature for Web View... 

Web-only “Click to Reveal” HINT function. Duplication of “click to reveal” solution function.

**Comment by jdoehnert** [comment]
As it relates to the PDF- the hint should be suppressed there.  It will only appear on the web view in a "click to reveal" setting.

**Comment by InconceivableVizzini** [comment]
Production mini-scrum feedback: Need a content example/link to show what they want it to look like on web.

**Comment by openstaxalina** [comment]
Tiny bit more info from Lisa @ W&N: "We don’t need the hint to collate anywhere. It would just be a click to reveal sentence or two that is masked in the PDF."

**Comment by openstaxalina** [comment]
One concern as discussed with @kathi-fletcher is that this would create a further difference between web view and PDF. cc: @InconceivableVizzini
