### ISSUE TITLE
Editor - Superscript Bug

### ISSUE THREAD

**Issue by eyg1** [Connexions/webview#1107]
Typing a term and adding a superscript does not allow you to type regularly afterwards:
![screen shot 2015-06-24 at 1 41 31 pm](https://cloud.githubusercontent.com/assets/12498368/8339325/34e2cf00-1a7c-11e5-8dbd-d211e2c7c8ad.png)

However, typing the entire phrase and then adding the superscript maintains formatting. 

![screen shot 2015-06-24 at 2 00 55 pm](https://cloud.githubusercontent.com/assets/12498368/8339500/88c320a6-1a7d-11e5-8eeb-5c73fb19eef8.png)

**Comment by edwoodward** [comment]
Please mark editor issues with Editor- in the title. This makes for easy identification later on.

**Comment by amberwebb** [comment]
This isn't necessarily a bug. Once you highlight the text you do not want superscripted and deselect the superscript icon you can type text regularly. I do see how this can be cumbersome. This is a usability issue that we can look into.
