### ISSUE TITLE
Editor--Underlining Issue

### ISSUE THREAD

**Issue by brittweinstein** [Connexions/webview#1108]
I'm not able to underline something, then create text that is not underlined following that. 
![screen shot 2015-06-24 at 4 06 51 pm](https://cloud.githubusercontent.com/assets/12631203/8341518/1010b50c-1a8b-11e5-86e9-09194d35470a.png)

I have a video, if you'd like me to email it to you--so you can watch as it happens.

**Comment by amberwebb** [comment]
I think this is expected behavior until you deselect the underline icon and works the same way in other WYSIWYG editors. Please see this as an example. http://www.tinymce.com/tryit/full.php
