### ISSUE TITLE
Editor - more list options

### ISSUE THREAD

**Issue by edwoodward** [Connexions/webview#1110]
From DMS testing

Need options to number using lowercase Roman numerals: i, ii, iii, iv

**Comment by amberwebb** [comment]
Would it also be helpful to have a way to number lists a,b,c, etc...? Maybe we can extend the ordered list plugin to include an option to choose list-style-type.

**Comment by edwoodward** [comment]
Legacy allows for different styles of lists. It would be good to have 
some of that. Some of Legacy's options are never used, like pilcrow. We 
should not implement those.
