### ISSUE TITLE
Can't edit featured books w/ Creative Commons Attribute 2.0 Licenses on dev

### ISSUE THREAD

**Issue by cburk** [Connexions/webview#1114]
On dev, trying to create an editable copy on featured books such as:

http://dev.cnx.org/contents/778e36af-4c21-4ef7-9c02-dae860eb7d14@9.71:1/Fundamentals-of-Electrical-Eng (CCAL version 1.0)

and

http://dev.cnx.org/contents/2ad74b7b-a72f-42a9-a31b-7e75542e54bd@3.74:1/Understanding-Basic-Music-Theo (CCAL version 2.0)

results in Internal Server Error 500.  Books w/ licenses of 3.0 or 4.0 seem unaffected.

Update: Non-featured books and pages seem to have this problem as well, as:
http://dev.cnx.org/contents/fef42655-1bdd-46cc-9610-a8118614894b@3/Guitar-Lesson-11:-Tied-Notes-a (CCAL version 2.0) has the same issue

**Comment by amberwebb** [comment]
This will be fixed as soon with cnx-authoring license upgrade. https://github.com/Connexions/cnx-authoring/issues/227
https://trello.com/c/lZmidAMm/1294-auto-upgrade-license-on-derived-copy
