### ISSUE TITLE
Editor - attributes on a paragraph are being added to subsequent paragraphs

### ISSUE THREAD

**Issue by edwoodward** [Connexions/webview#1146]
I was testing the data- change on dev.cnx.org. I created a module on legacydev.cnx.org and added a data: attribute to the lone paragraph and published. I then edited it on dev.cnx.org. I hit enter and added another paragraph and published. The resulting CNXML has the data- attribute on both paragraphs. It is not possible to add the attribute via the new editor so either the editor or the transform added it. I went back the dev.cnx.org and edited the page again. I added another paragraph and viewed the source. The new paragraph had the data- attribute.

Ross ran a test which added a note and then a new paragraph. His paragraph after the note did not have the data- attribute. It could be that hitting enter is cloning the previous paragraph.

Ed's legacydev module source - https://legacydev.cnx.org/content/m54559/latest/source
Ed's dev.cnx.org page -  http://dev.cnx.org/contents/8b519e09-8cc5-4bc2-ac25-3f5b867266c6/data--test
Ross's test module - https://legacydev.cnx.org/content/m54560/1.1/source

**Comment by amberwebb** [comment]
I can recreate this bug. It may be because of `contenteditable` attribute. http://www.w3.org/TR/2008/WD-html5-20080610/editing.html#contenteditable-breakBlock
