### ISSUE TITLE
Equations should be numbered by default

### ISSUE THREAD

**Issue by edwoodward** [Connexions/webview#1148]
Equations should be numbered by default. The numbering is on the right of the equation.

Equations on Legacy: https://legacy.cnx.org/content/m45096/1.4/?collection=col11454/1.5&legacy=true
![screenshot from 2015-08-05 13 41 50](https://cloud.githubusercontent.com/assets/1394695/9094567/3b331d8e-3b78-11e5-9249-91a2b7e6b798.png)

Same equations on rewrite: http://cnx.org/contents/f5083cb8-fe5e-4287-9717-293e1315d000@4/Introduction-to-Wavelets
![screenshot from 2015-08-05 13 43 30](https://cloud.githubusercontent.com/assets/1394695/9094589/55ae972e-3b78-11e5-945d-36a3177a451b.png)

**Comment by RoyEJohnson** [comment]
I have written code to do this. It numbers the equations on a page from 1 to whatever. 
Branch is https://github.com/Connexions/webview/tree/equation-numbering

**Comment by openstaxalina** [comment]
Has this been fixed with recipes?

**Comment by helenemccarron** [comment]
This should be the case, equations are handled via the recipes.
![2018-06-18_13-00-22](https://user-images.githubusercontent.com/8514591/41553522-a046f8da-72f7-11e8-8acc-e79b671925ce.png)

**Comment by helenemccarron** [comment]
Styling will be addressed in https://github.com/Connexions/webview/issues/1652

**Comment by Stackblocks** [comment]
Displaying as specified with updated version of content / code.

![image](https://user-images.githubusercontent.com/12678235/41624659-0d1d682e-73dc-11e8-92bb-4a8252fbb675.png)
