### ISSUE TITLE
Editbar is in published content

### ISSUE THREAD

**Issue by edwoodward** [Connexions/webview#1159]
I noticed this when doing testing on alpha.cnx.org, but confirmed the same problem is on production. At the bottom of content is a div element for the editbar. This should not be a part of published content.

![screenshot from 2015-08-26 10 40 09](https://cloud.githubusercontent.com/assets/1394695/9498339/ea057f5c-4bde-11e5-84ff-6ebf2cb24b44.png)

If you refresh the page, the div goes away.

**Comment by amberwebb** [comment]
@edwoodward Can you please provide a link to the content?

**Comment by edwoodward** [comment]
Will do when I am in the office later today. I was able to see the editbar on random content on alpha and production.
On Aug 27, 2015 7:26 AM, Amber Michelle Webb <notifications@github.com> wrote:@edwoodward Can you please provide a link to the content?

—Reply to this email directly or view it on GitHub.


  
  





!DSPAM:1106,55df01ff281551131879455!

**Comment by amberwebb** [comment]
@edwoodward NM about the link, I can confirm what you are seeing. The empty editbar div isn't actually in the published content, it's apart of the template that's being rendered. `src/scripts/modules/media/media-template.html`. When content is being edited, the toolbar is appended to this div. I don't think this is an actual bug.

**Comment by RoyEJohnson** [comment]
Concur: it's part of the template and the module cannot know going in whether it will be needed. Recommend closing.
