### ISSUE TITLE
License Page Styling

### ISSUE THREAD

**Issue by dak** [Connexions/webview#1171]
- [ ] Determine if definition lists are the best elements to use for a FAQ
- [ ] Update the styling for the definition lists to match the H1/H2/H3 styling on the rest of the site, or change the elements to headers.

**Comment by RoyEJohnson** [comment]
I've updated the same branch I was working on before. Is that the right approach?

**Comment by edwoodward** [comment]
You should create a new branch.

**Comment by dak** [comment]
Fixed in #1172
