### ISSUE TITLE
Accessibility - tabbing changes do not  work in Safari and Firefox

### ISSUE THREAD

**Issue by edwoodward** [Connexions/webview#1188]
We made some accessibility changes that allowed users to tab between features on the page. None of those are working in Safari or Firefox on my Mac. They work fine in Firefox and Chrome in Ubuntu. 

I am using OSX 10.8.5

**Comment by RoyEJohnson** [comment]
The Mac is set up by default to, um, disable accessibility. Instructions
for enabling keyboard navigation for both browsers here:
http://www.456bereastreet.com/archive/200906/enabling_keyboard_navigation_in_mac_os_x_web_browsers/

On Thu, Sep 17, 2015 at 3:18 PM, Ed Woodward <notifications@github.com>
wrote:

> We made some accessibility changes that allowed users to tab between
> features on the page. None of those are working in Safari or Firefox on my
> Mac. They work fine in Firefox and Chrome in Ubuntu.
>
> I am using OSX 10.8.5
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Connexions/webview/issues/1188>.
>



-- 
Roy Johnson
Javascript Developer
OpenStaxx
