### ISSUE TITLE
Editor - Images are not getting mime-type

### ISSUE THREAD

**Issue by edwoodward** [Connexions/webview#1201]
This problem may not be editor related.

If an image is added to a Page and the page published, the mime-type attribute is empty. This is causing PDF generation in Latex to fail  to add the image to the PDF.

The Page linked below does not have a mime-type in the HTML and in the CNXML the mime-type is empty.

Rewrite - http://demo.cnx.org/contents/5ed248cf-ffe6-4d17-b168-ea6d9d0a9fe3@1/PDF-Image-Test

Legacy - http://qa.cnx.org/content/m57448/latest/source

The image plugin or Authoring should be adding the mime-type to the image. It could be that it is being added and is lost in publishing.

**Comment by reedstrm** [comment]
fixed in https://github.com/oerpub/Aloha-Editor/pull/226
