### ISSUE TITLE
Should add Apple Touch Icons to Site

### ISSUE THREAD

**Issue by edwoodward** [Connexions/webview#1205]
There are multiple (150+) 404 errors each week in the Varnish logs for Apple touch icons. These icons are used when a user bookmarks our site or adds it to the home screen. The user does not see an error, but we should eliminate the 404s

404 http://cnx.org/apple-touch-icon-precomposed.png
404 http://cnx.org/apple-touch-icon.png

See this blog post for detailed information: https://mathiasbynens.be/notes/touch-icons

**Comment by cburk** [comment]
Alright, I think the code in this branch should fix the issue
https://github.com/Connexions/webview/tree/touch-icons

**Comment by edwoodward** [comment]
Can you do a pull request?

Thanks,
Ed

**Comment by openstaxalina** [comment]
resolved with above PR; closing
