### ISSUE TITLE
Short URLs - History is incorrect after clicking on a link in content

### ISSUE THREAD

**Issue by edwoodward** [Connexions/webview#1231]
* Go to http://dev.cnx.org/contents/Ax2o07Ul@9.4:_H3EiPTs@4/Displacement
 * Find a link under the Title "Displacement" for "Physical Qualities and Units". 
 * Click the Back button on the browser. It does not take you back to Displacement, but to the Page before Physical Qualities and Units.

**Comment by RoyEJohnson** [comment]
Tested today on Mac using Chrome, Firefox, and Safari, and all three behaved as expected.
