### ISSUE TITLE
Music plays automatically on this page

### ISSUE THREAD

**Issue by edwoodward** [Connexions/webview#1235]
Music plays when viewing this page in Chrome on Windows and Linux.

http://alpha.cnx.org/contents/HAMMvtlJ@1.4:TpiMt77U@4/Dimensions-of-Music

Legacy plays as well.
http://qa.cnx.org/content/m22649/1.4/?collection=col10697/1.1&legacy=true

This could be a content issue, but creating issue so we can look into it.

**Comment by openstaxalina** [comment]
music does not play now when visiting the page on qa.cnx.org.  closing
