### ISSUE TITLE
Editor - Missing image is not detected, so cannot be removed in editor

### ISSUE THREAD

**Issue by edwoodward** [Connexions/webview#1238]
This could be a transform error, but putting it here for now.

Some of the Rice University Press books have the Rice logo removed. It displays as a broken image in the content. When opened in the editor, the broken image displays as a box, but it cannot be edited or removed. It is possible to make the box larger and smaller, but nothing else.

Example
http://alpha.cnx.org/contents/OPolDtlN@1.6:TKP6mAli@6/Blakes-Body-Marcia-Brennan-and

**Comment by RoyEJohnson** [comment]
The image url is http://rup.rice.edu/flowering-buybutton.jpg, which is no longer there. Looks like maybe RUP doesn't handle the book any more.

**Comment by edwoodward** [comment]
RUP no longer exists so no logo. Regardless, the editor should detect 
the image and allow removal.
