### ISSUE TITLE
Concept Coach - Header is too tall on demo and alpha

### ISSUE THREAD

**Issue by edwoodward** [Connexions/webview#1270]
The spacing in the header is taller on demo and alpha than is it on dev.

Dev header
![screenshot from 2015-12-03 08 11 02](https://cloud.githubusercontent.com/assets/1394695/11562735/7c164986-9995-11e5-90cd-550cd987cd6d.png)

alpha header
![screenshot from 2015-12-03 08 11 24](https://cloud.githubusercontent.com/assets/1394695/11562745/87b62b1c-9995-11e5-80bd-080ec0dec94c.png)

**Comment by RoyEJohnson** [comment]
Looks like some css, namely modules/header/header.less is different there than on dev.
![screen shot 2015-12-03 at 9 21 47 am](https://cloud.githubusercontent.com/assets/7315241/11564541/5d4dc236-999f-11e5-898e-d7d01a186de3.png)
![screen shot 2015-12-03 at 9 21 59 am](https://cloud.githubusercontent.com/assets/7315241/11564540/5d4cf3f6-999f-11e5-878d-aa1385d96c69.png)

**Comment by RoyEJohnson** [comment]
I wasn't seeing this on my local install, but I am now. It looks like it's not-our CSS overriding ours for the "page-header" class.

**Comment by RoyEJohnson** [comment]
Looks like our brand-primary color has gone from green to orange.

**Comment by RoyEJohnson** [comment]
Amanda fixed it.
