### ISSUE TITLE
Figure number is left justified when there is no caption

### ISSUE THREAD

**Issue by edwoodward** [Connexions/webview#1356]
When a figure does not have a caption, the numbering is left justified which looks incorrect. For examples, see http://cnx.org/contents/SlHEEDcW@20/Adding-Multimedia-to-Your-Conn

**Figure without a caption**
![screenshot from 2016-01-26 08 12 44](https://cloud.githubusercontent.com/assets/1394695/12582748/9e7b45a0-c404-11e5-95f3-4aa2ddfa27fd.png)

**Figure with a caption**
![screenshot from 2016-01-26 08 13 50](https://cloud.githubusercontent.com/assets/1394695/12582791/cbb13b4c-c404-11e5-98dd-eb8eef5c6eae.png)

**Comment by RoyEJohnson** [comment]
I have put in a pull request that treats non-caption figure labels the same as captioned ones, so they're centered under the image regardless. Is that the desired behavior?

**Comment by RoyEJohnson** [comment]
Somewhat bizarrely, the PDF has almost the opposite layout.

![screen shot 2016-01-26 at 9 57 00 am](https://cloud.githubusercontent.com/assets/7315241/12585801/36367410-c413-11e5-92fa-08614700b378.png)
![screen shot 2016-01-26 at 9 57 12 am](https://cloud.githubusercontent.com/assets/7315241/12585802/36397c78-c413-11e5-8d19-2ddb21b0900d.png)

**Comment by edwoodward** [comment]
I think so.
