### ISSUE TITLE
Weird floating scrollbar from sidebar

### ISSUE THREAD

**Issue by pandafulmanda** [Connexions/webview#1359]
![screen shot 2016-01-26 at 8 23 35 pm](https://cloud.githubusercontent.com/assets/2483873/12601967/34a90c68-c46b-11e5-9a96-e11320fc54a7.png)

Happens after you open and close sidebar
I am unsure if this is only for the latest Chrome?

**Comment by RoyEJohnson** [comment]
Not on PC (Chrome 47 or 48.0.2564.82 m).

**Comment by pandafulmanda** [comment]
appears to only happen with latest chrome?  or in situations where the toc is in the pinned state -- the content has been scrolled to hide the top menu
