### ISSUE TITLE
Wrapped anchor text is not scrolled to correctly

### ISSUE THREAD

**Issue by edwoodward** [Connexions/webview#1367]
In this Page

http://cnx.org/contents/p8e91Qcm@6/Itse1359-1420-Understanding-se#Class_methods_versus_instance_methods

Click on any of  the links at the top of the page. The scrolling behavior is as expected the first time. Any other time, it scrolls beyond the title.

**Comment by edwoodward** [comment]
Looking at the same content in Firefox, fixing the wrapping does not solve the scroll location. It did fix it in Chrome. I might not be editing correctly in Firebug which might also be a factor.

**Comment by RoyEJohnson** [comment]
Extra weirdness: Initially, it scrolls beyond the title. Scroll up to the top, click a different link, then scroll back up and click the problem link, and it works. Clicking the problem link multiple times does not fix it, but clicking a different link and then the problem link worked for me in Firefox, Safari, and Chrome.

**Comment by RoyEJohnson** [comment]
This fix is languishing.

**Comment by edwoodward** [comment]
I noticed it earlier in the week. I was waiting on today's rollout 
before getting someone to merge it. Once  they roll out the Ask Us 
button fix, we can merge it.

Ed
