### ISSUE TITLE
 Improve mobile view of content on http://cnx.org

### ISSUE THREAD

**Issue by reedstrm** [Connexions/webview#1393]
- **Urgency:**           medium
- **Expected Due Date:** 8/20/2016
- **Type of Request:**   Feature
- **Requestor:**         @reedstrm 
### Explain reason for due date

We expect to rollout changes (CTE) that will 
bring out PDF and web formats in better alignment by the beginning of the 
summer. This has been seen as a major hurdle for use of the website by 
students in classes that have adopted one of our books. With that barrier 
removed, the difficulty in using the site on mobile will likely become the 
next major stumbling block.
### Description

While the top of page/ header is some what "responsive", with 
the
new header structure with the TOC on the side and an in book search box,
I've seen the top take between 1/4 and 1/3 of the available screen reading 
space. This needs revisiting with some UX design thought. Comparable book 
readers usually go into a "low distraction" mode, with just the text 
visible. We could do something similar, probably collapse the entire top 
into a hamburger menu, or 'left swipe" area, and accept swipes to navigate 
between pages.
### Who is the audience for this and what is the impact on them?

All of our 
students who ever use the website. Our mobile usage is increasing, both in 
absolute number and percentage of visitors. (Ed has the numbers)
### What happens if it is not done?

Students leave, not using the website. 
We lose the opportunity to know who is using the content, as well as the 
additional, interactive features that do not work in other formats. Worst 
case, they move to other sites, rather than to our other formats.

**Comment by openstaxalina** [comment]
Addressed with https://github.com/Connexions/webview/pull/1628, closing
