### ISSUE TITLE
Link to a figure in another page does not land on correct location

### ISSUE THREAD

**Issue by edwoodward** [Connexions/webview#1408]
from Richard Baldwin

Please go to http://cnx.org/contents/5sRB9gpG@5.3:GHIZVlcF@2/Json0220-Decoding-JSON-Strings

Scroll down to the sentence beneath Figure 1.

Click on the link to Figure 1 in the sentence that reads:

The contents of the JSON strings for this same data were displayed in Figure 1 of the earlier page titled Json0215: Encoding JSON Strings . 

Note that control doesn't land where it should on the target page. It should land at the top of Figure 1 on that page but it lands further down the page.

This is the case in both Firefox and Google Chrome.

**Comment by reedstrm** [comment]
I see this one landing correctly: it positions 'Figure 1' (the label) directly below the page header.
