### ISSUE TITLE
Link to an anchor from composite page

### ISSUE THREAD

**Issue by helenemccarron** [Connexions/webview#1450]
When targeting an anchor on a composite page, the links doesn't take you to the anchor itself but to the top of the page.

For example, clicking on ex. 4 in chapter 4 takes you to the top of the answer key page and not to the chapter 4 exercise 4 anchor (lower on the page).
http://cte-cnx-dev.cnx.org/contents/aWGdK2jw@11.330:S_xJI5Er@1/Self-Check-Questions

The url is correct and loads correctly on page reload.

**Comment by kerwinso** [comment]
Also see https://trello.com/c/HTRKJnP1/131-bug-cannot-link-to-id-in-webview, currently in progress.

**Comment by openstaxalina** [comment]
This was fixed with the Trello card Kerwin referenced above.  closing
