### ISSUE TITLE
Android App Link on legacy.cnx.org give a 404 error

### ISSUE THREAD

**Issue by chouston31** [Connexions/webview#1475]
If you click on the android app link on http://legacy.cnx.org/   you get redirected to a 404 error on cnx.org
<img width="1280" alt="screen shot 2016-12-09 at 11 01 34 am" src="https://cloud.githubusercontent.com/assets/17411988/21058438/8f87ae7c-be03-11e6-9634-aca600ae2357.png">
<img width="1147" alt="screen shot 2016-12-09 at 11 02 05 am" src="https://cloud.githubusercontent.com/assets/17411988/21058446/957b3a24-be03-11e6-8634-950888eae385.png">

@edwoodward

**Comment by edwoodward** [comment]
Fixed in https://github.com/Rhaptos/Products.CNXPloneSite/pull/3

**Comment by Stackblocks** [comment]
Now navigates correctly to https://play.google.com/store/apps/details?id=org.cnx.android
