### ISSUE TITLE
Book/page author displayed as TAKE() on dev

### ISSUE THREAD

**Issue by kerwinso** [Connexions/webview#1553]
Go to any book on dev.cnx.org, e.g. Biology: https://dev.cnx.org/contents/GFy_h8cu@10.61:fVAf83sY@12/Preface-to-Biology

Look at the `Book by:` and `Page by:` attributions near the top right of the page. The author is listed as `TAKE()`. There is also a pipe character `|` pre-pended to the attribution string.

Dev (left) compared to production (right):

![image](https://user-images.githubusercontent.com/11298165/27055077-d8462960-4f88-11e7-8afe-9c10e1b53477.png)

**Comment by reedstrm** [comment]
Took this to Katalyst, they recommend pinning to l20n v < 5 I thought @phil had a PR for that, but I can't find it.

**Comment by kerwinso** [comment]
@reedstrm I noticed this problem on tea.cnx.org as well. I'm concerned this bug will make it into the final deployment. Should this be a requirement for assignable webview?

**Comment by reedstrm** [comment]
@kerwin it's a fairly simple deployment issue. We just need to pin the version of a dependency.

**Comment by philschatz** [comment]
Something like https://github.com/Connexions/webview/commit/c8c79299512c6c67ffa4f89f4526dc544b5db31d . I'll make a PR
