### ISSUE TITLE
User thinks they need to pay for a book when "Download for Free" is greyed out

### ISSUE THREAD

**Issue by pumazi** [Connexions/webview#1588]
## The problem as reported
A student/user believes they need to pay for "Introduction to Sociology" after having clicked to [download the PDF](https://cnx.org/donate/download/afe4332a-c97f-4fc4-be27-4e4d384a32d8@7.23/pdf). This is because the "Download for Free" button is not active right away when the user navigates to the page.

## Acceptance Criteria
-"Download for Free" button loads when the page does (current behavior)
-"Download for Free" button never appears greyed out (new behavior)
-"Download for Free" button is always dark blue with white text, and clickable.

## Notes

The original reporter of this issue comes via Bonne Brown. Please get in touch with her if you need to followup with the originating user.

**Comment by pumazi** [comment]
Technically, the "Download for Free" button becomes active after 5-8 seconds. But that's like an eternity today. 

My suggestion would be to **make the button active but less prominent**. This is similar to what sites do with ads before you are able to see an article.

**Comment by kerwinso** [comment]
Related Trello card: https://trello.com/c/yMAkLZOI/133-user-thinks-they-need-to-pay-for-a-book-when-download-for-free-is-greyed-out

**Comment by edwoodward** [comment]
Since the PDF is now downloaded directly without going to the donation page, this is no longer needed. Closing.
