### ISSUE TITLE
Collapse header on mobile when scrolling on mobile

### ISSUE THREAD

**Issue by reedstrm** [Connexions/webview#1589]
We desperately need to collapse the header on scrolling  - it currently takes 1/4 - 1/2 the screen!

**Comment by kerwinso** [comment]
I think this is a related Trello card: https://trello.com/c/u4pwBB64/178-the-title-toc-and-search-bar-banner-on-top-of-each-book-is-too-intrusive

**Comment by openstaxalina** [comment]
yep, this is done
