### ISSUE TITLE
Notes with @type have unstyled labels

### ISSUE THREAD

**Issue by aiwenar** [Connexions/webview#1591]
Compare those `<note type="warning">` and `<note class="check-understanding">`:

![spectacle t26340](https://user-images.githubusercontent.com/385442/35150787-fb8407ee-fd1b-11e7-8596-cbc6331f5d74.png)

**Comment by reedstrm** [comment]
Fixed, and deployed:

https://cnx.org/contents/TqqPA4io@1.1:ATZlJC9S@4/41-Przemieszczenie-i-prdko#eip-654
![screenshot from 2018-02-06 09-05-05](https://user-images.githubusercontent.com/253212/35866523-0499887c-0b1d-11e8-95bf-819c26e4665a.png)

**Comment by aiwenar** [comment]
As we discussed with @reedstrm some 9 months ago (of course I forgot about it, of course) this was closed by mistake. The screenshot @reedstrm posted presents my workaround for Connexions/cnx-recipes#375, and is related to translation of titles (i.e. _warning_ instead of _ostrzeżenie_). This issue is actually about _styling_ of notes.

**Comment by openstaxalina** [comment]
Although this issue is in webview, it's likely related to cnxml --> html transforms.

**Comment by openstaxalina** [comment]
**Decision:** Content changes will be made, then we will assess if webview changes are required.

**Comment by PatBoj** [comment]
Verified on webview:
![image](https://user-images.githubusercontent.com/20907906/46276206-a4aa7680-c55f-11e8-8c3c-c3e3ade3f232.png)
