### ISSUE TITLE
Unwanted markup in page attribution tab

### ISSUE THREAD

**Issue by apienk** [Connexions/webview#1594]
![image](https://user-images.githubusercontent.com/9961826/35630898-ce1b745a-06a2-11e8-9084-4a6ca04183d8.png)

Notice `<span>` element in the first line of the bulleted list.

**Comment by reedstrm** [comment]
Oy, worse than that: the given URL is bogus, since this is a composite page, it only exists in a book context, so that URL will currently 404.

**Comment by edwoodward** [comment]
Reviewed attribution in a book and page context and did not see this problem. Closing as fixed.
