### ISSUE TITLE
books page is in: link to book is longer than 2 lines

### ISSUE THREAD

**Issue by kerwinso** [Connexions/webview#1610]
## Acceptance Criteria:
> The book title should link to the book and navigate directly to the specific page in the book you were viewing (also this **should be a max of two lines long and be ellipses if more)**

## Bug:
On https://dev.cnx.org/contents/xelFKBHs@6/Systems-Development-Life-Cycle, the book link expands to 3 lines. Acceptance criteria is 2 lines max.

![image](https://user-images.githubusercontent.com/11298165/38115795-04581300-3373-11e8-8d2a-1865a296f0ab.png)

**Comment by kerwinso** [comment]
I need to verify this is happening on the qa server after deploy.

**Comment by kerwinso** [comment]
yup, still there on https://qa.cnx.org/contents/xelFKBHs@6/Systems-Development-Life-Cycle:

![image](https://user-images.githubusercontent.com/11298165/38145582-a10f0126-340f-11e8-96fe-bb8ec806073c.png)


(you can also see the varnish caching issue in this screenshot)

**Comment by philschatz** [comment]
I think that adding in ellipses is only possible if the text is one line long. 2 lines with ellipses is not possible. Given that, is it better to have one line or 3? (who should I ask @reedstrm ?)

Here it is with one line:

![image](https://user-images.githubusercontent.com/253202/38148220-83827c6e-3423-11e8-8fbd-3ab46bb4b56a.png)

**Comment by reedstrm** [comment]
Style already in the pull-request, it just wasn't applied to the div. I added the class in #1613  Locally, it seems to DTRT: 
![image](https://user-images.githubusercontent.com/253212/38148312-867c56d6-341b-11e8-9e03-fa2580bd34eb.png)

**Comment by reedstrm** [comment]
one line at the narrow width leads to lots of "Derived copy of …" or "The title of parent book …" etc. Critical distinguishing info chopped off.

**Comment by philschatz** [comment]
Reopened to let @kerwinso confirm 😄

**Comment by kerwinso** [comment]
Appears to be working on qa server, need to check again on staging when webview is revved and re-deployed.

![image](https://user-images.githubusercontent.com/11298165/38150655-a639fd0c-3425-11e8-908f-befa7e5fa96c.png)

**Comment by kerwinso** [comment]
However as expected, the 2 lines max constraint does not apply in Firefox. Looks like you get the whole shebang.

![image](https://user-images.githubusercontent.com/11298165/38151586-8583c580-3429-11e8-9258-9e43a7889be4.png)

**Comment by kerwinso** [comment]
This is what it looks like in Edge, Windows 10. In addition to >2 lines, the bullets are misaligned:

![image](https://user-images.githubusercontent.com/11298165/38203294-5d0fe808-3664-11e8-998a-1e7a392ab8ae.png)

**Comment by kerwinso** [comment]
The decision of the team was to remove this constraint because it doesn't work consistently across browsers, looks bad in Edge, and may hide important info in the title.

This new criteria was tested on the qa server with a collection with a reeeeally long title (https://qa.cnx.org/contents/BWYBGK7C@2/Executive-Summary) and passed.

![image](https://user-images.githubusercontent.com/11298165/38268172-0db13b92-3743-11e8-9b85-b6959dc628e3.png)
