### ISSUE TITLE
caching issue: `textbook-view-*` elements showing instead of UI buttons & links

### ISSUE THREAD

**Issue by kerwinso** [Connexions/webview#1612]
Should be addressed by https://github.com/Connexions/cnx-deploy/pull/535 upon deployment.

![image](https://user-images.githubusercontent.com/11298165/38146118-2c1c33cc-3412-11e8-86ad-f4de847d0b6f.png)

![image](https://user-images.githubusercontent.com/11298165/38146121-2fa486ac-3412-11e8-94d3-5663bbd62d5f.png)

**Comment by kerwinso** [comment]
Need to request another rev and deploy of cnx-deploy

**Comment by reedstrm** [comment]
Fixed in https://github.com/Connexions/cnx-deploy/pull/535

**Comment by reedstrm** [comment]
For future deploys, at least. For this one, browsers are likely to cache the dictionary file for 
`(now - Last-Modified)*0.1` i.e. 10% of the apparent age of the page, in this case `dictionary.ftl` has a Last-Modified date of: `Thu, 15 Mar 2018 19:16:24 GMT`, so approx 2 days worst case, assuming an April 9 rollout

**Comment by philschatz** [comment]
@reedstrm If we wanted to be safe, does that mean we could deploy the existing code that is on production and then, 2 days later, deploy the new code?

Or does that mean we will always need to deploy the `dictionary.ftl` 2 days in advance?

**Comment by reedstrm** [comment]
Once this code is out, we're good - `dictionary.ftl` will follow along with `main.js` and `settings.js`. The idea of doing a bug-fix point release of cnx-deploy with just the varnish change is an excellent one - get the updated caching behavior out there _before_ the code change exposes it.

**Comment by kerwinso** [comment]
We are doing a hotfix so this bug will never be exposed to users. cnx-deploy will be revved off the latest production release, with the change in https://github.com/Connexions/cnx-deploy/pull/535/files added to it, to create this bug fix tag: https://github.com/Connexions/cnx-deploy/releases/tag/v2.12.7. 

This will then be verified on staging, and rolled out to prod.

**Comment by kerwinso** [comment]
I want to verify this fix is working on prod before I close this issue.

**Comment by kerwinso** [comment]
Verified on prod
