### ISSUE TITLE
UX: 'This page is in books' loading message in blank pane looks like a bug

### ISSUE THREAD

**Issue by kerwinso** [Connexions/webview#1620]
https://staging.cnx.org/contents/6AjDYAxi@16/Composizione-Grafica-in-Proces

![image](https://user-images.githubusercontent.com/11298165/38257269-887dde02-3725-11e8-9af8-48e5283958ca.png)

## wait for it...
![image](https://user-images.githubusercontent.com/11298165/38257289-9072a8a4-3725-11e8-864c-38ed18d4618e.png)

**Comment by reedstrm** [comment]
@sisiz Here's the bug.

**Comment by kerwinso** [comment]
https://trello.com/c/7XpChr94/436-ux-this-page-is-in-books-loading-message-in-blank-pane-looks-like-a-bug

**Comment by kerwinso** [comment]
Looks good on qa server. The loading pane updates so fast I recorded a video/animated gif of what it looks like loading this page: https://qa.cnx.org/contents/yWshIYVW@1/How-Changes-in-the-Cost-of-Liv

Watch the left pane closely:

![1620](https://user-images.githubusercontent.com/11298165/38278160-84809b38-3760-11e8-8265-36cb5514429b.gif)

In any event, definitely an improved user experience.

**Comment by kerwinso** [comment]
FYI, this is what it looks like on staging during those 3-4 seconds of loading time. The left pane is blank but open:

![image](https://user-images.githubusercontent.com/11298165/38322150-37013a44-37ff-11e8-8828-ac96531fc1a9.png)

cc @openstaxalina in case you want to consider a different user experience with Fred (e.g., default books list closed)
