### ISSUE TITLE
books page is in: reducing browser width causes page content to disappear

### ISSUE THREAD

**Issue by kerwinso** [Connexions/webview#1626]
1. Visit any page like this one: https://staging.cnx.org/contents/4fGVMb7P@1/Taboo-language-and-slanguage
2. Keep shrinking the browser width until it goes from this:

![image](https://user-images.githubusercontent.com/11298165/38327455-e1030a82-380d-11e8-8667-57fb2a5c42de.png)

to this:

![image](https://user-images.githubusercontent.com/11298165/38327555-1ee9dbfa-380e-11e8-9177-f8d8ef4425d2.png)

We should update the UX so that the Books list closes once browser width gets too small, so that page content is still visible.

keywords: content disappears

**Comment by kerwinso** [comment]
Not a showstopper for initial release.

**Comment by reedstrm** [comment]
Note that this only happens when you resize, not when you visit a page originally at a small size: we don't start w/ the book-list open if the window is too narrow. The "content goes away" the same way if you have the table of contents open and resize down.

**Comment by kerwinso** [comment]
Trello card:  https://trello.com/c/mkMLHLd3

**Comment by openstaxalina** [comment]
Hmmmmm, good points @PiotrKozlowski.  
How does the user collapse the ToC in the second screenshot?
Is it possible to show examples of the images that would not be readable with the screen at less than 640 px?

**Comment by PiotrKozlowski** [comment]
@openstaxalina 
By hitting `Contents` (pl: Spis treści) - this button will toggle toc.
About images I meant when screen width is 640px and `toc` is opened then there is about `260px` left for content. Mine first screenshot is showing how this looks like at `565px` width.

**Comment by PiotrKozlowski** [comment]
@openstaxalina The question here is what should happen when user want to open `toc`? Should content shrink or `toc` should be full width?

**Comment by openstaxalina** [comment]
@PiotrKozlowski OH, I understand now.  When the screen is at less than 640 px, the ToC will default to closed.  However, if the user manually re-opens it, it should be full width.  Does this make sense?

**Comment by PiotrKozlowski** [comment]
@openstaxalina Yes

**Comment by uskka** [comment]
Works fine. Tested on katalyst01.
<img width="507" alt="screen shot 2018-10-25 at 12 10 24" src="https://user-images.githubusercontent.com/40228918/47493279-36e82680-d84f-11e8-9a71-918848f66b8c.png">
