### ISSUE TITLE
Centered text shows up as a grey bar

### ISSUE THREAD

**Issue by lwtchu** [Connexions/webview#1633]
![screen shot 2018-05-11 at 10 02 41 am](https://user-images.githubusercontent.com/11299125/39931253-75fcbe74-5502-11e8-9432-68b138a24b81.png)
PDF **module m65585 1.3 Defining and Entrepreneurial Mindset or Spirit col23876**

![screen shot 2018-05-11 at 10 05 56 am](https://user-images.githubusercontent.com/11299125/39931400-e9bf0c7c-5502-11e8-96e7-bae7b9855468.png)
Webview https://devb.cnx.org/contents/6l7wf_cy@2.10:-WadO1qV@6/Defining-and-Entrepreneurial-M

Content is using `<emphasis class="centered-text">`

High priority because we shouldn't have missing text on webview.

**Comment by Stackblocks** [comment]
Displaying correctly in updated version of content / code. 

![image](https://user-images.githubusercontent.com/12678235/40393890-d6cce6b0-5de6-11e8-847e-b503644095eb.png)

**Comment by Stackblocks** [comment]
Displaying correctly in updated version of content / code.

![image](https://user-images.githubusercontent.com/12678235/40512367-372ef30e-5f68-11e8-8604-516466bebfea.png)
