### ISSUE TITLE
Caption appearing as grey and unclear

### ISSUE THREAD

**Issue by Stackblocks** [Connexions/webview#1638]
@Stackblocks commented on [Tue May 08 2018](https://github.com/Connexions/cnx-recipes/issues/392)

![grey caption](https://user-images.githubusercontent.com/33228728/39327501-d1db63f4-495d-11e8-8b0c-3e96a2cbc431.jpg)

**Comment by Stackblocks** [comment]
Tested in https://devb.cnx.org/contents/Mmq0W-88@11.1:1KJYQ8ob@5/top-titled-class-table-testing, caption is still light grey.

![image](https://user-images.githubusercontent.com/12678235/41623312-f3277742-73d7-11e8-8385-75d5386325e6.png)

**Comment by helenemccarron** [comment]
That's great news, @PatBoj ! Please reassign to a tester to confirm the issue can be closed

**Comment by Stackblocks** [comment]
Verified. Displaying as specified with updated version of content / code.

![image](https://user-images.githubusercontent.com/12678235/42328653-7880f1e4-8034-11e8-9095-5270c12745de.png)
