### ISSUE TITLE
Feature type/title text is the same size/font as body text

### ISSUE THREAD

**Issue by Stackblocks** [Connexions/webview#1641]
@Stackblocks commented on [Tue May 08 2018](https://github.com/Connexions/cnx-recipes/issues/395)

# In College Physics
<img width="925" alt="screen shot 2018-04-26 at 11 54 55 am" src="https://user-images.githubusercontent.com/1895432/39320088-b3aa117e-4948-11e8-94da-89775959f36a.png">

---

@hwangange commented on [Tue May 22 2018](https://github.com/Connexions/cnx-recipes/issues/395#issuecomment-391013936)

# In AP Physics

AP Physics - Section 13.4 Kinetic Theory - Not only is "Check Your Understanding" the same size/font as paragraph text, but it is placed inside the Solution, and not above the stated problem.
<img width="875" alt="screen shot 2018-05-22 at 9 35 24 am" src="https://user-images.githubusercontent.com/12180288/40369384-795b19d6-5da3-11e8-825d-6c0c8cda2a41.png">

--------------------------------------------

Same issue in Section 21.5. Additionally, "Exercise 1" is written underneath "Check Your Understanding" even though this problem can't possibly be both.

<img width="894" alt="screen shot 2018-05-22 at 10 01 14 am" src="https://user-images.githubusercontent.com/12180288/40370969-16c4d90c-5da7-11e8-9828-83582cb4583a.png">

**Comment by Adrianltd** [comment]
![image](https://user-images.githubusercontent.com/40228907/42228414-2e9edb64-7ee4-11e8-9146-2b1f21733457.png)

that's how it looks on devb.cnx.org (it's baked, but I'm not sure if it's baked correctly. @wilkus27 can say more about that). Can you (@Stackblocks ) check that?

**Comment by wilkus27** [comment]
At the first moment it looks that it's baked:
![phisics](https://user-images.githubusercontent.com/40228854/42229983-1c75f252-7ee8-11e8-8557-149b79425b21.JPG)
But parts of this book are totally different than in other baked one:

Biology (baked):
![ch_outline_biology](https://user-images.githubusercontent.com/40228854/42230091-6c3dabd6-7ee8-11e8-8f28-d8de0ba2dfb5.JPG)

College Phisics:
![ch_outline_phisics](https://user-images.githubusercontent.com/40228854/42230141-855aabe6-7ee8-11e8-8986-8e7821682015.JPG)

**Comment by helenemccarron** [comment]
@Adrianltd can you verify the book is baked properly?

**Comment by helenemccarron** [comment]
@wilkus27 I believe the last screenshot is actually showing the content baked properly. I think it's a separate issue, the chapter outline isn't styled and thus very confusing. I opened an issue here: #1686

**Comment by helenemccarron** [comment]
@Stackblocks can we move this issues to recipes? This is cause because the markup is an exercise with a type of "check your understanding", so it's not supported.

```
    <exercise id="fs-id1589233" type="check-understanding"><label/><title>Check Your Understanding</title>
    <problem id="fs-id2351786">
    <para id="import-auto-id1168465434656">If you consider a very small object such as a grain of pollen, in a gas, then the number of atoms and molecules striking its surface would also be relatively small. Would the grain of pollen experience any fluctuations in pressure due to statistical fluctuations in the number of gas atoms and molecules striking it in a given amount of time?</para>
    </problem>
````

**Comment by helenemccarron** [comment]
Issue moved to [Connexions/cnx-recipes #456](https://github.com/Connexions/cnx-recipes/issues/456) via [**ZenHub**](https://www.zenhub.com/)
