### ISSUE TITLE
H2 padding uneven

### ISSUE THREAD

**Issue by Stackblocks** [Connexions/webview#1642]
@Stackblocks commented on [Tue May 08 2018](https://github.com/Connexions/cnx-recipes/issues/396)

# Screenshot 1
end-of-para padding does not balance that after H2s
<img width="597" alt="screen shot 2018-04-26 at 9 51 29 am" src="https://user-images.githubusercontent.com/1895432/39313408-89f6838c-4937-11e8-815c-a612785f2028.png">

# Screenshot 2
![h2 padding](https://user-images.githubusercontent.com/33228728/39322630-1ff5d550-4950-11e8-9fbd-cf9e0c98566e.jpg)

**Comment by PatBoj** [comment]
I don't see the problem. I think it's because webview from screenshot wasn't baked.
![image](https://user-images.githubusercontent.com/20907906/41624427-f1bf781c-7415-11e8-806b-f55cfc8d0499.png)

**Comment by Stackblocks** [comment]
Displaying as specified with updated version of content / code.

![image](https://user-images.githubusercontent.com/12678235/41726248-5792bdc6-7537-11e8-8e6b-3a63801ddc7f.png)
