### ISSUE TITLE
Figure caption text same size as body text

### ISSUE THREAD

**Issue by Stackblocks** [Connexions/webview#1643]
@Stackblocks commented on [Tue May 08 2018](https://github.com/Connexions/cnx-recipes/issues/397)

[Example section in College Physics](https://devb.cnx.org/contents/Ax2o07Ul@9.98:HR_VN3f7@3/Introduction-to-Science-and-th)

![intro stats figure text same](https://user-images.githubusercontent.com/33228728/39322071-4af03f86-494e-11e8-9c8d-2009c31e8dee.jpg)

**Comment by PatBoj** [comment]
This issue does not appear in the baked book.
![image](https://user-images.githubusercontent.com/20907906/41610544-cf17d7e6-73ed-11e8-88d4-c2d5d69b5206.png)

**Comment by Stackblocks** [comment]
Displaying as specified with updated version of content / code.

![image](https://user-images.githubusercontent.com/12678235/41622717-19418550-73d6-11e8-8d14-88faf9d9513c.png)
