### ISSUE TITLE
Answer key has no line breaks

### ISSUE THREAD

**Issue by Stackblocks** [Connexions/webview#1644]
@nicolasdamiani commented on [Mon May 21 2018](https://github.com/Connexions/cnx-recipes/issues/398)

Answer key doesn't have any line breaks, making it one big block of text.

![screen shot 2018-05-21 at 1 44 12 pm](https://user-images.githubusercontent.com/28710954/40324512-5678977c-5cfe-11e8-9b19-1a1de21a422f.png)

---

@tomjw64 commented on [Mon May 21 2018](https://github.com/Connexions/cnx-recipes/issues/398#issuecomment-390765918)

at first glance, this is a styling issue rather than a recipe issue.

**Comment by helenemccarron** [comment]
![2018-06-18_16-18-55](https://user-images.githubusercontent.com/8514591/41562927-b53a002c-7313-11e8-8a16-26d3be11e5e3.png)

**Comment by helenemccarron** [comment]
This is ready for review.

**Comment by wilkus27** [comment]
Verified on devb. 
![test1](https://user-images.githubusercontent.com/40228854/41618074-ccf5ea46-73c7-11e8-8880-5ff5ec138e3e.JPG)
