### ISSUE TITLE
Math symbols styled incorrectly

### ISSUE THREAD

**Issue by Stackblocks** [Connexions/webview#1645]
@JoseEscalante6 commented on [Mon May 21 2018](https://github.com/Connexions/cnx-recipes/issues/401)

Ellipsis appears as three large dots rather than three periods
In the Descriptive Statistics Chapter (2) Geometric Mean Section (5)
This is a recurring issue throughout the book

![screenshot 16](https://user-images.githubusercontent.com/30252254/40328619-971b052c-5d0c-11e8-9d2b-9fed3ee51ad5.png)

There is also a problem with asterisks used for multiplication as well as weirdly styled less than (<) symbols. (Chapter 7 The Central Limit Theorem Section 4 Finite Population Correction Factor)

![screenshot 18](https://user-images.githubusercontent.com/30252254/40330852-e58916a2-5d13-11e8-88fe-f59056078a97.png)

---

@hwangange commented on [Mon May 21 2018](https://github.com/Connexions/cnx-recipes/issues/401#issuecomment-390795591)

AP PHYSICS:

Multiplication dot is abnormally large between "kg" and "m" in "Making Connections: Illustrations of Force Exerted" in Section 8.2 (Impulse).

<img width="889" alt="screen shot 2018-05-21 at 4 57 49 pm" src="https://user-images.githubusercontent.com/12180288/40332030-228f5efe-5d18-11e8-8019-f5f851f52993.png">

**Comment by PatBoj** [comment]
I think it's a content problem. Here I would like to present a proof.
![image](https://user-images.githubusercontent.com/20907906/42229229-482044c2-7ee6-11e8-8397-1a91d38a9947.png)
Symbol in the content: [bullet operator](https://www.fileformat.info/info/unicode/char/2219/index.htm)

![image](https://user-images.githubusercontent.com/20907906/42229266-5bc78972-7ee6-11e8-8280-6cf17eba4f07.png)
Symbol in the content: [angle](http://www.fileformat.info/info/unicode/char/2220/index.htm)

![image](https://user-images.githubusercontent.com/20907906/42229287-660ee196-7ee6-11e8-90b1-325ceb4391b7.png)
Symbol in the content: [bullet](https://www.fileformat.info/info/unicode/char/2022/index.htm)

**Comment by helenemccarron** [comment]
@openstaxalina I believe this is an encoding issue, it looks like those aren't supported characters. Could you please check the markup?

**Comment by openstaxalina** [comment]
@marcjeannott, would you be able to investigate the AP Physics issue(s), and also the Introductory Business Statistics issue(s) if you can?  Please confirm that the incorrect symbols are coded into the markup (making this a content issue).  We can also discuss more at our next team meeting and/or roundtable?

**Comment by marcjeannott** [comment]
@openstaxalina Yes! Let's meet about this, I can post my findings below, but would like to meet to discuss. 


![image](https://user-images.githubusercontent.com/33228728/42346608-d0ce74a0-8068-11e8-9636-6fdd29a97821.png)

**Comment by hwangange** [comment]
Hi, I separated this issue into 4 separate issues. You can find them linked below:

Large Ellipsis: [https://github.com/Connexions/webview/issues/1692](https://github.com/Connexions/webview/issues/1692)

Less than (<) symbols: [https://github.com/Connexions/webview/issues/1693](https://github.com/Connexions/webview/issues/1693)

Asterisks used for multiplication: [https://github.com/Connexions/webview/issues/1694](https://github.com/Connexions/webview/issues/1694)

Large multiplication dot: [https://github.com/Connexions/webview/issues/1695](https://github.com/Connexions/webview/issues/1695)
