### ISSUE TITLE
Custom bullet point list error

### ISSUE THREAD

**Issue by Stackblocks** [Connexions/webview#1647]
@jonathan-uba commented on [Mon May 21 2018](https://github.com/Connexions/cnx-recipes/issues/406)

In Chapter 21.1, there is an error in the bullet point list for the Virus Classification by Genome Structure table.
![biology 2e error](https://user-images.githubusercontent.com/39272234/40331801-1dac4498-5d17-11e8-9d3e-b0ecc1f15d27.jpg)

**Comment by Adrianltd** [comment]
![image](https://user-images.githubusercontent.com/40228907/41608897-dcd196be-73e9-11e8-99a0-86a1ad0f176c.png)
It's already fixed on devb.cnx.org

**Comment by wilkus27** [comment]
![test2](https://user-images.githubusercontent.com/40228854/41622884-ab47c3ec-73d6-11e8-80b6-1aad2e840aa2.JPG)
Verified
