### ISSUE TITLE
Figure & Table Text not confined within section

### ISSUE THREAD

**Issue by Stackblocks** [Connexions/webview#1648]
@JoseEscalante6 commented on [Mon May 21 2018](https://github.com/Connexions/cnx-recipes/issues/408)

The table in Chapter 13 Linear Regression and Correlation Section 4 The Regression Equation causes the Figure text included within Example 13.5 to appear outside of the box it is supposed to be within. 

![screenshot 19](https://user-images.githubusercontent.com/30252254/40331947-c57433e8-5d17-11e8-9dd1-e55c4062af48.png)

**Comment by Stackblocks** [comment]
Confirmed that this is still behaving erratically in the baked version of the book.

Link to test content: https://devb.cnx.org/contents/tWu56V64@33.86:8EtejTNd@30/134-The-Regression-Equation

![image](https://user-images.githubusercontent.com/12678235/41727469-0a9cade4-753a-11e8-87dd-3522d5fc6093.png)

**Comment by helenemccarron** [comment]
@openstaxalina, it looks like there are a table and an image inside a figure. The result isn’t very successful on webview. Is that something common? Should we support that kind of display, and if so, what is the desired result?

This is a screenshot from the PDF:
![2018-07-05_10-55-55](https://user-images.githubusercontent.com/8514591/42334060-ffe7653e-8041-11e8-8cb2-85dfdb974933.png)

**Comment by openstaxalina** [comment]
hmmmmm, good question @helenemccarron.  @marcjeannott, could you investigate (a) how this was done in markup, and (b) whether that markup is common?  If there's something searchable in the markup, you could use Atom to research this (?).

**Comment by marcjeannott** [comment]
@openstaxalina 
Looking at the markup, it appears these objects are in two different subfigure tags nested inside the typical figure tag. I've never seen subfigure tags used in any of our other books, so I'm pretty unfamiliar with the intended behavior. This book has two other modules using the subfigure tag (1.2 and 1.3), and looking at how those are displayed, I think the only difference is in those instances there are two _images_ are contained within the subfigure tags. This troublesome one has a _table_ and image instead.

I would propose that the simplest way we could fix this would be to create a new image of the table. Then use that new image with the other image in the same subfigure tags they are already in. This would make the two appear next to each other like the other subfigures in the text, as one figure. With the downside of losing the table number hyperlink, and the different styles (tables look different in PDF format compared to webview).

**Comment by openstaxalina** [comment]
@marcjeannott I think that is a great solution.  We would need to get alt text written for the image of the table, but I can help with that once we have the image of the table.  Are you comfortable making this image, perhaps using guidance from other table images in the book?  We can also consult with @lwtchu for guidance :-)

**Comment by marcjeannott** [comment]
Another suggestion would be to make each it's own entity.  I'll try this to reduce the end to maintain another piece of art.

**Comment by marcjeannott** [comment]
As discussed in roundtable, I've removed the subfigure tags, and instead simply and a table, and a figure. I did not see anything linking to the original subfigure table, so I think we're good on that end.
