### ISSUE TITLE
Vertically stretched image

### ISSUE THREAD

**Issue by Stackblocks** [Connexions/webview#1651]
@hwangange commented on [Tue May 22 2018](https://github.com/Connexions/cnx-recipes/issues/410)

<img width="374" alt="screen shot 2018-05-22 at 9 39 14 am" src="https://user-images.githubusercontent.com/12180288/40369641-03749764-5da4-11e8-8129-536cc55f3482.png">

Section 13.6 - Humidity, Evaporation, and Boiling

Image still appears stretched no matter how I resize the browser.

**Comment by helenemccarron** [comment]
This might be a content issue, the values are hardcoded within the image
![2018-06-19_10-19-05](https://user-images.githubusercontent.com/8514591/41606850-3f4fd05c-73aa-11e8-85c2-01b9554a1b1d.png)

**Comment by Stackblocks** [comment]
Content error fixed on Production.
