### ISSUE TITLE
Unformatted numbering of equations throughout book

### ISSUE THREAD

**Issue by Stackblocks** [Connexions/webview#1652]
@hwangange commented on [Mon May 21 2018](https://github.com/Connexions/cnx-recipes/issues/400)

It appears that basically ALL equations in the book, even those that are just steps to a solution, are numbered (ex. "1.2", "1.3") etc. even though the steps are already numbered (1), (2), etc.

<img width="854" alt="screen shot 2018-05-21 at 3 30 21 pm" src="https://user-images.githubusercontent.com/12180288/40328470-1f8e6990-5d0c-11e8-81f9-422e80d201db.png">

In the Webview version, the equations are not numbered at all.

<img width="710" alt="screen shot 2018-05-21 at 3 31 15 pm" src="https://user-images.githubusercontent.com/12180288/40328480-2597235e-5d0c-11e8-88b6-2f7f3844038a.png">

General formulas are numbered, which would make sense, but I thought they would appear bolded and aligned to the right, like so: (This is another textbook) 

<img width="777" alt="screen shot 2018-05-21 at 3 41 15 pm" src="https://user-images.githubusercontent.com/12180288/40328859-6a417b3e-5d0d-11e8-9f9c-82e014435386.png">

But instead, the numbering is also just plain text, and aligned to the left.

<img width="850" alt="screen shot 2018-05-21 at 3 41 43 pm" src="https://user-images.githubusercontent.com/12180288/40328909-8a81d8da-5d0d-11e8-8053-cb405e488988.png">

**Comment by helenemccarron** [comment]
Per Alina, please use the following as a reference

![2018-06-19_12-47-57](https://user-images.githubusercontent.com/8514591/41614804-105274e8-73bf-11e8-9a71-a9322c008861.png)

**Comment by PatBoj** [comment]
Fixed it
![image](https://user-images.githubusercontent.com/20907906/42227174-2b829a40-7ee1-11e8-8242-7c99ebd61404.png)
![image](https://user-images.githubusercontent.com/20907906/42227181-307325a6-7ee1-11e8-86c1-7c2f2aa122fd.png)

**Comment by wilkus27** [comment]
It looks now like that:
![ap_physics](https://user-images.githubusercontent.com/40228854/42336983-a18af408-8085-11e8-97a4-2f1fac0bebf6.JPG)
Are problems with equations correlated with this fix? I see there is new issue for that #1685. 
Should I test numbering of equations again after solving this problem?

**Comment by helenemccarron** [comment]
I think as far as this issue is concerned, the requirement has been met, at least for this release. We can concentrate on #1685 next release (cc @openstaxalina)
