### ISSUE TITLE
Equation text size much larger than surrounding text

### ISSUE THREAD

**Issue by Stackblocks** [Connexions/webview#1653]
@hwangange commented on [Mon May 21 2018](https://github.com/Connexions/cnx-recipes/issues/404)

Recurring problem. Some examples:

6.2: Centripetal Acceleration, Example 6.3
<img width="719" alt="screen shot 2018-05-21 at 4 24 26 pm" src="https://user-images.githubusercontent.com/12180288/40330716-74e9c18a-5d13-11e8-8d88-9e1944153089.png">

"7.50 x 10^4 rev/min" is oversized.. except for the exponent 4.

9.5: Simple Machines, paragraph.

<img width="500" alt="screen shot 2018-05-22 at 9 13 03 am" src="https://user-images.githubusercontent.com/12180288/40368016-5fabd7d0-5da0-11e8-9839-e08bc42ee33c.png">

Note the "net tau = 0".

**Comment by PatBoj** [comment]
The problem lays in MathML itself. Someone or something fixed font size in `mstyle` node: `<mstyle mathsize="12pt">`. I haven't seen `mstyle` node in any well-sized equations.

**Comment by helenemccarron** [comment]
@openstaxalina can you confirm this is a content issue?

**Comment by openstaxalina** [comment]
@marcjeannott please investigate the above content.  Do you see <mstyle mathsize="12pt"> being used in the markup itself?  I believe you can check this content on devb or on production.

**Comment by marcjeannott** [comment]
I was able to locate the mathsize="12pt" in the full source editor. After removing it, the math now appears at much more reasonable size.  I'm worried this 12pt style may be found in more places in the book, and would like to do a quick spot check and remove any others.
