### ISSUE TITLE
Line incorrectly placed above exponent

### ISSUE THREAD

**Issue by Stackblocks** [Connexions/webview#1654]
@hwangange commented on [Tue May 22 2018](https://github.com/Connexions/cnx-recipes/issues/409)

<img width="564" alt="screen shot 2018-05-22 at 9 30 47 am" src="https://user-images.githubusercontent.com/12180288/40369097-df8007cc-5da2-11e8-9f2c-d7daf1b1b539.png">

Section 13.4 Kinetic Theory, Example 13.11
Line should directly above the variable v, and then this entire quantity is raised to the second power. Instead, the line is placed above the quantity v^2.

---

@lwtchu commented on [Fri Jun 01 2018](https://github.com/Connexions/cnx-recipes/issues/409#issuecomment-393919462)

Might be a math rendering problem :(

**Comment by PatBoj** [comment]
It is not an issue, the line (that represent the average value) should be above v^2. It is because the mean kinetic energy is proportional to average squared velocity, not average velocity squared.

**Comment by Stackblocks** [comment]
Closing as a non-issue.
