### ISSUE TITLE
Empty caption in tables

### ISSUE THREAD

**Issue by Adrianltd** [Connexions/webview#1662]
![image](https://user-images.githubusercontent.com/40228907/41620248-66a8075a-7409-11e8-9275-c0a5c28959aa.png)
There's an empty `<caption></caption>` in each `os-table`. 
The example above  is taken from College Physics For AP® Courses, chapter 1.2

**Comment by Stackblocks** [comment]
Issue moved to [Connexions/cnx-recipes #434](https://github.com/Connexions/cnx-recipes/issues/434) via [**ZenHub**](https://www.zenhub.com/)
