### ISSUE TITLE
History buttons floats on top of header

### ISSUE THREAD

**Issue by wilkus27** [Connexions/webview#1664]
![button](https://user-images.githubusercontent.com/40228854/41787047-d4547bbc-760c-11e8-8abc-4da05b8f59c5.JPG)
Link to the example: https://devb.cnx.org/contents/GFy_h8cu@10.120:fVAf83sY@13/Preface
This bug is in all the books.

**Comment by Stackblocks** [comment]
Occurring with both the `Book` and `Page` buttons

![image](https://user-images.githubusercontent.com/12678235/41787228-526e1ce2-760d-11e8-9018-9ae2b2968fd3.png)

**Comment by PiotrKozlowski** [comment]
To solve this problem change `z-index` for higher value in:

```
/webview/src/scripts/modules/media/media.less
.pinnable.pinned{
  z-index:3; // or more, i suggest atleast 10
}
```

**Comment by helenemccarron** [comment]
@PiotrKozlowski feel free to create a new pull request with your change!

**Comment by wilkus27** [comment]
Verified on devb. Both Book and Page buttons work correctly.

Book:
![his_button](https://user-images.githubusercontent.com/40228854/42364822-d5449bf6-80fc-11e8-9f2b-bcd7412f8d2c.JPG)

Page:
![his_button2](https://user-images.githubusercontent.com/40228854/42364847-eae939d0-80fc-11e8-91d6-c000abe5f2ef.JPG)
