### ISSUE TITLE
Connected figures are of different heights

### ISSUE THREAD

**Issue by wilkus27** [Connexions/webview#1667]
![fig_height](https://user-images.githubusercontent.com/40228854/41878083-f7eef5e2-78d3-11e8-8208-46269bf60521.JPG)

Link to the figures: https://devb.cnx.org/contents/GFy_h8cu@10.120:agVo2CPX@12/11-The-Science-of-Biology#8141

**Comment by helenemccarron** [comment]
I believe this is working as intended. The image sizes are content driven. As a reference, this is a screenshot from the PDF
![2018-06-27_15-27-47](https://user-images.githubusercontent.com/8514591/41997831-be467b7a-7a1e-11e8-9636-f03fc6fd0fb3.png)
@openstaxalina can you confirm?

**Comment by openstaxalina** [comment]
I agree this is fine as-is, since the images are sized this way in the PDF.  However, this was a good thing to bring up @wilkus27 - thank you!
