### ISSUE TITLE
DevMath: Numbers should be suppressed in list with tokens

### ISSUE THREAD

**Issue by openstaxalina** [Connexions/webview#1668]
In DevMath (Prealgebra, Intermediate Algebra, Elementary Algebra) we used "tokens" (circled letters) to denote different exercises.  The solutions are listed under the exercises in Webview, and they have both the tokens and a number when they are in a list.  This occurs in legacy and Rewrite (but we mainly care about Rewrite which gets more viewing traffic).  See the attached screenshot.

We need to suppress the numbers on lists when the list is marked up like: < list list-type="enumerated" number-style="arabic" class="circled" >

Most modules in these books will have exhibit this issue, but the specific screenshot is from: https://cnx.org/contents/vryjhia2

<img width="769" alt="devmathtokens" src="https://user-images.githubusercontent.com/7863733/41888719-843cc432-78cc-11e8-923b-9139d8b78c6d.png">

**Comment by Adrianltd** [comment]
Recipe issue, solution lists are put into `ol` instead of `ul` during baking process. So I guess I will take care of this issue and all others related to recipes after our call.
@helenemccarron

**Comment by helenemccarron** [comment]
@Adrianltd I think in this case, we can simply hide the default for lists to use the token instead.

**Comment by Adrianltd** [comment]
@helenemccarron There is no Prealgebra recipe so I can't bake it. That page exists in 7 books (most of them are different Openstax Prealgebra versions and few from other authors).
If I can't bake it, I can't set `list-style: none` on that.

**Comment by openstaxalina** [comment]
Suggest moving to a future release; the DevMath books are out-of-scope for Assignable Webview Phase 1 (they'll probably be the first to prioritize in Phase 2).

**Comment by openstaxalina** [comment]
Confirmed we will remove this from Assignable Webview Phase 1 (AW for half).

**Comment by PiotrKozlowski** [comment]
This should be already fixed with #2016

**Comment by uskka** [comment]
Looks good. Tested on katalyst01. 
<img width="604" alt="screen shot 2018-10-29 at 16 37 01" src="https://user-images.githubusercontent.com/40228918/47661262-f9f69980-db98-11e8-8e10-15f0152b3e98.png">
