### ISSUE TITLE
Polish text on English webview

### ISSUE THREAD

**Issue by wilkus27** [Connexions/webview#1669]
When language of browser is non-English, part of text on the page is displayed in Polish (I don't check browsers with other languages):

![pol](https://user-images.githubusercontent.com/40228854/41901621-adb4a874-7931-11e8-8152-8048738b2cbb.JPG)

What is more, the same text on different pages, one time is in English and other time in Polish:

![links2](https://user-images.githubusercontent.com/40228854/41901847-457bb634-7932-11e8-9c02-7bf1bcc81abb.JPG)
![links3](https://user-images.githubusercontent.com/40228854/41901857-4a7f22ec-7932-11e8-9304-3cfb5746a3e5.JPG)

Other example: 

![links](https://user-images.githubusercontent.com/40228854/41901954-8c5ed644-7932-11e8-89d8-1cbb4c783d6f.JPG)

Licensing is all in Polish, on Term of Use page there are a few words in Polish and Accessibility Statement is all in English.

**Comment by helenemccarron** [comment]
@PiotrKozlowski feel free to create a new pull request with your change!

**Comment by PiotrKozlowski** [comment]
For example we can see footer in polish on home or about page but when we open any book then footer will be in english.

**Comment by PiotrKozlowski** [comment]
@helenemccarron Should I do something here?

**Comment by helenemccarron** [comment]
ooh, that's interesting. @reedstrm or @philschatz do you have any insight on this?

**Comment by philschatz** [comment]
@PiotrKozlowski & @helenemccarron : oh, I've seen this error too (I thought it was just one of my browser extensions but I guess not). Ah, l20n is running `JSON.parse(element.getAttribute('data-l10n-args') || null)];` which causes the exception.

And the element looks like the following:

`<span class="title" data-l10n-id="textbook-view-page-in-books" data-l10n-args="{&quote;numbooks&quote;: }">`

It seems `numbooks:` never has a number set to it which is causing the "Invalid JSON".

# Screenshot

![image](https://user-images.githubusercontent.com/253202/42327441-af28e85a-8039-11e8-8b5c-73a8445f1e24.png)

**Comment by PiotrKozlowski** [comment]
It's related to 
`webview\src\scripts\modules\media\tabs\contents\contents-template.html`
or
`dictionary.ftl` files

I need to check how l20n works to solve this

**Comment by openstaxalina** [comment]
I think this is resolved by the attached PR.  If so, this can likely be assigned to Natalia for testing.

**Comment by PiotrKozlowski** [comment]
We are waiting for @philschatz review for PR #1687

**Comment by openstaxalina** [comment]
Thank you, I asked Phil to review.

**Comment by wilkus27** [comment]
After investigation it turned out that the only problem was with the footer. I checked several books and in each of them I picked up a few random places for testing. In all of them footer is displayed correctly, e.g:

(https://katalyst01.cnx.org/contents/jQSmhtXo@16.36:2FtAHIO2@2/331-The-Yukawa-Particle-and-th)
![footer](https://user-images.githubusercontent.com/40228854/42985902-ae6fe5c4-8bf3-11e8-929b-ebf839d2ea09.JPG)
