### ISSUE TITLE
College Physics 24.2 crashes the browser

### ISSUE THREAD

**Issue by Dantemss** [Connexions/webview#1671]
URL: https://cnx.org/contents/Ax2o07Ul@11.1:R_XAX-aM@6/Production-of-Electromagnetic-

@reedstrm  thinks it might be an interaction between MathJax and the sim loading.

**Comment by Adrianltd** [comment]
No crash using Firefox 60.0.2 on Ubuntu 18.04

**Comment by openstaxalina** [comment]
No crash using Chrome Version 67.0.3396.99 on Mac OS 10.11.16.  @Dantemss could you report which browser for replication/testing?

**Comment by Dantemss** [comment]
Yep no longer crashes. Something fixed it, just not sure what.
