### ISSUE TITLE
Extra comma

### ISSUE THREAD

**Issue by wilkus27** [Connexions/webview#1672]
![comma](https://user-images.githubusercontent.com/40228854/41960961-6424d916-79f1-11e8-8063-5587766fb84f.JPG)

Link to the page: https://devb.cnx.org/contents/GFy_h8cu@10.120:6kS4-uei@12/31-Synthesis-of-Biological-Mac#fig-ch03_01_01

**Comment by openstaxalina** [comment]
This is acceptable English grammar, since "sped up" defines the word "catalyzed".
