### ISSUE TITLE
Biology => Extra space between parenthesis and link to figure.

### ISSUE THREAD

**Issue by wilkus27** [Connexions/webview#1673]
In all 4.3 and 7.5 modulas in Biology book there are extra spaces between parenthesis and link to the figure. In other modulas this space doesn't occur.

![parenthesis](https://user-images.githubusercontent.com/40228854/41967225-6ef241d4-7a01-11e8-9c75-7e53b044dfe2.JPG)

Links: https://devb.cnx.org/contents/GFy_h8cu@10.120:FPF-phhT@14/43-Eukaryotic-Cells ;
https://devb.cnx.org/contents/GFy_h8cu@10.120:jmCYmYol@7/75-Metabolism-without-Oxygen

**Comment by helenemccarron** [comment]
@openstaxalina I think this is a content issue, this is one of the examples I found in the CNXML: " ( <link target-id="fig-ch04-03-03" document=""/>). Such cells are typically found lining the small intestine, the organ that absorbs nutrients from digested food. This is an excellent example of form following function.".

**Comment by openstaxalina** [comment]
Assigning to @Bkblodget for content investigation.

**Comment by openstaxalina** [comment]
Nice find, @wilkus27 :-)

**Comment by brittweinstein** [comment]
Issue moved to [Connexions/content-managers #196](https://github.com/Connexions/content-managers/issues/196) via [**ZenHub**](https://www.zenhub.com/)
