### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by wilkus27** [Connexions/webview#1674]
![link2](https://user-images.githubusercontent.com/40228854/41983185-a00aeec0-7a2d-11e8-9e50-a72cb8d8963f.JPG)

Link to the page: https://devb.cnx.org/contents/GFy_h8cu@10.120:Gj6xeWoG@10/94-Signaling-in-Single-Celled-

**Comment by helenemccarron** [comment]
@openstaxalina This looks like it might be a content issue. It looks like the link to the iframe is incorrect: https://www.openstaxcollege.org/l/bacteria_bioflm

**Comment by openstaxalina** [comment]
@Bkblodget, I think the link should be https://www.openstax.org/l/bacteria_biofilm (note the added "i" in "film").  This directs to: https://www.youtube.com/watch?v=lpI4WCM_9pM.

Could you please correct this content on devb, and also on production, if this content exists there?

**Comment by openstaxalina** [comment]
Filed errata; closing.  (duplicate: https://github.com/Connexions/cnx-recipes/issues/490)
