### ISSUE TITLE
Too small distance between figures discription and list.

### ISSUE THREAD

**Issue by wilkus27** [Connexions/webview#1676]
![distance](https://user-images.githubusercontent.com/40228854/42037944-e739e26c-7ae9-11e8-8344-48f82a2de745.JPG)

Link: https://devb.cnx.org/contents/GFy_h8cu@10.120:1tJ55Ot6@7/102-The-Cell-Cycle

**Comment by Adrianltd** [comment]
Reopen for the tests

**Comment by wilkus27** [comment]
Verified on devb:

![small_distance](https://user-images.githubusercontent.com/40228854/42364999-7d9805cc-80fd-11e8-91ca-3f08ec4b3378.JPG)
