### ISSUE TITLE
Website from link can not load.

### ISSUE THREAD

**Issue by wilkus27** [Connexions/webview#1678]
Link from Link to Learning leads to website which can't load.
![link_problem](https://user-images.githubusercontent.com/40228854/42094732-f7a6e0b0-7bb0-11e8-93f5-71f4efdc89e3.JPG)

This is the last one Link to Learning on page: https://devb.cnx.org/contents/GFy_h8cu@10.120:fL0VrVv_@7/212-Virus-Infections-and-Hosts

**Comment by wilkus27** [comment]
I got this information:
![website_3](https://user-images.githubusercontent.com/40228854/42107549-220a39a2-7bd8-11e8-9263-56cee68aad2d.JPG)
It means that the website is unavailable

**Comment by openstaxalina** [comment]
That is strange!  Here is what I see:

![screen shot 2018-06-29 at 1 43 34 pm](https://user-images.githubusercontent.com/7863733/42109209-7cdb7cbe-7ba2-11e8-9c8b-c203b045ecee.png)

This error must be location-specific.  I will file content errata for this so we can consider pointing to another website, instead.
