### ISSUE TITLE
Inconsistancy in distance between QR code and text

### ISSUE THREAD

**Issue by wilkus27** [Connexions/webview#1681]
In the whole book there is inconsistancy in distance between QR code and text in Link to Learning boxes.
One way:
![distance_ltl3](https://user-images.githubusercontent.com/40228854/42223517-3c2d0244-7ed8-11e8-84df-1918f61305b4.JPG)

Another one:
![distance_ltl4](https://user-images.githubusercontent.com/40228854/42223680-a0126c54-7ed8-11e8-94dd-f309bf07ee50.JPG)

**Comment by Stackblocks** [comment]
Spacing appears consistent after new code deploy. There is some variance in the size of the QR codes themselves, but this is still the old content so we are more concerned about the structure.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/8805cdfb-0163-4de5-ac3d-d9b81bf432d5)
---
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/a87f3000-1c64-4183-925e-bd7726e75b6a)
---
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/65779e3f-9498-46f2-9c85-3843ca0f636b)
---
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/ead73f81-d1b1-4ae3-b3ef-39fc67136861)
---
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/fd6a5e97-69e6-45b2-9e56-dc126f92d38d)
---

**Comment by Stackblocks** [comment]
(And the link that was the demo of the issue is working correctly too)

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/1614ce6a-e6e4-4093-9c88-bd7604130845)
