### ISSUE TITLE
Two the same links next to each other

### ISSUE THREAD

**Issue by wilkus27** [Connexions/webview#1683]
In Unit 7-36.2 https://devb.cnx.org/contents/GFy_h8cu@10.120:sy9h_F-r@7/362-Somatosensation in Link to Learning box two links, which are next to each other direct to the same website.
![two_links](https://user-images.githubusercontent.com/40228854/42227586-1e63fb3c-7ee2-11e8-9742-dc81b4e63c80.JPG)

**Comment by openstaxalina** [comment]
@wilkus27 could you please submit errata for this for **Biology 2e** on openstax.org?  I'm going to close this issue.
