### ISSUE TITLE
Equations need design and styling

### ISSUE THREAD

**Issue by helenemccarron** [Connexions/webview#1685]
We need to design a more robust approach to numbered equations.

An example can be found in https://devb.cnx.org/contents/jQSmhtXo@14.60:lU8zWeww@3/134-Kinetic-Theory-Atomic-and-

![2018-07-05_11-10-28](https://user-images.githubusercontent.com/8514591/42334995-8864820a-8044-11e8-9f6f-20590e2b4be7.png)

**Comment by helenemccarron** [comment]
After a little bit of research, controlling the height of the equations might help (the screenshot isn't perfect but shows potential).

![2018-07-05_13-35-36](https://user-images.githubusercontent.com/8514591/42341396-8b40dc94-8058-11e8-8f21-d8268167da51.png)

**Comment by openstaxalina** [comment]
@helenemccarron I agree that looks much better.  I would approve that, except one thing:

Shouldn't the equations be centered, as they are in the PDF (screenshot below)?  Apologies if I missed another issue about this.

<img width="825" alt="screen shot 2018-07-05 at 2 20 15 pm" src="https://user-images.githubusercontent.com/7863733/42343450-b72e441c-805e-11e8-8b22-417039a94e35.png">

**Comment by openstaxalina** [comment]
@helenemccarron yes, that looks great.  I don't see the need for any further changes.

**Comment by Adrianltd** [comment]
I am to blame here. I overwrote the `.Mathjax_Display` with `width: auto !important;` in other issue (#1655). If we remove that, Mathjax elements, e.g. https://devb.cnx.org/contents/jQSmhtXo@14.60:vainocWC@3/51-Friction will not display inline properly. 
Any idea how to solve those, so they both display correct?
@helenemccarron

**Comment by PatBoj** [comment]
Good to hear that I didn't screw up :smile:.

**Comment by PatBoj** [comment]
@helenemccarron Is it fixed already? Adrian says that he undone his changes and equations should look like before.

**Comment by helenemccarron** [comment]
@Adrianltd is it possible to target `.Mathjax_Display` inside of tables rather than in such a wide fashion?

**Comment by helenemccarron** [comment]
This was addressed with PR #1726
