### ISSUE TITLE
College Physics Chapter outlines need to be designed and styled 

### ISSUE THREAD

**Issue by helenemccarron** [Connexions/webview#1686]
@openstaxalina, could you provide specs or the design guidance? Currently, they are very confusing.
![2018-07-05_11-06-21](https://user-images.githubusercontent.com/8514591/42335297-86a3c236-8045-11e8-8cc3-de313eedbc70.png)

**Comment by helenemccarron** [comment]
This would be using styles matching webivew or should we try to replicate a similar layout (centered text, block headers etc?)

**Comment by openstaxalina** [comment]
@helenemccarron styles matching webview, but using the screenshot as a guideline for moving the bullets closer to their section header, and making the entire outline more compact.

**Comment by helenemccarron** [comment]
![2018-07-05_13-20-42](https://user-images.githubusercontent.com/8514591/42342967-495279e6-805d-11e8-91ce-0a4ea839f4b8.png)
@openstaxalina approved :D Please make the chapter outline look like the above

**Comment by PatBoj** [comment]
![image](https://user-images.githubusercontent.com/20907906/42682461-f405cea0-868a-11e8-9357-6cf034eabf46.png)

**Comment by wilkus27** [comment]
Veriffied on katalyst01 (https://katalyst01.cnx.org/contents/Ax2o07Ul@11.32:HR_VN3f7@3/Introduction-to-Science-and-th):
![chapter_outline](https://user-images.githubusercontent.com/40228854/43128028-3a24a22c-8f31-11e8-893f-d21e58628299.JPG)
