### ISSUE TITLE
Different beginning of the module

### ISSUE THREAD

**Issue by wilkus27** [Connexions/webview#1688]
There are different ways how modules look at the beggining of the page in different books:

(1) Biology: (e.g. https://devb.cnx.org/contents/GFy_h8cu@10.120:agVo2CPX@12/11-The-Science-of-Biology) List on the grey background.

![begin_biology](https://user-images.githubusercontent.com/40228854/42375160-f5023f8e-811a-11e8-9b55-2dc33b000dd6.JPG)

(2) University Physics Volume 2: (e.g. https://devb.cnx.org/contents/eg-XcBxE@7.1:g5baFV-k@2/11-Temperature-and-Thermal-Equ) List on the grey background with title "Learning Objectives"

![begin_un_physics](https://user-images.githubusercontent.com/40228854/42375194-1093c92a-811b-11e8-8666-2eb7fa43707e.JPG)

(3) College Physics For AP® Courses: (e.g. https://devb.cnx.org/contents/jQSmhtXo@14.60:L4pdOADV@2/11-Physics-An-Introduction) List with title "Learning Objectives" without background

![begin_ap_phisics](https://user-images.githubusercontent.com/40228854/42375215-23211dc2-811b-11e8-8501-1ddc28ac7270.JPG)

**Comment by helenemccarron** [comment]
That is expected. Different books will have different chapter openers

**Comment by openstaxalina** [comment]
Yes, this is acceptable.  At some point we may try to standardize, but this meets the requirements for Assignable Webview.
