### ISSUE TITLE
Confusing link on the main page. (CNX Author/Legacy Site) 

### ISSUE THREAD

**Issue by uskka** [Connexions/webview#1689]
What: User can not click CNX Author link, both links are underlined together when user moves cursor to any of the links. Clicking redirects to the same page but design suggests that they are both different links. 

Where: devb and cnx.org 
https://cnx.org

![cnx button](https://user-images.githubusercontent.com/40228918/42375632-6a226158-811c-11e8-9978-dfb2b375dec6.png)

**Comment by openstaxalina** [comment]
This is out of scope for Assignable Webview.  I will prioritize this issue for later releases.

**Comment by openstaxalina** [comment]
An easy way to address this would be change the text to: **CNX Author (Legacy Site)**

**Comment by openstaxalina** [comment]
We would add work for the OpenStax Customer Support team -- updating several Support articles and other documentation -- if we were to make this change.  Because this is a low-priority issue, we will not make this change.  Closing this issue.  cc @helenemccarron @PiotrKozlowski @edwoodward @uskka
