### ISSUE TITLE
Math symbols styled incorrectly: Large Ellipsis

### ISSUE THREAD

**Issue by hwangange** [Connexions/webview#1692]
@JoseEscalante6 commented on Mon May 21 2018:

Ellipsis appears as three large dots rather than three periods
In the Descriptive Statistics Chapter (2) Geometric Mean Section (5)
This is a recurring issue throughout the book
![40328619-971b052c-5d0c-11e8-9d2b-9fed3ee51ad5](https://user-images.githubusercontent.com/12180288/42383257-5b2a0220-80fc-11e8-9107-d2b944fb029d.png)

**Comment by hwangange** [comment]
PatBoj: I think it's a content problem. Here I would like to present a proof.
![42229229-482044c2-7ee6-11e8-8397-1a91d38a9947](https://user-images.githubusercontent.com/12180288/42383323-83557d4c-80fc-11e8-8753-ad1704914afa.png)
Symbol in the content: [bullet operator](https://www.fileformat.info/info/unicode/char/2219/index.htm)

**Comment by hwangange** [comment]
marcjeannott:

![image](https://user-images.githubusercontent.com/12180288/42383541-1f1586a0-80fd-11e8-85d5-bff718aeecd6.png)

**Comment by lwtchu** [comment]
@marcjeannott &#8230;

**Comment by marcjeannott** [comment]
Bullets appear correctly now - 
![bullets](https://user-images.githubusercontent.com/33228728/43274583-2df55894-90c5-11e8-96e8-47d584a4ee0b.jpg)
