### ISSUE TITLE
Math symbols styled incorrectly: Less than (<) symbols

### ISSUE THREAD

**Issue by hwangange** [Connexions/webview#1693]
JoseEscalante6 commented on Mon May 21 2018:

There is a problem with weirdly styled less than (<) symbols.
Chapter 7 The Central Limit Theorem Section 4 Finite Population Correction Factor

![40330852-e58916a2-5d13-11e8-88fe-f59056078a97](https://user-images.githubusercontent.com/12180288/42383726-bb8f973c-80fd-11e8-8922-94e1d2843ab0.png)

**Comment by hwangange** [comment]
PatBoj: 

I think it's a content problem. Here I would like to present a proof.

![42229266-5bc78972-7ee6-11e8-8280-6cf17eba4f07](https://user-images.githubusercontent.com/12180288/42383755-d2eaee5e-80fd-11e8-823e-c3aa4ff6899f.png)
Symbol in the content: [angle](http://www.fileformat.info/info/unicode/char/2220/index.htm)

**Comment by hwangange** [comment]
marcjeannott:

It appears that the angle symbol is used instead of less than, or “∠” instead of “<”, because the editor thinks it’s an open tag otherwise. The code for this one is “&#8736;”

**Comment by lwtchu** [comment]
@marcjeannott `&lt;`

**Comment by marcjeannott** [comment]
The angle signs that were mistakenly being used as less than symbols, have been replaced with the correct symbol: &lt;
