### ISSUE TITLE
Math symbols styled incorrectly: Asterisks used for multiplication

### ISSUE THREAD

**Issue by hwangange** [Connexions/webview#1694]
JoseEscalante6 commented on Mon May 21 2018:

There is a problem with asterisks used for multiplication.
Chapter 7 The Central Limit Theorem Section 4 Finite Population Correction Factor

![40330852-e58916a2-5d13-11e8-88fe-f59056078a97-1](https://user-images.githubusercontent.com/12180288/42384004-8130e95a-80fe-11e8-9512-df4bff997416.png)

**Comment by lwtchu** [comment]
@marcjeannott interpunct `&#183;`

**Comment by marcjeannott** [comment]
I've replaced all the asterisks in the module with &#183; .
