### ISSUE TITLE
Math symbols styled incorrectly: Large multiplication dot

### ISSUE THREAD

**Issue by hwangange** [Connexions/webview#1695]
hwangange commented on Mon May 21 2018:

AP PHYSICS:

Multiplication dot is abnormally large between "kg" and "m" in "Making Connections: Illustrations of Force Exerted" in Section 8.2 (Impulse).

<img width="889" alt="40332030-228f5efe-5d18-11e8-8019-f5f851f52993" src="https://user-images.githubusercontent.com/12180288/42384130-ca62366a-80fe-11e8-9389-dd94b23aa88a.png">

**Comment by hwangange** [comment]
PatBoj: 

I think it's a content problem. Here I would like to present a proof.
<img width="713" alt="screen shot 2018-07-06 at 9 32 13 am" src="https://user-images.githubusercontent.com/12180288/42384457-a2a591c0-80ff-11e8-8061-1b6ef0694f4b.png">
(Note: I changed the screenshot because I think he accidentally pasted the wrong one?)

Symbol in the content: [bullet](https://www.fileformat.info/info/unicode/char/2022/index.htm)

**Comment by hwangange** [comment]
marcjeannott:

In AP Physics, the “•” are marked up as “&#8226;” I think this may have to do with the bullet being in the math tags. I can copy and paste it into a normal para tag and the bullet appears at a more reasonable size.  I can change it to “∙”, which appears smaller, but might still be too big?

**Comment by marcjeannott** [comment]
I've edited the content to instead use an even smaller bullet. Looks good now.
