### ISSUE TITLE
Intro to Business: unnumbered list displays as bullet style

### ISSUE THREAD

**Issue by helenemccarron** [Connexions/webview#1698]
@clteam18 commented on [Fri Jul 06 2018](https://github.com/Connexions/oer.exports/issues/3693)

**Chapter 17 - m10295 / Similar occurrence in few chapters**

**XML Coding:**
![image](https://user-images.githubusercontent.com/39794953/42385910-bcafdeca-815b-11e8-85a3-a87fa628c860.png)

**Online View:**
![image](https://user-images.githubusercontent.com/39794953/42385851-8dd9c390-815b-11e8-8470-70524bb3010b.png)

**bullet-style** attribute value is defined as **none**, however the content is displayed with bullet style.

**Comment by clteam18** [comment]
@openstaxalina Still the contents are displayed with the bullet style
![image](https://user-images.githubusercontent.com/39794953/42823010-159e0556-89fa-11e8-915c-1e9ec38438ab.png)

**Comment by openstaxalina** [comment]
@clteam18 thank you!  We were looking at the unbaked page above; apologies for the confusion.

@helenemccarron @Stackblocks at https://content02.cnx.org/contents/o0xnhd_t@3.1:sT9pws9t@2/172-Developing-Interpersonal-S I can confirm that unbulleted lists are displaying with bullets.  Let's park in scrum today.

**Comment by openstaxalina** [comment]
Helene will compare the page in the unbaked book with the page in the baked book to determine the issue.

**Comment by brittany-johnson** [comment]
![screen shot 2018-07-24 at 1 26 56 pm](https://user-images.githubusercontent.com/24909007/43158513-75469784-8f45-11e8-9c73-49c7b34e0ff9.png)
All baked books with elements with `[data-bullet-style="none"]` should now display without bullets. For testing purposes, make sure that the list element selected has `[data-is-baked="true"]` if it does not, this means you're looking at a unbaked book. I did my testing here: 
https://devb.cnx.org/contents/qAil3UeG@2.1:QPtDfnNA@2/172-Developing-Interpersonal-S 
If a popup bar appears suggesting the newer version, this version *maaaaay* not be baked.

**Comment by Stackblocks** [comment]
Displaying as specified with updated version of content / code.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/499808a3-e725-4493-bd10-f58e53cd8759)

**Comment by openstaxalina** [comment]
There may have been a regression here - @clteam18 reports still seeing this list as bulleted.
![bulletedlist](https://user-images.githubusercontent.com/7863733/44367964-e642fe80-a496-11e8-94b9-fa36c1c797eb.png)

**Comment by openstaxalina** [comment]
Content is at: https://content02.cnx.org/contents/o0xnhd_t@12.1:sT9pws9t@4/172-Developing-Interpersonal-S

**Comment by Stackblocks** [comment]
@openstaxalina I can confirm that the bulleting is appearing on Content02 and that the content is baked, and that the bulleting is not on devb (https://devb.cnx.org/contents/qAil3UeG@6.3:QPtDfnNA@3/172-Developing-Interpersonal-S).

One thing of note is that it appears that the oer.exports deploy to the content servers failed somehow, because the RhaptosPrint versions on the content servers and devb are at 0.128, but the content servers are on ornery.orthrus again. We will need to request DevOps redeploy the Content environments.

**Comment by Stackblocks** [comment]
From our discussion in the channel, it looks like the markup differences between the two could be the cause.

```<ul class="no-style" data-bullet-style="none" id="fs-idm251188768">
<li>K = Kind</li>
<li>I = Informed</li>
<li>N = New</li>
<li>D = Definite</li>
</ul>```

on devb

```<ul class="no-style" id="fs-idm251188768">
<li>K = Kind</li>
<li>I = Informed</li>
<li>N = New</li>
<li>D = Definite</li>
</ul>```

on content02.

Per @brittany-johnson "That class `data-bullet-style="none"` needs to be included on content02 for the style to be applied properly."
