### ISSUE TITLE
Intro to Business: References - Global

### ISSUE THREAD

**Issue by helenemccarron** [Connexions/webview#1700]
@clteam18 commented on [Fri Jul 06 2018](https://github.com/Connexions/cnx-recipes/issues/447)

**Global for all Chapters**

![image](https://user-images.githubusercontent.com/39794953/42384974-20f8d420-8159-11e8-87fe-4bb05e1cd6b1.png)

There is no separation between the Note numbers and the text in online view.

**Comment by openstaxalina** [comment]
We need to verify that the book is baked properly.  If this is truly an issue, it should be a relatively easy fix.

**Comment by brittany-johnson** [comment]
<img width="1345" alt="screen shot 2018-07-10 at 1 06 51 pm" src="https://user-images.githubusercontent.com/24909007/42700793-677e7a2c-868a-11e8-9042-61cb20676d04.png">

**Comment by Stackblocks** [comment]
Displaying as specified with updated version of content / code.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/fdfa6c5b-4440-4b2a-98db-d061d0c90513)
---
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/6c2e4279-62aa-4317-b22a-7d44b2421dd5)
