### ISSUE TITLE
No margin in table content

### ISSUE THREAD

**Issue by uskka** [Connexions/webview#1701]
Where: Every book on devb. Screen from devb / College Physics / 2.7-Falling-Objects 
https://devb.cnx.org/contents/Ax2o07Ul@9.98:nkhtuBIO@6/27-Falling-Objects

Description: No margin in all of the tables content. 

![screenshot-devb cnx org-2018 07 09-10-37-51](https://user-images.githubusercontent.com/40228918/42439917-79ef79a0-8364-11e8-9bf8-26d6791e395e.png)

**Comment by openstaxalina** [comment]
We would like to add padding so the content isn't flush with the border lines of the table.

**Comment by uskka** [comment]
Works fine. Tested on katalyst01.
![screenshot-katalyst01 cnx org-2018 07 24-10-53-33](https://user-images.githubusercontent.com/40228918/43127647-3ff38dcc-8f30-11e8-9b6a-d5b444d76cec.png)
