### ISSUE TITLE
Problem with "-" and "+" in tables

### ISSUE THREAD

**Issue by uskka** [Connexions/webview#1702]
Description: In tables when there is a "-" or "+" before number, there is no white space before other numbers so the table content doesn't look good. 

Where: Every table on devb. Screen from College Physics/ 2.7 Falling Objects
https://devb.cnx.org/contents/Ax2o07Ul@9.98:nkhtuBIO@6/27-Falling-Objects

![screenshot-devb cnx org-2018 07 09-11-30-55](https://user-images.githubusercontent.com/40228918/42442758-d36c0762-836b-11e8-9beb-f6f83f2e4efb.png)

**Comment by helenemccarron** [comment]
@openstaxalina is that something we should try to address?

**Comment by openstaxalina** [comment]
This display was acceptable for the PDF:

![screen shot 2018-07-09 at 5 08 30 pm](https://user-images.githubusercontent.com/7863733/42478564-c21f256e-839a-11e8-9709-974fdec390b4.png)

Therefore, I am going to close this issue.
