### ISSUE TITLE
Issue with big tables

### ISSUE THREAD

**Issue by uskka** [Connexions/webview#1705]
Description: When Contents are shown and table is too big, part of the table content is cut out of the screen. There should be mechanism that prevents such behaviour.

Where: Screen from devb/ Accounting / B | Present Values Table Set Rotated (Landscaped at 90°) as Art and Table
https://devb.cnx.org/contents/l6eNxxA-@2.6:YykWtsbi@3/B--Present-Values-Table-Set-Ro

![screenshot-devb cnx org-2018 07 09-15-58-18](https://user-images.githubusercontent.com/40228918/42454985-469448e2-8391-11e8-8ea6-9be424b92938.png)
![screenshot-devb cnx org-2018 07 09-15-58-56](https://user-images.githubusercontent.com/40228918/42454988-4836e6d2-8391-11e8-84a9-3f8f2ca03c3d.png)

**Comment by helenemccarron** [comment]
@openstaxalina I am not sure what we can do CSS wise to fix this type of issue.

**Comment by openstaxalina** [comment]
@helenemccarron can this be fixed with JavaScript?  I would like to try to include this with Assignable Webview.  The screen won't scroll right, so the content is completely inaccessible/illegible for the user.

**Comment by PiotrKozlowski** [comment]
You can try something like this:
```
.os-tabe{
  overflow: scroll;
  overflow-y: hidden;
}
```
Then in mobile you will be able to scroll table by swiping and on desktop you can scroll horizontally with `shift + scroll`. Eventually we can add js script which will allow to scroll tables horizontally on desktop also by swiping with mouse.

**Comment by openstaxalina** [comment]
Thank you @PiotrKozlowski !  I am concerned that many people do not know how to use shift + scroll.  How much work is it to add the js scripe that allows scrolling tables horizontally on the desktop with the mouse?  cc @helenemccarron  (Note: this card is still un-prioritized; we can discuss here and try to get this into a future sprint.)

**Comment by PiotrKozlowski** [comment]
So there are scripts for simulating touching on desktops (ex. https://hammerjs.github.io/touch-emulator/). If we can add this script then it should be easy to implement, but propably we do not want another script on webview so we should write our own logic for swiping tables which can be tricky.

**Comment by Stackblocks** [comment]
Issue moved to [Connexions/cnx-recipes #488](https://github.com/Connexions/cnx-recipes/issues/488) via [**ZenHub**](https://www.zenhub.com/)
