### ISSUE TITLE
Inconsistent font style of columns headers in tables

### ISSUE THREAD

**Issue by wilkus27** [Connexions/webview#1707]
In parts of tables in Introductory Business Statistics (e.g. https://devb.cnx.org/contents/tWu56V64@33.86:XEZYKVYN@6/22-Measures-of-the-Location-of) headers of columns are in block letters:

Module 2.2 Example 2.16
![big_font](https://user-images.githubusercontent.com/40228854/42504228-5e5f514c-843b-11e8-9f81-b0b698faadee.JPG)

and in other ones, in normal font:

Module 2.2 Try It 2.16
![small_font](https://user-images.githubusercontent.com/40228854/42504390-e4c8bd22-843b-11e8-94af-f85787b4f08c.JPG)

**Comment by wilkus27** [comment]
I created similar issue https://github.com/Connexions/cnx-recipes/issues/459. Which convention should be accepted: block letters, normal font or words in block letter with white spaces between each other?

**Comment by openstaxalina** [comment]
Agree; I am going to close this.

**Comment by openstaxalina** [comment]
created: https://github.com/Connexions/oer.exports/issues/3716

closing this issue.
