### ISSUE TITLE
Separate the Answer Key by Chapter

### ISSUE THREAD

**Issue by openstaxalina** [Connexions/webview#1708]
**Not a requirement for Assignable Webview MVP**

As a student, I need to be able to navigate to answers for the chapter that I am currently reviewing. 

Here is the Answer Key for _University Physics Volume 1_: https://cnx.org/contents/1Q9uMg_a:5qqYClIo
It takes a long time to typeset all the math and load the entire page.  

### Acceptance Criteria
-Each chapter's answer key appears on a separate page/url in webview
-In the left-hand ToC pane, the "Answer Key" defaults to collapsed, but can be expanded by clicking it
-When the "Answer Key" is expanded in the left-hand ToC pane, the chapters are nested/indented in numerical order below.
-The title of the page is Chapter [Number] (see screenshot)
-The answer key is still divided by sections, such as "Check Your Understanding", "Conceptual Questions", "Problems", etc.

![answerkeybychapter](https://user-images.githubusercontent.com/7863733/42526577-d2bfbae0-843b-11e8-9d27-8b5bdd487f84.png)

**Comment by openstaxalina** [comment]
Per Ross: BE tasks done, this now only needs recipe implementation.

**Comment by openstaxalina** [comment]
Per Helene, the following tasks remain:
-CSS Change the recipes to add data-type="composite-page" to chapter sections of the AK  CSS 
-Set each Page data-uuid-key attribute to be based on the book and which chapter they came from

**Comment by helenemccarron** [comment]
Issue moved to [Connexions/cnx-recipes #472](https://github.com/Connexions/cnx-recipes/issues/472) via [**ZenHub**](https://www.zenhub.com/)
