### ISSUE TITLE
Business Ethics - Art oversized in Webview

### ISSUE THREAD

**Issue by helenemccarron** [Connexions/webview#1709]
@mwest-WWprod commented on [Tue Jul 10 2018](https://github.com/Connexions/oer.exports/issues/3696)

content01
GLOBAL 

Art is appearing correctly/as expected in generated PDFs after the latest code rollout, but still appears oversized in webview.

Example from col10003 (Ch. 4)
PDF
![shareholders_pdf](https://user-images.githubusercontent.com/19212926/42526251-4e4f2f2c-8443-11e8-9987-6182ef6ea005.PNG)

Webview
![shareholders_webview](https://user-images.githubusercontent.com/19212926/42526273-58cb2bd6-8443-11e8-8a6a-685c8a23bb8c.PNG)

**Comment by lwtchu** [comment]
@helenemccarron if this is taking wayyy too much time, let's move to the next milestone. but hopefully this is a resolution thing?

**Comment by helenemccarron** [comment]
@lwtchu which book is this in? Do we have access to the data same data on devb? At a glance, it looks like it.

**Comment by openstaxalina** [comment]
Applied Business Ethics label. Alan is assisting in locating test content.

**Comment by openstaxalina** [comment]
Options:

- set a max height
- add a class to large images so we can scale them down, i.e. to 70%

**Comment by openstaxalina** [comment]
Options:
-ask vendors to add a class to any images that are too large in webview
-only allow images to be 75% of the viewport

**Comment by openstaxalina** [comment]
*Decision:* set max viewport width for all images to 60%

**Comment by Stackblocks** [comment]
Will also need to probably generate a class for text-heavy images, since this can cause them to be undersized from an a11y standpoint.

**Comment by openstaxalina** [comment]
@helenemccarron on this one - can you confirm that this affects *baked* books only (not all books)?  Thank you!

**Comment by helenemccarron** [comment]
@openstaxalina yes, the new CSS rule will be applied in `baked-content.css`

**Comment by lwtchu** [comment]
Going to put class `dpi-200` (36%) and `dpi-300` (24%) in the `<media>` tag

**Comment by lwtchu** [comment]
DECISION: Leave everything at 100% of the viewport. `scale-down` class to be used in the `<media>` tag.

**Comment by Stackblocks** [comment]
Thanks to @tomjw64 for pointing out that the class is `scaled-down`, not `scale-down`. Displaying as specified with updated version of content / code when the class is applied.

## Without class="scaled-down"
![image](https://user-images.githubusercontent.com/12678235/43591425-efdf0e0a-9638-11e8-879f-69be2371556f.png)

## With class="scaled-down"
![image](https://user-images.githubusercontent.com/12678235/43591448-fd7eb2b8-9638-11e8-9558-6a8c09a04941.png)
