### ISSUE TITLE
Different style of note

### ISSUE THREAD

**Issue by wilkus27** [Connexions/webview#1710]
The same part of book differs on devb, cnx and pdf. It looks like an issue on devb, but I'm not sure which version is correct.  

In the whole book note box looks like that: (e.g Module 2.3 https://devb.cnx.org/contents/tWu56V64@33.86:39NcLz3J@18/23-Measures-of-the-Center-of-t)
![note_devb2](https://user-images.githubusercontent.com/40228854/42564535-4cc1f554-8501-11e8-911a-75d1d54adfdb.JPG)

But there is moment, when it looks different: (Module 5.2 https://devb.cnx.org/contents/tWu56V64@33.86:d-NtEG_9@8/52-The-Uniform-Distribution)

![note_devb](https://user-images.githubusercontent.com/40228854/42564512-40f1634a-8501-11e8-9701-eb551126c201.JPG)

When I check how it looks on cnx.org, there is no difference in style of note, but in  fonts color  and distance between line and first sentence:
(https://cnx.org/contents/tWu56V64@34.3:d-NtEG_9@9/The-Uniform-Distribution)
![note_cnx](https://user-images.githubusercontent.com/40228854/42565012-9337706c-8502-11e8-9bb8-e5bf624c00b7.JPG)
(https://cnx.org/contents/tWu56V64@34.3:39NcLz3J@22/Measures-of-the-Center-of-the-)
![note_cnx2](https://user-images.githubusercontent.com/40228854/42565027-9a50bfa2-8502-11e8-8906-10612c8ff935.JPG)
 
In pdf, there is no difference:

![note_pdf](https://user-images.githubusercontent.com/40228854/42564475-23b653b2-8501-11e8-9ff0-131c2bf05679.JPG)
![note_pdf2](https://user-images.githubusercontent.com/40228854/42565129-eba9229a-8502-11e8-9f58-4487716de7a7.JPG)

**Comment by helenemccarron** [comment]
For  (Module 5.2 https://devb.cnx.org/contents/tWu56V64@33.86:d-NtEG_9@8/52-The-Uniform-Distribution) the markup is wrong: 
![2018-07-17_15-29-53](https://user-images.githubusercontent.com/8514591/42843644-60a79d6a-89d6-11e8-8723-7c2b2521a752.png)
cc @openstaxalina

**Comment by helenemccarron** [comment]
@openstaxalina this is a content issue: 
```
<note id="id15337317" type="Note"><label>Note</label>This asks for the 90<sup>th</sup> percentile.</note>
```
below a note that is working:
```
<note id="fs-idp118463488"><label/><title>NOTE</title><para id="fs-idm25880032">The words "<term>mean</term>" and "<term>average</term>" are often used interchangeably. The substitution of one word for the other is common practice. The technical term is "arithmetic mean," and "average" is technically a center location. However, in practice among non-statisticians, "average" is commonly accepted for "arithmetic mean."</para></note>```

**Comment by helenemccarron** [comment]
@wilkus27 for the ones on cnx.org, both of them are left unmodified, which explains why they appear the same (despite the wrong markup, it's correct enough to not look different when rendered on webview).

**Comment by openstaxalina** [comment]
@wilkus27 good eye!  Thank you @helenemccarron for diagnosing.

@marcjeannott could you please update this content in this module: https://cnx.org/contents/tWu56V64@34.3:d-NtEG_9@9/The-Uniform-Distribution

`<note><label/><title>NOTE</title><para>This asks for the 90<sup>th</sup> percentile.</para></note>
`

**Comment by marcjeannott** [comment]
I've edited this module. All appears well. 👍
