### ISSUE TITLE
Broken figure

### ISSUE THREAD

**Issue by wilkus27** [Connexions/webview#1711]
There is broken figure in Module 8.1 (https://devb.cnx.org/contents/tWu56V64@33.86:59n7-gS0@27/81-A-Confidence-Interval-for-a)
![broken_fig](https://user-images.githubusercontent.com/40228854/42577858-96e7106e-8525-11e8-87c3-652d58b5eb2e.JPG)

This is how it looks on cnx.org (https://cnx.org/contents/tWu56V64@34.3:59n7-gS0@27/A-Confidence-Interval-for-a-Po)
![image](https://user-images.githubusercontent.com/40228854/42577934-bdc31638-8525-11e8-9e53-180ae5e39616.png)

**Comment by openstaxalina** [comment]
Thank you @wilkus27 !  Submitted errata: https://openstax.org/errata/6450

closing here
