### ISSUE TITLE
Top Titled Tables need Title styled

### ISSUE THREAD

**Issue by helenemccarron** [Connexions/webview#1712]
@helenemccarron commented on [Wed Jul 11 2018](https://github.com/Connexions/cnx-recipes/issues/463)

# Scenario

Top Titled Tables need title styled.

# Reproducibility Details

- **Impact area**: baked tables with a top-title class
- **User**: everyone
- **URL / Location**: https://devb.cnx.org/contents/Mmq0W-88@14.1:1KJYQ8ob@5/14-top-titled-class-table-test
- **How many times were you able to reproduce the issue?** : all the time

## Steps to reproduce:

- Bake a book with top titled tables

## Screenshots

![2018-07-11_16-58-22](https://user-images.githubusercontent.com/8514591/42601700-1fbbc0be-852c-11e8-812f-eed0b40769ef.png)

# Environment:

- **Instance**:
- **OS**:
- **Browser**: 

# Impact

- **Severity**: 
- **Frequency of occurrence**:

**Comment by lwtchu** [comment]
We should make this bold and centered like the PDF (what you suggested to Alina during scrum today).

**Comment by brittany-johnson** [comment]
<img width="966" alt="screen shot 2018-07-18 at 3 52 36 pm" src="https://user-images.githubusercontent.com/24909007/42907174-a68f08be-8aa2-11e8-96ff-3e6b7725cc4a.png">

**Comment by helenemccarron** [comment]
please note that other padding issues in tables are being resolved here: https://github.com/Connexions/webview/issues/1701

**Comment by Stackblocks** [comment]
Displaying as specified with updated version of content / code.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/58d8f509-7b48-4f67-8b8d-020986288e63)
---
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/c2fafbd6-a6ec-47cf-96f0-3af3419749c1)
---
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/7eda3154-713f-4dec-8131-3070925d7051)
