### ISSUE TITLE
Intro to Business: Critical Thinking Questions

### ISSUE THREAD

**Issue by brittany-johnson** [Connexions/webview#1716]
@clteam18 commented on [Fri Jul 06 2018](https://github.com/Connexions/cnx-recipes/issues/446)

Critical Thinking Case - Global for all Chapters

![image](https://user-images.githubusercontent.com/39794953/42384783-8dab4c3e-8158-11e8-96af-29f4e1f14e8e.png)

**Critical Thinking Questions** under the section **Critical Thinking Case** has no space between paragraph and heading.

---

@openstaxalina commented on [Fri Jul 06 2018](https://github.com/Connexions/cnx-recipes/issues/446#issuecomment-403179020)

For Monday: Larissa should prioritize.

**Comment by brittany-johnson** [comment]
![screen shot 2018-07-17 at 10 41 19 am](https://user-images.githubusercontent.com/24909007/42828564-4e1ea878-89ae-11e8-9df1-854a34f68560.png)
A margin has been added to lists in EOC sections in baked books

**Comment by Stackblocks** [comment]
Displaying as specified with updated version of content / code.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/e31a2f98-79b3-43e6-b641-a37653d11dca)

--

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/99cfd81c-d553-418c-8e03-3ad8d53d23bd)
