### ISSUE TITLE
AP-Physics Check Your Understanding titles

### ISSUE THREAD

**Issue by Adrianltd** [Connexions/webview#1717]
In AP-Physics book there are few content related issues in `Check Your Understanding` sections. There should be `data-element-type="check-understanding"` set in the container `div`.

**Chapter 10.2:**
![3rotationalkinematics2](https://user-images.githubusercontent.com/40228907/42686183-67e3cdc2-8695-11e8-9400-6f16b6a5c87e.png)

**Chapter 21.5:**
![3identifyotherfactors2](https://user-images.githubusercontent.com/40228907/42686184-67ff36a2-8695-11e8-8b52-0b94f8ae8823.png)

**Chapter 28.5:**
![1whatisthemomentuof2](https://user-images.githubusercontent.com/40228907/42686185-681a449c-8695-11e8-9dbf-257f6adcabba.png)

**Chapter 28.4:**
![1supposeaspaceprobe2](https://user-images.githubusercontent.com/40228907/42686186-6836583a-8695-11e8-8522-c1a116885cf9.png)

**Chapter 28.6:**
![1aphotondecays2](https://user-images.githubusercontent.com/40228907/42686187-6851865a-8695-11e8-9abe-9d308b9b1275.png)

**Chapter 28.3:**
![1aparticleistravellingthrough2](https://user-images.githubusercontent.com/40228907/42686188-686a258e-8695-11e8-9c95-22299f9c72b6.png)

**Comment by openstaxalina** [comment]
@marcjeannott could you make these changes on production content when you get the chance?

**Comment by marcjeannott** [comment]
I've added the type="check-understanding" to all of these modules.
