### ISSUE TITLE
University Physics: equation styling regressions

### ISSUE THREAD

**Issue by openstaxalina** [Connexions/webview#1725]
Screenshots are pulled from: https://cnx.org/contents/1Q9uMg_a@10.18:Ej8o3nbb@7/32-Instantaneous-Velocity-and-

There are regressions related to numbered equations in _University Physics_:
![mathregressions1](https://user-images.githubusercontent.com/7863733/42893276-7b1f8a4c-8a79-11e8-9bd7-88e685267b4c.png)

![mathregressions2](https://user-images.githubusercontent.com/7863733/42893315-9b9e54c4-8a79-11e8-9356-e98e2cf51050.png)

Additionally, there is a regression in the centered math in this Example.  The equations are not numbered, but the formatting is incorrect:
![mathregressions3](https://user-images.githubusercontent.com/7863733/42893393-d1027dc0-8a79-11e8-80c0-ff169093f063.png)

Here is the proper display of the same Example in the PDF:
![properdisplayinpdf](https://user-images.githubusercontent.com/7863733/42893550-4237863e-8a7a-11e8-8abc-91d203806f21.png)

**Comment by kerwinso** [comment]
Older versions of the same content appear to look OK. Here's the book version 10.17, one version behind the latest: https://cnx.org/contents/1Q9uMg_a@10.17:Ej8o3nbb@7/32-Instantaneous-Velocity-and-

**Comment by Bkblodget** [comment]
Additional example from 3.1 of Volume 2: 
https://cnx.org/contents/eg-XcBxE@9.9:2fbhPmHK@3/31-Thermodynamic-Systems
<img width="1203" alt="screen shot 2018-07-18 at 11 43 54 am" src="https://user-images.githubusercontent.com/11299035/42895623-141ad84a-8a80-11e8-990a-7eede1302dae.png">

**Comment by hwangange** [comment]
_University Physics Volume 3_, Ch. 10 (Nuclear Physics)

[10.1: Properties of Nuclei](https://cnx.org/contents/rydUIGBQ@9.10:r_n6YAFt@3/101-Properties-of-Nuclei)

<img width="901" alt="screen shot 2018-07-18 at 11 46 41 am" src="https://user-images.githubusercontent.com/12180288/42895774-7bcb9a10-8a80-11e8-8370-4556c970a522.png">
<img width="925" alt="screen shot 2018-07-18 at 11 48 46 am" src="https://user-images.githubusercontent.com/12180288/42895822-9da412ac-8a80-11e8-8e77-0010ba8c2c77.png">

Example 10.1 in Webview:
![image](https://user-images.githubusercontent.com/12180288/42895934-f6936322-8a80-11e8-83cc-3648cbe98c36.png)
The same example (10.1) in PDF:
<img width="694" alt="screen shot 2018-07-18 at 11 52 57 am" src="https://user-images.githubusercontent.com/12180288/42895981-2246f290-8a81-11e8-8ce1-ebd36befb814.png">
<img width="701" alt="screen shot 2018-07-18 at 11 53 11 am" src="https://user-images.githubusercontent.com/12180288/42895999-2c41231a-8a81-11e8-86fd-c0e833e76ffe.png">

**Comment by Bkblodget** [comment]
the text between the numbered equations also looks odd. 3.2 of Volume 2: https://cnx.org/contents/eg-XcBxE@9.9:hZxUdQsI@2/32-Work-Heat-and-Internal-Ener

<img width="891" alt="screen shot 2018-07-18 at 11 52 15 am" src="https://user-images.githubusercontent.com/11299035/42896002-2d22a402-8a81-11e8-808a-214f980e9ed2.png">

**Comment by JoseEscalante6** [comment]
The equations used within this section include numbered and unnumbered equations, but it looks like it is acting incorrectly either way. Chapter 6 Section 3 https://cnx.org/contents/rydUIGBQ@9.10:SO11Ukif@2/63-The-Compton-Effect
![screenshot 12](https://user-images.githubusercontent.com/30252254/42896498-af6a5b48-8a82-11e8-99e4-f1b452b9545e.png)

**Comment by nicolasdamiani** [comment]
Alignment is behaving incorrectly for equations that should be centered, whether or not they are in Examples.
![screen shot 2018-07-18 at 12 09 36 pm](https://user-images.githubusercontent.com/28710954/42896839-c072c5e6-8a83-11e8-9a17-aabaf0e39d7d.png)

**Comment by JoseEscalante6** [comment]
This equation between equations 6.13 and 6.14 is not styling correctly in Chapter 6 Section 2 https://cnx.org/contents/rydUIGBQ@9.10:EW-vVPuy@3/62-Photoelectric-Effect
![screenshot 13](https://user-images.githubusercontent.com/30252254/42896834-bf605182-8a83-11e8-9a74-7e6416f8a99e.png)

**Comment by JoseEscalante6** [comment]
The two equations with right arrows aren't centered on their own line like they are meant to in Chapter 11  Section 1 https://cnx.org/contents/rydUIGBQ@9.10:YjkN816E@3/111-Introduction-to-Particle-P
![screenshot 14](https://user-images.githubusercontent.com/30252254/42897083-7db0d71a-8a84-11e8-9aa6-d8576e3c3040.png)

**Comment by Stackblocks** [comment]
Math displaying much more cleanly after fix is applied.

![image](https://user-images.githubusercontent.com/12678235/42897698-6b63b13e-8a86-11e8-82b0-71f85a27dd32.png)

---

![image](https://user-images.githubusercontent.com/12678235/42897709-7068ed16-8a86-11e8-90b3-3ea65e7e7c1d.png)


---

 
![image](https://user-images.githubusercontent.com/12678235/42897718-75524584-8a86-11e8-8e10-b47d6837a9b8.png)

---

![image](https://user-images.githubusercontent.com/12678235/42897724-7a1963c2-8a86-11e8-80ad-d479e84d8821.png)

**Comment by openstaxalina** [comment]
Confirmed each instance above is fixed on production.  Here's an example that Jose had noted in Vol 3, Chapter 11 Section 2:
<img width="752" alt="screen shot 2018-07-18 at 4 59 36 pm" src="https://user-images.githubusercontent.com/7863733/42910164-13b01aa6-8aac-11e8-86b4-b5102ab32ab0.png">

Further down the page, centered math in an example displays correctly:
<img width="772" alt="screen shot 2018-07-18 at 4 59 46 pm" src="https://user-images.githubusercontent.com/7863733/42910175-200adfde-8aac-11e8-8376-92f6a9b004c0.png">
