### ISSUE TITLE
left pane shows loading message 'This page is not in any books' when page is in a book

### ISSUE THREAD

**Issue by PiotrKozlowski** [Connexions/webview#1728]
Full desc:

https://trello.com/c/WQ4KGS5N/567-bug-left-pane-shows-loading-message-this-page-is-not-in-any-books-when-page-is-in-a-book

@kerwinso @philschatz

**Comment by kerwinso** [comment]
Moved this to `nice.naga` milestone so we can track for 7/30 release.

**Comment by Stackblocks** [comment]
Reported as verified by @kerwinso, closing.
