### ISSUE TITLE
Too small distance between columns

### ISSUE THREAD

**Issue by wilkus27** [Connexions/webview#1730]
There is too small distance between columns in table and the sentences from two different columns are too close to each other. (https://katalyst01.cnx.org/contents/s8Hh0oOc@11.1:LlKfCy5H@4/64-Prokaryotic-Cell-Division)
![table](https://user-images.githubusercontent.com/40228854/43008170-95d4152a-8c3a-11e8-9c68-1e47f88a60e4.JPG)

**Comment by openstaxalina** [comment]
@wilkus27 good find; please continue to look for such tables and please open a new issue with each table.  

We need to try to manually control the column widths for each of these tables using colwidth.  There is no good option for controlling this for CSS because it would affect all tables.

**Comment by openstaxalina** [comment]
@marcjeannott could you bring this up at the next CM roundtable?

**Comment by lwtchu** [comment]
@openstaxalina Talked to Ryan. She says the problem with this isn't the fact that it needs to be set col widths in the content. It's because the text is running right up against the border of each cell. There should be some padding.

**Comment by openstaxalina** [comment]
@helenemccarron could you review the above, and perhaps we can park at a scrum and/or next sprint planning?

**Comment by wilkus27** [comment]
@openstaxalina  I retest it after last deployment and it is displayed correctly now:

![table2](https://user-images.githubusercontent.com/40228854/43206821-d81880a2-9026-11e8-86b4-b370859a6c30.JPG)

**Comment by openstaxalina** [comment]
@wilkus27 thank you!  @helenemccarron FYI - I am going to close this issue.
