### ISSUE TITLE
Dot list in table

### ISSUE THREAD

**Issue by wilkus27** [Connexions/webview#1732]
There is a table with dot list inside. In pdf there are lists without items:

(https://katalyst01.cnx.org/contents/s8Hh0oOc@11.1:qwPV6RBh@5/C--Measurements-and-the-Metric)
![table_con_of_biol](https://user-images.githubusercontent.com/40228854/43084746-94afaaa4-8e99-11e8-88a4-c814dc1c77fb.JPG)

Pdf:
![table_con_of_biol_pdf](https://user-images.githubusercontent.com/40228854/43084796-aaceb488-8e99-11e8-98b1-86738cbe760a.JPG)

**Comment by openstaxalina** [comment]
@helenemccarron I reviewed and prioritized this issue.

**Comment by uskka** [comment]
Issue fixed. Tested on katalyst01. 

![screenshot-katalyst01 cnx org-2018 07 27-13-18-17](https://user-images.githubusercontent.com/40228918/43318050-a6e01a0c-919f-11e8-9874-7e947e1032a9.png)
