### ISSUE TITLE
Two types of modules beginning

### ISSUE THREAD

**Issue by wilkus27** [Connexions/webview#1736]
In Biology for AP at the beggining of the modules we have two informations: "By the end of this section, you will be able to" and "In this section, you will investigate the following questions" but in pdf we have just one information:

katalyst01 (https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:7fPPRIT6@4/11-The-Science-of-Biology)
![by_the_end_1 1](https://user-images.githubusercontent.com/40228854/43131843-51750fd0-8f3a-11e8-98d7-5797cd08b800.JPG)

pdf:
![by_the-end_1 1_pdf](https://user-images.githubusercontent.com/40228854/43131860-5bf1c5c0-8f3a-11e8-89c0-1e318fd6e4d0.JPG)

What is more, when in pdf there is box with "By the end of this section, you will be able to" in webview we see doubled information:

katalyst01 (https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:L2ccw6bD@7/12-Themes-and-Concepts-of-Biol)
![by_the_end_1 2](https://user-images.githubusercontent.com/40228854/43132059-f3369d2a-8f3a-11e8-8d32-e182bb3ecaca.JPG)

pdf:
![by_the_end_1 2_pdf](https://user-images.githubusercontent.com/40228854/43132013-c8ba5f0a-8f3a-11e8-8690-7fedb54683ad.JPG)

**Comment by helenemccarron** [comment]
Biology and AP Biology are expected to have two different types of learning objective, they have different recipes and templates to that effect.

**Comment by helenemccarron** [comment]
This might be a recipe issue. It looks like the content displays both the learning objectives and the metadata abstract. I'll move this to recipes for investigation.

**Comment by helenemccarron** [comment]
Issue moved to [Connexions/cnx-recipes #493](https://github.com/Connexions/cnx-recipes/issues/493) via [**ZenHub**](https://www.zenhub.com/)
