### ISSUE TITLE
Doubled distance between subcaption and figure

### ISSUE THREAD

**Issue by wilkus27** [Connexions/webview#1737]
Probably in all the books (checked in Biology for AP, Biology 2e, Concepts of Biology and College Physics for AP) when figure is in the grey box (e.g. "EVERYDAY CONNECTION", "VISUAL CONNECTION", "EXAMPLE") the distance between it and its subcaption is doubled:

e.g. Biology for AP (https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:7fPPRIT6@4/11-The-Science-of-Biology):
![subcaption_big](https://user-images.githubusercontent.com/40228854/43134290-e341bace-8f41-11e8-88b7-7b0fe1fecfde.JPG)

![subcaption_small](https://user-images.githubusercontent.com/40228854/43134300-e9639cc4-8f41-11e8-954d-0c5d89675ef5.JPG)

**Comment by uskka** [comment]
Works fine. Tested on Biology for AP - katalyst01 and Biology on katalyst01.

![screenshot-katalyst01 cnx org-2018 07 27-11-44-52](https://user-images.githubusercontent.com/40228918/43314249-ae54c952-9192-11e8-879d-626cb9d41ebd.png)
![screenshot-katalyst01 cnx org-2018 07 27-11-45-46](https://user-images.githubusercontent.com/40228918/43314251-afacf3e2-9192-11e8-8680-f09c96b80ace.png)
