### ISSUE TITLE
Issue with big tables

### ISSUE THREAD

**Issue by Stackblocks** [Connexions/webview#1739]
@Stackblocks commented on [Fri Jul 20 2018](https://github.com/Connexions/cnx-recipes/issues/488)

@uskka commented on [Mon Jul 09 2018](https://github.com/Connexions/webview/issues/1705)

Description: When Contents are shown and table is too big, part of the table content is cut out of the screen. There should be mechanism that prevents such behaviour.

Where: Screen from devb/ Accounting / B | Present Values Table Set Rotated (Landscaped at 90°) as Art and Table
https://devb.cnx.org/contents/l6eNxxA-@2.6:YykWtsbi@3/B--Present-Values-Table-Set-Ro

![screenshot-devb cnx org-2018 07 09-15-58-18](https://user-images.githubusercontent.com/40228918/42454985-469448e2-8391-11e8-8ea6-9be424b92938.png)
![screenshot-devb cnx org-2018 07 09-15-58-56](https://user-images.githubusercontent.com/40228918/42454988-4836e6d2-8391-11e8-84a9-3f8f2ca03c3d.png)

---

@helenemccarron commented on [Mon Jul 09 2018](https://github.com/Connexions/webview/issues/1705#issuecomment-403528455)

@openstaxalina I am not sure what we can do CSS wise to fix this type of issue. 

---

@openstaxalina commented on [Mon Jul 09 2018](https://github.com/Connexions/webview/issues/1705#issuecomment-403635479)

@helenemccarron can this be fixed with JavaScript?  I would like to try to include this with Assignable Webview.  The screen won't scroll right, so the content is completely inaccessible/illegible for the user.

---

@PiotrKozlowski commented on [Tue Jul 10 2018](https://github.com/Connexions/webview/issues/1705#issuecomment-403723587)

You can try something like this:
```
.os-table{
  overflow: scroll;
  overflow-y: hidden;
}
```
Then in mobile you will be able to scroll table by swiping and on desktop you can scroll horizontally with `shift + scroll`. Eventually we can add js script which will allow to scroll tables horizontally on desktop also by swiping with mouse.

---

@openstaxalina commented on [Tue Jul 10 2018](https://github.com/Connexions/webview/issues/1705#issuecomment-403898247)

Thank you @PiotrKozlowski !  I am concerned that many people do not know how to use shift + scroll.  How much work is it to add the js scripe that allows scrolling tables horizontally on the desktop with the mouse?  cc @helenemccarron  (Note: this card is still un-prioritized; we can discuss here and try to get this into a future sprint.)

---

@PiotrKozlowski commented on [Wed Jul 11 2018](https://github.com/Connexions/webview/issues/1705#issuecomment-404123303)

So there are scripts for simulating touching on desktops (ex. https://hammerjs.github.io/touch-emulator/). If we can add this script then it should be easy to implement, but propably we do not want another script on webview so we should write our own logic for swiping tables which can be tricky.

<blockquote><div><strong><a href="https://hammerjs.github.io/touch-emulator/">Touch Emulator - Hammer.js</a></strong></div><div>Add multi-touch gestures to your webpage.</div></blockquote>

---

@openstaxalina commented on [Fri Jul 20 2018](https://github.com/Connexions/webview/issues/1705#issuecomment-406688005)

@brittany-johnson will work with @PiotrKozlowski on some ideas for this.

---

@brittany-johnson commented on [Fri Jul 20 2018](https://github.com/Connexions/cnx-recipes/issues/488#issuecomment-406693308)

This issue was moved to recipes because we can fix it by adding an attribute `style="overflow-x:auto;"` to `.os-table`. 
Adding this attribute allows the user to scroll horizontally with their mouse and with their arrow keys to see tables that would normally be cut of and not fully fit in the width of the page. 
If you have any questions about how to do this via the recipes, feel free to ping me! @PiotrKozlowski

**Comment by PiotrKozlowski** [comment]
Merged and ready for testing at #1734 branch.

Please see that this table probably doesn't exists on katalyst01 and you will have to test it on localhost pointed to devb

**Testing scenario:**
To test it you need mouse or touch pad. 
On big tables you should be able to:
 - see scrollbar at the bottom of table and use it
 - click on the table and use arrows to scroll horizontally
 - swipe the table (click + hold and move coursor left / right) (table should scroll horizontally)
 - coursor should also change to grab icon
This behaviour shoudn't exist on smaller tables

**Comment by kerwinso** [comment]
@PiotrKozlowski I deployed the sha `9e9a1b023d2415e651c103ae68efa4d5580a3c41` to qa.cnx.org. I then copied over content here: https://qa.cnx.org/contents/lmUPwlcA@1/Present-Values-Table-Set-Rotat

I am not seeing this fix there. Please advise.

**Comment by PiotrKozlowski** [comment]
@kerwinso I applied this for tables inside parent with `.os-table` class and in your link there is no `.os-table` as it was on devb.

Should I apply this to all tables? And when you are using `.os-table` class?

**Comment by kerwinso** [comment]
@PiotrKozlowski Aha tahnks! After I baked the test collection containing that module, it works fine: https://qa.cnx.org/contents/DXGWD398@2.1:lmUPwlcA@1/A--Present-Values-Table-Set-Ro

I will leave this issue open for now in case the Katalyst QA team wants to verify.

**Comment by uskka** [comment]
@kerwinso We can not test it because this book doesn't exist in katalyst01 and we can not deploy on qa.cnx.org. Piotr's change is no longer visible on qa.cnx.org probably due to deploy from another brunch on this website.

**Comment by Stackblocks** [comment]
I'm able to scroll using trackpad, and by clicking/sliding on the scrollbar at the bottom with updated version of content / code. I am unable to click on the table and use left and right arrow keys to scroll, but I can tab to the table then use arrow keys. @openstaxalina, does this seem like an acceptable set of scrolling options?

![2018-08-02_09-50-46-1](https://user-images.githubusercontent.com/12678235/43591826-cfcfbdde-9639-11e8-86dc-459c526b63a7.gif)

**Comment by Stackblocks** [comment]
Scrolling was deemed acceptable, closing issue.

**Comment by kerwinso** [comment]
Verified on staging, https://staging.cnx.org/contents/3OgZKIqt@1.1:hlZpwRUG@1/A--Present-Values-Table-Set-Ro
