### ISSUE TITLE
Extra header in Science Practice Challenge Questions

### ISSUE THREAD

**Issue by wilkus27** [Connexions/webview#1740]
In Biology for AP in modules with exercises (Key Terms, Chapter Summary, Review Questions, Critical Thinking Questions, Test Prep for AP® Courses, Science Practice Challenge Questions) tasks are numbered one by one, but in the **Science Practice Challenge Questions** there is extra infrormation from which module the exercises are.
(e.g. https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:mQvIJaS1@7.1/Science-Practice-Challenge-Que)
![extra_header](https://user-images.githubusercontent.com/40228854/43144481-8b163dea-8f5d-11e8-8bbb-f91ea4f9a52e.JPG)

In pdf there is just numbering:
![no_header_pdf](https://user-images.githubusercontent.com/40228854/43144534-a5e6006a-8f5d-11e8-8868-b35583d130f0.JPG)

**Comment by helenemccarron** [comment]
This is a recipe issue, the EOC section should not be separated by section. Moving over.

**Comment by helenemccarron** [comment]
Issue moved to [Connexions/cnx-recipes #495](https://github.com/Connexions/cnx-recipes/issues/495) via [**ZenHub**](https://www.zenhub.com/)
