### ISSUE TITLE
Inconsistancy in numbering of figures between webview and pdf

### ISSUE THREAD

**Issue by wilkus27** [Connexions/webview#1744]
The numbering of figures is the same on katalyst01 and pdf to this moment:
https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:Ao-lRbxu@6/75-Metabolism-without-Oxygen
![figure_7 16_kat](https://user-images.githubusercontent.com/40228854/43206078-23e890e6-9025-11e8-9e59-e209d9eedce3.JPG)

PDF:
![figure_7 16_pdf](https://user-images.githubusercontent.com/40228854/43206169-5b736a2c-9025-11e8-8e8c-b7f876e22f34.JPG)

The next figure on katalyst01 have number **7.18** instead of **7.17**:
https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:jh6WGEi0@5/76-Connections-of-Carbohydrate
![figure_7 18_kat](https://user-images.githubusercontent.com/40228854/43206215-79426ed6-9025-11e8-8e4c-d85463003b21.JPG)

PDF:
![figure_7 17_pdf](https://user-images.githubusercontent.com/40228854/43206238-82e72580-9025-11e8-971a-74c96291f839.JPG)

**Comment by helenemccarron** [comment]
This is most likely a recipe issue, moving the issue over.

**Comment by helenemccarron** [comment]
Issue moved to [Connexions/cnx-recipes #494](https://github.com/Connexions/cnx-recipes/issues/494) via [**ZenHub**](https://www.zenhub.com/)
