### ISSUE TITLE
Wrong table in pdf

### ISSUE THREAD

**Issue by wilkus27** [Connexions/webview#1748]
There is wrong table in pdf. On katalyst01 it looks like that (https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:Ml3eLVPo@7.1/Review-Questions)

![diff_table_kat](https://user-images.githubusercontent.com/40228854/43264397-551d86fa-90e6-11e8-9491-69e5a820f34a.JPG)

PDF:

![diff_table_pdf](https://user-images.githubusercontent.com/40228854/43264412-5e044e98-90e6-11e8-909e-b79b5b287b4a.JPG)

Because the table on katalyst01 is numbered, it causes differences in numbering on webview and pdf.

Next table on katalyst01:

![next_table_kat](https://user-images.githubusercontent.com/40228854/43264514-b095b1ec-90e6-11e8-9947-f9d6b5f9dca8.JPG)

Next table on pdf:

![next_table_pdf](https://user-images.githubusercontent.com/40228854/43264535-be2569b0-90e6-11e8-86bf-720a31ccabc6.JPG)

**Comment by openstaxalina** [comment]
It looks like there was some type of errata update to the table after the PDF was generated.  The simplest solution would be to remove the numbering on the table in webview on cnx.org.  That way, the numbering will not be thrown off.  @Bkblodget could you make this table unnumbered in webview?  It's here: https://cnx.org/contents/bDIuMp-w@7.1:xAaCmxuG@6/Laws-of-Inheritance

**Comment by brittweinstein** [comment]
Issue moved to [Connexions/content-managers #195](https://github.com/Connexions/content-managers/issues/195) via [**ZenHub**](https://www.zenhub.com/)
