### ISSUE TITLE
a11y: Ensure the solution is read when exercise "Show Solution" is clicked (aria-live?)

### ISSUE THREAD

**Issue by brittweinstein** [Connexions/webview#1757]
@brittweinstein commented on [Thu Jul 26 2018](https://github.com/Connexions/content-managers/issues/165)

From https://drive.google.com/file/d/0BxiTbl6K_ZNRelpxRlkwYkZnb3c/view

Issue 10: There is no feedback for 'show solution' buttons
Video example: https://drive.google.com/file/d/0B2fFZC6BqvTLTVJkUXdRUmN1UVk/view?usp=sharing
Reference to standards
1.3.1 Info and Relationships: Information, structure, and relationships conveyed through presentation can be
programmatically determined or are available in text. (Level A)
Suggestion
After selecting the ‘show solution’ button screen reader should read the feedback with the correct answer.

**Comment by openstaxalina** [comment]
@helenemccarron will analyze and assign points.

**Comment by brittweinstein** [comment]
Can slide if needed

**Comment by helenemccarron** [comment]
Addressed in PR #1816

**Comment by Stackblocks** [comment]
With this in place clicking on `[Show Solution]` causes JAWS to read out `ｏｐｅｎ　ｂｒａｃｋｅｔ　ｓｈｏｗ　ｓｏｌｕｔｉｏｎ　ｃｌｏｓｅ　ｂｒａｃｋｅｔ　ｕｓｅ　ｊａｗｓ　ｋｅｙ　ｐｌｕｓ　ｍ　ｔｏ　ｍｏｖｅ　ｔｏ　ｃｏｎｔｒｏｌｌｅｄ　ｅｌｅｍｅｎｔ　ｓｈｏｗ　ｈｉｄｅ　ｓｏｌｕｔｉｏｎ` instead of reading out the solution. Removing from petty.pegasus and sliding.

**Comment by openstaxalina** [comment]
Since this issue will be fixed with baked books, we could defer this change.   In Larissa's terms, "If you're bored, do this one."

**Comment by PiotrKozlowski** [comment]
This is ready for testing but it was merged into #1963

**Comment by uskka** [comment]
Works fine. Tested on katalyst01.
https://drive.google.com/file/d/1N06YF5VYjiKa4SORNcvnB9OMwZKRNnDh/view?usp=sharing
