### ISSUE TITLE
Webview - accessibility issues backlog

### ISSUE THREAD

**Issue by brittweinstein** [Connexions/webview#1760]
@brittweinstein commented on [Tue Jul 24 2018](https://github.com/Connexions/content-managers/issues/120)

https://trello.com/b/8DKh5iQR/cnx-backlog?menu=filter&filter=label:accessibility

**Comment by openstaxalina** [comment]
@openstaxalina to make these into GitHub issues.

**Comment by openstaxalina** [comment]
Broke out into #1943 and #1944.  Closing this issue.
