### ISSUE TITLE
Dots appear in table content

### ISSUE THREAD

**Issue by uskka** [Connexions/webview#1764]
Description: There are no dots in pdf, dots should be removed. Issue was fixed for Concepts of Biology(https://github.com/Connexions/webview/issues/1732 )but still appears in other biology books.

Biology 2e: 
https://katalyst01.cnx.org/contents/jVCgr5SL@8.197:Rhq7pkI2@3/C--Measurements-and-the-Metric
Biology for AP® Courses:
https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:-p-m85Qc@4/C--Measurements-and-the-Metric

![screenshot-katalyst01 cnx org-2018 07 30-10-07-51](https://user-images.githubusercontent.com/40228918/43385777-ed0dfe60-93e1-11e8-8b1e-507ed646c065.png)

**Comment by helenemccarron** [comment]
@openstaxalina this might be more of a content issue, should we remove all list bullets in tables or should the content have control over what can have bullets or not?

**Comment by openstaxalina** [comment]
@helenemccarron I agree; the content should control what can have bullets or not.  @uskka would you be able to share other examples like this, so we can correct them in the content?

**Comment by wilkus27** [comment]
Examples from Biology for AP finded on katalyst01:
(1) https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:FL8ttb-h@5/121-Mendels-Experiments-and-th -> Table.12.1

(2) https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:jsEMosra@5/211-Viral-Evolution-Morphology -> Table.21.1

(3) https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:-p-m85Qc@4/C--Measurements-and-the-Metric

**Comment by brittweinstein** [comment]
Issue moved to [Connexions/content-managers #194](https://github.com/Connexions/content-managers/issues/194) via [**ZenHub**](https://www.zenhub.com/)
