### ISSUE TITLE
 Link to learning with youtube link doesn't scale 

### ISSUE THREAD

**Issue by uskka** [Connexions/webview#1765]
**Description**: Link to learning with youtube link, doesn't scale when website gets zoomed out. Works fine on katalyst01 where the book is beaked. 

**Where**: cnx,  biology 2e, screen from Safari. 

https://cnx.org/contents/jVCgr5SL@13.1:rinsWGYq@9/Groups-of-Protists

![image](https://user-images.githubusercontent.com/40228918/43393238-a13e41ba-93f6-11e8-9680-cc225bed583c.png)

**Comment by PiotrKozlowski** [comment]
This is fixed on baked books. Should we apply the same css for not baked books or should you bake content on production?
cc @helenemccarron

**Comment by helenemccarron** [comment]
@openstaxalina This might be a question for you, this might be a global issue but would imply heavy regression testing.

**Comment by openstaxalina** [comment]
@helenemccarron I would like to fix this for baked books **only**. cc @Stackblocks

**Comment by uskka** [comment]
Issue already fixed for baked books.
