### ISSUE TITLE
Preface: reduce padding before a nested section header

### ISSUE THREAD

**Issue by openstaxalina** [Connexions/webview#1766]
Location: https://content02.cnx.org/contents/o0xnhd_t@7.1:44D1SI_3@1/Preface

![prefaceheaders1](https://user-images.githubusercontent.com/7863733/43422072-385d917e-940e-11e8-8b0a-2c671f978895.png)

This will likely apply to all business titles.  Need to decide whether it applies to all baked books.  All baked books should have a similar cnxml structure in the preface.

**Comment by openstaxalina** [comment]
![prefaceheaders2](https://user-images.githubusercontent.com/7863733/43422268-d1e1a0c4-940e-11e8-9d8d-00bb55f53107.png)

**Comment by helenemccarron** [comment]
![2018-07-31_10-45-57](https://user-images.githubusercontent.com/8514591/43470741-edea2ca0-94ae-11e8-920c-b4fe904e8eb9.png)

**Comment by Stackblocks** [comment]
Displaying as specified with updated version of content / code.
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/d8e1d8be-83b9-4e6c-b3f4-7eab1cb4bb35)
