### ISSUE TITLE
Problem with distance between QR code and text - 2

### ISSUE THREAD

**Issue by wilkus27** [Connexions/webview#1767]
There is no distance between QR code and text again:
https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:UOJ2Y4LM@4/155-Ribosomes-and-Protein-Synt

![qr_again](https://user-images.githubusercontent.com/40228854/43448514-76565b82-94ae-11e8-95ca-fa402c1e7233.JPG)

**Comment by wilkus27** [comment]
#1681

**Comment by PiotrKozlowski** [comment]
Merged and ready for testing at #1734 branch

**Comment by wilkus27** [comment]
Verified on katalyst01:

![qr](https://user-images.githubusercontent.com/40228854/43514895-79cfbb04-9581-11e8-9d2e-a346cf365142.JPG)
