### ISSUE TITLE
Unnumbered table in pdf

### ISSUE THREAD

**Issue by wilkus27** [Connexions/webview#1769]
On katalyst01 table is numbered but in pdf it isn't.

katalyst01: (https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:ghsF7IPX@7.1/Test-Prep-for-AP-Courses)

![numbered_table_kat](https://user-images.githubusercontent.com/40228854/43453955-ce7ea820-94bb-11e8-96ea-e4e9a3dbced2.JPG)

PDF:

![unnumbered_tab_pdf](https://user-images.githubusercontent.com/40228854/43453967-d88707b8-94bb-11e8-9c39-29d3a484ab94.JPG)

It causes inconsistency in numbering:

katalyst01:

![second_tab_kat](https://user-images.githubusercontent.com/40228854/43454011-fca351ba-94bb-11e8-958a-f5d653e8e8e0.JPG)

PDF:

![second_tab_pdf](https://user-images.githubusercontent.com/40228854/43454027-04afb4de-94bc-11e8-94b3-0b334d39bd10.JPG)

**Comment by wilkus27** [comment]
The same problem: https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:f_wVv68_@7.1/Test-Prep-for-AP-Courses ->Table.19.3 and Table.19.4 are unnumbered in pdf:

![another_tab_pdf](https://user-images.githubusercontent.com/40228854/43455453-2dd39106-94c0-11e8-8c75-766e4e6e402d.JPG)

**Comment by openstaxalina** [comment]
@helenemccarron I didn't find a special class that would have caused these to be unnumbered in the PDF.  Do you think there is a rule in the CCAP Template that does not allow tables in EOC to be numbered?

**Comment by wilkus27** [comment]
The same problem in College Physics for AP (https://katalyst01.cnx.org/contents/jQSmhtXo@16.36:eLDpZlgR@16.36/Test-Prep-for-AP-Courses)

katalyst01:

![table_ap_ph](https://user-images.githubusercontent.com/40228854/43784562-b1dbff7a-9a64-11e8-9552-89721448ebc7.JPG)

PDF:

![table_ap_ph_pdf](https://user-images.githubusercontent.com/40228854/43784585-bd0203e0-9a64-11e8-8196-0322cf6ca349.JPG)
