### ISSUE TITLE
a11y: Enable AssistiveMML so MathML is read by screenreaders

### ISSUE THREAD

**Issue by brittweinstein** [Connexions/webview#1773]
From https://drive.google.com/file/d/0BxiTbl6K_ZNRelpxRlkwYkZnb3c/view "Issue 7"

Reference to standards
1.1.1 Non-text Content: All non-text content that is presented to the user has a text alternative that serves the
equivalent purpose (Level A)
Suggestion
Add correct alt text to formulas to make them accessible.

#Description
This video (prepared by a vendor who did an audit on our Biology book) — https://drive.google.com/file/d/0B2fFZC6BqvTLQnRQUTlTZXdxcmM/view — shows MathML not being read by a screenreader (mainly in the last few seconds).

Phil S.'s research indicates we need to:

"enable the `AssistiveMML` extension introduced in http://docs.mathjax.org/en/latest/upgrading/whats-new-2.6.html?highlight=screenreader (fortunately we are running v2.6.1 so no need to fully regression test all the content with math in it)"

#Impact
* **Severity**: [x] High [ ] Medium  [ ] Low
* **Frequency of Occurrence**: [ ] High [x] Medium  [ ] Low

#Acceptance
MathML equations are read by a screenreader in web view.

Link to PR: https://github.com/Connexions/webview/pull/1635 ![image.png](https://images.zenhubusercontent.com/5a01faba8a75884b90866af7/812133c9-434b-4de7-9b4b-55ec231cd9f1)

**Comment by kerwinso** [comment]
@alancooke1 has his machine back and will comment in this card when he tests on prod.

**Comment by kerwinso** [comment]
Alan says: Improvements to JAWS' MathML reading are consistent on Production. It parses equations, greek characters, and fractions much better than it had previously
