### ISSUE TITLE
enable swiping big tables with mouse for desktop users

### ISSUE THREAD

**Issue by brittweinstein** [Connexions/webview#1774]
swipe-tables.js is allowing users swiping tables with their mouse (it's imitating touching) instead of using scrollbar at the bottom (it's working like on the trello boards where you ...

# Test plan
Merged and ready for testing at #1734 branch.

Please see that this table probably doesn't exists on katalyst01 and you will have to test it on localhost pointed to devb

Testing scenario:
To test it you need mouse or touch pad.

On big tables you should be able to:

- see scrollbar at the bottom of table and use it
- click on the table and use arrows to scroll horizontally
- swipe the table (click + hold and move coursor left / right) (table should -scroll horizontally)
- cursor should also change to grab icon

This behaviour shoudn't exist on smaller tables

https://github.com/Connexions/webview/pull/1741
https://github.com/Connexions/webview/issues/1739

Per Kerwin: Failed initial tests on qa. I see no scrollbar in the big table here: https://qa.cnx.org/contents/lmUPwlcA@1/Present-Values-Table-Set-Rotat

**Comment by Stackblocks** [comment]
Should this be closed alongside https://github.com/Connexions/webview/issues/1739 ?

**Comment by brittweinstein** [comment]
Sounds good! I know Kerwin looked at this and I believe this morning we said we were comfortable releasing :)

**Comment by kerwinso** [comment]
Re-opening to track testing on staging.

**Comment by kerwinso** [comment]
Verified on staging, https://staging.cnx.org/contents/3OgZKIqt@1.1:hlZpwRUG@1/A--Present-Values-Table-Set-Ro
