### ISSUE TITLE
Incorrect display of the list

### ISSUE THREAD

**Issue by wilkus27** [Connexions/webview#1777]
When A,B,C,D list appears in the pdf, such item displays from the new line:
![list_in_text_pdf](https://user-images.githubusercontent.com/40228854/43516590-4607fb74-9586-11e8-9cc0-914fff4c26e0.JPG)

On webview items are in line:
(https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:3E6YBlds@7.1/Science-Practice-Challenge-Que)

![list_kat](https://user-images.githubusercontent.com/40228854/43516635-7848d176-9586-11e8-8300-432ecfb981cb.JPG)

**Comment by helenemccarron** [comment]
@openstaxalina is this something we need to address? First we cannot target only Biology, so this may have wide implications, second, I think this doesn't look bad.

**Comment by openstaxalina** [comment]
@helenemccarron this display is not good; the block of text is difficult to parse and the letters ("A", "B", etc.) are closer to the _preceding_ content.  Let's brainstorm on this one.

@wilkus27 do you have a rough count of how many items like this you found in AP Biology?

**Comment by wilkus27** [comment]
@openstaxalina I noticed that this issue appears through the book just in module **Science Practice Challenge Questions**. If it is needed I can find all of  the exercises where this problem occurs. Up to the 17th module I found 34 items like this.

**Comment by helenemccarron** [comment]
Apologies, this is indeed a bug. The `p` are inline, they _should_ be after @PatBoj  fix for the problems and solutions containers. @PatBoj do you mind taking a look?

**Comment by PatBoj** [comment]
@helenemccarron First paragraph `p` should be displayed as `inline` while other ones should be displayed as `block`. This is how it looks like after my changes. I've done this on my browser only so it's not fixed yet.
![image](https://user-images.githubusercontent.com/20907906/43887842-3d8fb74e-9bc0-11e8-8d86-037c4e9edbc3.png)

**Comment by helenemccarron** [comment]
Perfect, @PatBoj , that's what I thought! Can you please link to this issue so it gets tested along with your changes?

**Comment by PatBoj** [comment]
Ok @helenemccarron, no problem. This issue #1636 is related to this one.

**Comment by wilkus27** [comment]
Verified on katalyst01:

![list](https://user-images.githubusercontent.com/40228854/43957517-5dd7820a-9ca8-11e8-819e-50ace7133698.JPG)
