### ISSUE TITLE
Book Summary/Abstract + Keywords Do Not Populate to CNX from Legacy

### ISSUE THREAD

**Issue by brittweinstein** [Connexions/webview#1780]
#Scenario
A book summary, or abstract, can be filled in on legacy but not show on CNX.org.

#Steps to Reproduce
1. Navigate to cnx.org
2. Click "Introduction to Sociology 2e" on the homepage
3. Scroll to the bottom of the page
4. Click "More Information"
5. Note that the summary is blank
6. Click "Legacy Site" in the top right
7. Once the page loads, click the collection title "Introduction to Sociology 2e"
8. Note that the summary IS filled in: https://legacy.cnx.org/content/col11762/1.8

* **Product**: [ ] Tutor   [ ] Concept Coach [ ] OS Web [ ] Content Production Toolkit [x] CNX

* **How many times were you able to reproduce the issue?** Multiple
* **Images or Screenshots Included:** [ ] Yes  [x] No  (_attach below_)

#Environment:

* **Instance**: [x] production  [ ] qa  [ ] staging  [ ] dev  [ ] content
* **OS**: [x] Mac OSX  [ ] Windows  [ ] iOS  [ ] Android
* **Browser**: [x] Chrome  [ ] Firefox  [ ] Safari  [ ] Opera  [ ] IE  [ ] Edge

#Impact

* **Severity**: [ ] High [x] Medium  [ ] Low
* **Frequency of Occurrence**: [x] High [ ] Medium  [ ] Low

See thread here: https://openstax.slack.com/archives/C0LA54Q5C/p1532623950000197

Ross sez:

Bey and I just walked through this. There's multiple, interacting bugs, none of them in neb/press. The already mentioned lack of html_abstract() conversion in the DB. For both abstract and keywords, the 'create a legacy collection from DB' is missing both keywords and abstract, so they're not getting copied back.

Needs PRs attached

Needs regression testing in legacy and batch.

**Comment by kerwinso** [comment]
Ross to attach PRs and also open a new PR for cnx-deploy.
Bey & Kerwin to come up with something resembling a test plan

**Comment by reedstrm** [comment]
https://github.com/Rhaptos/Products.RhaptosRepository/pull/19

https://github.com/Rhaptos/Products.RhaptosModuleStorage/releases/tag/v1.2.2

(Apparently, I did that one directly :-) )

**Comment by reedstrm** [comment]
Note that conversion of cnxml to html abstract is still missing

**Comment by brittweinstein** [comment]
@Bkblodget to create new card for ^^^

**Comment by kerwinso** [comment]
new abstracts will publish and show up in legacy, but not in webview (until cnxml to html abstract) is fixed

**Comment by kerwinso** [comment]
Initial test plan thoughts:
> I'm thinking we make a series of publishes (with minor changes to keywords and/or abstract) at the collection level on legacy, and then verify that *a.* the keywords and abstract are still there and *b.* that the changes made it through
