### ISSUE TITLE
Placeholder: Webview Test Automation

### ISSUE THREAD

**Issue by brittweinstein** [Connexions/webview#1781]
Legacy2Press Tests: No issues
Webview Tests: Issues with functionality 

The goal is to reduce the burden of releasing Webview. 

Definition of Done: When Mike merges PR and TestRail cards are complete with all passing rates. 

Currently blocked on a few test cases due to bugs on Webview:
https://github.com/openstax/cnx-automation/issues/38 
Bug card for this is in backlog:https://trello.com/c/DL7xEWon/226-book-summaries-inconsistently-populate-to-new-web-view
https://github.com/openstax/cnx-automation/issues/98 

Assigning Kerwin; the QA interns are working on this now.

**Comment by kerwinso** [comment]
Work on this is always in progress, but we are at a point now where we can start integrating automated webview tests into our "real-life" testing cycle! This is a big step forward.

**Comment by kerwinso** [comment]
We want to get to a point where automating tests are part of the work for every new feature. As for this card, it will probably remain open for awhile since we are constantly adding regression tests, which then need to be automated.
