### ISSUE TITLE
Add canonical link to PDF downloads

### ISSUE THREAD

**Issue by brittweinstein** [Connexions/webview#1782]
High priority task from SEO review: google indexes the PDF downloads, and returns links to them as reasonably high quality results. Rather than blocking indexing the PDFs, we need to add rel-canonical links. This will require code in nginx static file server to lookup the UUID for any given book, based on the existing PDF link Or, we rework the link to somehow include the UUID (query param at end?)

SEE PAGE 57 IN PRESENTATION FOR INSTRUCTIONS https://drive.google.com/file/d/1ApcddmwyOtRXMladfh0-9kzcp4-k0UT3/view 

## PRs
https://github.com/Connexions/cnx-archive/pull/589
https://github.com/Connexions/cnx-archive/pull/591

## Test plan
1. Load a book
1. Open Dev Tools
1. Click PDF download link
1. Filter in Network activity for 'pdf'
1. Appropriate entry will look like: `prealgebra-13.1.pdf`
1. In response headers, look for something that looks like this: 
`Link: <https://staging.cnx.org/contents/caa57dab-41c7-455e-bd6f-f443cda5519c/prealgebra> ;rel="Canonical"` *(no version numbers in the URL)*
1. Going to the link inside `Link` header should land on the first intro module page of the book, not the preface.

## Acceptance Criteria
-Book PDF should point to first intro module page of book. (NOT preface)
-Module PDFs should point to that module in the master book.
-Canonical tags should not be added to Cloudfront URLs - there is a separate task addressing those.

**Comment by brittweinstein** [comment]
@reedstrm to split this card between both books and modules work.

**Comment by reedstrm** [comment]
This is on hold pending decision on what we should provide for google on the page that we land on at the canonical link.

**Comment by Bkblodget** [comment]
Courtney will join scrum on 8/23 to discuss SEO decisions

**Comment by kerwinso** [comment]
Ross says:
1) Does not show up in the PDF at all - it's in the HTTP headers - so needs to be tested by looking at those headers - there are a number of ways to do that, either in browser, or at the commandline.
2) We still have some that are served - that part is _not_ in the currently releasable code, since I don't have the canonical-book info in the DB yet. (also needed for the archive and other page links, BTW)
3) This will have no impact on cloudfront - this is not a change in the PDF, it is a change in how the PDF is served; and besides, we don't host these files there. :slightly_smiling_face:

**Comment by kerwinso** [comment]
@reedstrm Can you please specify where to find the http headers and what to look for? Also feel free to send the paper you mentioned if you think that would help. Thanks!

**Comment by kerwinso** [comment]
Clicking on https://staging.cnx.org/exports/caa57dab-41c7-455e-bd6f-f443cda5519c@13.1.pdf/prealgebra-13.1.pdf returns this as part of the response header: 
`Link: <https://staging.cnx.org/contents/caa57dab-41c7-455e-bd6f-f443cda5519c@13.1/prealgebra-13.1> ;rel="Canonical"`

Does canonical include version number? @reedstrm to fwd documentation to @kerwinso.

**Comment by kerwinso** [comment]
@reedstrm says that canonical should NOT include version number. So please fix that (also tests in cnx-archive). :)

**Comment by reedstrm** [comment]
Fixed in #591 - requested @Dantemss  and @BryanEliDimas for review.

**Comment by kerwinso** [comment]
This is what it looks like on qa now:
![image](https://user-images.githubusercontent.com/11298165/45060420-563fb000-b065-11e8-9746-c377aad97017.png)

**Comment by kerwinso** [comment]
Passed on staging. Looks like this now: 
`Link: <https://staging.cnx.org/contents/caa57dab-41c7-455e-bd6f-f443cda5519c/prealgebra> ;rel="Canonical"`

![image](https://user-images.githubusercontent.com/11298165/45117590-a711e000-b11b-11e8-8105-c645356573ab.png)
