### ISSUE TITLE
Incorrect footnote format

### ISSUE THREAD

**Issue by wilkus27** [Connexions/webview#1788]
The same problem as in issue #1677 : 

(1) https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:qn1hGEbS@6/122-Characteristics-and-Traits
![footnote](https://user-images.githubusercontent.com/40228854/43583841-fdc263c8-9660-11e8-8baa-7050c0552351.JPG)

Other examples:
(2) https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:IZVC8cIx@4/132-Chromosomal-Basis-of-Inher

(3) https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:BvHXZ0LI@6/142-DNA-Structure-and-Sequenci

**Comment by helenemccarron** [comment]
cc @openstaxalina

**Comment by openstaxalina** [comment]
Issue moved to [Connexions/content-managers #200](https://github.com/Connexions/content-managers/issues/200) via [**ZenHub**](https://www.zenhub.com/)
