### ISSUE TITLE
Table align issue

### ISSUE THREAD

**Issue by uskka** [Connexions/webview#1789]
Description: Table content is centered while the table header is left aligned. 

Where : https://katalyst01.cnx.org/contents/Ax2o07Ul@11.32:RCFtg_5-@7/61-Rotation-Angle-and-Angular-

![screenshot-katalyst01 cnx org-2018 08 02-16-49-07](https://user-images.githubusercontent.com/40228918/43592059-08d851fa-9675-11e8-9726-b215b2d7dd41.png)

**Comment by PiotrKozlowski** [comment]
This is probably content issue because in this table `mathml` is generated as `<math display="block">` so MathJax is generating this as a block.

In other table: https://katalyst01.cnx.org/contents/1Q9uMg_a@10.18:7P5bvslo@5/C--Fundamental-Constants `mathml` starts with `<math display="inline">` and then it's generated properly.

Should we force MathJax to be always inline inside of the tables?

**Comment by helenemccarron** [comment]
CC @openstaxalina

**Comment by wilkus27** [comment]
The same problem in College Physics for AP **Table 6.1** (https://katalyst01.cnx.org/contents/jQSmhtXo@16.36:M4Nu7PGW@2/61-Rotation-Angle-and-Angular-)****

**Comment by openstaxalina** [comment]
It is left aligned in the PDF:
<img width="251" alt="screen shot 2018-08-06 at 8 55 22 pm" src="https://user-images.githubusercontent.com/7863733/43749765-10af5fd8-99bb-11e8-82b5-b94041f218cc.png">

@helenemccarron is there something in the CCAP template that is forcing the math to be left-aligned?  I would feel more comfortable making a decision about left-aligning math if we had already made this decision for the PDF.  Please also advise - would this affect all math in all tables in baked books?

**Comment by helenemccarron** [comment]
@openstaxalina after poking at the CNXML, I tested `<entry align="left">` and `<entry align="right">` and here are the results on devb: https://devb.cnx.org/contents/s9dMX57l@1.3:Y6Fh4O2c@4/61-Rotation-Angle-and-Angular-
The PDF defaults all tables to left align in AP physics, but we cannot do that in Webview. I think changing the content to display the tables cells as desired is a better option for controlling tables.

**Comment by openstaxalina** [comment]
Okay, I am going to move this to the content-managers repo.  cc @helenemccarron , @PiotrKozlowski

**Comment by openstaxalina** [comment]
Issue moved to [Connexions/content-managers #214](https://github.com/Connexions/content-managers/issues/214) via [**ZenHub**](https://www.zenhub.com/)
