### ISSUE TITLE
scaled-down images' captions should scale down with the image

### ISSUE THREAD

**Issue by lwtchu** [Connexions/webview#1791]
![image](https://user-images.githubusercontent.com/12678235/43591448-fd7eb2b8-9638-11e8-9558-6a8c09a04941.png)
Caption to go to 60% with the image.

**Comment by tomjw64** [comment]
If it is desired for captions to scale down with the images, then we can use a recipe change to copy the `scaled-down` class on the media tags to the encompassing `os-figure`, the apply the smaller width to both
`.scaled-down > img` 
and
`.scaled-down > [data-type="media"] > img`

**Comment by openstaxalina** [comment]
*Decision:* We will not do recipe magic.  We will put the scaled-down class on the figure tag if there is on; on the media tag if there is no figure tag.  This will be a ornery.orthrus.junior fix.
