### ISSUE TITLE
fetch exercises by nickname

### ISSUE THREAD

**Issue by kerwinso** [Connexions/webview#1795]
info is in https://github.com/Connexions/cnx-publishing/pull/221

and 
https://trello.com/c/Y6pftTpZ/577-cnx-code-fetch-exercises-by-nickname?menu=filter&filter=label:release-2018.08.13

---
This work is needed to support listing and referring to assessments by a "nickname".

Per Ross - I concur w/ 2 days - there's both Webview/JS work and PDF pipeline work

Story card: https://trello.com/c/JeVQGCsD/573-change-request-exercises-support-a-nickname-so-that-in-the-future-tutor-can-fetch-exercises-via-that-nickname-or-question-id

#Acceptance
- Browse to a module that includes an exercise using its nickname in webview (or create one that looks something like this: https://github.com/Connexions/webview/blob/master/test/data/exercises/ex004.html)
- The exercise should render properly.
- Generate a BAKED pdf that includes this module.
- The exercise should appear in the baked pdf.

**Comment by kerwinso** [comment]
@Dantemss to add link to test module

**Comment by Dantemss** [comment]
@kerwinso added a link but I only have the html version. Will probably need content team help to generate the required cnxml to obtain this html.

**Comment by kerwinso** [comment]
What we discovered in group testing session with CMs: (Alina, Ryan, Larissa)

- exercise with nickname does not appear in legacy (https://legacy-qa.cnx.org/content/m68711/latest/?collection=col27787/1.1)
- module needs to be inside a BAKED collection (e.g., with print parameter 'University Physics w/ recipe') -- cannot be a standalone module
- does _not_ work in PDF -- vendor needs to rely on webview for testing

## Test results
1. Exercise with nickname does successfully appear in webview here -- collection with recipe:
https://qa.cnx.org/contents/c23f6e52-5d6c-4026-8692-d50b83dc3e58@1.1

1. Does NOT appear in a collection WITHOUT recipe:
https://qa.cnx.org/contents/wj9uUl1s@2.1:Z0le6ogO@1/APUSH-Nickname-Test

1. Also, the baked PDF does NOT render the exercise: 
https://legacy-qa.cnx.org/content/col27787/latest/pdf

Per @openstaxalina , this is acceptable for 8/13/18 release to meet vendor requirements. I will need to test on staging.

We should discuss if we need to create new issues to address not being able to fetch exercises by nickname in an _un_-baked collection.

**Comment by kerwinso** [comment]
Need exercises-staging to be updated in order to test this on staging.cnx.org. Deployment should happen tonight (per Greg).

**Comment by kerwinso** [comment]
Exercise fetch by nickname working on staging (col25580): https://staging.cnx.org/contents/95FDHlA1@1.1:NSxVhMil@1/Nickname-Test

Successfully pulled 17194 from exercises-staging.
