### ISSUE TITLE
Two similar tables have different padding in it's content

### ISSUE THREAD

**Issue by uskka** [Connexions/webview#1796]
Description: Two similar tables have different padding in it's content which looks bad. They should have the same padding. 

https://katalyst01.cnx.org/contents/Ax2o07Ul@11.32:cjQyhWg-@7/Useful-Information

![screenshot-katalyst01 cnx org-2018 08 03-09-35-29](https://user-images.githubusercontent.com/40228918/43630523-d828a866-9700-11e8-8be0-e856b08d99d8.png)

**Comment by PiotrKozlowski** [comment]
For now width of columns depends on the length of longest word. 
Btw. Those tables doesn't have `<thead>`

**Comment by openstaxalina** [comment]
The current behavior is acceptable; see the screenshot of the same content in the PDF:

<img width="382" alt="screen shot 2018-08-06 at 8 29 50 pm" src="https://user-images.githubusercontent.com/7863733/43748905-83b09c76-99b7-11e8-827d-4066bbff3786.png">

I am going to close this issue.
