### ISSUE TITLE
Business Ethics - Spacing after endnotes

### ISSUE THREAD

**Issue by brittweinstein** [Connexions/webview#1799]
@mwest-WWprod commented on [Thu Jul 19 2018](https://github.com/Connexions/oer.exports/issues/3713)

content01
GLOBAL - Webview

No space is included in the Webview after endnotes; endnotes should have space between endnote number and start of text. 

![endnote spacing_webview](https://user-images.githubusercontent.com/19212926/42971181-651adf98-8b79-11e8-8d33-936d85608525.png)

---

@openstaxalina commented on [Thu Aug 02 2018](https://github.com/Connexions/oer.exports/issues/3713#issuecomment-410127296)

This might be fixed by: https://github.com/Connexions/webview/issues/1700
If this is still an issue, we will move this issue to webview or cnx-recipes.

**Comment by helenemccarron** [comment]
![image](https://user-images.githubusercontent.com/8514591/43856202-7fd1c0d8-9b0d-11e8-907d-fc66a1d3749e.png)

**Comment by Stackblocks** [comment]
Displaying as specified with updated version of content / code.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/65bed8a2-1121-455e-ae4c-53e8f323acc2)
