### ISSUE TITLE
Too long distance between words in table

### ISSUE THREAD

**Issue by helenemccarron** [Connexions/webview#1800]
@wilkus27 commented on [Thu Aug 02 2018](https://github.com/Connexions/cnx-recipes/issues/519)

The problem from issue #459 also occurs in Biology for AP:
(1) https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:qZUaLE-Z@7.1/Science-Practice-Challenge-Que -> table 6.2
![distance_header](https://user-images.githubusercontent.com/40228854/43583335-871f0e5c-965f-11e8-88b5-2b6265ba94bd.JPG)

Other examples:
(2) https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:7ExM0p8o@7.1/Science-Practice-Challenge-Que -> table 10.5

(3) https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:TBWIYI1m@7.1/Science-Practice-Challenge-Que -> table 13.1

(4) https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:xBv3uJqm@7.1/Science-Practice-Challenge-Que -> table 35.1

**Comment by PiotrKozlowski** [comment]
Those headings have `<div data-type="newline" id="77388"><br></div>` after each word so it looks like content issue.

Also you probably wanted to reference `459` from `cnx-recipes` https://github.com/Connexions/cnx-recipes/pull/459

![th](https://user-images.githubusercontent.com/31478212/43701140-6c9117e4-9955-11e8-8b5e-24b8876cfc6d.png)

**Comment by openstaxalina** [comment]
Issue moved to [Connexions/content-managers #199](https://github.com/Connexions/content-managers/issues/199) via [**ZenHub**](https://www.zenhub.com/)
