### ISSUE TITLE
Issue with math symbols in tables

### ISSUE THREAD

**Issue by helenemccarron** [Connexions/webview#1802]
@uskka commented on [Thu Aug 02 2018](https://github.com/Connexions/cnx-recipes/issues/518)

Description: Math symbols in tables are centred and have a big padding while the rest of the content is not centred which makes the tables to look like something broke. 

Where: katalyst01 / College Physics / Useful Information
https://katalyst01.cnx.org/contents/Ax2o07Ul@11.32:cjQyhWg-@7/Useful-Information

![screenshot-katalyst01 cnx org-2018 08 02-12-37-22](https://user-images.githubusercontent.com/40228918/43579383-3887e3f2-9652-11e8-9d34-1f7fdd46dba1.png)
![screenshot-katalyst01 cnx org-2018 08 02-12-59-47](https://user-images.githubusercontent.com/40228918/43579930-f38ccce8-9653-11e8-8bbe-02318bd0aa44.png)

---

@helenemccarron commented on [Fri Aug 03 2018](https://github.com/Connexions/cnx-recipes/issues/518#issuecomment-410285692)

Issue moved to [Connexions/webview #1801](https://github.com/Connexions/webview/issues/1801) via [**ZenHub**](https://www.zenhub.com/)

**Comment by PiotrKozlowski** [comment]
If you will inspect those equations then you can see `<script>` tag next to them and inside of it there is `mathml` from which MathJax was generating equation.

For centerd equations `mathml` **before rendering** had `display="block"` and this is why MathJax is generating those as a blocks. 

I assume that author can set `mathml` to be `inline` or `block` < you can inspect other elements to see that their `mathml` **before rendering** had `display="inline"`

**Comment by openstaxalina** [comment]
Confirmed this displays properly in the PDF; we should emulate that behavior:

<img width="320" alt="screen shot 2018-08-06 at 8 28 11 pm" src="https://user-images.githubusercontent.com/7863733/43748849-442edd24-99b7-11e8-93d6-a0aac9d93582.png">

**Comment by helenemccarron** [comment]
@PiotrKozlowski the content is baked but I think there is a bug with tables in appendices, they do not look like they are handled properly. I don't remember which issue it was but I remember another issue about tables in appendices, this might be related to that. 

I would make sure the tables are handled before changing the CSS, there are rules for handling math in tables already implemented in `baked-content.less`
