### ISSUE TITLE
Different content on webview and PDF

### ISSUE THREAD

**Issue by wilkus27** [Connexions/webview#1806]
Example 10.1 has different content on webview and pdf. It causes inconsistancy in equation numbering:
https://katalyst01.cnx.org/contents/jQSmhtXo@16.36:bs_J-Oeb@3/101-Angular-Acceleration

![diff_cont](https://user-images.githubusercontent.com/40228854/43717591-543274f8-9988-11e8-8acd-6327a8b76237.JPG)

PDF:

![diff_cont_pdf](https://user-images.githubusercontent.com/40228854/43717600-5dd167bc-9988-11e8-8df9-8af1c3d861c1.JPG)

**Comment by openstaxalina** [comment]
Transferring to content-managers - we need to make webview equation 10.5 unnumbered so that the equation numbering will not be thrown off between webview & PDF on these titles.

**Comment by openstaxalina** [comment]
Issue moved to [Connexions/content-managers #234](https://github.com/Connexions/content-managers/issues/234) via [**ZenHub**](https://www.zenhub.com/)
