### ISSUE TITLE
Allow unicode characters in URLs

### ISSUE THREAD

**Issue by BryanEliDimas** [Connexions/webview#1813]
The two related PRs:
1. https://github.com/Connexions/webview/pull/1631
2. https://github.com/Connexions/cnx-archive/pull/556

The test plans are similar, included in each PR, but for convenience, also provided below.

Test plan
=====
Story
-----
AAT, I'd like a webview test that asserts Unicode in URL is allowed

Steps
---
1. Visit:
https://qa.cnx.org/contents/TqqPA4io@1.1:tjWnLaNJ@2 
it redirects to this url but URL-encoded https://qa.cnx.org/contents/TqqPA4io@1.1:tjWnLaNJ@2/123-Naprężenie-odkształcenie-i-moduł-sprężystości, which is equal to this: https://qa.cnx.org/contents/NJcqgO_j@2/P%C5%82yny-g%C4%99sto%C5%9B%C4%87-i-ci%C5%9Bnienie

instead of:
https://qa.cnx.org/contents/TqqPA4io@1.1:tjWnLaNJ@2/123-Naprenie-odksztacenie-i-mo
2. Ie.: if the Unicode characters in the URL become stripped out (from the page title), this is a bug.

Expected result
----
- A URL with Unicode characters shows up complete in the address bar.
- Whitespace is replaced with dashes.
- Punctuation is stripped out (ie. question marks, exclamation marks)

cnx-archive test plan
======
Steps
------
1. Visit a sitemap for a publisher who has published a book with unicode characters (ie.: Katalyst whose books are in a different language, https://qa.cnx.org/sitemap-katalysteducation.xml)
2. Unicode (aka. non-ascii) characters should be present in the URLs, but URL-escaped. In other words, expect this URL:  https://qa.cnx.org/contents/34972a80-efe3-4f36-90d4-e0661d202e24@2/P%C5%82yny-g%C4%99sto%C5%9B%C4%87-i-ci%C5%9Bnienie to be present instead of https://qa.cnx.org/contents/34972a80-efe3-4f36-90d4-e0661d202e24@2/p-yny-g-sto-i-ci-nienie

Expected result
----------------
- Unicode characters do not become stripped out from URLs in a sitemap.
- Whitespace is replaced with dashes.
- Punctuation is stripped out (ie. question marks, exclamation marks)

**Comment by kerwinso** [comment]
@BryanEliDimas In the browser, the URL looks correct. However, if I go to to the location bar and copy and paste the URL into another application (e.g., Sublime Text), the pasted URL has no unicode characters. Is this acceptable behavior?

_Screenshot: URL in browser vs. Sublime Text_:
![image.png](https://images.zenhubusercontent.com/5afb36564b5806bc2bd34a19/7c84c928-43bc-431c-8ef1-c5cfd072e4cd)

**Comment by openstaxalina** [comment]
From @BryanEliDimas: "Yes, I believe that is acceptable behavior. URLs really are character encoded but browser are just able to display them correctly."

I am fine with this behavior.

cc @kerwinso

**Comment by kerwinso** [comment]
Assigning back to @BryanEliDimas to fix [the bug I found](https://github.com/Connexions/webview/issues/1813#issuecomment-413583728) in the Katalyst sitemap.

**Comment by BryanEliDimas** [comment]
My test plan was wrong. The current behavior is the expected (and hopefully correct—according to the SEO god) behavior. Updated the test plan—and back to QA @kerwinso.

**Comment by kerwinso** [comment]
Working as desired on staging.

### Test 1 (webview)
Go to https://staging.cnx.org/contents/TqqPA4io@1.1:tjWnLaNJ@2. Redirects properly with unicode characters displaying in URL:

![image.png](https://images.zenhubusercontent.com/5afb36564b5806bc2bd34a19/19b50b36-53bd-453b-b8f6-a569124dc75d)

### Test 2 (cnx-archive)
Go to https://staging.cnx.org/sitemap-katalysteducation.xml. URLs are properly showing URL-escaped unicode characters:
![image.png](https://images.zenhubusercontent.com/5afb36564b5806bc2bd34a19/b1cf9afa-9cb4-4a48-b05b-366254c3f1c3)

And, copying and pasting any of those URLs redirects properly to a URL displaying the unicode characters:
![image.png](https://images.zenhubusercontent.com/5afb36564b5806bc2bd34a19/abe6ff00-c9a4-4270-82af-09d63d05fffe)
