### ISSUE TITLE
Headers and cell content differently aligned in table

### ISSUE THREAD

**Issue by wilkus27** [Connexions/webview#1814]
(https://katalyst01.cnx.org/contents/jQSmhtXo@16.36:Sn5TqjF8@16.36/Test-Prep-for-AP-Courses)

![strange_table](https://user-images.githubusercontent.com/40228854/43843807-a6621548-9b28-11e8-8876-41d2720712b8.JPG)

Headers of the columns and figures inside the table are differently aligned.

PDF:

![strange_table_pdf](https://user-images.githubusercontent.com/40228854/43844148-57186d7e-9b29-11e8-8004-cfd0efc7fd7e.JPG)

**Comment by openstaxalina** [comment]
I think that issue 2 (table is unnumbered in PDF) is related to: https://github.com/Connexions/webview/issues/1769
(This table is also in Test Prep for AP Courses.)

If we can remove the numbering for this table with a recipe or similar change, that only leaves issue 3 (alignment).  

For issue 3 - I am curious about the devs' thoughts whether we can properly target and style this table.

**Comment by PatBoj** [comment]
I can look into it. Just to be clear, I'm going to remove table number in the EOC and that will solve those 2 issues (nr 1 and nr 2). The issue nr 3 is already solved by @PiotrKozlowski.

**Comment by PiotrKozlowski** [comment]
@wilkus27 `3` is ready for testing at #1822 branch

**Comment by openstaxalina** [comment]
cleaned up this issue to reflect only the problem we are solving with @PiotrKozlowski's code.  :-)

**Comment by wilkus27** [comment]
Verified on katalyst01:

![fig_align](https://user-images.githubusercontent.com/40228854/44044653-8e406152-9f26-11e8-9dd3-e7eccf29cafb.JPG)
