### ISSUE TITLE
Additional dot in list

### ISSUE THREAD

**Issue by wilkus27** [Connexions/webview#1820]
There is a list with extra dot (https://katalyst01.cnx.org/contents/jQSmhtXo@16.36:4yAGHqDY@16.36/Test-Prep-for-AP-Courses)

![dot](https://user-images.githubusercontent.com/40228854/43900939-7a89e806-9be6-11e8-9f7a-5708335835af.JPG)

This is how it looks in PDF:

![dot_pdf](https://user-images.githubusercontent.com/40228854/43900958-867e1060-9be6-11e8-9024-8310621611b7.JPG)

**Comment by PiotrKozlowski** [comment]
Markup for this looks like this:
```
...
<ul data-labeled-item="true" id="fs-id2216568a">
    <li>
        <ol id="eip-id1383327" type="I">
            <li>gamma rays</li>
            <li>infrared</li>
            <li>radio</li>
            <li>ultraviolet</li>
        </ol>
    </li>
</ul>
<ol data-mark-prefix="(" data-mark-suffix=")" id="fs-id2216568" type="a">
    <li data-mark-prefix="(" data-mark-suffix=")">I, II, and III</li>
    <li data-mark-prefix="(" data-mark-suffix=")">I and IV only</li>
    <li data-mark-prefix="(" data-mark-suffix=")">II and III only</li>
    <li data-mark-prefix="(" data-mark-suffix=")">III only</li>
</ol>
```

So there is `<ol>...</ol>` inside of `<li>...</li>`. Should this be created that way?

**Comment by openstaxalina** [comment]
I agree this is an issue with the markup.  Moving to content-managers repo.

**Comment by openstaxalina** [comment]
Issue moved to [Connexions/content-managers #237](https://github.com/Connexions/content-managers/issues/237) via [**ZenHub**](https://www.zenhub.com/)
