### ISSUE TITLE
Get This Book button should change appearance on focus

### ISSUE THREAD

**Issue by openstaxalina** [Connexions/webview#1823]
Update the button to display when the focus is on it by inverting the color (normally green with white text; when in focus, white with green text).  

There is already a PR for this issue: https://github.com/Connexions/webview/pull/1624

**Comment by helenemccarron** [comment]
Addressed in PR #1816

**Comment by Stackblocks** [comment]
## Before 
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/f746b455-1952-40ed-88dc-19f845e9d86e)

## After
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/2c261abf-7c3f-49b4-b142-a1d83bda3947)
