### ISSUE TITLE
Mess with terms from Index

### ISSUE THREAD

**Issue by wilkus27** [Connexions/webview#1826]
On katalyst01 (https://katalyst01.cnx.org/contents/jQSmhtXo@16.36:Xm0hU3Qa@16.36/Index) one term from the middle of the index appears on the top and there are two headers **Symbols**

![symbols_kat](https://user-images.githubusercontent.com/40228854/44038267-b89775b8-9f16-11e8-8f41-f2169dfff026.JPG)

In PDF it looks like that:

![symbols_pdf](https://user-images.githubusercontent.com/40228854/44038318-d379c6d8-9f16-11e8-8e52-278f684ef9d6.JPG)

Additional terms from the top of the webview display properly in pdf:

![term_pdf](https://user-images.githubusercontent.com/40228854/44038447-19383952-9f17-11e8-94b2-e295a8e694af.JPG)

But on katalyst01 are missed:

![term_kat](https://user-images.githubusercontent.com/40228854/44038511-3da0a45a-9f17-11e8-9e4f-4f202fa16648.JPG)

**Comment by openstaxalina** [comment]
Since code freeze is this week, and there is a national holiday in Poland, I am going to defer this to the backlog.  cc @helenemccarron @PiotrKozlowski @PatBoj @Adrianltd

**Comment by openstaxalina** [comment]
Previously this was occurring with terms in figure captions, and we elected not to support terms inside figure captions.  

However, I checked the first term (drift velocity) and it is not in a figure caption, so this could use some additional investigation.

**Comment by PiotrKozlowski** [comment]
This looks like recipes issue, because webview is not manipulating with order of code. It can manipulate only visually with content.
cc @helenemccarron , @openstaxalina

**Comment by openstaxalina** [comment]
Issue moved to [Connexions/cnx-recipes #562](https://github.com/Connexions/cnx-recipes/issues/562) via [**ZenHub**](https://www.zenhub.com/)
