### ISSUE TITLE
Principles of Management ONLY: Change Exploring Business Careers class

### ISSUE THREAD

**Issue by Bkblodget** [Connexions/webview#1828]
Please change the feature title from Exploring Business Careers to **Exploring Managerial Careers**.

Please change the associated class from exploring-business-careers to `exploring-manager-careers`.

Also need to change the text that displays to “Exploring Managerial Careers”.

**Comment by brittany-johnson** [comment]
Issue moved to [Connexions/cnx-recipes #567](https://github.com/Connexions/cnx-recipes/issues/567) via [**ZenHub**](https://www.zenhub.com/)
