### ISSUE TITLE
Updates to cnx.org/about/contact

### ISSUE THREAD

**Issue by brittweinstein** [Connexions/webview#1832]
# Description
We offer our mailing address rather than physical address in outward communications. We should also remove the office/parking map and the phone number; Support had decided our primary means of contact should be through email and chat, but we have phone numbers elsewhere in the support hub if people need them. Here is the address we use:

OpenStax
Rice University
6100 Main Street MS-375
Houston, Texas 77005

# Impact
* **Severity**: [ ] High [x] Medium  [ ] Low
* **Frequency of Occurence**: [x] High [ ] Medium  [ ] Low

# Acceptance
- the map no longer appears on cnx.org/about/contact
- the address displayed on cnx.org/about/contact is our 6100 Main address listed above
- the words "(Google map)" are removed from cnx.org/about/contact
- phone number is no longer listed on cnx.org/about/contact
- Remove the headers "Technical Support" and "General Questions", as well as the content underneath each header.
- Revise the text under the header "Questions?" as follows:
Please feel free to e-mail us at support@openstax.org.
- **The same changes should be made at: https://legacy.cnx.org/aboutus/contact**

------

From Courtney: "Hi, I wanted to check in on this request. It was mentioned in the CNX SEO meeting that we don't even have this page in our sitemap because it's out of date, so people are not likely to find it in search results. If we make these simple changes, we should be able to add it to the sitemap." 

## PRs
https://github.com/Connexions/webview/pull/1851

**Comment by TomWoodward** [comment]
i'm not sure how to get legacy updated, people are saying there might be some kind of admin ui the change needs to be made in.

**Comment by TomWoodward** [comment]
legacy changes on staging 
https://legacy-staging.cnx.org/aboutus/contact

let me know when and I can copy to prod

**Comment by kerwinso** [comment]
# Test plan
- [ ] the map no longer appears on cnx.org/about/contact
- [ ] the address displayed on cnx.org/about/contact is our 6100 Main address listed above
- [ ] the words "(Google map)" are removed from cnx.org/about/contact
- [ ] phone number is no longer listed on cnx.org/about/contact
- [ ] Remove the headers "Technical Support" and "General Questions", as well as the content underneath each header.
- [ ] Revise the text under the header "Questions?" as follows: 
`Please feel free to e-mail us at support@openstax.org.`

**Comment by kerwinso** [comment]
@TomWoodward When trying to verify the Polish version of this page, I ran into issues. Please advise after looking at the screenshot below.
![image](https://user-images.githubusercontent.com/11298165/44605886-afc7f500-a7b0-11e8-9cb3-1b5da945576f.png)

**Comment by kerwinso** [comment]
English version on qa.cnx.org looks good (Alina also approved).

<details>
<summary>Click to see image</summary>

![image](https://user-images.githubusercontent.com/11298165/44607719-059f9b80-a7b7-11e8-9232-558a91b059f0.png)

</details>

**Comment by kerwinso** [comment]
Polish dictionary fixed here: https://github.com/Connexions/webview/pull/1870

**Comment by kerwinso** [comment]
Looks good on https://qa.cnx.org/about/contact based on test plan here: https://github.com/Connexions/webview/issues/1832#issuecomment-415806381. Will need to verify on staging.

**Comment by kerwinso** [comment]
Verified on staging.
