### ISSUE TITLE
Clarify Display of Non OpenStax CNX textbooks on CNX.org

### ISSUE THREAD

**Issue by brittweinstein** [Connexions/webview#1833]
#Description

People are getting confused that the books on the bottom of the cnx.org home page are not official OpenStax texts as they have OpenStax logos on them and there is no copy to clarify how those books are different than the official books above them on the page

#Impact
* **Severity**: [ ] High [ ] Medium  [ ] Low
* **Frequency of Occurence**: [ ] High [ ] Medium  [ ] Low

#Acceptance

#Ideas from Jeff:
-add a line between the OpenStax and non-OpenStax books
-add a blurb explaining these are user-generated content
![nonOS.png](https://images.zenhubusercontent.com/5a01faba8a75884b90866af7/be640b7a-e309-49b8-826f-0b1ed3f17278)![more non OS.png](https://images.zenhubusercontent.com/5a01faba8a75884b90866af7/78c0fbb8-3fa4-435f-8916-f64322bd3fd2)

## PRs
https://github.com/Connexions/webview/pull/1888
https://github.com/Connexions/webview/pull/1852

**Comment by philschatz** [comment]
What about "Community-created books!" rather than "OpenStax CNX Books"?

**Comment by openstaxalina** [comment]
Need to provide a mockup.

**Comment by openstaxalina** [comment]
Tentative mock-up - needs MarCom approval on the new copy:
![cnx community created content](https://user-images.githubusercontent.com/7863733/44355363-03190b00-a472-11e8-8649-29518af787b0.png)

**Comment by openstaxalina** [comment]
Also want to discuss a change like this higher on the page with MarCom:
![cnx openstax content](https://user-images.githubusercontent.com/7863733/44355763-1678a600-a473-11e8-9dc2-cba0857e53c3.png)

**Comment by kerwinso** [comment]
@TomWoodward I cannot verify the Polish version of the CNX front page due to the problem I mentioned here: https://github.com/Connexions/webview/issues/1832#issuecomment-415871196

**Comment by TomWoodward** [comment]
@kerwinso the final version of my change had a bug fixed by this https://github.com/Connexions/webview/pull/1870 so we need that merged now too.

**Comment by kerwinso** [comment]
@openstaxalina @TomWoodward I'm testing this on https://qa.cnx.org in Polish and have 3 questions. Please see screenshots below with the questions.

![image](https://user-images.githubusercontent.com/11298165/44814468-6d345d00-aba2-11e8-8da1-dcecf77cd0a3.png)

![image](https://user-images.githubusercontent.com/11298165/44814472-6f96b700-aba2-11e8-8b2b-0302dec8c457.png)

**Comment by openstaxalina** [comment]
@kerwinso thank you! Here are my responses:

1 - yes, should be translated
2 - no, their books are available at openstax.org
3 - yes, should be translated

Please let me know if I can help get the translations for this.

**Comment by kerwinso** [comment]
@TomWoodward Looks like we do want the new headers `OpenStax Textbooks` and `Community-Created Content` to be translated to Polish — please work with Alina if you need help getting those translations.

**Comment by kerwinso** [comment]
## Something vaguely resembling a test plan
- [ ] [Marcom markup 1](https://github.com/Connexions/webview/issues/1833#issuecomment-414392532)
- [ ] [Marcom markup 2](https://github.com/Connexions/webview/issues/1833#issuecomment-414394746)
- [ ] `OpenStax Textbooks` and `Community-Created Content` to be translated to Polish

### Under "Textbooks by OpenStax"
- [x] Change "Textbooks by OpenStax" to "OpenStax Textbooks"
- [x] replace exclamation point with period after "you" ("...select the subject that interests you.")
- [x] is it possible to make openstax.org a link?

### Under "Community-Created Content"
- [x] replace "our" with "a" ("...a community")

@kerwinso

**Comment by kerwinso** [comment]
@alina to ping Katalyst for header translations

**Comment by openstaxalina** [comment]
Polish translations:

OpenStax Textbooks - Podręczniki OpenStax
Community-Created Content - Zasoby stworzone przez użytkowników

**Comment by kerwinso** [comment]
Polish headers look good. Need to verify all these changes make it to staging.

**Comment by kerwinso** [comment]
Verified on staging.
