### ISSUE TITLE
In book search: make magnifying glass icon clickable

### ISSUE THREAD

**Issue by brittweinstein** [Connexions/webview#1834]
I think this is more of a UX enhancement than a bug.

1. Go to cnx.org
1. Click on any book
1. Enter any search terms in the search bar at the top
1. Try to click the magnifying glass icon on the right side of the search bar. You can't. Only pressing Enter on the keyboard executes the search.![click.png](https://images.zenhubusercontent.com/5a01faba8a75884b90866af7/44212892-e87e-48b7-be81-c7e0ba4fdd88)

## PRs
https://github.com/Connexions/webview/pull/1854

**Comment by kerwinso** [comment]
working on qa server.

**Comment by kerwinso** [comment]
Working on staging.
