### ISSUE TITLE
Please change cnx@cnx.org to support@openstax.org in "OpenStax CNX Account Created" email

### ISSUE THREAD

**Issue by brittweinstein** [Connexions/webview#1837]
# Description 

cnx@cnx.org is listed as the avenue to reach out for help with CNX issues in the "OpenStax CNX Account Created" email.  Yesterday (03/29/2018), I emailed cnx@cnx.org to see where it goes and Keith Kerr (knk1@rice.edu) replied to my inquiry and I have yet receive my email via the service desk. 

Customer service ticket #3416 regarding unanswered inquiries sent to cnx@cnx.org.

# Impact
* **Severity**: [ ] High [ ] Medium  [ ] Low
* **Frequency of Occurence**: [ ] High [ ] Medium  [ ] Low

# Acceptance
- [x] Change cnx@cnx.org to support@openstax.org in the account creation email.

![email.png](https://images.zenhubusercontent.com/5a01faba8a75884b90866af7/15ac098f-127a-4b38-bc38-8a2a0961e0fb)

**Comment by kerwinso** [comment]
This is a legacy issue, not accounts.

**Comment by reedstrm** [comment]
Template that contains this email is in  Products.CNXPloneSite/Products/CNXPloneSite/skins/cnx_overrides/registered_notify_template.pt

**Comment by reedstrm** [comment]
Fixed in https://github.com/Rhaptos/Products.CNXPloneSite/pull/4

**Comment by kerwinso** [comment]
The email address looks correct now (`support@openstax.org`) on qa.cnx.org on `Products.CNXPloneSite==0.76.3dev` -- so I'm calling this issue passed and ready for regression testing.

However, I found another bug while testing this, which I opened here: https://github.com/Connexions/webview/issues/1939

**Comment by kerwinso** [comment]
Verified on staging.
![image](https://user-images.githubusercontent.com/11298165/45645517-4a50e680-ba86-11e8-8d2f-b1790f10cc27.png)
