### ISSUE TITLE
Add a hyperlinked table of contents to the intro page of each book

### ISSUE THREAD

**Issue by openstaxalina** [Connexions/webview#1838]
If a user searches for multiple search terms related to a certain subject, our book is more likely to be surfaced if we have one page that lists all topics in this way. Google will also rate the page higher because it will be more comprehensive content on the subject and will act as a “master page” for the book. This change will also help with the canonical redirects from PDFs; if we need to redirect a user from a full book PDF to the first page of a book, having the entire TOC available on that page gives a better user experience.
Design/Notes
The table of contents appears in full on the intro page for each book, beneath the current content.
Each entry in the table is hyperlinked to the corresponding module.
If it cuts down on work, this task only needs to be done on the most current versions of each book.

# PRs
#1886
#1894 

# Acceptance Criteria
- [x] OpenStax books look like the [first screenshot](https://user-images.githubusercontent.com/636227/44805542-87663f00-ab92-11e8-8fa9-c2166cbf1fc6.png) in #1886 
	- [x] frontpage/cms description shows just on the openstax books
- [x] Non-OpenStax books look like the [second screenshot](https://user-images.githubusercontent.com/636227/44805558-92b96a80-ab92-11e8-81b2-05f45089c295.png) in #1886  
- [x] TOC only shows on the default page page of the book (i.e., on the url that's just the book ID) 
	- [x] OpenStax book: the first page that's not the preface
	- [x] non-OpenStax book: first page

**Comment by openstaxalina** [comment]
![ToCMockUp.png](https://images.zenhubusercontent.com/5b57372fb01a900cfd923015/27698acc-277b-4b88-9ef8-17ac33f54182)

**Comment by TomWoodward** [comment]
@openstaxalina what do you mean by "in column format"?

also to be clear, the new content on the intro page will be essentially the same as the content in the "contents" sidebar right?

**Comment by openstaxalina** [comment]
Hi Tom - by column format, I meant that we may want to consider a 2-3 column format, especially for the ToCs that are particularly long.  

And yes, that's correct that it's the same content that is in the "contents" sidebar.

**Comment by TomWoodward** [comment]
@openstaxalina should it list all the subsections like the toc on openstax.org? 

eg: ![image.png](https://images.zenhubusercontent.com/5b64af5daccf60659df0f246/d978a77d-a7b8-4b15-9332-d10779e9fa35)

or just the top level sections? from a layout perspective it might be hard to do subsections with indentation in the column format you described.

**Comment by openstaxalina** [comment]
Other possible solutions for this issue:
- default to the ToC being expanded when a person lands on the first intro page of the book
- create a true landing page where users are directed instead of to the first intro page.  This page would include the marketing "About" text as well as the hyperlinked ToC.

**Comment by openstaxalina** [comment]
*Decision:*
Described by Ross: "implement it as, when landing on a book-only url, rather than doing "soft" redirect to the first page (we fetch the first page, then rewrite the location bar) , how about we make a landing page, that _for now_ consists of fetching the first page and doctoring it up w/ extra stuff, *but not rewrite the location bar*.

That preserves the behavior/rendering of the page itself, gives google content on the page we serve as the canonical URL, which will make them happier.
That gives us a landing page for the book (from a developers perspective) whose initial design just happens to be the content of the first page + other stuff.

**Comment by openstaxalina** [comment]
@TomWoodward To answer your question: It should list the subsections, like the ToC on openstax.org does (or like the one on CNX does if you expand the chapters).  Having the subsections is more important than having the columns.  We could look at it without the columns and see if there are any design tweaks that could be made.

Also to cover what we discussed in sprint planning, this should **not** be a tab at the bottom of the page.  It should appear below the intro content (separated by a line as indicated on the mockup).

**Comment by TomWoodward** [comment]
![localhost_8000_contents_yqv9q0hh 13 1_pllt9fyr 6_introduction](https://user-images.githubusercontent.com/636227/44680291-50b1ec80-aa0b-11e8-9c93-1a74e2f7e070.png)

@openstaxalina can you verify that i'm going in the right direction here? i'm actually going to have to touch a lot of different modules to make this happen and don't want to get too deep without checking on the design.

**Comment by kerwinso** [comment]
Verified acceptance criteria on staging for both OpenStax and non-OpenStax books.
