### ISSUE TITLE
Two types of lists next to each other

### ISSUE THREAD

**Issue by wilkus27** [Connexions/webview#1839]
**katalyst01** (https://katalyst01.cnx.org/contents/MBiUQmmY@20.1:y0GFmfab@8/11-Definitions-of-Statistics-P):

![two_lists](https://user-images.githubusercontent.com/40228854/44195339-02fad180-a139-11e8-8b6b-2239519b4ece.JPG)

**PDF:**

![two_lists_pdf](https://user-images.githubusercontent.com/40228854/44195347-0aba7600-a139-11e8-9648-778fd97032a5.JPG)

Similar problem was described in #1682

**Comment by openstaxalina** [comment]
I believe this is a content issue:

![orderedalpha list](https://user-images.githubusercontent.com/7863733/44218243-ea8db580-a13e-11e8-9d3b-cc96420c30cb.png)

moving to content-managers repo

**Comment by openstaxalina** [comment]
Issue moved to [Connexions/content-managers #239](https://github.com/Connexions/content-managers/issues/239) via [**ZenHub**](https://www.zenhub.com/)
