### ISSUE TITLE
Extra spacing after number in EOC exercises

### ISSUE THREAD

**Issue by helenemccarron** [Connexions/webview#1841]
![2018-08-16_11-01-11](https://user-images.githubusercontent.com/8514591/44220265-b5d02d00-a143-11e8-86ca-2114cb2917f1.png)

**Comment by helenemccarron** [comment]
fixed in pr #1816 


![image](https://user-images.githubusercontent.com/8514591/44222716-0e56f880-a14b-11e8-9960-22dea258623e.png)

**Comment by Stackblocks** [comment]
Displaying as specified with updated version of content / code.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/f798e0f9-40a9-4c86-b317-c6beb0de98db)
