### ISSUE TITLE
Bullets in List in Table Cut Off 

### ISSUE THREAD

**Issue by openstaxalina** [Connexions/webview#1843]
Webview on the left; PDF on the right:
![bulletscutoff](https://user-images.githubusercontent.com/7863733/44233857-a0bac480-a16a-11e8-980d-7329f6664579.png)

Link to content: https://content02.cnx.org/contents/o0xnhd_t@10.20:DfYAJShE@4/43-Corporations-Limiting-Your-

**Comment by openstaxalina** [comment]
Another example of this content: https://content02.cnx.org/contents/o0xnhd_t@10.20:FeqYe8JF@4/51-Entrepreneurship-Today

**Comment by lwtchu** [comment]
Another example: https://content02.cnx.org/contents/o0xnhd_t@10.20:MwVrrGEx@4/61-The-Role-of-Management#fs-idm226416352

**Comment by openstaxalina** [comment]
Another example: https://content02.cnx.org/contents/o0xnhd_t@10.20:mnLvpdmD@2/53-Small-Business-Driving-Amer

**Comment by PiotrKozlowski** [comment]
Related to #1831

**Comment by openstaxalina** [comment]
Leaving this open for Alan's tracking purposes (more content to test against #1821).

**Comment by Stackblocks** [comment]
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/1d4bb105-7140-4f19-b1b4-cf8b22b16603)
