### ISSUE TITLE
Multi-Line Table Caption Starts on Next Line

### ISSUE THREAD

**Issue by openstaxalina** [Connexions/webview#1844]
![incorrecttablecaption](https://user-images.githubusercontent.com/7863733/44234639-b335fd80-a16c-11e8-98dd-3102610db043.png)

Link to content: https://content02.cnx.org/contents/o0xnhd_t@10.20:FeqYe8JF@4/51-Entrepreneurship-Today

The problem only occurs when the table caption goes more than one line.  Here's a shorter caption with the correct behavior:
![tablecaptioncorrect](https://user-images.githubusercontent.com/7863733/44234604-9ef20080-a16c-11e8-8eea-744e41bba217.png)

**Comment by lwtchu** [comment]
https://content02.cnx.org/contents/o0xnhd_t@10.20:N5jiZS3y@4/68-Trends-in-Management-and-Le

**Comment by brittany-johnson** [comment]
![screen shot 2018-08-21 at 10 11 28 am](https://user-images.githubusercontent.com/24909007/44410744-af1e2d00-a52a-11e8-9d05-f995c388b5a7.png)
![screen shot 2018-08-21 at 10 11 48 am](https://user-images.githubusercontent.com/24909007/44410745-af1e2d00-a52a-11e8-9513-35ca888358b5.png)
Single and multiline line table captions are now displaying correctly

**Comment by Stackblocks** [comment]
Displaying as specified with updated version of content / code.

## Single Line Caption
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/0ba5f53b-39d8-4c74-9bba-d307696df9c9)

## Multi-Line Caption
![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/ff0a310c-3003-4ec4-bd44-c1908eff5cb0)
