### ISSUE TITLE
Solutions that are not in pdf appear on the webview

### ISSUE THREAD

**Issue by wilkus27** [Connexions/webview#1848]
In PDF for Biology for AP Courses there is no solutions to the exercises, but on webview in random places appears **Show Solution** option with answer, e.g. 
1) https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:DjWiKQhq@7.1/Review-Questions

![show_sol](https://user-images.githubusercontent.com/40228854/44331655-656e0d80-a46a-11e8-93fd-d8bb6a697811.JPG)

The rest of examples:

2) https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:ob-BK9ym@7.1/Critical-Thinking-Questions -> **31**
3) https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:u-dLAkh8@7.1/Critical-Thinking-Questions -> **37**
4) https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:uT-qEGZP@7.1/Critical-Thinking-Questions -> **30**
5) https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:KVq3gv_T@7.1/Critical-Thinking-Questions -> **26**, **33**
6) https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:ZJfTguR1@7.1/Critical-Thinking-Questions -> **29**, **31**
7) https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:eLz1mgWJ@7.1/Critical-Thinking-Questions -> **24**, **28**
8) https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:-BkPjec3@7.1/Critical-Thinking-Questions -> **25**, **30**
9) https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:opUfXDb0@7.1/Critical-Thinking-Questions -> **85**
10) https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:iW_8hnMU@7.1/Critical-Thinking-Questions -> **33**
11) https://katalyst01.cnx.org/contents/bDIuMp-w@7.1:Mpp13h0J@7.1/Review-Questions -> **12**, **14**

**Comment by openstaxalina** [comment]
This is likely a content-related issue.  Moving to content-managers for investigation.

**Comment by openstaxalina** [comment]
Issue moved to [Connexions/content-managers #246](https://github.com/Connexions/content-managers/issues/246) via [**ZenHub**](https://www.zenhub.com/)
