### ISSUE TITLE
Extra box in solution

### ISSUE THREAD

**Issue by wilkus27** [Connexions/webview#1849]
In solution to **Example 2.32** there is extra box **USING THE TI-83, 83+, 84, 84+ CALCULATOR**. In PDF is just list.

katalyst01(https://katalyst01.cnx.org/contents/MBiUQmmY@20.1:gp5Hz9v3@13/27-Measures-of-the-Spread-of-t)

![extra_box](https://user-images.githubusercontent.com/40228854/44344939-22c02b80-a492-11e8-8c56-e7932772ec1f.JPG)

PDF:

![extra_box_pdf](https://user-images.githubusercontent.com/40228854/44344949-29e73980-a492-11e8-94cc-ae2076f37838.JPG)

**Comment by openstaxalina** [comment]
The PDF should probably have that header!  I am going to move this to oer.exports.

**Comment by openstaxalina** [comment]
Issue moved to [Connexions/oer.exports #3743](https://github.com/Connexions/oer.exports/issues/3743) via [**ZenHub**](https://www.zenhub.com/)
