### ISSUE TITLE
Select dropdowns in Firefox on Mac and Linux are ugly

### ISSUE THREAD

**Issue by dak** [Connexions/webview#185]
See: https://github.com/twbs/bootstrap/issues/765
https://bugzilla.mozilla.org/show_bug.cgi?id=649849
https://github.com/silviomoreto/bootstrap-select
http://stackoverflow.com/questions/5912791/how-to-remove-the-arrow-from-a-select-tag-in-firefox

**Comment by edwoodward** [comment]
Tested in Firefox 35.0.1 on Ubuntu and the dropdown is unchanged
![screenshot from 2015-02-25 14 47 47](https://cloud.githubusercontent.com/assets/1394695/6380224/ad46361c-bcfd-11e4-92a6-6e57211976e7.png)

**Comment by amberwebb** [comment]
@edwoodward They are unchanged in Firefox on Mac too. Are we sure this change was deployed?

**Comment by edwoodward** [comment]
User error. Used wrong server for test.  It is working on demo.cnx.org.  Much better.

**Comment by reedstrm** [comment]
Righto. Has this been merged to master as well?
