### ISSUE TITLE
Issue with white bullets

### ISSUE THREAD

**Issue by wilkus27** [Connexions/webview#1850]
In Introductory Statistics are lists with white bullets. Sometimes they occure on webview but they are not in pdf:

katalyst01(https://katalyst01.cnx.org/contents/MBiUQmmY@20.1:lad5IvLg@8/23-Measures-of-the-Location-of)

![white_bullet](https://user-images.githubusercontent.com/40228854/44345951-0671be00-a495-11e8-8d80-fabc883ccbc7.JPG)

PDF:

![white_bullet_pdf](https://user-images.githubusercontent.com/40228854/44345961-0d98cc00-a495-11e8-895d-cb31e44c6ef1.JPG)

But sometimes they are in a both places:

katalyst01(https://katalyst01.cnx.org/contents/MBiUQmmY@20.1:gp5Hz9v3@13/27-Measures-of-the-Spread-of-t)

![white_bullet2](https://user-images.githubusercontent.com/40228854/44346231-be06d000-a495-11e8-96c5-e2d4e3c7ed09.JPG)

PDF:

![extra_box_pdf](https://user-images.githubusercontent.com/40228854/44346245-c828ce80-a495-11e8-942c-9fbe949dc5c1.JPG)

So @openstaxalina  I'm not sure they should be removed from webview or added to pdf.

**Comment by openstaxalina** [comment]
We should try to duplicate the behavior from the PDF.  

It looks like the markup is a little different in these cases:
![screen shot 2018-08-20 at 11 54 27 am](https://user-images.githubusercontent.com/7863733/44354589-e11e8900-a46f-11e8-8d3e-53fa9824fb81.png)

![screen shot 2018-08-20 at 11 54 39 am](https://user-images.githubusercontent.com/7863733/44354601-e54aa680-a46f-11e8-92a4-7ea600d9dac7.png)

Does this require a content change, or can this be resolved in a recipe/webview?

**Comment by PiotrKozlowski** [comment]
User agent style (browser styles) for default sets `list-style-type` to `circle` for lists inside other lists:
```
ul ul, ol ul {
    list-style-type: circle;
}
```
We can set it in webview to `list-style-type: disc` which is normal dot, but this will be global change for nested lists inside baked books. I can also target nested lists only inside `.os-solution-container` but I'm not sure if this is ideal workaround.
Whats your call @openstaxalina ?

**Comment by openstaxalina** [comment]
Hmm, I am nervous about a global change for a relatively low-priority issue.  I would like to move this to the content-managers repo and either make changes there or accept this small difference between the PDF & webview.

I'll flag this for discussion at Thursday's scrum to finalize a decision.  cc @PiotrKozlowski @wilkus27

**Comment by openstaxalina** [comment]
Issue moved to [Connexions/content-managers #275](https://github.com/Connexions/content-managers/issues/275) via [**ZenHub**](https://www.zenhub.com/)
