### ISSUE TITLE
Lists in exercises without margins

### ISSUE THREAD

**Issue by PatBoj** [Connexions/webview#1855]
That issue was originally created on `cnx-recipes` repo https://github.com/Connexions/cnx-recipes/issues/555. 

Natalia writes:
> After activating _exercise-container_ flag, when the exercise begins with the list, the list displays without margins:
> 
> katalyst01 (https://katalyst01.cnx.org/contents/kRfPjKij@4.5:pKpFhGyF@4.5/Answer-Key)
> 
> ![answer_lists](https://user-images.githubusercontent.com/40228854/44210671-64d23000-a167-11e8-8055-55abf682766e.JPG)

**Comment by PatBoj** [comment]
I've simply changed display style for lists which are direcly below the problem (or solution) number. I've also deleted top margin to those lists in order to reduce the space between the number and first element of the list.

## ***Before:***
![image](https://user-images.githubusercontent.com/20907906/44396373-fa413b80-a53c-11e8-8353-27208f48f68b.png)

## ***After:***
![image](https://user-images.githubusercontent.com/20907906/44396379-ff9e8600-a53c-11e8-9a09-78689f7b7194.png)

## ***PDF:***
![image](https://user-images.githubusercontent.com/20907906/44396382-03320d00-a53d-11e8-8b89-0f37e8f33087.png)

**Comment by wilkus27** [comment]
After deployment in Introductory Statistics text displayed under the number and in Macroeconomics for AP I didn't see any changes. So I tried to bake both of this books. Than in Macroeconomics still were no changes  but Introductory Statistics displayed like before deployment. Next I deployed again and now in both books exercises display incorrectly, e.g.

Introductory statistics(https://katalyst01.cnx.org/contents/MBiUQmmY@20.1:xvUdEJ3p@20.1/Practice):

![stat](https://user-images.githubusercontent.com/40228854/44668939-0e92a600-aa1f-11e8-8f89-da84ec370fdf.JPG)

Macroeconomics for AP(https://katalyst01.cnx.org/contents/kRfPjKij@4.5:cW9mg8jr@4.5/Review-Questions)

![macro](https://user-images.githubusercontent.com/40228854/44669034-3c77ea80-aa1f-11e8-97e7-f2d52e0d1944.JPG)

**Comment by helenemccarron** [comment]
@wilkus27 in this case, it looks like the book was baked properly but the CSS in webview isn't working as intended. @PatBoj and @Adrianltd I have lost track of the state of the `os-problem-container` and `os-solution-container` fixes. Can you please take a look?

**Comment by PatBoj** [comment]
@wilkus27 It should be OK right now, you can test it.

**Comment by wilkus27** [comment]
Verified on katalyst01.

**Introductory Statistics:**

![stat2](https://user-images.githubusercontent.com/40228854/44788978-bb922d80-ab9b-11e8-8ed4-44d27b1c800c.JPG)

**Introductory Business Statistics:**

![business2](https://user-images.githubusercontent.com/40228854/44789008-cf3d9400-ab9b-11e8-84ce-1cf044f176c9.JPG)

**Principles of Macroeconomics for AP® Courses 2e**

![macro2](https://user-images.githubusercontent.com/40228854/44789072-fb591500-ab9b-11e8-90f1-1d9f25bbc98c.JPG)
