### ISSUE TITLE
Edited: Blank Space Between Question Number and Period

### ISSUE THREAD

**Issue by helenemccarron** [Connexions/webview#1858]
@uskka commented on [Mon Aug 13 2018](https://github.com/Connexions/cnx-recipes/issues/543)

Description: There is an empty line after each question number.
 
https://katalyst01.cnx.org/contents/vEmOH-_p@4.48:m6uU43lg@4.48/Self-Check-Questions

PDF
<img width="1264" alt="screen shot 2018-08-13 at 18 45 44" src="https://user-images.githubusercontent.com/40228918/44045793-f438aeb2-9f29-11e8-8694-61bd6da0b79e.png">
Webview
![screenshot-katalyst01 cnx org-2018 08 13-18-39-52](https://user-images.githubusercontent.com/40228918/44045799-fab67af8-9f29-11e8-9807-4ed24bde022a.png)

---

@uskka commented on [Thu Aug 16 2018](https://github.com/Connexions/cnx-recipes/issues/543#issuecomment-413474744)

After baking the book with latest recipes from katAW.petty.pegasus issue was fixed. Tested on katalyst01
![image-5](https://user-images.githubusercontent.com/40228918/44198830-ad2b2700-a142-11e8-87af-e54ca984d452.png)

---

@openstaxalina commented on [Thu Aug 16 2018](https://github.com/Connexions/cnx-recipes/issues/543#issuecomment-413586360)

What about the space between the question number and period - it looks a little strange.  Is this something that can be adjusted?

![questionperiodgap](https://user-images.githubusercontent.com/7863733/44218411-435d4e00-a13f-11e8-9fd5-fdd1ae55e367.png)

---

@helenemccarron commented on [Thu Aug 16 2018](https://github.com/Connexions/cnx-recipes/issues/543#issuecomment-413616182)

https://github.com/Connexions/webview/issues/1841 should address this.

---

@openstaxalina commented on [Fri Aug 17 2018](https://github.com/Connexions/cnx-recipes/issues/543#issuecomment-413949412)

Resolved as part of petty.pegasus - @uskka, could you retest with updated code?

---

@uskka commented on [Mon Aug 20 2018](https://github.com/Connexions/cnx-recipes/issues/543#issuecomment-414360286)

After the deploy with latest changes still looks the same. Tested on katalyst01.
![screenshot-katalyst01 cnx org-2018 08 20-17-28-51](https://user-images.githubusercontent.com/40228918/44350041-bac41200-a49e-11e8-8a38-7fe857f39fe2.png)

---

@openstaxalina commented on [Mon Aug 20 2018](https://github.com/Connexions/cnx-recipes/issues/543#issuecomment-414385784)

@helenemccarron could you review this when you get a chance?  Note that we refined this issue to focus on the space after the question number.  Above you mentioned that this should be fixed with petty.pegasus.  However; this issue is still occurring.  How do you recommend moving forward on this one?

---

@helenemccarron commented on [Mon Aug 20 2018](https://github.com/Connexions/cnx-recipes/issues/543#issuecomment-414389942)

I think my solution may have been too specific. I'll take a look for a better an more global approach.

**Comment by uskka** [comment]
Looks good. Tested on katalyst01.

![screenshot-katalyst01 cnx org-2018 08 23-16-16-58](https://user-images.githubusercontent.com/40228918/44531005-03263e80-a6f0-11e8-8861-2c4f949ab3bc.png)

**Comment by openstaxalina** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/17214cec-3a6c-478a-a7bf-17ba4cf5b00c-361c6ea6-266f-41d9-8feb-a2c7f8c5a321-v1.png?transparent=1&palette=1&width=246)
