### ISSUE TITLE
Different paddings in boxes

### ISSUE THREAD

**Issue by wilkus27** [Connexions/webview#1863]
On katalyst01 boxes have different paddings even they have the same headers, e.g. https://katalyst01.cnx.org/contents/MBiUQmmY@20.1:qLYH79kX@9/3-2-Independent-and-Mutually-Exclusive-Events

![boxes](https://user-images.githubusercontent.com/40228854/44465404-b96d2380-a61d-11e8-8c00-cd78e34d8438.JPG)

**Comment by openstaxalina** [comment]
It looks like this is in the content; the first Example is a para:
<img width="834" alt="screen shot 2018-08-22 at 9 01 08 am" src="https://user-images.githubusercontent.com/7863733/44468073-03d4ad00-a5ea-11e8-98fc-695d87c0b5d6.png">

While the second example is in a problem tag:
<img width="810" alt="screen shot 2018-08-22 at 9 01 32 am" src="https://user-images.githubusercontent.com/7863733/44468093-0d5e1500-a5ea-11e8-923e-8904142f576e.png">


I am going to leave this open in case there are any other noticeable instances of this, then will move to the content-managers repo. cc @wilkus27

**Comment by openstaxalina** [comment]
Issue moved to [Connexions/content-managers #274](https://github.com/Connexions/content-managers/issues/274) via [**ZenHub**](https://www.zenhub.com/)
