### ISSUE TITLE
Different numbering of exercises

### ISSUE THREAD

**Issue by helenemccarron** [Connexions/webview#1864]
@wilkus27 commented on [Tue Aug 14 2018](https://github.com/Connexions/cnx-recipes/issues/547)

There is difference in numbering of exercises between webview and pdf.

katalyst01 (https://katalyst01.cnx.org/contents/kRfPjKij@4.5:pAeLAwQZ@7/A--The-Use-of-Mathematics-in-P)

![nr_ex_kat](https://user-images.githubusercontent.com/40228854/44091544-1f16cb4c-9fce-11e8-8ec6-2836645c5509.JPG)

PDF:

![nr_ex_pdf](https://user-images.githubusercontent.com/40228854/44091555-272d0788-9fce-11e8-88ec-3346d3b2d1f6.JPG)

Similar problem was resolved in issue #527

---

@wilkus27 commented on [Tue Aug 21 2018](https://github.com/Connexions/cnx-recipes/issues/547#issuecomment-414710325)

This is how it looks now on katalyst01:

![ex_nr](https://user-images.githubusercontent.com/40228854/44408189-2f12ba00-a560-11e8-8555-349b57dc639d.JPG)

@openstaxalina I'm not sure, which displays of exercises content is correct in this case. The flag **exercise container** is turn on in this book, so now text is next to the number of exercise. But in pdf content is below. So which way of display is better here?

---

@openstaxalina commented on [Tue Aug 21 2018](https://github.com/Connexions/cnx-recipes/issues/547#issuecomment-414842055)

@wilkus27 good point!
It would be best to either (a) style "Exercise ## in some way to differentiate it from the exercise content, **or** (b) move the exercise content onto the next line as it is in the PDF.  @Adrianltd is there any way to specifically target these exercises and implement one of those two solutions?

---

@helenemccarron commented on [Wed Aug 22 2018](https://github.com/Connexions/cnx-recipes/issues/547#issuecomment-415048444)

It looks like enable the feature flag for exercise container fixed the numbering issue. What's left is a display issue, moving to webview.

**Comment by PatBoj** [comment]
@wilkus27 It should be OK right now, you can test it.

**Comment by wilkus27** [comment]
Verified on katalyst01:

![ex_a](https://user-images.githubusercontent.com/40228854/44789973-4ecc6280-ab9e-11e8-93f0-7f14d193bfd3.JPG)
