### ISSUE TITLE
Line break after assessment number

### ISSUE THREAD

**Issue by marcjeannott** [Connexions/webview#1865]
The assessment questions at the end of chapter in Business Ethics have line breaks after the number. 
![regression2](https://user-images.githubusercontent.com/33228728/44470569-b3604e00-a5ef-11e8-9660-0ae6df975c5e.jpg)

**Comment by openstaxalina** [comment]
@Stackblocks, based on https://github.com/Connexions/webview/issues/1858#issuecomment-415430884, it seems like this should be resolved.  Would you be willing to rebake _Business Ethics_ on devb with latest code and retest?

cc @helenemccarron
