### ISSUE TITLE
Broken Note in solutions 

### ISSUE THREAD

**Issue by uskka** [Connexions/webview#1868]
Note is not displaying correctly. 

https://katalyst01.cnx.org/contents/tWu56V64@34.15:0oDyO3Y8@34.15/Solutions

Webview
![screenshot-katalyst01 cnx org-2018-08-23-11-30-10](https://user-images.githubusercontent.com/40228918/44517466-12919180-a6c8-11e8-84af-1fa4d8d1e394.png)

PDF
![01](https://user-images.githubusercontent.com/40228918/44517534-47054d80-a6c8-11e8-886e-6d021c60f19d.png)

**Comment by wilkus27** [comment]
Same problem in Introductory Statistics: https://katalyst01.cnx.org/contents/MBiUQmmY@20.1:z5OiUaGM@20.1/Solutions -> **87**

**Comment by Adrianltd** [comment]
This should be fixed by https://github.com/Connexions/webview/pull/1867

**Comment by PiotrKozlowski** [comment]
Ready for testing

**Comment by wilkus27** [comment]
Verified on katalyst01.

**Introductory Statistics:**

![stat](https://user-images.githubusercontent.com/40228854/44844163-6fea8d00-ac4a-11e8-8902-3dce5581d124.JPG)

**Introductory Business Statistics:**

![business](https://user-images.githubusercontent.com/40228854/44844197-81cc3000-ac4a-11e8-8be5-457c79982717.JPG)
