### ISSUE TITLE
Additional empty box in webview 

### ISSUE THREAD

**Issue by uskka** [Connexions/webview#1869]
There is an additional container 'USING THE TI-83...' in the webview. 

Similar to https://github.com/Connexions/webview/issues/1849

Webview (Example 5.7 solution)
https://katalyst01.cnx.org/contents/tWu56V64@34.15:pBCWX6Gi@32/5-3-The-Exponential-Distribution

![screenshot-katalyst01 cnx org-2018-08-23-13-05-30](https://user-images.githubusercontent.com/40228918/44522230-2e039900-a6d6-11e8-9a9d-2bb96d94b880.png)

PDF
![000](https://user-images.githubusercontent.com/40228918/44522426-c4d05580-a6d6-11e8-9ce5-de2656ebc4ad.png)

**Comment by PiotrKozlowski** [comment]
This block have attribute `data-type="note"` so this behaviour is correct for webview. If this shouldn't be a `note` then probably it should be changed in content.
```
<div class="statistics calculator ui-has-child-title" data-has-label="true" data-label="" data-type="note" id="fs-idm57824464"><header><h3 class="os-title" data-type="title" data-label-parent=""><span class="os-title-label">Using the TI-83, 83+, 84, 84+ Calculator</span></h3></header><section><div class="os-note-body">
</div></section></div>
```
cc @openstaxalina

**Comment by PatBoj** [comment]
@openstaxalina It is content, because this note is empty in raw (not baked) html file.

![image](https://user-images.githubusercontent.com/20907906/44581870-c023a400-a79f-11e8-93f7-44e7caba0ab8.png)

**Comment by openstaxalina** [comment]
Issue moved to [Connexions/content-managers #263](https://github.com/Connexions/content-managers/issues/263) via [**ZenHub**](https://www.zenhub.com/)
