### ISSUE TITLE
Two the same headers

### ISSUE THREAD

**Issue by wilkus27** [Connexions/webview#1871]
On katalyst01 (https://katalyst01.cnx.org/contents/MBiUQmmY@20.1:QNwpYJrT@9/8-3-A-Population-Proportion -> **Example 8.12**) there are two the same headers:

![two_head](https://user-images.githubusercontent.com/40228854/44586802-41cffd80-a7b1-11e8-833d-5ebfffed5ac9.JPG)

PDF:

![two_head_pdf](https://user-images.githubusercontent.com/40228854/44586811-4bf1fc00-a7b1-11e8-9050-09f9e17bebfd.JPG)

**Comment by PatBoj** [comment]
@openstaxalina One word - content :laughing:, proof below (second screen is from raw - not baked - html file).

![image](https://user-images.githubusercontent.com/20907906/44590239-f91d4200-a7ba-11e8-9d88-54d03afa4581.png)
![image](https://user-images.githubusercontent.com/20907906/44590241-fae70580-a7ba-11e8-9fa7-7f65d6ee4a10.png)

**Comment by openstaxalina** [comment]
Issue moved to [Connexions/content-managers #262](https://github.com/Connexions/content-managers/issues/262) via [**ZenHub**](https://www.zenhub.com/)
