### ISSUE TITLE
Inconsistent displaying of headers of formulas

### ISSUE THREAD

**Issue by wilkus27** [Connexions/webview#1873]
In Pdf headers of formulas display in the middle:

![name_eq_pdf](https://user-images.githubusercontent.com/40228854/44663508-121f3080-aa11-11e8-8a04-f89f7d7a6d7f.JPG)

On katalyst01 (https://katalyst01.cnx.org/contents/MBiUQmmY@20.1:AeeflfGs@10/10-1-Two-Population-Means-with-Unknown-Standard-Deviations) they are aligned to the left:

![name_eq](https://user-images.githubusercontent.com/40228854/44663582-4a267380-aa11-11e8-8d37-95345f334a52.JPG)

What is more, sometimes they are written like above (in normal font) and sometimes in bold (https://katalyst01.cnx.org/contents/MBiUQmmY@20.1:_WrUBaGD@6/10-2-Two-Population-Means-with-Known-Standard-Deviations):

![name_eq2](https://user-images.githubusercontent.com/40228854/44663773-bc975380-aa11-11e8-81e7-7646bfe434d5.JPG)

**Comment by PatBoj** [comment]
@wilkus27 some phrases are written bold, because they are important terms and will be displayed at the end of the book.

**Comment by wilkus27** [comment]
@PatBoj in PDF all centered headers are written bold. If we want to have the same effect on webview it could be resolved just by the content?

**Comment by PatBoj** [comment]
@wilkus27 not necessary, it can be done in css (I've already done that :smile:, waiting for review).

**Comment by wilkus27** [comment]
Changes were merged accidentally before review, so I have already tested them. Everything works properly:

![head1](https://user-images.githubusercontent.com/40228854/44720271-8ec01680-aac6-11e8-9e30-19cad5d47a47.JPG)

![head2](https://user-images.githubusercontent.com/40228854/44720280-967fbb00-aac6-11e8-846a-87b81606a266.JPG)
