### ISSUE TITLE
Wrong displaying of figures in exercises

### ISSUE THREAD

**Issue by wilkus27** [Connexions/webview#1878]
On katalyst01(https://katalyst01.cnx.org/contents/MBiUQmmY@20.1:5vVwPq6h@20.1/Solutions) when exercise begins from figure it display at the left side. It causes wrapping numbering of image.

![fig_left](https://user-images.githubusercontent.com/40228854/44721214-76053000-aac9-11e8-8bf5-a9c31109d15f.JPG)

In PDF figures are centered:

![fig_left_pdf](https://user-images.githubusercontent.com/40228854/44721232-85847900-aac9-11e8-85d1-7365e198702b.JPG)

**Comment by wilkus27** [comment]
@openstaxalina I'm not sure, should figure in exercises be left aligned or centered? If the first solution is correct, the only problem here is wrapping numbering.

**Comment by PatBoj** [comment]
@openstaxalina in my opinion, it should look like this (left alignment and non wrapping figure numbering).
![image](https://user-images.githubusercontent.com/20907906/44721574-a6999980-aaca-11e8-8eb2-a8569f76c145.png)

**Comment by openstaxalina** [comment]
@PatBoj I am flexible on this one; I think we should go with whatever is cleanest from a coding perspective.  cc @helenemccarron

**Comment by PatBoj** [comment]
Ready for testing.

## **Before:**
![image](https://user-images.githubusercontent.com/20907906/45083182-62764c80-b0fb-11e8-8193-a0f014343bef.png)

## **After:**
![image](https://user-images.githubusercontent.com/20907906/45083184-65713d00-b0fb-11e8-9f89-e9b4bfc3a493.png)

**Comment by wilkus27** [comment]
Verified on katalyst01:

![figure_left](https://user-images.githubusercontent.com/40228854/45288410-e27d2780-b4ea-11e8-8c5c-dc11d005fc35.JPG)
