### ISSUE TITLE
Inconsistent displaying of content from Using the Calculator box

### ISSUE THREAD

**Issue by wilkus27** [Connexions/webview#1879]
On katalyst01 content from **Using the Calculator** box displays in few ways:

1) https://katalyst01.cnx.org/contents/MBiUQmmY@20.1:LERaJJIp@6/11-4-Test-for-Homogeneity

![calc1](https://user-images.githubusercontent.com/40228854/44724019-e57f1d80-aad1-11e8-9eb8-c8b9635ef94b.JPG)

2) https://katalyst01.cnx.org/contents/MBiUQmmY@20.1:OPnvi2o4@7/11-3-Test-of-Independence

![calc2](https://user-images.githubusercontent.com/40228854/44724136-26773200-aad2-11e8-9b48-238c57b44da1.JPG)

3) https://katalyst01.cnx.org/contents/MBiUQmmY@20.1:38NI55rV@10/2-2-Histograms-Frequency-Polygons-and-Time-Series-Graphs

![calc3](https://user-images.githubusercontent.com/40228854/44724190-4eff2c00-aad2-11e8-8277-c85a83e29dbb.JPG)

**Comment by openstaxalina** [comment]
Issue moved to [Connexions/content-managers #273](https://github.com/Connexions/content-managers/issues/273) via [**ZenHub**](https://www.zenhub.com/)
