### ISSUE TITLE
Buttons on the bottom of the page move when clicked

### ISSUE THREAD

**Issue by uskka** [Connexions/webview#1882]
All of the buttons on the bottom of the page move slightly when clicked. Appears in all of the books.

Reproduction steps:

1.Scroll to the bottom of the page.
2. Click any button. 
3. Click on the background. 

https://katalyst01.cnx.org/contents/tWu56V64@34.15:fVN7UicZ@7/7-4-Finite-Population-Correction-Factor

![screenshot-katalyst01 cnx org-2018 08 29-15-40-53](https://user-images.githubusercontent.com/40228918/44791468-f72ff600-aba1-11e8-9403-27e801030696.png)

**Comment by openstaxalina** [comment]
@uskka Are you able to capture a .gif or video screen capture of this issue?  Are there any patterns that you can identify as to when this occurs?

**Comment by uskka** [comment]
This is how it looks like. 3 screens one for every reproduction step. It occurs every time I try to reproduce it.

1.  Scroll to the bottom of the page.
2. Click any button.
3. Click on the background.

![output_yfkjbs](https://user-images.githubusercontent.com/40228918/45618993-fccd7d00-ba77-11e8-929e-05c8a2efc77e.gif)

**Comment by PiotrKozlowski** [comment]
Ready for testing

**Comment by uskka** [comment]
Fixed. Verified on katalyst01.
![output_ehpvnk](https://user-images.githubusercontent.com/40228918/46008403-ee591400-c0bc-11e8-9e27-7dfb97c10d77.gif)
