### ISSUE TITLE
Extra space between sentences

### ISSUE THREAD

**Issue by wilkus27** [Connexions/webview#1887]
On katalyst01 in the whole book in random places occur blank spaces between sentences, e.g.
https://katalyst01.cnx.org/contents/MBiUQmmY@20.1:0_rgGM3Y@5/3-3-Two-Basic-Rules-of-Probability

![space](https://user-images.githubusercontent.com/40228854/44810930-8dc8db00-abd3-11e8-96df-1584bb698778.JPG)

https://katalyst01.cnx.org/contents/MBiUQmmY@20.1:W0j59DyL@4/9-1-Null-and-Alternative-Hypotheses

![space2](https://user-images.githubusercontent.com/40228854/44811348-bdc4ae00-abd4-11e8-85a7-299fbca8446b.JPG)

**Comment by PiotrKozlowski** [comment]
There are `<div data-count="1" data-type="newline" id="19182"><br></div>` nodes at those places so it's content issue.

cc @openstaxalina

**Comment by openstaxalina** [comment]
Issue moved to [Connexions/content-managers #288](https://github.com/Connexions/content-managers/issues/288) via [**ZenHub**](https://www.zenhub.com/)
