### ISSUE TITLE
Redirect CNX Give page to OpenStax Give page

### ISSUE THREAD

**Issue by openstaxalina** [Connexions/webview#1891]
We should redirect the “Give” page on CNX.org to the OpenStax “Give” page.  This has several benefits:
(a) users will be added to Salesforce (and all the benefits, both to users & OpenStax, that come with that)
(b) users will receive a properly-formatted gift receipt and have the opportunity to learn more about OpenStax
(c) easier for accounting purposes; the funds are not separate

# Acceptance Criteria
- [x] link to https://openstax.org/give from the cnx.org header
- [x] https://cnx.org/donate redirects to https://openstax.org/give 
- [x] when a user clicks "Give" from the CNX homepage, they are redirected to **in the same tab**
- [ ] regression tests are added/updated to cover the test cases above

# PRs
https://github.com/Connexions/webview/pull/1907

**Comment by kerwinso** [comment]
Verified working on qa.cnx.org, webview sha `7f2345288efd81088783b66b5beebc5748a5c5bb`.

@TomWoodward if you want to automate the regression test, it's here: https://openstax.testrail.com/index.php?/cases/view/210412
Slack me and I can get you a Testrail login.

**Comment by kerwinso** [comment]
Verified working on staging.cnx.org.
