### ISSUE TITLE
Remove donation prompts for CNX Downloads

### ISSUE THREAD

**Issue by openstaxalina** [Connexions/webview#1892]
We should remove the donation prompts when a user wants a file (PDF, EPUB, or ZIP) from cnx.org.

The pages are confusing to users.  Sometimes users think they must donate to receive a PDF.  CS reports that this causes confusion about our mission, and frustration as well as requests for refunds.  Also, if the download button ever malfunctions as it did in last week's critical situation, users are even more convinced they must donate...a mandatory donation isn't really a donation!  

# Acceptance Criteria
- [x] when a user selects an option under the "Get This Book!" button toward the top right of a page in a book on cnx.org, they are **not** directed to a donation prompt.  Instead, the download is initiated.
- [x] when a user selects an option under the "Downloads" tab on the bottom of a page in a book on cnx.org, they are **not** directed to a donation prompt.  Instead, the download is initiated.
- [ ] add automated tests to ensure the correct link is present 

# Example of a donation prompt page:
<img width="1421" alt="screen shot 2018-08-30 at 3 44 42 pm" src="https://user-images.githubusercontent.com/7863733/44878118-aab0ed00-ac6b-11e8-9abe-f4374e58204f.png">

# PRs
https://github.com/Connexions/webview/pull/1907

**Comment by kerwinso** [comment]
Verified on qa.cnx.org, webview sha `7f2345288efd81088783b66b5beebc5748a5c5bb`.

**Comment by kerwinso** [comment]
Verified working on staging.
