### ISSUE TITLE
hyperlinked TOC: links should go to top of module

### ISSUE THREAD

**Issue by kerwinso** [Connexions/webview#1896]
Related to #1838. 

We noticed that clicking on a link in the new TOC jumps you to where the content starts, but below the header — so the user can’t tell which module number they landed on. The preferred experience is to land at the top of the module, or at least at a location where the module number and title are visible.

![image](https://user-images.githubusercontent.com/11298165/45050234-52e8fc00-b046-11e8-8c33-8ed661100eb1.png)

**Comment by openstaxalina** [comment]
Update:
Issue occurs in *Chrome*, not in Safari or Firefox.
Issue does not occur from left-hand ToC navigation pane.
Issue occurs only when first navigating to a module, either from the hyperlinked ToC in the intro page body, or clicking "Next" or "Back".

**Comment by openstaxalina** [comment]
Here are Tom's notes on this issue:
https://openstax.slack.com/archives/C0LA54Q5C/p1536174056000100

**Comment by PiotrKozlowski** [comment]
It works correctly after setting `height: 160px` to `<header id="header">`. I'm not sure why, because `<header>` doesn't seem to rerender after page change and it's height seems to be `160px` all the time anyway. I tried to set `min-height: 160px` but it wasn't working. It has to be `height: 160px`.

**Comment by uskka** [comment]
Works fine. Tested on katalyst01 using Chrome.
https://drive.google.com/file/d/18ymNs5kYkzFQT-TxLonB54YVWjl98XnY/view?usp=sharing
