### ISSUE TITLE
Bullets appear in webview but are not visible in PDF

### ISSUE THREAD

**Issue by uskka** [Connexions/webview#1900]
Black bullets appear in webview but are not visible in the PDF, there are 4 lists like this in the Preface. 

https://staging.cnx.org/contents/J_WQZJkO@6.1:a3dFfRuk@6/Preface

WebView
![screenshot-staging cnx org-2018 09 05-11-04-16](https://user-images.githubusercontent.com/40228918/45083652-b2a1de80-b0fc-11e8-85db-1a73e8429419.png)

PDF
<img width="651" alt="screen shot 2018-09-05 at 11 05 00" src="https://user-images.githubusercontent.com/40228918/45083625-9ef67800-b0fc-11e8-9e08-98792f557f75.png">

**Comment by PiotrKozlowski** [comment]
This should be managed by adding `data-bullet-style="none"` to list in content.

**Comment by openstaxalina** [comment]
Issue moved to [Connexions/content-managers #293](https://github.com/Connexions/content-managers/issues/293) via [**ZenHub**](https://www.zenhub.com/)
