### ISSUE TITLE
Broken picture in the Preface/ About This Book

### ISSUE THREAD

**Issue by uskka** [Connexions/webview#1901]
Broken picture in the Preface/ About This Book. 

https://staging.cnx.org/contents/J_WQZJkO@6.1:a3dFfRuk@6/Preface

![screenshot-staging cnx org-2018 09 05-11-37-28](https://user-images.githubusercontent.com/40228918/45085158-5345cd80-b100-11e8-89a3-e093d6eea4b7.png)

**Comment by PiotrKozlowski** [comment]
This image have `height: intrinsic;` style which is not supported at least on mine and Stefans browsers. It should be set to something else.

**Comment by PiotrKozlowski** [comment]
Related to #1895

**Comment by PiotrKozlowski** [comment]
This is fixed with #1894

**Comment by openstaxalina** [comment]
@uskka please retest; this is the code we just deployed to staging.

**Comment by uskka** [comment]
Issue was fixed with the deploy. 
<img width="917" alt="screen shot 2018-09-05 at 17 05 52" src="https://user-images.githubusercontent.com/40228918/45102456-15f83480-b12e-11e8-90db-c7432a08a523.png">
