### ISSUE TITLE
Margins in tables with bullet lists.

### ISSUE THREAD

**Issue by wilkus27** [Connexions/webview#1902]
On staging.cnx.org (https://staging.cnx.org/contents/kRfPjKij@5.1:pKpFhGyF@5.1/Answer-Key -> answers to the **Chapter 18**) is table with too big margin:

![answer_stag](https://user-images.githubusercontent.com/40228854/45090936-1afabb00-b111-11e8-9f9b-8130d0f4173b.JPG)

There was an another problem before: https://github.com/Connexions/webview/issues/1831.

Screen from this issue:

![webview_margin](https://user-images.githubusercontent.com/40228854/45091157-e6d3ca00-b111-11e8-9387-be64f79d55fe.JPG)

This problem used to occur for this table too.

Screen from issue https://github.com/Connexions/content-managers/issues/199:

![content_199](https://user-images.githubusercontent.com/40228854/45091237-1387e180-b112-11e8-8d35-b3e6b5196336.JPG)

Now Table 11.1 displays properly:

![11_stag](https://user-images.githubusercontent.com/40228854/45091293-3fa36280-b112-11e8-976c-30adb6a16e4c.JPG)

But in Table from Answer Key (first screen) margin is doubled.

**Comment by PiotrKozlowski** [comment]
Tables from this link doesn't have `os-table` class

**Comment by openstaxalina** [comment]
We should discuss whether this is a code or content issue.  It seems related to https://github.com/Connexions/cnx-recipes/issues/595

**Comment by Adrianltd** [comment]
This will most probably be solved after https://github.com/Connexions/cnx-recipes/issues/595 will be merged.

**Comment by wilkus27** [comment]
@Adrianltd After baking there is no problem with horizontal alignment of lists, but now occurs issue with vertical alignment.

![table_list](https://user-images.githubusercontent.com/40228854/45290845-dd22db80-b4f0-11e8-924e-af22baf8c070.JPG)

**Comment by PiotrKozlowski** [comment]
@Adrianltd Those `<td>`s have `data-valign="top"` attribute so there should be rule in css which will align those to `top` instead of `middle`

**Comment by wilkus27** [comment]
Verified on katalyst01 (https://katalyst01.cnx.org/contents/kRfPjKij@4.5:pKpFhGyF@4.5/Answer-Key)

![table2](https://user-images.githubusercontent.com/40228854/45364678-061f9b00-b5db-11e8-8541-1c0070970203.JPG)
