### ISSUE TITLE
AP Physics - Learning Objectives styling

### ISSUE THREAD

**Issue by lwtchu** [Connexions/webview#1904]
![Screen Shot 2018-09-05 at 11.53.49 AM.png](https://images.zenhubusercontent.com/5b57310fb26dd832dfe45b43/92b7415c-0e46-44c9-82df-e1056208850f)

Is it possible to style the Learning Objectives and put them in a box? It's a bit confusing if it goes from a Learning Objective straight into a paragraph.

https://staging.cnx.org/contents/jQSmhtXo@17.1:m47PSR2W@3/2-2-Vectors-Scalars-and-Coordinate-Systems

**Comment by openstaxalina** [comment]
This isn't required for the release.  We'll discuss on tomorrow's call whether this is feasible.

**Comment by PiotrKozlowski** [comment]
This is section have a `learning-objectives` class so I can apply proper styles to all sections with this class.

**Comment by openstaxalina** [comment]
@lwtchu to provide a hex value for the color of box/outline/shaded header around the content.

**Comment by PiotrKozlowski** [comment]
@lwtchu are you okay to style this like other boxes?
example:
![style](https://user-images.githubusercontent.com/31478212/45166344-16a8cd80-b1f7-11e8-9c6b-b1cddaba294b.png)

**Comment by lwtchu** [comment]
@PiotrKozlowski that's what I was thinking. Let's have it match the other boxes. 

Thank you :)

**Comment by PiotrKozlowski** [comment]
Ready for testing

**Comment by wilkus27** [comment]
Verified on katalyst01 (https://katalyst01.cnx.org/contents/jQSmhtXo@16.37:m47PSR2W@3/2-2-Vectors-Scalars-and-Coordinate-Systems)

![learning](https://user-images.githubusercontent.com/40228854/45344847-ff763100-b5a4-11e8-9595-d0eb7f38603b.JPG)

**Comment by openstaxalina** [comment]
re-verified on staging after today's rev:
![screen shot 2018-09-21 at 2 38 48 pm](https://user-images.githubusercontent.com/7863733/45902449-1807f780-bdac-11e8-996d-3522df32fea9.png)
