### ISSUE TITLE
hyperlinks to English versions of Katalyst University Physics missing

### ISSUE THREAD

**Issue by kerwinso** [Connexions/webview#1905]
For Katalyst Univ. Physics vols 1,2 & 3, there's a string that says `Click here for the English version of University Physics` -- but there's nothing to click.

This string appears in two places:
1. On the cnx front page -- click Show More under any of the KUP blurbs. It's the last sentence of the summary.
1. In the new hyperlinked TOC inside KUP vols. 1,2 & 3.

![image](https://user-images.githubusercontent.com/11298165/45108692-f1d32e00-b102-11e8-8f31-060642ac1117.png)

![image](https://user-images.githubusercontent.com/11298165/45108697-f7c90f00-b102-11e8-8a74-27a97f4d99b3.png)

**Comment by kerwinso** [comment]
Part 1 of the bug is live on cnx.org now.

**Comment by openstaxalina** [comment]
Issue also occurs for _Biology_ (1e).  So it appears that any links in the descriptions from openstax.org do not work.  Is it possible to remedy this?

**Comment by PiotrKozlowski** [comment]
Ready for testing

**Comment by uskka** [comment]
Works fine. Tested on katalyst01.
![screenshot-katalyst01 cnx org-2018 09 28-16-58-47](https://user-images.githubusercontent.com/40228918/46216478-f379c580-c33f-11e8-8ef2-00963dc57242.png)
