### ISSUE TITLE
Adjust padding in preface headers

### ISSUE THREAD

**Issue by openstaxalina** [Connexions/webview#1909]
Webview on the left; PDF on the right.
![prefaceheaderpadding](https://user-images.githubusercontent.com/7863733/45113759-d4a55c00-b110-11e8-950b-430f213d43a5.png)

Link to content on staging: https://staging.cnx.org/contents/vEmOH-_p@5.1:RJVDImdU@6/Preface

The webview padding should be similar to the PDF.  There is too much space between the author's name and institution and their bio.

This can be deferred to the next release if needed.

**Comment by PiotrKozlowski** [comment]
There are `<div data-type="newline" id="61397"><br></div>` belowe authors names, so it's content.

**Comment by openstaxalina** [comment]
Issue moved to [Connexions/content-managers #297](https://github.com/Connexions/content-managers/issues/297) via [**ZenHub**](https://www.zenhub.com/)
