### ISSUE TITLE
Business Titles - Quotes smaller font

### ISSUE THREAD

**Issue by lwtchu** [Connexions/webview#1911]
![Screen Shot 2018-09-05 at 2.07.20 PM.png](https://images.zenhubusercontent.com/5b57310fb26dd832dfe45b43/b8f9370c-42fa-4ec6-bae5-1abb7f89bc3a)

Is it possible to have the quote section match the base font? 

https://devb.cnx.org/contents/qAil3UeG@7.4:HngPeN1n@7.4/Critical-Thinking-Case

**Comment by brittany-johnson** [comment]
![screen shot 2018-09-10 at 10 42 37 am](https://user-images.githubusercontent.com/24909007/45308216-93cd8e80-b4e6-11e8-93d1-e39f0411c66c.png)

![screen shot 2018-09-10 at 10 43 33 am](https://user-images.githubusercontent.com/24909007/45308217-93cd8e80-b4e6-11e8-88fa-9b7ba04174ab.png)

**Comment by brittany-johnson** [comment]
Blockquote text size now matches body text size

Blockquote
![screen shot 2018-09-10 at 10 42 37 am](https://user-images.githubusercontent.com/24909007/45308282-ba8bc500-b4e6-11e8-81bd-29373e8f1431.png)

Regular body text
![screen shot 2018-09-10 at 10 43 33 am](https://user-images.githubusercontent.com/24909007/45308318-cd9e9500-b4e6-11e8-93d5-4e342d35e48d.png)

**Comment by Stackblocks** [comment]
Displaying as specified with updated version of content / code.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/410d2702-653e-4542-b118-2e8a0c27e6b0)
