### ISSUE TITLE
Content in table cells centered in PDF, but not webview

### ISSUE THREAD

**Issue by openstaxalina** [Connexions/webview#1913]
webview on the left; PDF on the right
![econ2etablecentering](https://user-images.githubusercontent.com/7863733/45116451-5d73c600-b118-11e8-9ef2-4a1a3cd43f8d.png)

Content on staging: https://staging.cnx.org/contents/vEmOH-_p@5.1:RnWi-sXU@3/17-3-How-to-Accumulate-Personal-Wealth

I think this is likely a content issue but would like @PatBoj @Adrianltd or @PiotrKozlowski to confirm if possible.

**Comment by PiotrKozlowski** [comment]
This is webview, because those table cell have a `data-align="center"` attribute.

**Comment by PiotrKozlowski** [comment]
Ready for testing

**Comment by uskka** [comment]
Fixed on Katalyst01.
![screenshot-www youtube com-2018 09 10-14-51-39](https://user-images.githubusercontent.com/40228918/45298544-1c5d2680-b509-11e8-9059-1885493736a4.png)
