### ISSUE TITLE
Feature title doesn't match pdf

### ISSUE THREAD

**Issue by oscryan** [Connexions/webview#1915]
Science Practices Connection is missing an s on webview:
![Screen Shot 2018-09-05 at 3.24.01 PM.png](https://images.zenhubusercontent.com/5b572ec492e09f0d21193829/7f43429a-2659-495b-9818-67f8f3a43015)

**Comment by openstaxalina** [comment]
Will be fixed in content: https://github.com/Connexions/content-managers/issues/295

Closing.
