### ISSUE TITLE
AP Physics - math not showing up in index

### ISSUE THREAD

**Issue by lwtchu** [Connexions/webview#1916]
![Screen Shot 2018-09-05 at 3.37.44 PM.png](https://images.zenhubusercontent.com/5b57310fb26dd832dfe45b43/21b42c1c-c6ee-4f08-922d-abf539417f4a)

Should look like this: 
![Screen Shot 2018-09-05 at 3.41.23 PM.png](https://images.zenhubusercontent.com/5b57310fb26dd832dfe45b43/dc49f844-30d1-4ec3-a0fb-d78e815cbe87)

https://staging.cnx.org/contents/jQSmhtXo@17.1:Xm0hU3Qa@17.1/Index

**Comment by PiotrKozlowski** [comment]
This looks like content issue. @PatBoj, @Adrianltd can you confirm?

**Comment by oscryan** [comment]
A problem in College physics as well:
<img width="810" alt="screen shot 2018-09-06 at 5 32 23 pm" src="https://user-images.githubusercontent.com/1895432/45188631-d9463f00-b1fa-11e8-92e9-4c4fa944e44a.png">

**Comment by PatBoj** [comment]
This issue is realated to recipes https://github.com/Connexions/cnx-recipes/issues/604.
