### ISSUE TITLE
Adoption form screenshot somehow insinuated into review questions

### ISSUE THREAD

**Issue by oscryan** [Connexions/webview#1917]
It's definitely not in the cnxml; the exercise it shows up in is a tutor-import question.

![Screen Shot 2018-09-05 at 3.30.40 PM.png](https://images.zenhubusercontent.com/5b572ec492e09f0d21193829/45943ca0-9bf5-486e-aef4-f13743d37e64)

**Comment by PiotrKozlowski** [comment]
Link to problem: https://staging.cnx.org/contents/bDIuMp-w@9.1:H6aDiFrM@9.1/Review-Questions

This image is sent to webview with all content so it's recipes or content related. 

@PatBoj , @Adrianltd Can you check if somehow this is added with recipes?

**Comment by Adrianltd** [comment]
This can't be a recipe issue. 

@openstaxalina can you verify that this is content related? This issue does not occur katalyst01.

**Comment by openstaxalina** [comment]
@Adrianltd we also thought this was content related; however, @oscryan checked the content pretty thoroughly.  @oscryan could you share screenshots of the source content - both the cnxml & from Exercises?

**Comment by openstaxalina** [comment]
I am also sharing this with the CNX team in case this is related to staging.cnx.org rather than the content or recipe specifically.

**Comment by openstaxalina** [comment]
Issue resolved!  The reason this is happening is because staging.cnx.org points to exercises-staging.openstax.org.  The exercise (ID: 78) on exercises-staging has the adoption form as a screenshot, likely a QA test of some kind.

**Comment by kerwinso** [comment]
The offending image is here:
https://s3-us-west-2.amazonaws.com/openstax-assets/DLSklViDF-staging/exercises/attachments/large_65c63c19c944e128b846fe3bf0ebe54ec087cf4569eff1fe24a7ab56baeaa0b0.png

which is in the exercise json here: https://exercises-staging.openstax.org/api/exercises/78
