### ISSUE TITLE
Most index terms missing in webview

### ISSUE THREAD

**Issue by oscryan** [Connexions/webview#1918]
For example, the letter N:
![Screen Shot 2018-09-05 at 5.26.03 PM.png](https://images.zenhubusercontent.com/5b572ec492e09f0d21193829/b231fbc2-2647-4300-a234-635b80853278)

**Comment by oscryan** [comment]
also in business stats
<img width="808" alt="screen shot 2018-09-05 at 6 39 19 pm" src="https://user-images.githubusercontent.com/1895432/45126893-44304100-b13b-11e8-92e2-16fa8f3da8e7.png">

**Comment by openstaxalina** [comment]
@oscryan this could be occurring because webview does not index terms from collated sections (i.e. glossaries).  Could you retest and see if that the reason for the missing terms?

**Comment by oscryan** [comment]
Yes, that appears to be it. This seems like a significant oversight, but I guess people might not use webview index very much.

**Comment by openstaxalina** [comment]
Yes, that's exactly it, since we have in book search.  When we polled faculty about this, they ranked improvements to the index -- even in PDF, where there are lots of issues like not combining terms due to different capitalizations, etc. -- very low.
