### ISSUE TITLE
Bullet list in table

### ISSUE THREAD

**Issue by wilkus27** [Connexions/webview#1922]
On staging.cnx.org (https://staging.cnx.org/contents/jVCgr5SL@15.1:Rhq7pkI2@9/C-Measurements-and-the-Metric-System) there is table with bullet lists:

![dot_list](https://user-images.githubusercontent.com/40228854/45152978-d59ec200-b1d2-11e8-83a1-33b2bd4c90bf.JPG)

The same problem was resolved in Concept of Biology https://github.com/Connexions/webview/issues/1732

**Comment by PiotrKozlowski** [comment]
Those lists have empty `data-bullet-style` attributes when it should be set to `none`: `data-bullet-style="none"`, so it's content issue.

**Comment by openstaxalina** [comment]
Screenshot from PDF for reference:
<img width="631" alt="screen shot 2018-09-06 at 8 07 04 am" src="https://user-images.githubusercontent.com/7863733/45159254-e5ef7680-b1ab-11e8-99db-f58f70acc034.png">

**Comment by openstaxalina** [comment]
Issue moved to [Connexions/content-managers #296](https://github.com/Connexions/content-managers/issues/296) via [**ZenHub**](https://www.zenhub.com/)
