### ISSUE TITLE
Intro to Business - bulleted lists within a table not showing

### ISSUE THREAD

**Issue by helenemccarron** [Connexions/webview#1923]
@Bkblodget commented on [Wed Sep 05 2018](https://github.com/Connexions/cnx-recipes/issues/596)

# Scenario

List-style for a list within a table is set to bulleted - styling is correct in PDF but bullets are not showing in webview

# Reproducibility Details

- **https://cnx.org/contents/Tgl3H6iq@4.164:aJs0fVsd@4/6-2-Planning**: 

## Screenshots

**PDF**
![Screen Shot 2018-09-05 at 10.52.07 AM.png](https://images.zenhubusercontent.com/5b572db8a74e9a33056ecb3c/c651dc44-f7f1-4c90-afc6-88d3b05094ed)

**Markup**
![Screen Shot 2018-09-05 at 10.52.46 AM.png](https://images.zenhubusercontent.com/5b572db8a74e9a33056ecb3c/70ce4aec-08ff-410f-9ba7-afb4093cff9b)

**Webview**
![Screen Shot 2018-09-05 at 10.52.15 AM.png](https://images.zenhubusercontent.com/5b572db8a74e9a33056ecb3c/8794b765-47aa-4d4d-aef9-19af41e27afd)

---

@openstaxalina commented on [Wed Sep 05 2018](https://github.com/Connexions/cnx-recipes/issues/596#issuecomment-418808737)

assigning to @lwtchu to prioritize.  I wasn't sure if this was moderate or low based on our Slack thread.

**Comment by brittany-johnson** [comment]
This issue was fixed in `katAW.queued.quadcopter` and will be released on production Tuesday 8/11/18 @Stackblocks

**Comment by Stackblocks** [comment]
Displaying as specified with updated version of content / code.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/6a6209f1-113e-4e5e-8aca-00244c08d0d7)
