### ISSUE TITLE
Edge: Donate slider missing the handle (vertical bar)

### ISSUE THREAD

**Issue by kerwinso** [Connexions/webview#1927]
(found by our offshore tester, who tests in Windows 8.1 in Edge and FF)

1. In MS Edge, go to https://cnx.org/donate
1. Notice the slider has no vertical bar to slide.

![image](https://user-images.githubusercontent.com/11298165/45231716-959f1400-b292-11e8-8811-7e7cab1c60a8.png)

You can still click along the slider to increment the dollar amount. You can also still click Donate Now, the default amount of $10 will be pre-filled in the ensuing form.

**Comment by openstaxalina** [comment]
Closing this because we are removing the donation pages and slider from the downloads on cnx.org
