### ISSUE TITLE
Equation numbering is not styled properly 

### ISSUE THREAD

**Issue by uskka** [Connexions/webview#1935]
Equation numbering is not styled properly because it's missing "os-equation-number" class. 

College Physics
https://staging.cnx.org/contents/Ax2o07Ul@14.1:5AeKbonU@8/34-2-General-Relativity-and-Quantum-Gravity

College Physics For AP® Courses(reference)
https://staging.cnx.org/contents/jQSmhtXo@17.2:CQh5rf9m@5/1-2-Physical-Quantities-and-Units

College Physics
![screenshot-staging cnx org-2018 09 11-12-50-12](https://user-images.githubusercontent.com/40228918/45357083-85a26f80-b5c5-11e8-80e2-bbfe8a9e33a4.png)

College Physics For AP® Courses(reference)
<img width="922" alt="screen shot 2018-09-11 at 13 06 08" src="https://user-images.githubusercontent.com/40228918/45357103-92bf5e80-b5c5-11e8-9cf7-4fedfeb60ad4.png">

**Comment by openstaxalina** [comment]
Also, shouldn't the os-equation-number class be added as a part of this issue?  https://github.com/Connexions/cnx-recipes/issues/609

**Comment by PiotrKozlowski** [comment]
@Adrianltd One more case for your work. Those equations numbers are also on the left insted right

**Comment by uskka** [comment]
Thank you. Fixed by recipes. Screen from katalyst01.
<img width="776" alt="screen shot 2018-09-11 at 16 30 02" src="https://user-images.githubusercontent.com/40228918/45366941-5baa7680-b5e0-11e8-84c7-1aee6e01bd46.png">
