### ISSUE TITLE
legacy account created email bug: help links 404

### ISSUE THREAD

**Issue by kerwinso** [Connexions/webview#1939]
After creating a new account in legacy, a new user gets an email that looks something like this:

```
Your account on the OpenStax CNX system has been created. Your username
is aitbsp.  Please activate your account by visiting

https://legacy-qa.cnx.org/passwordreset/7d5c630a558d7b06318fd322090e540b?userid=aitbsp

You must activate your account before Sep 19, 2018 12:00 pm GMT-5.
If you do not confirm your account before this date, or if you encounter
any problems with the account activation,
please visit http://cnx.org/mail_password_form to generate a new activation
link for your account.

For help getting started with OpenStax CNX, creating content, or to learn
about new features that are available, please visit http://cnx.org/help .
If you have any questions or encounter any difficulties along the way,
please feel free to email us at support@openstax.org and we will be happy
to assist you.

Thank you for joining OpenStax CNX!


--
OpenStax CNX
```

The problem is that both `http://cnx.org/mail_password_form` and `http://cnx.org/help` go to 404 pages.

![image](https://user-images.githubusercontent.com/11298165/45441466-b2698c00-b684-11e8-91b7-037f9627e0ab.png)

NOTE: The correct repo to make the fix is https://github.com/Rhaptos/Products.CNXPloneSite, but I filed this issue in webview for greater visibility.

**Comment by kerwinso** [comment]
This has likely been live on prod for a long time.

**Comment by openstaxalina** [comment]
Change first link to: https://legacy.cnx.org/mail_password_form
Change second link to: https://legacy.cnx.org/help

**Comment by edwoodward** [comment]
https://github.com/Connexions/Products.CNXPloneSite/pull/5

**Comment by reedstrm** [comment]
Fixed via https://github.com/Connexions/Products.CNXPloneSite/pull/5
Needs legacy egg produced and deployed to enable QA testing on qa.cnx.org

**Comment by brittweinstein** [comment]
Verified on QA.

**Comment by brittweinstein** [comment]
This is still failing on staging per Otto's tests.

**Comment by omehes** [comment]
Tested on staging.cnx.org, versions:
"date": "2018-10-29 13:20:54 CDT",
 "webview": "88925f64dd7f9d91468ce60ec995a9be5c18bf51 (v0.40.0)",
 "cnx-archive": "4.6.0",
 "cnx-publishing": "0.14.1",
 "oer.exports": "upbeat.undine v0.65.0",
 "press": "7.0.1",
 "cnx-deploy": "v2.30.1"

All links in the email works. Fixed.
