### ISSUE TITLE
Equation numbering wrapping around the equation

### ISSUE THREAD

**Issue by marcjeannott** [Connexions/webview#1948]
**Problem**

The equation number seems to be wrapping around the image on staging.

![wrap around numbering](https://user-images.githubusercontent.com/33228728/45704071-a32e8680-bb3b-11e8-918f-7b7bad1cf896.jpg)

This is unlike the other equations found in this book.

**More Detail**

Link - https://staging.cnx.org/contents/jQSmhtXo@19.1:WwXAbgy9@19.1/Answer-Key

**Comment by Adrianltd** [comment]
@marcjeannott Equations in the Answer Key should not be numbered. If you look at your link again you can verify that it does no longer exist due to the recipe fix.

**Comment by marcjeannott** [comment]
Yes! This has been fixed in the newest recipe fix. Thanks Adrian, I'm closing this now.
