### ISSUE TITLE
Book description text issue on mobile

### ISSUE THREAD

**Issue by edwoodward** [Connexions/webview#1951]
The book description in the first Intro page is being pushed far to the right by the book cover. The cover should be above the text on mobile instead of to the left. The problem was seen on Android and iPhone.

![screenshot_20180919-073548](https://user-images.githubusercontent.com/1394695/45756233-ffe67b80-bbe5-11e8-8cf0-4424d9edbdc2.png)

**Comment by Adrianltd** [comment]
@edwoodward could you verify the fix?

**Comment by openstaxalina** [comment]
Per conversation on the call, Stefan (and/or Natalia) will test this.

**Comment by uskka** [comment]
Works fine. Tested on katalyst01.

**IOS**
![42730735_597082417356617_8514398005732835328_n](https://user-images.githubusercontent.com/40228918/46279976-eee52500-c56a-11e8-807d-4a2c3fd6d130.jpg)

** Android**
![screenshot_20180929-081624_samsung internet](https://user-images.githubusercontent.com/40228918/46279923-c0674a00-c56a-11e8-9911-afe41e24a477.jpg)
