### ISSUE TITLE
Visual Connection repeats twice

### ISSUE THREAD

**Issue by marcjeannott** [Connexions/webview#1956]
In *AP Biology* the sections called "Visual Connection" appear twice. This is found throughout the book, but here's a link to one of them: https://staging.cnx.org/contents/bDIuMp-w@12.1:wIx28lku@6/11-2-Sexual-Reproduction

![visualconnectionx2](https://user-images.githubusercontent.com/33228728/45886026-98fbca80-bd7d-11e8-892a-1b1855e37dec.jpg)

Currently on production server, it correctly only shows one visual connection.

**Comment by openstaxalina** [comment]
We will park this on Monday to determine if we could/should resolve this in the content.

**Comment by PiotrKozlowski** [comment]
There are two `<header>` tags so it's probably related to recipes. @Adrianltd, @PatBoj can you confirm?
```
<header>
   <h3 class="os-title" data-type="title" data-label-parent="Visual Connections">
      <span class="os-title-label">Visual Connection</span>
   </h3>
</header>
<header>
   <h3 class="os-title" data-type="title" data-label-parent="Visual Connections">
      <span class="os-title-label">Visual Connection</span>
   </h3>
</header>
```

**Comment by Adrianltd** [comment]
I believe it's the same as here https://github.com/Connexions/content-managers/issues/305.

**Comment by Adrianltd** [comment]
Issue moved to [Connexions/cnx-recipes #642](https://github.com/Connexions/cnx-recipes/issues/642) via [**ZenHub**](https://www.zenhub.com/)
