### ISSUE TITLE
Figure Numbering off 

### ISSUE THREAD

**Issue by marcjeannott** [Connexions/webview#1957]
In AP Bio, Figure 15.7 in the PDF is numbered 15.8 in the baked webview.  https://staging.cnx.org/contents/bDIuMp-w@16.1:MWnotoAf@11/15-2-Prokaryotic-Transcription

![unequalfigurenumbers](https://user-images.githubusercontent.com/33228728/45967489-c9e53500-bff3-11e8-9a84-fe90dd58096f.jpg)

It mysteriously bumps up a number (the last figure number in 15.1 is Figure 15.6) from one section to the next. Both Ryan and I have looked at this, and we can't figure out where this missing figure is coming from. My _best guess_ is that somehow the figure in the "Science Practice Challenge Questions" called Figure 15.18 (so 15.19 in current baked webview) is also being counted as 15.7 in the baked webview. In the unbaked book, this figure would be the only thing in between Figures 15.6 and 15.7. 

May the force be with you. 🙏

**Comment by openstaxalina** [comment]
Issue moved to [Connexions/cnx-recipes #654](https://github.com/Connexions/cnx-recipes/issues/654) via [**ZenHub**](https://www.zenhub.com/)
