### ISSUE TITLE
For each independent page (all versions) of OpenStax content, add a canonical tag that points to the corresponding page-in-book of the most updated version within the master book on CNX.org

### ISSUE THREAD

**Issue by brittweinstein** [Connexions/webview#1959]
@openstaxalina commented on [Tue Sep 25 2018](https://github.com/Connexions/cnx/issues/28)

## Overview/Purpose
This will help Google spiders know what content to crawl among our duplicate content.
## Design/Notes
Technical implementation is in webview to update the html header, much like the title tag is updated, as each new page is viewed.
## PRs
What PRs need to be merged to complete this task/feature
## Test Plan
There are 4 scenarios to test. All rely on checking the page json for the canonical UUID. The canonical UUID in the page json is the canonical book for the page. It is set even if the book is not viewed in the context of a book. The canonical link can be found by inspecting the source of the <head> element in browser dev tools. The Page UUID can be found in the "More Information" tab at the bottom of any page. Make sure the Page button is selected. 

Example URL to page Json
>https://archive-staging.cnx.org/contents/ad9b9d37-a5cf-4a0d-b8c1-083fcc4d3b0c.json

Example canonical UUID in page json
>canonical:	"fe7c617f-e275-460c-8eea-b7558aaaa129"

Example canonical link
```<link rel="canonical" href="https://staging.cnx.org/contents/fe7c617f-e275-460c-8eea-b7558aaaa129:ad9b9d37-a5cf-4a0d-b8c1-083fcc4d3b0c">```

**Scenario 1** - Page in a book context. The URL should contain the canonical UUID and the current page UUID. This should work with any OpenStax book.
**Scenario 2** - Page outside of a book context, but it has a canonical UUID in the page json.The URL should contain the canonical UUID and the current page UUID
Example URL - https://staging.cnx.org/contents/gHr6ArMq@18/The-Circle-of-Fifths
**Scenarion 3** - Page is not in a book. The canonical URL should contain the page UUID only
Example URL - https://staging.cnx.org/contents/OlIuW7sM@1/Derived-copy-of-The-Circle-of-Fifths
**Scenario 4** - Page is in a book, but the canonical is null. This will happen rarely, but is possible. The URL should contain the current book and page UUIDs. The test URL on staging I used to write the code now has a canonical UUID, so I'm not sure this is testable.

## Acceptance Criteria
-pages in derived versions of OpenStax books point back to the OpenStax book

**Comment by brittweinstein** [comment]
CC @openstaxalina moving this to 11.05.18 Release

**Comment by edwoodward** [comment]
https://github.com/Connexions/webview/pull/2005

**Comment by omehes** [comment]
Testing as per discussion and instructions from Ed:

staging.cnx.org
and
archive-staging.cnx.org/contents/....json

Scenario 1 - Page in a book context. The URL should contain the canonical UUID and the current page UUID. This should work with any OpenStax book.
- selected Biology and Chemistry books - canonical links/IDs are the same
Scenario 2 - Page outside of a book context, but it has a canonical UUID in the page json.The URL should contain the canonical UUID and the current page UUID
Example URL - https://staging.cnx.org/contents/gHr6ArMq@18/The-Circle-of-Fifths
- used above example - IDs the same
Scenarion 3 - Page is not in a book. The canonical URL should contain the page UUID only
Example URL - https://staging.cnx.org/contents/OlIuW7sM@1/Derived-copy-of-The-Circle-of-Fifths
- used above example and another: https://staging.cnx.org/contents/LZ5cvGq_@1/Derived-copy-of-Derived-copy-of-Introduction-to-Anatomy-Module-4-Functions-of-Human-Life
- canonical IDs for the book = null (only page IDs are shown)
Scenario 4 - Page is in a book, but the canonical is null. This will happen rarely, but is possible. The URL should contain the current book and page UUIDs. The test URL on staging I used to write the code now has a canonical UUID, so I'm not sure this is testable.
- not able to test (cannot find any case of this character)
