### ISSUE TITLE
Chemistry2e - Art oversized in webview

### ISSUE THREAD

**Issue by openstaxalina** [Connexions/webview#1962]
@mwest-WWprod commented on [Mon Sep 24 2018](https://github.com/Connexions/oer.exports/issues/3784)

content04
GLOBAL

As with #3696, art in webview is oversized.  Art looks correct within the PDF output.

![oversized art chemistry](https://user-images.githubusercontent.com/19212926/45982597-55c48480-c027-11e8-866c-f21fea5ba470.PNG)

Would we be able to use the 'scaled down' class to treat affected figures, as in Ethics?

---

@mwest-WWprod commented on [Tue Sep 25 2018](https://github.com/Connexions/oer.exports/issues/3784#issuecomment-424447539)

@openstaxalina my apologies, I mistakenly opened this in oer.exports.

---

@openstaxalina commented on [Wed Sep 26 2018](https://github.com/Connexions/oer.exports/issues/3784#issuecomment-424758848)

@mwest-WWprod no worries.
The scaled-down class is a great suggestion; however, looking back at https://github.com/Connexions/webview/issues/1709, it currently only works in baked books.  We will not be ready to bake Chemistry until early 2019.  

I spoke with Larissa, and we agree that it would be preferable for you to add the scaled-down class when images are too large.  However, you will not see any effect.  If you share the list of images that have the class with us (perhaps in the same format that you deliver the list to the XML team), we can ensure that they are properly scaled down once we bake Chemistry.

Please let us know your thoughts when you get the chance.  Anthony alerted me that this may have schedule impact; however, we should be able to accommodate that.

**Comment by lwtchu** [comment]
Closing since we have a solution listed above.
