### ISSUE TITLE
Missing whitespaces in books descriptions

### ISSUE THREAD

**Issue by uskka** [Connexions/webview#1964]
Every `<br>` tag from books description was disabled so now only whitespaces that appeared in plain text are visible.  `<br>` tags should be enabled again or whitespaces should be added to content. Tags were removed in this issue https://github.com/Connexions/webview/issues/1905.

![screenshot-katalyst01 cnx org-2018 09 28-16-49-50](https://user-images.githubusercontent.com/40228918/46216852-c5e14c00-c340-11e8-9ccc-0f8ba2d70988.png)

**Comment by PiotrKozlowski** [comment]
Ready for testing

**Comment by uskka** [comment]
Issue fixed. Tested on katalyst01.
![screenshot-katalyst01 cnx org-2018 10 09-19-41-56](https://user-images.githubusercontent.com/40228918/46687558-6b2ad880-cbfb-11e8-9009-350bba93c500.png)
