### ISSUE TITLE
Additional line breaks

### ISSUE THREAD

**Issue by wilkus27** [Connexions/webview#1977]
On katalyst01 are places with additional line breaks in the middle of the sentences. Probably they appear because in PDF those sentences look better with break line in specific place.

1. https://katalyst01.cnx.org/contents/LnN76Opl@14.4:jccCTwYm@3/3-2-Newton-s-Great-Synthesis

![break1](https://user-images.githubusercontent.com/40228854/46862552-63468080-ce15-11e8-8e28-17308584c4a4.JPG)

2. https://katalyst01.cnx.org/contents/LnN76Opl@14.4:0k5OsbbT@14.4/Collaborative-Group-Activities

![break2](https://user-images.githubusercontent.com/40228854/46862653-a0ab0e00-ce15-11e8-9fbb-e2fc18bbfc22.JPG)

**Comment by Adrianltd** [comment]
Here's the culprit:
![newline](https://user-images.githubusercontent.com/40228907/46872498-90eef200-ce34-11e8-9367-9344c97baa3f.png)

**Comment by lwtchu** [comment]
This seems like a small enough fix for CMs. We can copy this to the CM board and Katalyst can fix on katalyst01.

**Comment by brittweinstein** [comment]
Katalyst team to remove line break from footnote when @lwtchu shares credentials.

**Comment by lwtchu** [comment]
Verified fixed on katalyst01 server.
