### ISSUE TITLE
KNOWN ISSUE: Blank space between text and equation

### ISSUE THREAD

**Issue by wilkus27** [Connexions/webview#1979]
In **Astronomy** textbook on katalyst01 is place where between paragraph and equation occurs blank space. Probably this issue is related with https://github.com/Connexions/content-managers/issues/299.

 https://katalyst01.cnx.org/contents/LnN76Opl@14.4:nWRC8nG_@7/5-6-The-Doppler-Effect

![eq1](https://user-images.githubusercontent.com/40228854/46871418-a6165180-ce31-11e8-9a18-ae61ae4876d4.JPG)

**Comment by Adrianltd** [comment]
I agree that this is content related and related to to https://github.com/Connexions/content-managers/issues/299 

The Mathjax element structure is causing that gap.

**Comment by lwtchu** [comment]
Low priority: I think we can treat this as a known issue and move it to the CM backlog.

**Comment by lwtchu** [comment]
Issue moved to [Connexions/content-managers #432](https://github.com/Connexions/content-managers/issues/432) via [**ZenHub**](https://www.zenhub.com/)
