### ISSUE TITLE
Wrong display of equation

### ISSUE THREAD

**Issue by wilkus27** [Connexions/webview#1981]
On katalyst01 (https://katalyst01.cnx.org/contents/LnN76Opl@14.4:ezVfd5hL@4/18-3-Diameters-of-Stars) there is equation with blank space inside:

![equation](https://user-images.githubusercontent.com/40228854/47012059-aa997d80-d143-11e8-8543-6604dd3e1035.JPG)

**Comment by openstaxalina** [comment]
@lwtchu could you take a look at this one and advise on next steps before Thursday's call if possible?  I thought newline was the culprit, but this is all math.  Maybe malformed?  It looks fine in the PDF:
![screen shot 2018-10-16 at 3 36 07 pm](https://user-images.githubusercontent.com/7863733/47045762-3a95f200-d159-11e8-9e61-32c45cfcfdce.png)

We might want to take a peek at the content, but I would say this is low-priority (maybe Tier 1).

**Comment by lwtchu** [comment]
It's in a math table - I think it's meant to align somehow to the equal sign but it's not working out. I agree we can make this low-priority. I don't think it's displaying correctly in the PDF so it'll take some time to figure out.

**Comment by lwtchu** [comment]
Moving to content-manager repo. We'll mark this as a known issue but it's low-priority.

**Comment by lwtchu** [comment]
Issue moved to [Connexions/content-managers #445](https://github.com/Connexions/content-managers/issues/445) via [**ZenHub**](https://www.zenhub.com/)
