### ISSUE TITLE
WAITING (Courtney to replicate or close this issue) Current book versions not showing up in Google Analytics

### ISSUE THREAD

**Issue by brittweinstein** [Connexions/webview#1992]
# Scenario
Some versions of books are not reporting to some of their Google Analytics properties. For example, in the CNX.org property, the latest version showing up for College Physics is 10.1, but the current version of College Physics is 14.2 (and there have been multiple in between). The more current versions of College Physics ARE showing up in the book-specific College Physics property AND in the OpenStax Books Web View property.

The most current version of Sociology 2e (11.1) is ONLY showing up in OpenStax Books Web View and is NOT showing up in CNX.org or in the Sociology 2e property.

This means we are tracking incorrectly and using data.

All book versions should track to three properties - CNX.org (UA-7903479-1), OpenStax Books Web View (UA-101537094-1), and their book-specific property.  We need to have something in place to make sure every new version gets tracking for all three.

# Steps to Reproduce

* **Product**: [ ] Tutor   [ ] Concept Coach [ ] OS Web [ ] Content Production Toolkit [x] CNX

* **How many times were you able to reproduce the issue?** 

* **Images or Screenshots Included:** [ ] Yes  [ ] No  (_attach below_)

# Environment:
 
* **Instance**: [ ] production  [ ] qa  [ ] staging  [ ] dev  [ ] content
* **OS**: [ ] Mac OSX  [ ] Windows  [ ] iOS  [ ] Android
* **Browser**: [ ] Chrome  [ ] Firefox  [ ] Safari  [ ] Opera  [ ] IE  [ ] Edge

# Impact

* **Severity**: [x] High [ ] Medium  [ ] Low
* **Frequency of Occurrence**: [ ] High [ ] Medium  [ ] Low

# Next Steps for User
If the card is accepted or rejected, what does user need to know now?

**Comment by brittweinstein** [comment]
From Courtney: In another example - the current version of Intro to Sociology 2e is 11.1. Version 11.1 is only showing up in the OpenStax Books Web view property. It is NOT showing up in the CNX.org property or the Intro to Sociology 2e property.

**Comment by edwoodward** [comment]
From the debugger print out, we are sending this data for the location and page. We are not sending the same data for the IDs that are being sent twice.

UA-30227798-14
-----------------------
location         (&dl)   https://cnx.org/contents/02040312-72c8-441e-a685-20e9333f3e1d
page             (&dp)   /contents/02040312-72c8-441e-a685-20e9333f3e1d

location         (&dl)   https://cnx.org/contents/02040312-72c8-441e-a685-20e9333f3e1d
page             (&dp)   /contents/AgQDEnLI@11.1:TrIRM88K@7/Introduction-to-Sociology

UA-101537094-1
-----------------------
location         (&dl)   https://cnx.org/contents/02040312-72c8-441e-a685-20e9333f3e1d
page             (&dp)   /contents/02040312-72c8-441e-a685-20e9333f3e1d

location         (&dl)   https://cnx.org/contents/02040312-72c8-441e-a685-20e9333f3e1d
page             (&dp)   /contents/AgQDEnLI@11.1:TrIRM88K@7/Introduction-to-Sociology

UA-7903479-1
--------------------
location         (&dl)   https://cnx.org/
page             (&dp)   /contents/AgQDEnLI@11.1:TrIRM88K@7/Introduction-to-Sociology

**Comment by philschatz** [comment]
These PR's might be related (just searched for "analytics" in the closed PR's):

- https://github.com/Connexions/webview/pull/1660
- https://github.com/Connexions/webview/pull/1657
- https://github.com/Connexions/webview/pull/1656
- https://github.com/Connexions/webview/pull/1630
- https://github.com/Connexions/webview/pull/1630
- https://github.com/Connexions/webview/pull/1605

**Comment by CourtneyRay** [comment]
@edwoodward @philschatz I am not able to recreate this issue in Analytics today. I'll do some more exploring this week to see if the "current versions not showing" issues needs to be closed. I created a separate issue for the duplicate URLs per page visit.

**Comment by CourtneyRay** [comment]
I am unable to replicate this issue (some versions not showing up in tracking) in Google Analytics - I'm closing this issue.
