### ISSUE TITLE
Track PDF downloads in Google Analytics

### ISSUE THREAD

**Issue by brittweinstein** [Connexions/webview#1993]
# Description
We want to be able to see how many users download PDFs of our content in CNX so we can get a better picture of usage. 

Note that we decided to do this for all file downloads (zip & PDF) for all content on CNX.

# Impact
* **Severity**: [ ] High [x] Medium  [ ] Low
* **Frequency of Occurence**: [x] High [ ] Medium  [ ] Low

# Acceptance
PDF downloads are tracked as events in Google Analytics. Format/setup should mirror how downloads are tracked as events on OSWeb for consistency.

# Next Steps for User
_If the card is accepted or rejected, what does user need to know now?_

**Comment by brittweinstein** [comment]
From Courtney: Hi! This function is really important to Unicorn development, and Kim and JP have asked for information on amount of PDF downloads in CNX. Is there a way that this work could be moved up?

**Comment by edwoodward** [comment]
A quick check of production shows that currently we are not sending anything on PDF downloads.

**Comment by edwoodward** [comment]
https://github.com/Connexions/webview/pull/2082

![screenshot from 2018-11-20 12-24-47](https://user-images.githubusercontent.com/1394695/48794858-ceab2a00-ecc0-11e8-8740-98d411769934.png)

**Comment by brittweinstein** [comment]
Otto will need to install Google Analytics debugger and then will download a PDF and see the effect in the debugger. This is a Chrome extension.

**Comment by omehes** [comment]
Verified on staging.cnx.org for pdf, zip and epub files. OK

{"date": "2018-11-30 13:34:04 CST",
 "webview": "969e07959a31572cdb61fec6f4573b5644d55637 (v0.42.0)",
 "cnx-archive": "4.6.0",
 "cnx-publishing": "0.14.1",
 "oer.exports": "worried.werewolf v0.67.0",
 "press": "7.0.1",
 "cnx-deploy": "v2.32.1"
}
