### ISSUE TITLE
Remove dots from lists in preface

### ISSUE THREAD

**Issue by uskka** [Connexions/webview#1994]
Dots in lists should be removed, there is not a single list with a dot in the PDF. Webview should look like the PDF.

https://katalyst01.cnx.org/contents/yqV9q0HH@13.2:F2OdurwH@24/Preface

Webview (list 1)
![screenshot-katalyst01 cnx org-2018 10 23-12-20-25](https://user-images.githubusercontent.com/40228918/47354719-b6df8680-d6bf-11e8-81cb-94a052b437d2.png)

PDF
![screenshot-d3bxy9euw4e147 cloudfront net-2018 10 23-12-20-01](https://user-images.githubusercontent.com/40228918/47354724-bcd56780-d6bf-11e8-803f-de5b930b8d02.png)

PDF (list 2,3,4)
![screenshot-d3bxy9euw4e147 cloudfront net-2018 10 23-12-25-38](https://user-images.githubusercontent.com/40228918/47354785-e42c3480-d6bf-11e8-9dfd-2d44c3e05016.png)
#############################################################################

![screenshot-d3bxy9euw4e147 cloudfront net-2018 10 23-12-25-24](https://user-images.githubusercontent.com/40228918/47354790-e8585200-d6bf-11e8-8afd-b9680a96fc16.png)
#############################################################################
![screenshot-d3bxy9euw4e147 cloudfront net-2018 10 23-12-38-32](https://user-images.githubusercontent.com/40228918/47355054-a8459f00-d6c0-11e8-92e5-184912ed117c.png)

**Comment by PiotrKozlowski** [comment]
@PatBoj If you want me to handle this in webview I'll need you to add some specific class so I can target those lists.

Btw. There are `<div data-type="newline">` so I'll not remove them. They should be automatically fixed after merging https://github.com/Connexions/rhaptos.cnxmlutils/pull/170

**Comment by PatBoj** [comment]
@PiotrKozlowski Ok, if you want you can do this :), thanks.

**Comment by PiotrKozlowski** [comment]
Acctually there is selector for removing bullets `data-bullet-style="none"`. But class will also work, because there should be added some `margin-bottom` for paragraphs.

**Comment by lwtchu** [comment]
I removed the bullets on katalyst01 and will do this on production.

**Comment by lwtchu** [comment]
Issue moved to [Connexions/content-managers #451](https://github.com/Connexions/content-managers/issues/451) via [**ZenHub**](https://www.zenhub.com/)
