### ISSUE TITLE
One letter terms

### ISSUE THREAD

**Issue by wilkus27** [Connexions/webview#1997]
On katalyst01 (https://katalyst01.cnx.org/contents/havxkyvS@12.1:irEQ7kJz@12.1/Index) there is a problem with one letter terms. On webview they are treated as headers. This problem occured in other books https://github.com/Connexions/content-managers/issues/225

webview
1) 
![term_a](https://user-images.githubusercontent.com/40228854/47368134-5feaa900-d6e1-11e8-90f8-5a44bde09991.JPG)
2)
![term_k](https://user-images.githubusercontent.com/40228854/47368151-6711b700-d6e1-11e8-9aef-a5de785dde1b.JPG)

PDF
1)
![term_a_pdf](https://user-images.githubusercontent.com/40228854/47368169-6f69f200-d6e1-11e8-8499-e826d6dd26bb.JPG)
2)
![term_k_pdf](https://user-images.githubusercontent.com/40228854/47368186-798bf080-d6e1-11e8-9c6f-225123168f2d.JPG)

**Comment by lwtchu** [comment]
We'll have to talk to Anthony to redo some of these terms. I'll close this and move it to the content-manager board. By the next content refresh hopefully these will be gone.

**Comment by lwtchu** [comment]
Issue moved to [Connexions/content-managers #440](https://github.com/Connexions/content-managers/issues/440) via [**ZenHub**](https://www.zenhub.com/)
