### ISSUE TITLE
Mobile devices: Search bar opens and covers large part of the display 

### ISSUE THREAD

**Issue by omehes** [Connexions/webview#1998]
Steps:
1. run staging.cnx.org on a smaller mobile device 
2. open a book
3. start scrolling the page up/down
4. turn device to landscape orient and scroll up
Expected: You should be able to scroll the pages up and down without any major distractions, like the search bar rolling down and covering half of the display
Actual: when scrolling up (towards the top of the page), the search bar tends to roll in on top of the content. It makes the reading very difficult especially in landscape orient on phones.

I tried on Android phone LG G3 on Chrome

@brittweinstein 

 
![Screenshot_2018-10-22-15-52-21.png](https://images.zenhubusercontent.com/5bc8d1f2fe40ab78d94e65fb/ff385c66-a55a-4751-8e0a-3cc27caff832)

**Comment by openstaxalina** [comment]
I missed this bug while I was out!  
I agree that the search bar rolling in when you scroll up is desired.
I really like both mock-ups.  I will review these with the CNX team to see if they have a preference.  Additionally, we will assess the test load for this.  

cc @PiotrKozlowski @omehes

**Comment by openstaxalina** [comment]
Oh, good point @omehes.  @PiotrKozlowski is it possible to show what this will look like in landscape (horizontal)?  If this is out of scope for you, let me know, and I will think about how to move forward.

**Comment by PiotrKozlowski** [comment]
It should look like this: (it's from resolution `> 768px` but I can adjust it for LG G3)
![resp](https://user-images.githubusercontent.com/31478212/48123350-f5597180-e279-11e8-9230-24f24c6fafd5.png)

**Comment by omehes** [comment]
Looks good. @PiotrKozlowski @openstaxalina

**Comment by openstaxalina** [comment]
@omehes I assigned you and moved this to the Regression Testing column so that you can regression test on staging next week.

**Comment by PiotrKozlowski** [comment]
It's not merged yet. Also I'm not sure if I understood correctly - change in vertical view (toggling searchbar) is not needed? 

I've just changed some paddings in vertical view and change media breakpoint for landscape mode so it looks like on the screen I've attached earlier:

![landscape](https://user-images.githubusercontent.com/31478212/48260778-08f10d80-e41d-11e8-9871-ba048675c921.png)
![vertical](https://user-images.githubusercontent.com/31478212/48260779-08f10d80-e41d-11e8-8971-c6c35b276e2b.png)

Let me know if this is okay for this issue or you want feature with toggling search bar after click?

**Comment by openstaxalina** [comment]
This looks great in the screenshots above @PiotrKozlowski

**Comment by PiotrKozlowski** [comment]
Merged into master

**Comment by omehes** [comment]
Verified on qa.cnx.org on LG G3 and simulated mob devices. Fixed

{"date": "2018-11-20 12:14:23 CST",
 "webview": "a05781ee00cde05e5ce04d017c361d7a3cde1722 (v0.41.1-33-ga05781e)",
 "cnx-archive": "582474ce6a01415179dcbbb982bcc469fd870b58",
 "cnx-publishing": "6d86c1f9f797119d0bb9302a33ca1cfebba86005",
 "oer.exports": "vagrant.valkyrie v0.66.0",
 "press": "7.1.0",
 "cnx-deploy": "v2.31.0-21-g5c78537"
}

**Comment by omehes** [comment]
verified on reverted staging.cnx.org. ok

{"date": "2018-11-28 17:45:22 CST",
 "webview": "5512a7c1a8bcee7f5940fdbb5e75be44cb7e1583 (v0.41.1)",
 "cnx-archive": "4.6.0",
 "cnx-publishing": "0.14.1",
 "oer.exports": "vagrant.valkyrie v0.66.0",
 "press": "7.0.1",
 "cnx-deploy": "v2.31.2"
}
