### ISSUE TITLE
Mobile devices: Some text can go off screen in both orients

### ISSUE THREAD

**Issue by omehes** [Connexions/webview#1999]
Steps:
1. run staging.cnx.org on a smaller mobile device (I tested on Android phone LG G3) 
2. open a book, like https://staging.cnx.org/contents/AndhM9Sd@4.13:QQLN142k@8/Dividing-Polynomials
3. scroll around the page in both orients
Expected: the text should be readable in both orients and should not be cut-off
Actual: Some text, like math equations or tables can have end parts cut-off in portrait or both orients. See examples below:

1. Link: https://staging.cnx.org/contents/AndhM9Sd@4.13:QQLN142k@8/Dividing-Polynomials
- in this case the table is so wide that its right section (part of Function column and all of f(c) column) is hidden in both orient, making it unreadable for the user.

![Screenshot_2018-10-22-14-52-11.png](https://images.zenhubusercontent.com/5bc8d1f2fe40ab78d94e65fb/c3f5e1da-cb0e-4f5b-8811-680062508b75)

2. Link: https://staging.cnx.org/contents/AndhM9Sd@4.13:2oR4tJO8@6/Polynomial-Equations
- text is cut-off in portrait orient only

![Screenshot_2018-10-22-14-37-42.png](https://images.zenhubusercontent.com/5bc8d1f2fe40ab78d94e65fb/71c8df5d-7873-4081-ab0c-cdf0998b7eac)

3. Another example: https://staging.cnx.org/contents/AndhM9Sd@4.13:gc_Ek8hX@2/Sequences
- solution section is shifted off the screen in portrait orient

![Screenshot_2018-10-22-15-51-06.png](https://images.zenhubusercontent.com/5bc8d1f2fe40ab78d94e65fb/5c1a8faa-8fe6-4148-b185-a81a486ba6f4)

@brittweinstein

**Comment by edwoodward** [comment]
@PiotrKozlowski We were wondering if it is possible to get MathJax to wrap the math that is an issue. Please give it a try.

**Comment by omehes** [comment]
Hi,

on mobile devices I cannot scroll the tables, like in  
https://staging.cnx.org/contents/AndhM9Sd@4.13:QQLN142k@8/Dividing-Polynomials

If student uses a phone to read the book, some sections will be lost  
in both orients (in some cases only in Portrait).

Ottó



Quoting Piotr Kozłowski <notifications@github.com>:

**Comment by PiotrKozlowski** [comment]
@omehes Tables are fixed only in baked books. Intermediate Algebra is not baked. Would you like me to create similar solution for tables in not baked books?

**Comment by omehes** [comment]
@PiotrKozlowski That would be a good solution to the problem but let's see what @edwoodward @brittweinstein think about it (pls see the above messages).

**Comment by edwoodward** [comment]
@PiotrKozlowski Adding the ability to scroll side to side on tables in non-baked books would be great. I don't think we should change equations that are not marked with the proper data-type unless they are marked as Block. That should allow you to add the side to side scrolling without resizing.

**Comment by PiotrKozlowski** [comment]
@omehes Changes merged into master. You should be able to scroll equations with `data-type="equation"` and tables in baked and unbaked books.

**Comment by philschatz** [comment]
Also, MathJax has an a11y plugin that supports zooming on click/hover. I am not sure if it is configurable but that might be easier than implementing the scroll. It also has the benefit of keeping the math small on a phone but getting bigger when clicked

![mathjax](https://user-images.githubusercontent.com/253202/47873906-6e6f4980-dde0-11e8-9fc2-c3d7756fd86a.gif)

/cc @edwoodward

**Comment by PiotrKozlowski** [comment]
@omehes I can see changes at `qa.cnx.org`, can you confirm?

**Comment by omehes** [comment]
@PiotrKozlowski I checked on qa.cnx.org. Some sections are scrollable, some not. Also, there is still a lot of spillage of equations beyond the screen. I guess this is all related to data-type issue discussed above?

**Comment by PiotrKozlowski** [comment]
Yes, only equations with `data-type="equation"` are scrollable. You can check if equations has this attribute with `right click` ? `Inspect element` above equation and then find this equation in dev tools.

Which sections are not scrollable but should be? This might be the case when table is automatically shrinking cells which is preventing `overflox: auto;` from work.
