### ISSUE TITLE
mobile device: some buttons/text overlap in portrait orient

### ISSUE THREAD

**Issue by omehes** [Connexions/webview#2000]
Steps:

1. run staging.cnx.org on a smaller mobile device (I used Android phone LG G3)
2. open a book and scroll to the bottom of the page
3. in portrait orient, tap on "More information" button
Expected: "More information" section opens and buttons/text remain displayed organised and side-by-side
Actual: Some buttons and text overlap in portrait orient (see attached screen shot). This applies to any book on smaller mob devices.

I tried on Android phone LG G3 on Chrome

Link: https://staging.cnx.org/contents/AndhM9Sd@4.13:HCaG_W5c@4/Introduction

Screen shot: 
![Screenshot_2018-10-23-12-28-31.png](https://images.zenhubusercontent.com/5bc8d1f2fe40ab78d94e65fb/9594f9ae-5369-49f7-b8bb-73a7c37c714e)

Note that something similar happens with Attribution and History buttons:

![Screenshot_2018-10-23-12-45-51.png](https://images.zenhubusercontent.com/5bc8d1f2fe40ab78d94e65fb/d3b1318b-4aec-4ba5-9a3a-c72d899811c0)

**Comment by uskka** [comment]
In History section issue was fixed but still doesn't work for Attribution.

![44753988_282336835725785_3779686432977715200_n](https://user-images.githubusercontent.com/40228918/47517084-6155d600-d887-11e8-9a7f-f15d3bc11758.jpg)
![44811200_2160619457336155_7979437924682825728_n](https://user-images.githubusercontent.com/40228918/47517086-61ee6c80-d887-11e8-8fa3-d89c956311e8.jpg)

**Comment by uskka** [comment]
Looks good. Tested on katalyst01.
![screenshot_20181026-121521_firefox](https://user-images.githubusercontent.com/40228918/47560614-0b317300-d919-11e8-9dbe-5d918ffe5427.jpg)

**Comment by omehes** [comment]
I am re-opening this issue as I verified it on qa.cnx.org and staging.cnx.org. Still not fixed (or merged). Waiting for the fix.
@edwoodward @brittweinstein @uskka

**Comment by PiotrKozlowski** [comment]
@omehes It' working on http://katalyst01.cnx.org/
I can't see mine code on qa.cnx.org and staging.cnx.org which mean deploy wasn't succesfull or something else happend.

**Comment by omehes** [comment]
@PiotrKozlowski OK. Let's leave it open until I can verify it on qa or staging. I will talk to the team here in Houston about how the closing of bugs should happen now that they have a dedicated tester here (me) :)

**Comment by omehes** [comment]
@PiotrKozlowski Nice meeting you :) Started 2 weeks ago :) I think that should be the right procedure. I guess, if you do test a bug, add your results into it and then assign it to me, so I can do my testing. But I will talk to Helene about this. I will let you know or she will.

**Comment by PiotrKozlowski** [comment]
@omehes Changes are now avaible on `staging.cnx.org`

**Comment by openstaxalina** [comment]
We may want to track this with the milestone "CNX Q4" since Otto is responsible for testing.  But Piotr is on the Katalyst team, so it's a bit confusing what milestone it should be in.  

I'm going to leave everything alone for now.  I'll make a note to follow up on the status of this next week if not earlier.

**Comment by PiotrKozlowski** [comment]
Merged into master, ready for tests.

**Comment by omehes** [comment]
I verified this issue on qa and staging.cnx.org. It seems to be fixed on both in FF and Chrome. Checked on real Android phone LG G3 and simulated devices.

**Comment by openstaxalina** [comment]
If this is on staging, it seems that it got tagged with the 11-05 (really 11-07) release.  I'm going to adjust the tags on this issue.  cc @brittweinstein

**Comment by omehes** [comment]
@openstaxalina it looks fixed on staging and qa.

**Comment by omehes** [comment]
Reverified on staging. Fixed.
