### ISSUE TITLE
Accounting - Padding increase above images

### ISSUE THREAD

**Issue by brittweinstein** [Connexions/webview#2001]
@mwest-WWprod commented on [Mon Oct 15 2018](https://github.com/Connexions/cnx-recipes/issues/678)

content03
GLOBAL

Padding above **images** is too small (sufficient above figures).  Please increase slightly.

![imagepadding_webview](https://user-images.githubusercontent.com/19212926/46980975-5c816d00-d0a4-11e8-864e-2f77b23c7f82.png)

---

@openstaxalina commented on [Tue Oct 16 2018](https://github.com/Connexions/cnx-recipes/issues/678#issuecomment-430299750)

Need @lwtchu to review/specify a value for padding increase.

**Comment by brittany-johnson** [comment]
<img width="722" alt="screen shot 2018-11-15 at 2 37 22 pm" src="https://user-images.githubusercontent.com/24909007/48580151-03476c00-e8e4-11e8-8fe1-8b3ce55e386d.png">
1em of padding has been added to images that are not in figure tags

**Comment by brittany-johnson** [comment]
@Stackblocks ready for testing!
