### ISSUE TITLE
Examples in Appendix

### ISSUE THREAD

**Issue by Adrianltd** [Connexions/webview#2003]
@wilkus27 commented on [Mon Oct 22 2018](https://github.com/Connexions/cnx-recipes/issues/690)

https://katalyst01.cnx.org/contents/havxkyvS@12.1:njDsQlIO@8/B-Essential-Mathematics

There is some problem with headers inside examples. They are displayed below the content of the example.

webview

![example](https://user-images.githubusercontent.com/40228854/47301312-e38f9180-d61e-11e8-8c53-ba224630ffee.JPG)

PDF

![example_pdf](https://user-images.githubusercontent.com/40228854/47301328-ed18f980-d61e-11e8-94d4-9fc48de590c1.JPG)

**Comment by Adrianltd** [comment]
Should be fixed with https://github.com/Connexions/cnx-recipes/pull/671/commits/51fca73d415e7e05c847b92219d42da706d12076

**Comment by wilkus27** [comment]
Verified on katalyst01:

![headers](https://user-images.githubusercontent.com/40228854/48197922-80f50000-e357-11e8-853d-a029749ca318.JPG)
