### ISSUE TITLE
mobile devices: elements are not centered and overlaps

### ISSUE THREAD

**Issue by omehes** [Connexions/webview#2004]
Steps:
1. run staging.cnx.org on smaller device (LG G3, Samsung S5 phones, iPhone X, etc)
2. click on hamburger icon, then click Search link
3. OpenXtax CNX Library search page opens - check the images and links
Expected: Page elements (images and link text) should be centered and not overlap
Actual: Images are shifted in both orients to the right (not centered), they overlap and some links overlap too (see screen shots)

Screen shots:

![Screen Shot 2018-10-24 at 10.46.35 AM.png](https://images.zenhubusercontent.com/5bc8d1f2fe40ab78d94e65fb/b0502686-6033-403e-b4c0-f40081ee0b7d)

![Screen Shot 2018-10-24 at 10.45.46 AM.png](https://images.zenhubusercontent.com/5bc8d1f2fe40ab78d94e65fb/3a8842bb-2ac3-49b8-a19c-fb0c308b9fcb)

![Screenshot_2018-10-24-09-03-25.png](https://images.zenhubusercontent.com/5bc8d1f2fe40ab78d94e65fb/8147a45f-035b-493a-8a9a-487674e97993)

**Comment by PiotrKozlowski** [comment]
Merged into master. Ready for testing.

**Comment by openstaxalina** [comment]
Similar question as https://github.com/Connexions/webview/issues/2000 as to where this should be tracked.  But I will leave it in the Katalyst milestone until we can discuss!

**Comment by omehes** [comment]
Verified on qa.cnx.org on Safari, FF and Chrome on LG G3 and simulated mobile devices. Fixed

{"date": "2018-11-09 09:47:35 CST",
 "webview": "600e7e1b5e0f475f4446e55dfe089a765d45c211 (v0.40.0-54-g600e7e1)",
 "cnx-archive": "f8606f11828558c5f35eea288f26b67fdb3ddea1",
 "cnx-publishing": "f8f75cf4d7be6e689b4e381094a9bb3b017eef36",
 "oer.exports": "upbeat.undine v0.65.0",
 "press": "7.0.1",
 "cnx-deploy": "v2.30.2-28-g5653595"
}

**Comment by omehes** [comment]
Verified on staging.cnx.org on Safari, FF and Chrome on LG G3 and Acer 7" tablet and simulated mobile devices. Fixed

{"date": "2018-11-15 14:23:15 CST",
 "webview": "5512a7c1a8bcee7f5940fdbb5e75be44cb7e1583 (v0.41.1)",
 "cnx-archive": "4.6.0",
 "cnx-publishing": "0.14.1",
 "oer.exports": "vagrant.valkyrie v0.66.0",
 "press": "7.1.0",
 "cnx-deploy": "v2.31.1"
}
