### ISSUE TITLE
mobile devices: primary text with too large font size overlaps with the image 

### ISSUE THREAD

**Issue by omehes** [Connexions/webview#2006]
Steps:

1. run staging.cnx.org on smaller device (LG G3, Samsung S5 phones, iPhone X, etc)
2. check the main page (the image and the title text)
Expected: Image and primary title text should be organised similar way as on desktops (text to the left of the main image subject)
Actual: Primary title text overlaps with the image and has incorrect height (see screen shots)

Screen shot on iPhone X:
![Screen Shot 2018-10-24 at 1.16.01 PM.png](https://images.zenhubusercontent.com/5bc8d1f2fe40ab78d94e65fb/5601b446-5b24-4945-8285-446cbea59706)

Screen shot on Desktop (correct):
![Screen Shot 2018-10-24 at 2.28.43 PM.png](https://images.zenhubusercontent.com/5bc8d1f2fe40ab78d94e65fb/7622be9c-8430-4eda-becb-eb1a71e14476)

**Comment by edwoodward** [comment]
@omehes I think the secondary line of text is hidden on purpose on mobile. The height of the primary text on the image is definitely an issue.

**Comment by PiotrKozlowski** [comment]
It's very hard to do something with this text because of background image, but I've added white overlay above it and some white shadow around text to make it more readable, I've also aligned text to the left but I didn't change font-size, because smaller size is even harder to read at this background.

Let me know if this is okay.

![homeresp](https://user-images.githubusercontent.com/31478212/47649969-1e457c80-db7f-11e8-9f27-4a717e29653c.png)

**Comment by omehes** [comment]
@PiotrKozlowski it is better now but that empty space above the text... It feels like everything is shifted to the bottom. From what you are saying, it is not easy to shift the text upwards and use that empty space for the text?

**Comment by PiotrKozlowski** [comment]
@omehes I've moved this text to the bottom so it not overlap with her face, but I can actually move it to the top. Is this better:?

![homeresp](https://user-images.githubusercontent.com/31478212/47659286-eba67e80-db94-11e8-82b3-5ec878ea7370.png)

**Comment by omehes** [comment]
@PiotrKozlowski definitely better.  I will need to test it on various device screen sizes. I guess, I could push the fix to qa and test it. Not sure how all this works yet, I am still learning the processes :)

**Comment by PiotrKozlowski** [comment]
@omehes I've merged changes to `master` so you should be able to deploy and check :)

**Comment by openstaxalina** [comment]
@PiotrKozlowski is there any chance of moving the text so that "Space" falls on the beige background instead of the blue backpack?  cc @omehes

**Comment by PiotrKozlowski** [comment]
1 or 2? @openstaxalina @omehes 

**1:**
![1](https://user-images.githubusercontent.com/31478212/47835673-752c9b00-dda5-11e8-94bb-33c9fa7c8aa0.JPG)
**2:**
![2](https://user-images.githubusercontent.com/31478212/47835674-75c53180-dda5-11e8-92f4-b2d143c31137.JPG)

**Comment by omehes** [comment]
@PiotrKozlowski the first pls (1). looks good

**Comment by openstaxalina** [comment]
I agree!  Let's go with 1 @PiotrKozlowski. cc @omehes

**Comment by PiotrKozlowski** [comment]
Merged into master

**Comment by omehes** [comment]
@PiotrKozlowski @openstaxalina I don't see this fix in staging or qa. It needs to be deployed to qa? Or staging?

**Comment by openstaxalina** [comment]
@omehes This one is in the 11/20 release, so it will not be on staging yet (right now staging has the 11/7 release on it).  I think that you do need to deploy to QA in order to see this.  I will make a note to park this in scrum.

**Comment by PiotrKozlowski** [comment]
It's working for me at `qa.cnx.org`. If you see something different it may be caused bye either cache or different resolution. Or maybe server was already deployed
![qa](https://user-images.githubusercontent.com/31478212/48122726-86c7e400-e278-11e8-9a2c-fca67d76dcab.png)

**Comment by omehes** [comment]
I checked this on real Android phones (LG G3 and ZTE), and emulated devices. I cleared cache on Chrome. The text is shifted too high up. See attached screenshot.
On Firefox it looks good.
![screenshot_2018-11-07-08-23-43](https://user-images.githubusercontent.com/44207656/48137892-ab1bc480-e268-11e8-8008-404f933ad3ef.png)

**Comment by PiotrKozlowski** [comment]
@omehes I've pushed new change. There is difference between Firefox and Google Chrome in caluclating height and position of relative elements. Probably we should use `reset.css` and `normalize.css` but this will require special forces to check if nothing is broken.

**Comment by omehes** [comment]
verified on staging.cnx.org. Looks good on FF, Chrome and Safari on various mobile devices (simulated and real LG G3, Acer Tablet)

{"date": "2018-11-15 14:23:15 CST",
 "webview": "5512a7c1a8bcee7f5940fdbb5e75be44cb7e1583 (v0.41.1)",
 "cnx-archive": "4.6.0",
 "cnx-publishing": "0.14.1",
 "oer.exports": "vagrant.valkyrie v0.66.0",
 "press": "7.1.0",
 "cnx-deploy": "v2.31.1"
}
