### ISSUE TITLE
Alignment of table header

### ISSUE THREAD

**Issue by wilkus27** [Connexions/webview#2011]
The header of table should be centered
katalyst01 (https://katalyst01.cnx.org/contents/CImQfPDv@3.13:DgkT5Ky_@3/1-4-Multiply-and-Divide-Integers)

![left](https://user-images.githubusercontent.com/40228854/47564646-fb6c5b80-d925-11e8-9a80-fa1fbc9cc11d.JPG)

**Comment by PiotrKozlowski** [comment]
Merged into master. Ready for testing :)

**Comment by wilkus27** [comment]
Verified on katalyst01 

![head](https://user-images.githubusercontent.com/40228854/47728584-ec0b4c00-dc5e-11e8-8a13-68860d1da46c.JPG)
