### ISSUE TITLE
First sentence in Show Solution

### ISSUE THREAD

**Issue by wilkus27** [Connexions/webview#2012]
In most of **Examples**, in **Show Solution** the first sentence is in paragraph, while rest of sentences are not.

![below_code](https://user-images.githubusercontent.com/40228854/47570114-9c164780-d935-11e8-9532-259298c7bfc3.JPG)

It causes inconsistent alignment
katalyst01 (https://katalyst01.cnx.org/contents/CImQfPDv@3.13:zMLdd__D@7/1-1-Introduction-to-Whole-Numbers)

![below_sol2](https://user-images.githubusercontent.com/40228854/47570197-c2d47e00-d935-11e8-8445-fe5751edab51.JPG)

**Comment by PatBoj** [comment]
Definitely content issue.

**Comment by lwtchu** [comment]
Something is wrong with the transforms here.  The CNXML is below. Everything is in a para tag and each item is separated by a newline tag. I can separate it out into separate paragraphs.

@wilkus27 Let me know if this happens anywhere else so I can fix it. I'll move it over to the content managers board and treat this as a low priority fix.

```<para>Identify the words that indicate periods.<newline/>
Except for the first period, all other periods must have three places. Draw three blanks to indicate the number of places needed in each period. Separate the periods by commas.<newline/>
Then write the digits in each period.<newline/>
<media id="fs-id1170655154739" alt="An image has two lines of text. The upper lines read “nine billion”, followed by a comma, and “two hundred forty six million”, also followed by a comma. The words “billion” and “million” are underlined and each phrase has a curly bracket underneath. The lower lines read “seventy three thousand”, followed by a comma, and “one hundred eighty nine”. The word “thousand” is underlined and each phrase has a curly bracket underneath.">
<image mime-type="image/jpeg" src="CNX_ElemAlg_Figure_01_01_022_img.jpg"/>
</media><newline/>
The number is 9,246,073,189.</para>```

**Comment by lwtchu** [comment]
Issue moved to [Connexions/content-managers #453](https://github.com/Connexions/content-managers/issues/453) via [**ZenHub**](https://www.zenhub.com/)
