### ISSUE TITLE
Centered equations in table

### ISSUE THREAD

**Issue by wilkus27** [Connexions/webview#2014]
Equations in table should be aligned to the left as headers (https://katalyst01.cnx.org/contents/CImQfPDv@3.13:faHRo7tY@5/1-2-Use-the-Language-of-Algebra)

![eq_align](https://user-images.githubusercontent.com/40228854/47573365-6c6b3d80-d93d-11e8-8545-9042225d195a.JPG)

**Comment by lwtchu** [comment]
We can treat this as a low priority known issue. I'll move this to the content-manager board and close this issue out.

@wilkus27 does this happen anywhere else?

**Comment by lwtchu** [comment]
Issue moved to [Connexions/content-managers #452](https://github.com/Connexions/content-managers/issues/452) via [**ZenHub**](https://www.zenhub.com/)
