### ISSUE TITLE
Books button does not collapse the side nav area on small screen sizes (obstructs the page view)

### ISSUE THREAD

**Issue by omehes** [Connexions/webview#2021]
![Screen Shot 2018-10-29 at 3.48.13 PM.png](https://images.zenhubusercontent.com/5bc8d1f2fe40ab78d94e65fb/c963b2ee-a1c7-4abd-a329-271ac6f3e63f)Steps:
1. run staging.cnx.org on mobile device or screens with sizes <640 pixels
2. open a single content page (not a book), for example: https://staging.cnx.org/contents/QILbGRy4@3/Hearing-Harmony-What-is-Harmony
3. button that opens and closes the "ToC" is labelled "Books" and the side nav area should be open by default (This page is in this book...)
4. On Desktop, resize the browser to small sizes, on mobile devices check the displayed info

Actual: All you see is the "This page is in this book..." side nav area with list of book titles but no page content (text is obscured by the side nav) and button does not collapse the bar
Expected: On mobile devices or small display sizes the side nav area ("This page is in this book...") should be collapsible by tapping on the Books button

Checked on mobile Android LG G3

This issue was found here: https://jenkins-dev.cnx.org:8080/blue/organizations/jenkins/connexions-continuous-delivery%2Fwebview/detail/master/11/tests/

**Comment by openstaxalina** [comment]
This is actually intentional; more information here: https://github.com/Connexions/webview/issues/1626.

I am going to close this issue.

**Comment by omehes** [comment]
Reopening the issue as per discussions on slack.
@openstaxalina

**Comment by openstaxalina** [comment]
@PiotrKozlowski, would you be able to take a look at this when you have the chance?  cc @paulinaszczucinska, @helenemccarron 

Note that this panel behaves differently than the Table of Contents panel, that you fixed with #1626.  Also, this panel only occurs when the user is visiting a *page* outside of a book.

**Comment by PiotrKozlowski** [comment]
Merged into master. Ready for deploy and tests.

**Comment by omehes** [comment]
Verified on qa.cnx.org on FF, Chrome and Safari on various mobiles. Fixed. Books button is collapsible.

@PiotrKozlowski 
Just a note, that when a page is not in any book and you get the message "This page is not in any books", all that empty screen is scrollable. Should we switch off scrolling for that case? It is not a big deal, only unnecessary.

**Comment by PiotrKozlowski** [comment]
@omehes I can do this, however I would like to have this in separate issue if you can create one.

**Comment by omehes** [comment]
@PiotrKozlowski 
This issue is fixed. I will create a separate bug as per notes above.

**Comment by omehes** [comment]
fixed on staging. verified on simulated devices.

{"date": "2018-11-15 14:23:15 CST",
 "webview": "5512a7c1a8bcee7f5940fdbb5e75be44cb7e1583 (v0.41.1)",
 "cnx-archive": "4.6.0",
 "cnx-publishing": "0.14.1",
 "oer.exports": "vagrant.valkyrie v0.66.0",
 "press": "7.1.0",
 "cnx-deploy": "v2.31.1"
}
