### ISSUE TITLE
Accounting - Addition of hanging indent in webview footnotes

### ISSUE THREAD

**Issue by brittany-johnson** [Connexions/webview#2027]
@mwest-WWprod commented on [Mon Oct 15 2018](https://github.com/Connexions/cnx-recipes/issues/680)

content03
GLOBAL

Footnote content in webview can be confusing without hanging indents. Please add if possible.

![footnoteindent_webview](https://user-images.githubusercontent.com/19212926/46982686-44611c00-d0ab-11e8-9325-3e390fb7af88.png)

---

@openstaxalina commented on [Tue Oct 16 2018](https://github.com/Connexions/cnx-recipes/issues/680#issuecomment-430301948)

Agree.  
Description of hanging indents: https://guides.rasmussen.edu/c.php?g=225376&p=5846714

cc @lwtchu

**Comment by brittany-johnson** [comment]
Is this an okay amount of indention? Or should it be decreased or increased? @openstaxalina @lwtchu 
![screen shot 2018-11-01 at 11 46 41 am](https://user-images.githubusercontent.com/24909007/47866094-de270980-ddcb-11e8-8f48-acb4d1806c1a.png)

**Comment by openstaxalina** [comment]
This looks great to me!  @brittany-johnson @lwtchu

**Comment by brittany-johnson** [comment]
@Stackblocks Ready for testing!

**Comment by Stackblocks** [comment]
Displaying as specified with updated version of content / code.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/1299a835-6225-4a49-a8e4-c21a15df4c47)
