### ISSUE TITLE
mobile devices: search results screen gets overlapping text

### ISSUE THREAD

**Issue by omehes** [Connexions/webview#2028]
Steps:
1. launch staging.cnx.org on a tablet or iPad or iPhone X
2. tap on Search and type in something to search for (e.g. the circle of fifth)
3. check out the search results screen in both orients
Expected: text and graphics do not overlap
Actual: the numbers in the left grey sidebar shifts out of the sidebar and overlap with text (see attached screen shots)

This seems to happen on various tablets, iPad and even larger phones like iPhone X, kindle but not on majority of phones.

![Screen Shot 2018-10-31 at 9.09.27 AM.png](https://images.zenhubusercontent.com/5bc8d1f2fe40ab78d94e65fb/bbc2226c-b413-430a-b6f6-cf75b90eda44)

![Screen Shot 2018-10-31 at 9.07.57 AM.png](https://images.zenhubusercontent.com/5bc8d1f2fe40ab78d94e65fb/981e2410-e39a-4f3e-be93-5730a03565b8)

**Comment by openstaxalina** [comment]
@PiotrKozlowski, I placed this in the current sprint in case you have time. If not, no worries, it can slide to the next.  cc @paulinaszczucinska @helenemccarron

**Comment by PiotrKozlowski** [comment]
Merged into master, you can deploy and test :)

**Comment by omehes** [comment]
@PiotrKozlowski 
Hi. I tested this on chrome and FF on staging.cnx.org. I see some long line of numbers crossing the whole page when I click on the More button. See the attached screen shot. Is this a new feature or a secret message from E.T.? :) :) 

![searchRES2.png](https://images.zenhubusercontent.com/5bc8d1f2fe40ab78d94e65fb/2add0571-1dd3-47ca-9ae6-5ba9700db9a7)

![searchRES.png](https://images.zenhubusercontent.com/5bc8d1f2fe40ab78d94e65fb/474c006d-5ba6-41ba-b3b4-66c78c98ce55)

**Comment by PiotrKozlowski** [comment]
It looks like I didn't add one line to the commit. It should be right now on the master.

**Comment by omehes** [comment]
Redeployed to qa and reverified on qa.cnx.org on various devices, Chrome, FF, Safari. 
Fixed

**Comment by pumazi** [comment]
You can also verify it is correct on master by looking at http://staged.cnx.org.

**Comment by omehes** [comment]
Reverified on staging.cnx.org on various simulated devices (and Acer tablet), Chrome, FF, Safari.
Fixed

{"date": "2018-11-15 14:23:15 CST",
 "webview": "5512a7c1a8bcee7f5940fdbb5e75be44cb7e1583 (v0.41.1)",
 "cnx-archive": "4.6.0",
 "cnx-publishing": "0.14.1",
 "oer.exports": "vagrant.valkyrie v0.66.0",
 "press": "7.1.0",
 "cnx-deploy": "v2.31.1"
}
