### ISSUE TITLE
WAITING WW REVIEW: Accounting - Leading in webview lists

### ISSUE THREAD

**Issue by brittany-johnson** [Connexions/webview#2031]
@mwest-WWprod commented on [Mon Oct 15 2018](https://github.com/Connexions/cnx-recipes/issues/679)

content03
GLOBAL

Lists in webview have inconsistent leading between items.

![listspacing_webview](https://user-images.githubusercontent.com/19212926/46982618-f77d4580-d0aa-11e8-9fb6-116bdf5a5cf6.png)

---

@openstaxalina commented on [Tue Oct 16 2018](https://github.com/Connexions/cnx-recipes/issues/679#issuecomment-430301477)

@oscryan would you mind reviewing the content in this case?  I have never seen this kind of styling issue with a list.

If content is correct, please post a screenshot of the markup with a link, and remove your assignment.

cc @lwtchu 

---

@oscryan commented on [Tue Oct 16 2018](https://github.com/Connexions/cnx-recipes/issues/679#issuecomment-430309259)

The content is treated differently in each list item. The first item has the text inside only the item tag; the second item has two paragraph tags nested in the list tag. The third has no nesting, like the first. This seems to have caused the item number to center vertically in the third case, but I don't know why it's different from the first.

---

@oscryan commented on [Tue Oct 16 2018](https://github.com/Connexions/cnx-recipes/issues/679#issuecomment-430309807)

https://legacy-content03.cnx.org/content/m10005/latest
<img width="1115" alt="screen shot 2018-10-16 at 11 41 50 am" src="https://user-images.githubusercontent.com/1895432/47032674-8edcaa00-d138-11e8-8f76-093d2d14efa0.png">

<blockquote><img src="https://legacy-content03.cnx.org/book_icon_cnx.png" width="48" align="right"><div>Portal</div><div><strong><a href="https://legacy-content03.cnx.org/content/m10005/latest/">Compute a Predetermined Overhead Rate and Apply Overhead to Production</a></strong></div><div>Job order cost systems maintain the actual direct materials and direct labor for each individual job. Since production consists of overhead—indirect materials, indirect labor, and other overhead—we need a methodology for applying that overhead. Unfortunately, the nature of indirect material, indirect labor, and other overhead expenses makes it impossible to determine the exact amount of overhead for each specific job. For example, how do you know the cost of electricity and heat for manufacturing one job? And, if you did, is it fair to say products manufactured in January are more expensive than the same product manufactured in March because of heat expense?</div></blockquote>

---

@openstaxalina commented on [Tue Oct 16 2018](https://github.com/Connexions/cnx-recipes/issues/679#issuecomment-430311118)

It seems that paras were used only for the list item that has more than one paragraph.

@oscryan is this semantically correct CNXML?  Unless you advise CNXML changes, I'll ask developers to review this.

---

@oscryan commented on [Tue Oct 16 2018](https://github.com/Connexions/cnx-recipes/issues/679#issuecomment-430311492)

It's not consistent, but it's not incorrect. It might be best if we keep the styling on list items from changing due only to what's contained in them.

---

@openstaxalina commented on [Tue Oct 16 2018](https://github.com/Connexions/cnx-recipes/issues/679#issuecomment-430312396)

Thank you!  I will ask the devs to look into this next sprint.

**Comment by brittany-johnson** [comment]
![screen shot 2018-11-05 at 2 25 43 pm](https://user-images.githubusercontent.com/24909007/48024656-dbe3e880-e106-11e8-9eb9-4a2c85ac1b88.png)
The issue ended up being with a margin being placed on `<p>` inside lists. Which is why the spacing between 1. and 2. appears to be correct, but between 2. and 3. is not correct.

**Comment by PatBoj** [comment]
@brittany-johnson unfortunately your fix causes some problems in other books. To be specific it's a _Elementary Algebra_ book.

## **Before:**
![image](https://user-images.githubusercontent.com/20907906/48192597-8434bf80-e348-11e8-9164-a4eef9849c00.png)

## **After:**
![image](https://user-images.githubusercontent.com/20907906/48192604-872fb000-e348-11e8-8246-ba2ddd424dd4.png)

**Comment by Stackblocks** [comment]
Displays correctly in the test content on devb, may warrant further investigation into what Patryk pointed out above. 

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/122fa242-c37c-4365-8711-76a5834d897c)

**Comment by openstaxalina** [comment]
After talking with @brittany-johnson about the options and impacts to fixing this technically, we have decided to **unmerge** her PR.  Her PR will be reversed in the 12/4 release.

@oscryan would you be able to test adding `<newline>` instead of `<para>`?  If that results in acceptable spacing between the list items, we should update WiseWire about how to handle this in the markup.

**Comment by oscryan** [comment]
ok

**Comment by oscryan** [comment]
List items with para have para ends now rendered `<newline/><newline/>`
https://legacy-content03.cnx.org/content/m10005/latest/

**Comment by openstaxalina** [comment]
@oscryan, is there a newline after the last paragraph in the second list item?  

Here's the display; the issue between items 2 and 3 has not been resolved:
![screen shot 2018-11-16 at 10 21 32 am](https://user-images.githubusercontent.com/7863733/48633698-748d2a80-e989-11e8-9224-c151b797336f.png)

**Comment by oscryan** [comment]
newlines at the end of item 1 and after every paragraph in item 2:
<img width="927" alt="screen shot 2018-11-16 at 10 35 27 am" src="https://user-images.githubusercontent.com/1895432/48634556-6dffb280-e98b-11e8-976d-878b56703f27.png">

**Comment by brittweinstein** [comment]
WW confirmed receipt on Nov. 16.
