### ISSUE TITLE
Two types of headers in Review Exercises

### ISSUE THREAD

**Issue by wilkus27** [Connexions/webview#2033]
In PDF headers in **Review Exercises** section are written in two ways:

1) #_Number_ + Title of the Section

![rev ex_subtitle](https://user-images.githubusercontent.com/40228854/47928740-59211a80-dec7-11e8-9026-221c3cb637a4.JPG)

2) #_Number_ + Section #_number_ + Title of the Section
![rev ex2](https://user-images.githubusercontent.com/40228854/47928878-c2a12900-dec7-11e8-85eb-c6655b698d9c.JPG)

The first version is the right one.

Links to the webview (katalyst01)
1) https://katalyst01.cnx.org/contents/CImQfPDv@3.14:F2eI9_FH@3.14/Review-Exercises
2) https://katalyst01.cnx.org/contents/CImQfPDv@3.14:squKFFOM@3.14/Review-Exercises

**Comment by lwtchu** [comment]
@wilkus27 This is a pure content issue. I'll say it's low priority and I'll move it to the content manager repo for us to fix

**Comment by lwtchu** [comment]
Issue moved to [Connexions/content-managers #463](https://github.com/Connexions/content-managers/issues/463) via [**ZenHub**](https://www.zenhub.com/)
