### ISSUE TITLE
Different link in PDF and on webview

### ISSUE THREAD

**Issue by wilkus27** [Connexions/webview#2035]
On katalyst01 (https://katalyst01.cnx.org/contents/CImQfPDv@3.14:5ZqBJk4A@3/4-3-Graph-with-Intercepts) in **Example 4.21** in **Show Solution** there is a link which is named by **Example 4.21** but it leads to the top of the section **4.3**.

![link](https://user-images.githubusercontent.com/40228854/47998202-c8cd1a80-e0fe-11e8-9d9a-2bb3666bb700.JPG)

What is more, this link in PDF is named by **Table 4.28** but there is no table with this number in PDF. After click on this link we stay in the same place, which suggest that it should lead to the table below, but it is not numbered.

![link_pdf](https://user-images.githubusercontent.com/40228854/47998383-72141080-e0ff-11e8-85cc-a6f457a39027.JPG)

NOTICE: numbering of tables in PDF is wrong. There is another issue about that. On webview it should have number **4.24**.

**Comment by openstaxalina** [comment]
This likely needs content investigation first.

**Comment by lwtchu** [comment]
![screen shot 2018-11-07 at 4 08 28 pm](https://user-images.githubusercontent.com/11299125/48164190-66fbe480-e2a7-11e8-96c1-59ebbe765c08.png)

It links to the following table, however that table doesn't have unnumbered class. Should I rephrase the sentence to say "as shown in the following table."?

**Comment by openstaxalina** [comment]
@lwtchu that sounds like a good solution that will resolve the webview now and the PDF when it's regenerated.

**Comment by lwtchu** [comment]
@openstaxalina should we fix any of the issues regarding - there's no class on the table but it's still unnumbered. and natalia says the numbering is also off.

**Comment by openstaxalina** [comment]
The reason it says Example 4.21 is because this is hard-coded in the markup:
![screen shot 2018-11-08 at 11 49 25 am](https://user-images.githubusercontent.com/7863733/48230346-4e0b3600-e370-11e8-8a08-95621acba3da.png)

Therefore, this is a content fix that I'll open an issue for.

**Comment by openstaxalina** [comment]
*Decision:* Change to "in the following table."

**Comment by openstaxalina** [comment]
Issue moved to [Connexions/content-managers #465](https://github.com/Connexions/content-managers/issues/465) via [**ZenHub**](https://www.zenhub.com/)
