### ISSUE TITLE
Numbering by Step #

### ISSUE THREAD

**Issue by wilkus27** [Connexions/webview#2038]
In _Elementary Algebra_ in **How To** note and in section **Key Concepts** there are lists which should be numbered by _Step 1, Step 2 etc._

webview (e.g. https://katalyst01.cnx.org/contents/CImQfPDv@3.14:Tj87ETCR@4/3-1-Use-a-Problem-Solving-Strategy)

![step_how_to](https://user-images.githubusercontent.com/40228854/48010120-4738b500-e11d-11e8-8b36-dcdb39309c6e.JPG)

PDF:
![step_how_to_pdf](https://user-images.githubusercontent.com/40228854/48010170-5d467580-e11d-11e8-8792-a27b918dd1fe.JPG)

webview (e.g. https://katalyst01.cnx.org/contents/CImQfPDv@3.14:7BOr1QuT@3.14/Key-Concepts)

![step_key](https://user-images.githubusercontent.com/40228854/48010210-72230900-e11d-11e8-80f8-aad07db06021.JPG)

PDF:
![step_key_pdf](https://user-images.githubusercontent.com/40228854/48010235-7d763480-e11d-11e8-82d6-e678d41a6a7d.JPG)

**Comment by openstaxalina** [comment]
Hopefully these have the `stepwise` class on them; we should check in sprint planning.

**Comment by lwtchu** [comment]
@openstaxalina they do :)!
![screen shot 2018-11-07 at 3 57 22 pm](https://user-images.githubusercontent.com/11299125/48163637-da045b80-e2a5-11e8-9edf-c50638ec1e16.png)

**Comment by openstaxalina** [comment]
Thanks @lwtchu !
In that case, @PatBoj could you use that class to add the word "Step" before each number?  I think this is what we decided to do with all lists with that class.

cc @helenemccarron

**Comment by openstaxalina** [comment]
Issue moved to [Connexions/cnx-recipes #704](https://github.com/Connexions/cnx-recipes/issues/704) via [**ZenHub**](https://www.zenhub.com/)
