### ISSUE TITLE
Lists and figures out of the padding

### ISSUE THREAD

**Issue by wilkus27** [Connexions/webview#2040]
On katalyst01( e.g. https://katalyst01.cnx.org/contents/CImQfPDv@3.14:Z8sTwcjE@4/3-3-Solve-Mixture-Applications - Example 3.26) in Show Solution lists and figures are too far to the left:

![out](https://user-images.githubusercontent.com/40228854/48011567-54a36e80-e120-11e8-8e6d-36cf1727dfb9.JPG)

**Comment by lwtchu** [comment]
@wilkus27 is this global or just once instance?

**Comment by lwtchu** [comment]
@wilkus27 would it be too difficult to list all instances? if it is, we can treat this as a known issue. it's just messy mark up that needs to be cleaned up i think.

**Comment by wilkus27** [comment]
@lwtchu It's possible to do, but there will be a lot of instances and it is very likely that this issue also occurs in two other Algebra books (Prealgebra, Intermediate Algebra) so it could be a very long list of all cases. But  in the other hand maybe we can use Stefan's tool, so it will be easier to find this instances. @uskka we can find **Examples** by your tool. That's correct?

**Comment by openstaxalina** [comment]
I think this is not worth more time investigating right now, due to the time involved to locate and fix these instances.  I am going to move this to content-managers in the backlog.  Thank you very much @wilkus27 and @lwtchu for the investigation on this!

**Comment by openstaxalina** [comment]
Issue moved to [Connexions/content-managers #464](https://github.com/Connexions/content-managers/issues/464) via [**ZenHub**](https://www.zenhub.com/)
