### ISSUE TITLE
WAITING (https://github.com/Connexions/content-managers/issues/452) Centered equations in table

### ISSUE THREAD

**Issue by openstaxalina** [Connexions/webview#2051]
So for this table 1.4 (https://katalyst01.cnx.org/contents/CImQfPDv@3.14:faHRo7tY@6/1-2-Use-the-Language-of-Algebra) the word `Expression` is not being centered.

![Screen Shot 2018-11-08 at 9.56.08 AM.png](https://images.zenhubusercontent.com/5b57310fb26dd832dfe45b43/85a62e78-5b99-4b09-8424-5ef672d7dd20)

**Here is the CNXML:** 
```row valign="top">
<entry valign="top" align="center">Expression</entry>
<entry valign="top" align="left">In Words</entry>
</row>
</thead>
<tbody>
<row valign="top">
<entry valign="top" align="center"><m:math><m:mrow><m:msup><m:mn>7</m:mn><m:mn>2</m:mn></m:msup></m:mrow></m:math></entry>
<entry valign="top" align="left">7 to the second power or 7 squared</entry>
</row>
<row valign="top">
<entry valign="top" align="center"><m:math><m:mrow><m:msup><m:mn>5</m:mn><m:mn>3</m:mn></m:msup></m:mrow></m:math></entry>
<entry valign="top" align="left">5 to the third power or 5 cubed</entry>```

**Comment by openstaxalina** [comment]
**Looks like the CNXML isn't being transformed right...here is the html:**
![Screen Shot 2018-11-08 at 10.05.01 AM.png](https://images.zenhubusercontent.com/5b57310fb26dd832dfe45b43/0ba6d8f9-b444-4b59-a629-3a540d9c74e2)

**Comment by lwtchu** [comment]
While we're at it, should we make sure that any alignment to the left, right or center will work?

**Comment by PiotrKozlowski** [comment]
Please take a look on my response here: https://github.com/Connexions/content-managers/issues/452#issuecomment-437294319 and let me know if you can check if changing order of attributes will work.

**Comment by openstaxalina** [comment]
@PiotrKozlowski yes, we will test this in content.  cc @paulinaszczucinska

**Comment by lwtchu** [comment]
fixed in content.
