### ISSUE TITLE
Images in line with text

### ISSUE THREAD

**Issue by wilkus27** [Connexions/webview#2053]
On katalyst01 (https://katalyst01.cnx.org/contents/havxkyvS@12.1:lNfBQIBE@12.1/Answer-Key) there are images in line with text:

**Chapter 2 - 35.**

![fig_in_line](https://user-images.githubusercontent.com/40228854/48268973-bfadb780-e436-11e8-87fc-0b0e0363ab40.JPG)

**PDF:**

![fig_pdf](https://user-images.githubusercontent.com/40228854/48268986-c805f280-e436-11e8-87b3-b090907aa25c.JPG)

**Chapter 8 - 21.**

![wrap_fig_8 21](https://user-images.githubusercontent.com/40228854/48269180-42cf0d80-e437-11e8-9619-7a38069afbdd.JPG)

**PDF:**

![wrap_pdf](https://user-images.githubusercontent.com/40228854/48269199-4a8eb200-e437-11e8-939e-10cba2cdfcf9.JPG)

**Comment by openstaxalina** [comment]
@Adrianltd could you see if there is a technical reason/fix for this? cc @helenemccarron

**Comment by wilkus27** [comment]
Verified on katalyst01:

![2 35](https://user-images.githubusercontent.com/40228854/49516102-0b6a4a00-f899-11e8-8b98-ad5ebea19eb4.JPG)

![8 21](https://user-images.githubusercontent.com/40228854/49516106-102efe00-f899-11e8-9ff2-0bbb7ef460ee.JPG)
