### ISSUE TITLE
Lists in Answer Key

### ISSUE THREAD

**Issue by wilkus27** [Connexions/webview#2054]
On katalyst01 (https://katalyst01.cnx.org/contents/havxkyvS@12.1:lNfBQIBE@12.1/Answer-Key) all lists in Answer Key are hardcoded. Sometimes points are in line and sometimes they are separated by newline:

Chapter 1:

![list2](https://user-images.githubusercontent.com/40228854/48270331-1d8fce80-e43a-11e8-8702-848c2cb807f0.JPG)

![list](https://user-images.githubusercontent.com/40228854/48270344-22ed1900-e43a-11e8-8d17-e1d849f95fb7.JPG)

PDF:

![list_pdf](https://user-images.githubusercontent.com/40228854/48270353-297b9080-e43a-11e8-80cf-f29e97a1d43c.JPG)

**Comment by lwtchu** [comment]
Thanks - I'll move this to the CM repo.

**Comment by lwtchu** [comment]
Issue moved to [Connexions/content-managers #470](https://github.com/Connexions/content-managers/issues/470) via [**ZenHub**](https://www.zenhub.com/)
