### ISSUE TITLE
Search field shows mixed status

### ISSUE THREAD

**Issue by omehes** [Connexions/webview#2056]
Steps:

1. run (qa.)cnx.org on (mobile) device/desktop
2. open a book
3. enter something into search field and click on the search icon (magnifier) in the field to start the search
Actual: the search icon changes into x and search results are shown
4. now delete all the text in the search field (use the delete button on keyboard)
Actual: The search icon within the field remains x 
Expected: The icon should change back to the search icon (magnifier) to indicate that new search can be done

5. Now type in text again in the field
Actual: text appears in the field but the icon remains x. If you click on it, clears the search field and results and the search icon (magnifier) appears

![searchx](https://user-images.githubusercontent.com/44207656/48370977-4a352780-e680-11e8-91e3-33f839446f13.png)

**Comment by PiotrKozlowski** [comment]
@omehes 
Acctually after investigation I think this is expected behaviour. The `x` icon is for clearing results and on desktop you can search for something elese just by typing and hitting enter. However I agree that it's not the best UX. I think we should just remove `x` icon totally. Is that okay?
cc @openstaxalina

**Comment by openstaxalina** [comment]
@PiotrKozlowski I think that is a good solution.  Let's move forward with that.  cc @omehes

**Comment by PiotrKozlowski** [comment]
Merged into master. (x) icons is removed when text is deleted.

**Comment by omehes** [comment]
Verified on FF and Chrome on qa.cnx.org. Fixed

{"date": "2018-11-20 12:14:23 CST",
 "webview": "a05781ee00cde05e5ce04d017c361d7a3cde1722 (v0.41.1-33-ga05781e)",
 "cnx-archive": "582474ce6a01415179dcbbb982bcc469fd870b58",
 "cnx-publishing": "6d86c1f9f797119d0bb9302a33ca1cfebba86005",
 "oer.exports": "vagrant.valkyrie v0.66.0",
 "press": "7.1.0",
 "cnx-deploy": "v2.31.0-21-g5c78537"
}

**Comment by omehes** [comment]
reverified on staging.cnx.org
fixed

{"date": "2018-11-26 11:18:53 CST",
 "webview": "969e07959a31572cdb61fec6f4573b5644d55637 (v0.42.0)",
 "cnx-archive": "4.6.0",
 "cnx-publishing": "0.14.1",
 "oer.exports": "worried.werewolf v0.67.0",
 "press": "7.1.0",
 "cnx-deploy": "v2.32.0"
}
