### ISSUE TITLE
Distance between figure and item of the list

### ISSUE THREAD

**Issue by wilkus27** [Connexions/webview#2059]
On katalyst01 (https://katalyst01.cnx.org/contents/CImQfPDv@3.15:-NOYkX5J@3.15/Key-Concepts) there is too small padding between items of the list:

![distance](https://user-images.githubusercontent.com/40228854/48479778-990dc900-e808-11e8-9153-870f5f49fd0b.JPG)

**Comment by wilkus27** [comment]
Could be related with https://github.com/Connexions/webview/issues/2031

**Comment by openstaxalina** [comment]
@lwtchu when you are back -- is there any chance of converting this to tables **with titles** in a list?

**Comment by lwtchu** [comment]
@openstaxalina sorry just saw this now - i think it'll be hard to convert it to a table since it's important that the operators in the equation needs to line up right on the line for the table

**Comment by wilkus27** [comment]
@openstaxalina the problem was with distance between figure and the sentence from the next point. But on your screenshot everything display correctly now. @PiotrKozlowski can we check which change repaired this issue? 

@openstaxalina about <newline> there are a lot of additional blank spaces in all dev-math books, so I've added their labels to the issue: https://github.com/Connexions/content-managers/issues/288

**Comment by openstaxalina** [comment]
@wilkus27 it still seems like there is too much distance here:
![spacebeforetables](https://user-images.githubusercontent.com/7863733/49387106-a242d500-f6e6-11e8-832b-53425470cecc.png)

**Comment by wilkus27** [comment]
@openstaxalina the problem in this issue was with **too small** distance between those objects:

![distance](https://user-images.githubusercontent.com/40228854/49388659-bc030d00-f724-11e8-940f-0e13961dfe28.JPG)

The problem which you're describing I thought that could be solved by issue Connexions/content-managers#288. Is it not correct? Should I create seperate issue about it?

**Comment by openstaxalina** [comment]
@wilkus27 ah, thanks.  If you could just add this instance to #288 in content-managers as another example, that would help us look for the correct items when we make those changes.  Thanks again!
