### ISSUE TITLE
Figure with grey caption

### ISSUE THREAD

**Issue by wilkus27** [Connexions/webview#2063]
On katalyst01 (https://katalyst01.cnx.org/contents/CImQfPDv@3.15:DHh18HNo@5/7-6-Quadratic-Equations) in **Example 7.70** there is a figure with grey caption:

![caption](https://user-images.githubusercontent.com/40228854/48545729-e486ac80-e8c6-11e8-8aa4-8d477a5ebaa7.JPG)

In PDF there is no such caption:

![caption_pdf](https://user-images.githubusercontent.com/40228854/48545815-1566e180-e8c7-11e8-8c29-9c78a52f4923.JPG)

**Comment by openstaxalina** [comment]
<img width="1438" alt="screen shot 2018-11-19 at 12 43 50 pm" src="https://user-images.githubusercontent.com/7863733/48727778-cb4c6b80-ebf8-11e8-93fb-a62c2aec88f7.png">

It looks to be a caption on a figure within the table.   It looks like alt text to me.

@lwtchu what do you think of classifying this as a low-priority issue that content managers can fix before we release DevMath in Assignable Webview on production?

**Comment by openstaxalina** [comment]
@marcjeannott is already making this change as part of another project; he will update this issue when complete.

**Comment by marcjeannott** [comment]
I've completed this on production~ https://cnx.org/contents/CImQfPDv@3.29:DHh18HNo@15/Quadratic-Equations
