### ISSUE TITLE
Prevent indexing of certain pages in robots.txt

### ISSUE THREAD

**Issue by edwoodward** [Connexions/webview#2067]
Google sent an alert that an admin page had a display issue on mobile. Google should not be indexing any pages that are under cnx.org/a/. We need to prevent this by adding a disallow in robots.txt.  

This should also disallow the haproxy-status page as well

URL from Google Alert
>https://cnx.org/a/print-style/ccap-developmental-math
>https://cnx.org/haproxy-status

**Acceptance Criteria**

robots.txt file on server should contain...
>Disallow: /a/
>Disallow: /haproxy-status

**Comment by brittany-johnson** [comment]
Issue moved to [Connexions/cnx-deploy #925](https://github.com/Connexions/cnx-deploy/issues/925) via [**ZenHub**](https://www.zenhub.com/)
