### ISSUE TITLE
Links to the section exercises

### ISSUE THREAD

**Issue by wilkus27** [Connexions/webview#2074]
On katalyst01 (https://katalyst01.cnx.org/contents/CImQfPDv@3.15:jFwbH1ty@4/10-5-Graphing-Quadratic-Equations#fs-id1166502109318) there are links which lead to the exercises from end of section. On webview all of them are named by **Example 10.54**.

![links](https://user-images.githubusercontent.com/40228854/48701885-d64ece00-ebef-11e8-806e-f8b48719e36a.JPG)

This is how it looks in PDF:

![links_pdf](https://user-images.githubusercontent.com/40228854/48701994-131ac500-ebf0-11e8-8f90-41aca6b90ffb.JPG)

Both, on webview and in PDF, these links navigate to those exercises:

![ex_link_pdf](https://user-images.githubusercontent.com/40228854/48702079-3f364600-ebf0-11e8-8a42-4907ea978062.JPG)

**Comment by PiotrKozlowski** [comment]
I think this may be related to recipies, cc @PatBoj 

Elefind:
Search for `.autogenerated-content:hasText(Example 10.54)`:
`Found 4 instances in: 10.5 Graphing Quadratic Equations`
Same results for `a:hasText(Example 10.54)`:
`Found 4 instances in: 10.5 Graphing Quadratic Equations`

**Comment by PatBoj** [comment]
It's not content issue, so it could be a recipe.

**Comment by wilkus27** [comment]
Issue moved to [Connexions/cnx-recipes #751](https://github.com/Connexions/cnx-recipes/issues/751) via [**ZenHub**](https://www.zenhub.com/)
