### ISSUE TITLE
[Elementary Algebra] Math out of the padding

### ISSUE THREAD

**Issue by wilkus27** [Connexions/webview#2077]
Below is the list of instances of mathematical equations out of the padding, e.g.

![math_out](https://user-images.githubusercontent.com/40228854/48760434-3acc6480-eca6-11e8-9ef2-0d92c3c169b1.JPG)

 Place | Link (katalyst01)
:---------:|:----------------:
Example 3.24 | https://katalyst01.cnx.org/contents/CImQfPDv@3.15:RMC_iBKa@3/3-2-Solve-Percent-Applications
Example 3.55 - 3.58 | https://katalyst01.cnx.org/contents/CImQfPDv@3.15:THpXLlSz@4/3-6-Solve-Applications-with-Linear-Inequalities
Example 4.34 | https://katalyst01.cnx.org/contents/CImQfPDv@3.15:ukK0bN45@3/4-4-Understand-Slope-of-a-Line
Example 4.51, 4.52, 4.54 | https://katalyst01.cnx.org/contents/CImQfPDv@3.15:tegV4wXG@5/4-5-Use-the-Slope-Intercept-Form-of-an-Equation-of-a-Line
Example 4.64 | https://katalyst01.cnx.org/contents/CImQfPDv@3.15:_LEEVWcM@3/4-6-Find-the-Equation-of-a-Line
Example 5.10, 5.11 | https://katalyst01.cnx.org/contents/CImQfPDv@3.15:D5n2sgz3@4/5-1-Solve-Systems-of-Equations-by-Graphing
Example 5.39 | https://katalyst01.cnx.org/contents/CImQfPDv@3.15:ZArS1Z0P@6/5-4-Solve-Applications-with-Systems-of-Equations
above Example 6.1 | https://katalyst01.cnx.org/contents/CImQfPDv@3.15:SadrhUaw@3/6-1-Add-and-Subtract-Polynomials
Example 7.34 - 7.36 | https://katalyst01.cnx.org/contents/CImQfPDv@3.15:ntLHiuvZ@4/7-3-Factor-Quadratic-Trinomials-with-Leading-Coefficient-Other-than-1
Example 7.64, 7.66 | https://katalyst01.cnx.org/contents/CImQfPDv@3.15:UovuKZl2@4/7-5-General-Strategy-for-Factoring-Polynomials
Example 7.76, 7.78 - 7.80 | https://katalyst01.cnx.org/contents/CImQfPDv@3.15:DHh18HNo@5/7-6-Quadratic-Equations
Example 8.88 | https://katalyst01.cnx.org/contents/CImQfPDv@3.15:_L9Vlwth@5/8-9-Use-Direct-and-Inverse-Variation

**Comment by openstaxalina** [comment]
Issue moved to [Connexions/content-managers #488](https://github.com/Connexions/content-managers/issues/488) via [**ZenHub**](https://www.zenhub.com/)
