### ISSUE TITLE
Different size of mathematical objects

### ISSUE THREAD

**Issue by wilkus27** [Connexions/webview#2078]
On katalyst01 (https://katalyst01.cnx.org/contents/CImQfPDv@3.15:ukK0bN45@3/4-4-Understand-Slope-of-a-Line) some mathematical objects are bigger than another ones

![diff_math](https://user-images.githubusercontent.com/40228854/48775259-d1138100-eccc-11e8-8bb7-a300be95a4cf.JPG)

Second example

![math2](https://user-images.githubusercontent.com/40228854/48775362-1b94fd80-eccd-11e8-8a21-f2e17bafbcf2.JPG)

I've noticed only two instances. Probably it is problem with displaying this kind of notation.
Here is example, where it displays properly:

![notation](https://user-images.githubusercontent.com/40228854/48775732-3320b600-ecce-11e8-93aa-4beb2e863360.JPG)

**Comment by PiotrKozlowski** [comment]
It's set in the content: (`mathsize="140%"`)
`<mstyle displaystyle="true" mathsize="140%"><mrow><mn>1</mn><mo>,</mo><mn>2</mn></mrow>`

**Comment by openstaxalina** [comment]
@lwtchu do you know the rationale behind setting this value in the content?  We could use Batch to remove `mathsize` attributes unless it's serving a purpose in the PDF...

**Comment by openstaxalina** [comment]
Issue moved to [Connexions/content-managers #482](https://github.com/Connexions/content-managers/issues/482) via [**ZenHub**](https://www.zenhub.com/)

**Comment by lwtchu** [comment]
Confirmed it serves no purpose in the PDF. We will delete the tag on production, but since it isn't everywhere, I won't make the change on katalyst01

**Comment by openstaxalina** [comment]
@wilkus27 FYI ^
This will be a "known issue" on katalyst01.
