### ISSUE TITLE
Introduction header

### ISSUE THREAD

**Issue by wilkus27** [Connexions/webview#2080]
On katalyst01 (https://katalyst01.cnx.org/contents/CImQfPDv@3.15:4ruFtbL1@3/Introduction-to-Quadratic-Equations) main header of the module is different than in PDF:

webview
![intro](https://user-images.githubusercontent.com/40228854/48790155-08932500-ecef-11e8-81dd-4f71e9fb8b79.JPG)

PDF:
![intro_pdf](https://user-images.githubusercontent.com/40228854/48790171-10eb6000-ecef-11e8-9ca7-ed274d2fb436.JPG)

In all other chapters first module is called by **Introduction**.

**Comment by openstaxalina** [comment]
@lwtchu this seems like a content fix.  We could just fix it directly on production and close this if you agree.  cc @wilkus27

**Comment by openstaxalina** [comment]
Issue moved to [Connexions/content-managers #486](https://github.com/Connexions/content-managers/issues/486) via [**ZenHub**](https://www.zenhub.com/)
