### ISSUE TITLE
Mobile devices: Search list box gets detached from its field 

### ISSUE THREAD

**Issue by omehes** [Connexions/webview#2083]
Steps:
1. start qa.cnx.org in Chrome in a simulated device (Nexu 7, Samsung S7, iPhone X, 5S, ...)
2. click on Search/Advanced Search
3. start typing into Author, Title or Keywords fields. Type something you already searched for before, so it is remembered
Expected: Box with the list of previously searched words open right next to the appropriate field (below it)
Actual: Box with the list of previously searched words opens somewhere on the screen detached from its appropriate field (see attached screen shots)

I tested this on simulated mobile devices in Chrome. 
Note, I couldn't reproduce on real mobile phone LG G3.
Also, does not happen on Chrome, Safari or FF browsers. 

{"date": "2018-11-20 12:14:23 CST",
 "webview": "a05781ee00cde05e5ce04d017c361d7a3cde1722 (v0.41.1-33-ga05781e)",
 "cnx-archive": "582474ce6a01415179dcbbb982bcc469fd870b58",
 "cnx-publishing": "6d86c1f9f797119d0bb9302a33ca1cfebba86005",
 "oer.exports": "vagrant.valkyrie v0.66.0",
 "press": "7.1.0",
 "cnx-deploy": "v2.31.0-21-g5c78537"
}

![searchfield](https://user-images.githubusercontent.com/44207656/48798046-6876d500-ecc9-11e8-91b9-6cfbf55a40c1.png)

![searchfield3](https://user-images.githubusercontent.com/44207656/48798065-6e6cb600-ecc9-11e8-8dac-2f1ded479eb5.png)

**Comment by PiotrKozlowski** [comment]
I cannot reproduce this issue. It might be just a Google Chrome bug in the specific brower version. cc @omehes @openstaxalina

**Comment by omehes** [comment]
I see now what it causes. If the zoom in the simulated device window is less or more than 100%, it happens. Not a real issue. It does not happen on real devices. Closing
@PiotrKozlowski @openstaxalina
