### ISSUE TITLE
Update Text on Home Page

### ISSUE THREAD

**Issue by edwoodward** [Connexions/webview#2084]
On the Hero image of the CNX home page, the text reads...

>View and share free educational material in small modules that can be organized as courses, books, reports or other academic assignments.

This text was taken from Legacy and is not relevant now. It should be changed to something like

>View and share free educational material that can be organized as books or other academic assignments.

**Comment by openstaxalina** [comment]
Customer Support and I reviewed and approved the language as proposed above.  cc @brittany-johnson -- this can slide forward if needed.

**Comment by brittany-johnson** [comment]
@Stackblocks Ready for review

**Comment by Stackblocks** [comment]
Displaying as specified with updated version of content / code.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/91ec366c-06d6-4e46-836d-5d561884b318)
