### ISSUE TITLE
Update Text on Search Page

### ISSUE THREAD

**Issue by edwoodward** [Connexions/webview#2085]
The Search page has text above the category images that is outdated and should be updated. The Search page is at https://cnx.org/browse

Current Text
>The content in OpenStax CNX comes in two formats: modules, which are like small "knowledge chunks," and collections, which are groups of modules structured into books or course notes, or for other uses. Our open license allows for free use and reuse of all our content. 

Change to something like...

>The content in OpenStax CNX comes in two formats: Pages, which are like small "knowledge chunks," and Books, which are groups of Pages. Our open license allows for free use and reuse of all our content.

**Comment by openstaxalina** [comment]
Customer Support and I reviewed and approved the language as proposed above.  cc @brittany-johnson -- this can slide forward if needed.

**Comment by brittany-johnson** [comment]
<img width="996" alt="screen shot 2018-12-06 at 12 42 12 pm" src="https://user-images.githubusercontent.com/24909007/49604801-7d539980-f954-11e8-94aa-84cfe43eb2b0.png">

**Comment by Stackblocks** [comment]
Text on the page has been updated, but following the deploy of the current state of webview master, the navigation buttons on the top of the page have disappeared. @brittany-johnson can you take a look and see if you can ID a cause or verify that this is unrelated?

![image](https://user-images.githubusercontent.com/12678235/49660332-eba76300-fa0b-11e8-9dda-56edd7f296d0.png)

**Comment by openstaxalina** [comment]
@reedstrm's PR corrects the issue Alan noted above: https://github.com/Connexions/webview/pull/2120

@brittany-johnson will input a screenshot confirming this.

**Comment by openstaxalina** [comment]
Re-verified on staging with latest deploy (w/  **x-20190108-equations** hotfixes)
<img width="1288" alt="screen shot 2019-01-11 at 4 16 03 pm" src="https://user-images.githubusercontent.com/7863733/51062355-43f9f380-15bc-11e9-97ef-aed1250ffc93.png">
