### ISSUE TITLE
Blank spaces between images

### ISSUE THREAD

**Issue by wilkus27** [Connexions/webview#2088]
On katalyst01 (https://katalyst01.cnx.org/contents/AndhM9Sd@4.13:02l1UzkA@4/1-1-Use-the-Language-of-Algebra) there is a very long distance between images:

![images](https://user-images.githubusercontent.com/40228854/48908428-744dcd00-ee6a-11e8-9027-44e43f54a431.JPG)

PDF:

![images_pdf](https://user-images.githubusercontent.com/40228854/48908439-7b74db00-ee6a-11e8-8ea4-66a628431347.JPG)

**Comment by PiotrKozlowski** [comment]
Additional padding was added as a fix to https://github.com/Connexions/webview/issues/2001
What should we do in that case? @openstaxalina

**Comment by openstaxalina** [comment]
Thanks @wilkus27 and @PiotrKozlowski -- I'll discuss this with the Books team tomorrow.

**Comment by openstaxalina** [comment]
We decided to leave this as-is.
