### ISSUE TITLE
Step lists not written as ordered lists

### ISSUE THREAD

**Issue by wilkus27** [Connexions/webview#2090]
In each of Algebra books there are a few instances of lists with Step item which are not created as `<ol>`.

_**I. Lists as a mathematical objects**_

### Intermediate Algebra

1. https://katalyst01.cnx.org/contents/AndhM9Sd@4.13:2ESj5AFj@3/6-3-Factor-Special-Products
a. ![int_1](https://user-images.githubusercontent.com/40228854/49013998-ed0c9c00-f17e-11e8-9db5-347b8d0c0dcb.JPG)
b. ![int_2](https://user-images.githubusercontent.com/40228854/49014006-f39b1380-f17e-11e8-8f52-c8cb961fb6f5.JPG)
2. https://katalyst01.cnx.org/contents/AndhM9Sd@4.13:qlzOq4Ax@4.13/Key-Concepts
![int_3](https://user-images.githubusercontent.com/40228854/49014232-c1d67c80-f17f-11e8-852b-b9109dd90b19.JPG)

### Elementary Algebra

1. https://katalyst01.cnx.org/contents/CImQfPDv@3.15:p-75hORO@6/7-4-Factor-Special-Products
a. below Try It 7.84
b. below Try It 7.94
2. https://katalyst01.cnx.org/contents/CImQfPDv@3.15:vFUEVg-_@3.15/Key-Concepts
below header 7.4 Factor Special Products

_**II. Lists as a `<p>`**_

### Prealgebra

1. https://katalyst01.cnx.org/contents/yqV9q0HH@13.3:YUmknzp9@18/4-6-Add-and-Subtract-Mixed-Numbers 
a. ![pre_1](https://user-images.githubusercontent.com/40228854/49023411-73cd7300-f197-11e8-94ae-0185cd6b3e9a.JPG)
b. below Try It 4.180
2. https://katalyst01.cnx.org/contents/yqV9q0HH@13.3:f1xOZGvS@21/6-2-Solve-General-Applications-of-Percent 
above Example 6.23

_**III. Hardcoded Step**_

### Prealgebra

1. https://katalyst01.cnx.org/contents/yqV9q0HH@13.3:iOGYkRRI@13.3/Key-Concepts
a. ![pre_2](https://user-images.githubusercontent.com/40228854/49025379-cd37a100-f19b-11e8-8ba9-bae18a331921.JPG)
b. ![pre_3](https://user-images.githubusercontent.com/40228854/49025648-68c91180-f19c-11e8-8abc-a8cf55067004.JPG)

**Comment by openstaxalina** [comment]
@wilkus27 my understanding on this is that:
-the **content** matches the PDF: Step 1, Step 2...
-but the **display** is inconsistent

Is this accurate?  If so, I propose moving this to content-managers as a low-priority backlog item.  cc @lwtchu

**Comment by wilkus27** [comment]
@openstaxalina Yes, that's right. Patryk is working on https://github.com/Connexions/cnx-recipes/issues/704, where he want to add numbering by Step in recipes, but his changes will not impact on instances from above, because they are written in different way than most of the lists.

**Comment by openstaxalina** [comment]
Okay, thanks @wilkus27.  @lwtchu I'm moving this to the CM Backlog as low priority.  It seems like we should eventually standardize the way these are coded for a consistent display, but it's not crucial for Assignable Webview.

**Comment by openstaxalina** [comment]
Issue moved to [Connexions/content-managers #484](https://github.com/Connexions/content-managers/issues/484) via [**ZenHub**](https://www.zenhub.com/)
