### ISSUE TITLE
Disappearing headers in sections from EoC

### ISSUE THREAD

**Issue by wilkus27** [Connexions/webview#2092]
On katalyst01, when you go to the last section from some chapter, e.g. https://katalyst01.cnx.org/contents/AndhM9Sd@4.13:kWoglDtR@4/8-8-Use-the-Complex-Number-System 

![last_sec](https://user-images.githubusercontent.com/40228854/49075934-2e14b700-f238-11e8-9362-a14f5b84ef4e.JPG)

and click on **Next**, than in the first section from EoC, main header is invisible:

![next_sec](https://user-images.githubusercontent.com/40228854/49076097-88157c80-f238-11e8-941e-c3b0be56c0e7.JPG)

The same, when you again click on **Next**:

![next_sec2](https://user-images.githubusercontent.com/40228854/49076207-c27f1980-f238-11e8-9248-4b082bdd83a9.JPG)

But when you go back, the header displays:

![back_sec](https://user-images.githubusercontent.com/40228854/49076296-f0fcf480-f238-11e8-9994-54e9a52e7bb9.JPG)

**Comment by PiotrKozlowski** [comment]
Ready for testing

**Comment by wilkus27** [comment]
Verified on katalyst01. Working now properly.
