### ISSUE TITLE
No title Solution in Examples

### ISSUE THREAD

**Issue by wilkus27** [Connexions/webview#2094]
On katalyst01 (e.g. https://katalyst01.cnx.org/contents/AndhM9Sd@4.13:P6amxZo2@3/5-2-Properties-of-Exponents-and-Scientific-Notation) in Examples in Show Solution option should be title **Solution** 

![sol_web](https://user-images.githubusercontent.com/40228854/49088434-8dcf8a00-f259-11e8-980b-c7e805cbf5fa.JPG)

PDF:
![sol_pdf](https://user-images.githubusercontent.com/40228854/49088448-9627c500-f259-11e8-914b-08169ea99e51.JPG)

**Comment by wilkus27** [comment]
@openstaxalina This title displays in Prealgebra and Elementary Algebra. I talked with Patryk and he said that in dev-math books it's added by content.

**Comment by openstaxalina** [comment]
@wilkus27 thank you.  @lwtchu I'm adding this to the CM backlog.  Since the word "[Show/Hide] Solution" is just above the content, I don't think this is a crucial fix for Assignable Webview, but it will likely need to be standardized across the DevMath series for Baked PDF.

**Comment by openstaxalina** [comment]
Issue moved to [Connexions/content-managers #485](https://github.com/Connexions/content-managers/issues/485) via [**ZenHub**](https://www.zenhub.com/)
