### ISSUE TITLE
Lists and figures out of the padding

### ISSUE THREAD

**Issue by brittweinstein** [Connexions/webview#2097]
@openstaxalina commented on [Thu Nov 08 2018](https://github.com/Connexions/content-managers/issues/464)

@wilkus27 commented on [Mon Nov 05 2018](https://github.com/Connexions/webview/issues/2040)

On katalyst01( e.g. https://katalyst01.cnx.org/contents/CImQfPDv@3.14:Z8sTwcjE@4/3-3-Solve-Mixture-Applications - Example 3.26) in Show Solution lists and figures are too far to the left:

![out](https://user-images.githubusercontent.com/40228854/48011567-54a36e80-e120-11e8-8e6d-36cf1727dfb9.JPG)

---

@lwtchu commented on [Wed Nov 07 2018](https://github.com/Connexions/webview/issues/2040#issuecomment-436790196)

@wilkus27 is this global or just once instance? 

---

@wilkus27 commented on [Thu Nov 08 2018](https://github.com/Connexions/webview/issues/2040#issuecomment-436911000)

@lwtchu It is a global issue.

---

@lwtchu commented on [Thu Nov 08 2018](https://github.com/Connexions/webview/issues/2040#issuecomment-437066958)

@wilkus27 would it be too difficult to list all instances? if it is, we can treat this as a known issue. it's just messy mark up that needs to be cleaned up i think.

---

@wilkus27 commented on [Thu Nov 08 2018](https://github.com/Connexions/webview/issues/2040#issuecomment-437074913)

@lwtchu It's possible to do, but there will be a lot of instances and it is very likely that this issue also occurs in two other Algebra books (Prealgebra, Intermediate Algebra) so it could be a very long list of all cases. But  in the other hand maybe we can use Stefan's tool, so it will be easier to find this instances. @uskka we can find **Examples** by your tool. That's correct?

---

@openstaxalina commented on [Thu Nov 08 2018](https://github.com/Connexions/webview/issues/2040#issuecomment-437172257)

I think this is not worth more time investigating right now, due to the time involved to locate and fix these instances.  I am going to move this to content-managers in the backlog.  Thank you very much @wilkus27 and @lwtchu for the investigation on this!

---

@wilkus27 commented on [Tue Nov 13 2018](https://github.com/Connexions/content-managers/issues/464#issuecomment-438281545)

@lwtchu @openstaxalina I noticed that also block equations are aligned with word **Solution**, not with other text and sometimes tokens, which are not in `<p>`, e.g. https://katalyst01.cnx.org/contents/CImQfPDv@3.15:tegV4wXG@5/4-5-Use-the-Slope-Intercept-Form-of-an-Equation-of-a-Line **Example 4.49** 

![block](https://user-images.githubusercontent.com/40228854/48418109-c00ac300-e754-11e8-9d0c-6aa2447e1f61.JPG)

I discussed it with @PiotrKozlowski and his idea is to set that everything without lists shouldn't have margins in os-solution-container. This is how it would look:

![padding](https://user-images.githubusercontent.com/40228854/48418664-26dcac00-e756-11e8-9a52-63be9b2cdcb5.png)

But it will be a global change, so for example it also impact on Introductory Statistics. Now it looks like that: https://katalyst01.cnx.org/contents/MBiUQmmY@23.1:CY4aJuYS@20/1-2-Data-Sampling-and-Variation-in-Data-and-Sampling

![statistics](https://user-images.githubusercontent.com/40228854/48418867-b5e9c400-e756-11e8-842c-74c61679093e.JPG)

<blockquote><div><strong><a href="https://katalyst01.cnx.org/contents/CImQfPDv@3.15:tegV4wXG@5/4-5-Use-the-Slope-Intercept-Form-of-an-Equation-of-a-Line">OpenStax CNX</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://katalyst01.cnx.org/contents/MBiUQmmY@23.1:CY4aJuYS@20/1-2-Data-Sampling-and-Variation-in-Data-and-Sampling">OpenStax CNX</a></strong></div></blockquote>

---

@openstaxalina commented on [Tue Nov 13 2018](https://github.com/Connexions/content-managers/issues/464#issuecomment-438321959)

@wilkus27 and @PiotrKozlowski Thank you!  It would be great to have a technical solution rather than a content solution across many instances.  Let's discuss this on tomorrow's call.

**Comment by wilkus27** [comment]
Verified on katalyst01:

**Elementary Algebra**

![elem_alg](https://user-images.githubusercontent.com/40228854/49649298-00deba80-fa29-11e8-8933-9454450c2e75.JPG)

**Introductory Statistics**

![stat](https://user-images.githubusercontent.com/40228854/49649314-0d631300-fa29-11e8-8c86-f4059dd0fb9c.JPG)
