### ISSUE TITLE
Remove bullet lists from Preface

### ISSUE THREAD

**Issue by wilkus27** [Connexions/webview#2102]
On katalyst01 (https://katalyst01.cnx.org/contents/Sr8Ev5Og@9.4:F_mjYFfh@20/Preface) dots from bullet lists should be removed:

webview:

![dots](https://user-images.githubusercontent.com/40228854/49372462-0cfe0b80-f6fb-11e8-8cb1-314b8f1b964b.JPG)

PDF:

![dots_pdf](https://user-images.githubusercontent.com/40228854/49372484-1f784500-f6fb-11e8-9434-c159cbef85ff.JPG)

**Comment by Adrianltd** [comment]
The first list has in the content `data-bullet-style="bullet"`.
Another one can be fixed in code. Actually that fix will fix both, but `data-bullet-style="bullet"` will remain in the first list, which will be incorrect then and might cause issues in the future.

**Comment by helenemccarron** [comment]
@openstaxalina I think it would be best to change the bullet style in content then make sure the css targets the `data-bullet-style` properly. Currently, @Adrianltd's fix will change all list to not have bullets in recipes. I think that might cause unintended consequences later.

**Comment by openstaxalina** [comment]
Yep, let's avoid that broad of a change.  We can adjust this in content.

**Comment by openstaxalina** [comment]
Issue moved to [Connexions/content-managers #500](https://github.com/Connexions/content-managers/issues/500) via [**ZenHub**](https://www.zenhub.com/)
