### ISSUE TITLE
Grey line in lists on webview 

### ISSUE THREAD

**Issue by uskka** [Connexions/webview#2104]
The grey line on the left is not visable in the PDF and there should be a new empty line between two points on the list like in the PDF. 
https://katalyst01.cnx.org/contents/AgQDEnLI@11.1:JHjddfwj@5/1-4-Why-Study-Sociology

**WebView**
![screenshot-katalyst01 cnx org-2018 12 04-12-39-07](https://user-images.githubusercontent.com/40228918/49440977-78acab00-f7c5-11e8-9755-5910487813f6.png)

**PDF**
![m](https://user-images.githubusercontent.com/40228918/49441065-b1e51b00-f7c5-11e8-845f-9c1c29ae9cb8.png)

**Comment by PiotrKozlowski** [comment]
I can for sure add more space between list items in here but removing grey line is global change for `<blockquote>`. 

There are two ways to create citations: using `<q>` and using `<blockquote>`. Citations created with `<q>` doesn't have a grey line.

@openstaxalina  Please check #2106 and let me know if I should remove grey line globally or just adjust space between list elements in `<q>` and `<blockquote>`

**Comment by openstaxalina** [comment]
Actually, I think that this looks good as-is.  The styling doesn't need to match the PDF exactly.  I like that the grey line adds attention to the fact this is a quote/citation.  I am going to close this issue @PiotrKozlowski @uskka @wilkus27.
