### ISSUE TITLE
Inconsistent way of creating citations

### ISSUE THREAD

**Issue by wilkus27** [Connexions/webview#2106]
There are two ways of creating citation in Psychology:

1) By `<q>` e.g. https://katalyst01.cnx.org/contents/Sr8Ev5Og@9.4:I97J3Te3@11/8-3-Problems-with-Memory

![cit_1](https://user-images.githubusercontent.com/40228854/49450626-b61d3280-f7dd-11e8-81e5-2ce7ff9641d7.JPG)

PDF:

![cit1_pdf](https://user-images.githubusercontent.com/40228854/49450647-bf0e0400-f7dd-11e8-999b-3a062833242a.JPG)

2) By `<blockquote>` e.g. https://katalyst01.cnx.org/contents/Sr8Ev5Og@9.4:sOgJ7A3i@10/13-3-Organizational-Psychology-The-Social-Dimension-of-Work

![cit2](https://user-images.githubusercontent.com/40228854/49450762-04cacc80-f7de-11e8-8e7d-6c9133802122.JPG)

PDF:

![cit2_pdf](https://user-images.githubusercontent.com/40228854/49450779-0c8a7100-f7de-11e8-98c3-b43a4853e3ee.JPG)

As you can see in PDF all citations look the same.

@openstaxalina in which way we want to display citation on webview?

**Comment by wilkus27** [comment]
@openstaxalina I think that solution of issue created by Stefan (https://github.com/Connexions/webview/issues/2104) probably depends on the decision

**Comment by openstaxalina** [comment]
I think that we should use `<blockquote>` as the styling looks better.  I am going to move this to the content-managers repo.

**Comment by openstaxalina** [comment]
Issue moved to [Connexions/content-managers #494](https://github.com/Connexions/content-managers/issues/494) via [**ZenHub**](https://www.zenhub.com/)
