### ISSUE TITLE
Exercises under the number

### ISSUE THREAD

**Issue by brittany-johnson** [Connexions/webview#2115]
@wilkus27 commented on [Thu Nov 15 2018](https://github.com/Connexions/cnx-recipes/issues/714)

The content of the exercises from end of each sections should be displayed next to the number:

katalyst01 (https://katalyst01.cnx.org/contents/CImQfPDv@3.15:zMLdd__D@7/1-1-Introduction-to-Whole-Numbers)

![ex_cont](https://user-images.githubusercontent.com/40228854/48557378-da74a600-e8e6-11e8-94c5-3dbfa0070c6b.JPG)

PDF:

![ex_cont_pdf](https://user-images.githubusercontent.com/40228854/48557391-e95b5880-e8e6-11e8-8b46-239bb5a9f113.JPG)

**Comment by brittany-johnson** [comment]
<img width="668" alt="screen shot 2018-12-06 at 11 39 08 am" src="https://user-images.githubusercontent.com/24909007/49601900-b556de80-f94c-11e8-9d10-3298538f5a1b.png">

**Comment by brittany-johnson** [comment]
@paulinaszczucinska I saw that you moved this to PDM/UX review. Who would you like me to assign to the card to review it?

**Comment by paulinaszczucinska** [comment]
@brittany-johnson Helene, Adrian and Patryk reviewed 2116 PR and now it is in QA testing.

**Comment by uskka** [comment]
Unfortunately the issue still appears on webview, tested on macOS and Windows with Chrome, Firefox and Safari. Screenshot from Katalyst01 ![screenshot-katalyst01 cnx org-2018 12 13-15-02-59](https://user-images.githubusercontent.com/40228918/49943454-359ab800-fee8-11e8-9f06-545b46dbb306.png)

**Comment by brittany-johnson** [comment]
The code was never actually merged to master after review. Sorry about that! @uskka

**Comment by uskka** [comment]
Looks good. Tested on katalyst01. 
![screenshot-katalyst01 cnx org-2018 12 18-12-56-49](https://user-images.githubusercontent.com/40228918/50152624-6867f600-02c4-11e9-8ffb-bc01ec496913.png)
