### ISSUE TITLE
Missing title in Get Connected

### ISSUE THREAD

**Issue by wilkus27** [Connexions/webview#2137]
On katalyst01 (https://katalyst01.cnx.org/contents/W8wOWXNF@18.8:RoFNuV0o@3/3-5-Advantages-and-Disadvantages-of-Federalism) there is a note **Get Connected** without subtitle:

![title](https://user-images.githubusercontent.com/40228854/49943169-7e9e3c80-fee7-11e8-8a2f-f335216b130b.JPG)

PDF:

![title_pdf](https://user-images.githubusercontent.com/40228854/49943177-84941d80-fee7-11e8-9a8d-3286a88f5566.JPG)

This is the only one case in this book.

**Comment by openstaxalina** [comment]
I'm not sure what's going on here.  I compared the HTML on production from a different note to see if these two looked different _before_ baking, too.  They look the same to me.

Left: https://cnx.org/contents/W8wOWXNF@18.12:RoFNuV0o@6/Advantages-and-Disadvantages-of-Federalism
Right: https://cnx.org/contents/W8wOWXNF@18.12:p6XzOSUt@9/Engagement-in-a-Democracy

![getconnectednotesonprod](https://user-images.githubusercontent.com/7863733/50028715-339f2a80-ffb6-11e8-9531-06f7de8382a3.png)

@PatBoj would you be able to look into this?

**Comment by PatBoj** [comment]
@openstaxalina It's because there is a table inside the note. I could look into it deeper and try to fix it via recipe.

**Comment by openstaxalina** [comment]
@PatBoj From my perspective, we do want to support tables inside notes, without an impact to the title on the table. If you could look into supporting this, that would be much-appreciated!  cc @helenemccarron

**Comment by PatBoj** [comment]
I've done nothing and it's fixed now :smile:
https://katalyst01.cnx.org/contents/W8wOWXNF@18.8:RoFNuV0o@3/3-5-Advantages-and-Disadvantages-of-Federalism
@wilkus27 could you confirm and close issue if you decide that the problem is gone?

![image](https://user-images.githubusercontent.com/20907906/50560677-732e7c00-0d03-11e9-8642-9d78ec84979a.png)

**Comment by wilkus27** [comment]
Yes, I confirm. Now it is working:

![title](https://user-images.githubusercontent.com/40228854/50589972-1e1c7280-0e89-11e9-8d0e-d8d435310774.JPG)

**Comment by openstaxalina** [comment]
Confirmed also working correctly in American Government 2e in production webview:

<img width="1281" alt="screen shot 2019-02-13 at 10 55 53 am" src="https://user-images.githubusercontent.com/7863733/52729077-166ae600-2f7e-11e9-8869-a27811b9f922.png">
