### ISSUE TITLE
Empty collections should not be allowed to be published

### ISSUE THREAD

**Issue by omehes** [Connexions/webview#2144]
When I click:
https://staging.cnx.org/contents/fbedafc0-c560-4dbc-90d5-4d54ec1aa63c@1.1

the collection does not load, just spins forever. As per comments from Ross, the collection is empty. 

Empty collections should not be allowed to be published in webview. This is fixed in legacy.

Other related issue is here: https://github.com/Connexions/webview/issues/2143

**Comment by Bkblodget** [comment]
Issue moved to [Connexions/cnx-press #314](https://github.com/Connexions/cnx-press/issues/314) via [**ZenHub**](https://www.zenhub.com/)
