### ISSUE TITLE
Unnumbered table in PDF

### ISSUE THREAD

**Issue by wilkus27** [Connexions/webview#2148]
On katalyst01 (https://katalyst01.cnx.org/contents/AndhM9Sd@4.13:Nq3qcyIB@6/2-4-Solve-Mixture-and-Uniform-Motion-Applications) in **Example 2.47** table in Show Solution has number **2.2**:

![table_webview](https://user-images.githubusercontent.com/40228854/50592601-1e226f80-0e95-11e9-99fa-4d1ca8e48109.JPG)

In PDF this table is unnumbered:

![table_pdf](https://user-images.githubusercontent.com/40228854/50592618-2ed2e580-0e95-11e9-8b48-de3ea5556b91.JPG)

**Comment by PatBoj** [comment]
There is a typo in the table class name. Should be *class=unnu**m**bered* not *class=unnu**n**bered*.

![image](https://user-images.githubusercontent.com/20907906/50594770-2df28180-0e9e-11e9-8b94-9f1bbcd2a792.png)

**Comment by openstaxalina** [comment]
Issue moved to [Connexions/content-managers #512](https://github.com/Connexions/content-managers/issues/512) via [**ZenHub**](https://www.zenhub.com/)
