### ISSUE TITLE
Extra list

### ISSUE THREAD

**Issue by wilkus27** [Connexions/webview#2149]
On katalyst01 (https://katalyst01.cnx.org/contents/yqV9q0HH@13.3:JBQVYZxr@13.3/Key-Concepts) there is an extra list with one item:

![list_web](https://user-images.githubusercontent.com/40228854/50592962-b0774300-0e96-11e9-9327-ca46c23f42af.JPG)

This problem also occurs in PDF:

![list_pdf](https://user-images.githubusercontent.com/40228854/50592982-c38a1300-0e96-11e9-813c-93377506ae8b.JPG)

**Comment by openstaxalina** [comment]
It seems that section summaries are always in list format, even if the list only contains one item.  I am closing this issue.
