### ISSUE TITLE
Two types of lists for one item

### ISSUE THREAD

**Issue by wilkus27** [Connexions/webview#2150]
On katalyst01 (https://katalyst01.cnx.org/contents/yqV9q0HH@13.3:-MajHA0Y@13.3/Answer-Key) there are two types of lists next to each other:

![double_lists](https://user-images.githubusercontent.com/40228854/50593222-c89b9200-0e97-11e9-861d-c8c2841a5643.JPG)

**Comment by PatBoj** [comment]
This is content problem, because those lists do not have `circled` class.

**Comment by openstaxalina** [comment]
Issue moved to [Connexions/content-managers #513](https://github.com/Connexions/content-managers/issues/513) via [**ZenHub**](https://www.zenhub.com/)
