### ISSUE TITLE
test creating pdf of math and non-math books

### ISSUE THREAD

**Issue by omehes** [Connexions/webview#2283]
use baked pdf cli to create collection pdfs of math and non-math books
check the time of mathify process on these types of books
check the size of these types of books
 
books with literally no math: 
Sociology 2e 
U.S. History
Business Ethics
American Government 2e
book with ONE math: Organizational Behavior

**Comment by brittweinstein** [comment]
Issue moved to [openstax/cnx #746](https://github.com/openstax/cnx/issues/746) via [**ZenHub**](https://www.zenhub.com/)
