### ISSUE TITLE
Accounting Appendix

### ISSUE THREAD

**Issue by kswanson33** [Connexions/webview#2307]
It looks like the appendix class is missing in accounting.

![image.png](https://images.zenhubusercontent.com/5fa9a1a6a99686111a824015/f243f022-2a2e-470f-8987-ee103b550d7f)

(Should have `class="appendix"` on the selected div.)

According to #3115, the preface is also missing.

**Comment by lwtchu** [comment]
@kswanson33 did this still need to be added into the content? if it's missing on production, i'll have to get them added in.

**Comment by lwtchu** [comment]
Real card here: https://github.com/openstax/cnx-recipes/issues/3128
