### ISSUE TITLE
Fix Validation error in LLPH

### ISSUE THREAD

**Issue by ne-newton** [Connexions/webview#2316]
CE found a duplicated id in LLPH, which needs to be fixed to move LLPH to RAP for Tutor to use.

`Found 1 duplicate(s) with id='BRI_APUSH_08_03_Draft'`

- [ ] Fix validation error

- [ ] Trigger CORGI job with latest collection version

- [ ] Notify Neil/Bey

**Comment by oscryan** [comment]
Hey, there are only 3 instances of this string in the collection and they all have different functions. one's a Figure ID, one's a link to that figure, and one's the filename of the image the figure displays. This shouldn't be causing a conflict.
