### ISSUE TITLE
Add option to run CORGI jobs on forked book repos.

### ISSUE THREAD

**Issue by ckline-tryptic** [Connexions/webview#2317]
# Story
As a tester, it would be very useful to be able to fork a book repo and run CORGI jobs against it.

# Acceptance Criteria
- [ ] osbook repos are forkable
- [ ] corgi accepts full github repo urls in the Collection ID field

**Comment by m1yag1** [comment]
Existing issue for securing CORGI backend in case we want to edit / add comments: [1172](https://github.com/openstax/cnx/issues/1172)

**Comment by m1yag1** [comment]
Issue moved to [openstax/cnx #1561](https://github.com/openstax/cnx/issues/1561) via [**ZenHub**](https://www.zenhub.com/)
