### ISSUE TITLE
Improve Print CSS

### ISSUE THREAD

**Issue by philschatz** [Connexions/webview#332]
Printing or saving as a PDF contains a lot of text on top of text, whitespace, and unnecessary elements. Below is a module with **0** content at 50% . At 100% it would be 4 pages long.
![connexions - college physics](https://f.cloud.github.com/assets/253202/2056638/ba8095a2-8ae5-11e3-9f7d-307cb4b82231.png)
![connexions - college physics2](https://f.cloud.github.com/assets/253202/2056639/ba83c04c-8ae5-11e3-8b0c-6e89a2e680e0.png)

**Comment by brittweinstein** [comment]
@philschatz can we close this? This is very old and I believe work has been done in other regards to improve this.
