### ISSUE TITLE
Firefox - Preview causes selections to be reset

### ISSUE THREAD

**Issue by edwoodward** [Connexions/webview#563]
If I add an Exercise or Example and select a type other than the default, they return to the default when I preview the Page.  The steps are
 * Edit a Page in a Book
 * Add an Exercise and select Homework from the dropdown.
 * Preview the Page and the Exercise returns the selection to Exercise.

**Comment by amberwebb** [comment]
This happens in Chrome as well, although Example doesn't appear to have a dropdown.
