### ISSUE TITLE
user with only view permission can still edit

### ISSUE THREAD

**Issue by reedstrm** [Connexions/webview#812]
Users with only the view permission, like a new role request, do not get the Aloha editor, but they can still edit the metadata, and they git the 'preview' tool button, which, if toggled, gives them the true preview, but also access to the 'edit' button, and can then get the aloha edit bar loaded (but still not aloha)

Expected result: users w/ just 'view' and not 'edit' get 'Preview' like screen, with no open to switch back to edit.

**Comment by amberwebb** [comment]
This has been fixed. I added a user as an author, logged into that user account, and previewed the content before accepting the role. I did not have access to the edit link and was not able to edit metadata.
