### ISSUE TITLE
Roles - Cannot edit content, but listed as Author and Copyright Holder

### ISSUE THREAD

**Issue by edwoodward** [Connexions/webview#816]
User A created a book and added User B as an author and copyright holder.  User A then added a Page to the Book.  User B accepted the Roles, but cannot edit the Page User A created. When looking at the Metadata on the Page, User B is listed as an Author and Copyright holder, but cannot edit.

The correct solution is to either add User B and allow them to edit, or don't add User B and don't allow them to edit.

**Comment by amberwebb** [comment]
@karenc @reedstrm @edwoodward  This is an authoring issue, not webview.

**Comment by amberwebb** [comment]
@dak Webview is pulling metadata fields from the book if the user does not have access to the page. User A sent role request to User B for author. User B accepted. User A then creates a page but does not add a role for User B. User B cannot edit the page, but is listed as an author in the metadata. See comment from @karenc

**Comment by dak** [comment]
This scenario should no longer be possible due to backend changes.
