### ISSUE TITLE
Editor - Edit dropdown has no effect on text

### ISSUE THREAD

**Issue by edwoodward** [Connexions/webview#837]
I entered text in a Page, selected some text and chose Heading from the edit dropdown and nothing happened.  I tried all of the options and nothing happened. This worked in the past.

**Comment by amberwebb** [comment]
Zendesk is causing this issue, there is no problem with the format plugin. A fix for this is to set the proper CORS settings.

@dak @reedstrm @edwoodward

**Comment by dak** [comment]
@amberwebb As far as I can tell, it appears that Zendesk is listening for a `click` event on a link inside a `dropdown-menu` class.  It appears that this is just a weird coincidental name collision with Zendesk's code (which really should be namespaced to keep it separate and attaching event handlers to only its own DOM elements).

I am seeing a separate error of `Uncaught TypeError: Cannot set property 'innerHTML' of undefined` in aloha, although the changes are still being applied correctly.

I suppose we can either rename the `dropdown-menu` class to something else or add an `event.stopPropagation()` to the click handler in aloha to prevent it from bubbling up to Zendesk, which I suspect may be attaching its listener to the document.

**Comment by amberwebb** [comment]
@dak  That's why I thought there was a conflict with Bootstrap and Zendesk since dropdown-menu is a Bootstrap class name, although conflict isn't probably the best word to describe it. The separate error you are seeing is similar to errors for the other plugins.

I will take another look at this.

**Comment by dak** [comment]
@amberwebb I'm inclined to say it's a bug in Zendesk, although that doesn't help us.  We may have to add `event.stopPropagation()` to Aloha for now with a note attached as to why.

**Comment by amberwebb** [comment]
This is only happening in Chrome.

**Comment by dak** [comment]
Fixed in #860
