### ISSUE TITLE
Successful 'Update' on role-acceptance page when nothing is selected

### ISSUE THREAD

**Issue by pumazi** [Connexions/webview#839]
It's possible to select the 'Update' button within the role-acceptance page without having selected one or more of the roles. The message that is returned in the interface leads one to believe they have successfully accepted their role.

I'd suggest we disable the button when one or more has not been selected. The cues need to be clearer as to what can be selected in this interface.

There may be an issue in authoring, since both authors are in an unknown acceptance state. We'll need to analyze the path taken by @rpcode2014 and @nyxer95.

(CC @edwoodward @rpcode2014  Followup to Connexions/cnx-archive#276 )

**Comment by amberwebb** [comment]
I think this issue is partially fixed now that publish blockers have been added.
