### ISSUE TITLE
Section modal needs styling

### ISSUE THREAD

**Issue by amberwebb** [Connexions/webview#845]
Need bootstrap modal for renaming a section. Currently, when renaming a section user sees a browser popup window.

**Comment by edwoodward** [comment]
To get to the modal, edit a Book, Open Table Of Contents, Select Add..Section. The Section is added to the end of the content. Click the pencil icon to edit the section. This is the modal that needs styling.
![screenshot from 2015-08-07 14 40 09](https://cloud.githubusercontent.com/assets/1394695/9144395/3e15486a-3d12-11e5-8879-7af8d095bc8c.png)

**Comment by RoyEJohnson** [comment]
Do we want to incorporate http://vitalets.github.io/x-editable/demo-bs3.html?c=popup ?

**Comment by edwoodward** [comment]
We have some modals that have styling. They are a part of editing: new 
page, new book, publishing. We should copy that style.

**Comment by RoyEJohnson** [comment]
What I meant to ask was whether a modal dialog is called for when editing a single text field. A modal field (in edit mode, it's a text input, otherwise, it's just text) is less jarring.
