### ISSUE TITLE
Email address missing from author email link

### ISSUE THREAD

**Issue by amberwebb** [Connexions/webview#846]
Click on author name in book or page. Email opens with the book title as the subject, but no email address. 'Mailto' value is missing.

**Comment by dak** [comment]
I'm unable to duplicate this issue.  Looking at `http://localhost:8000/contents/031da8d3-b525-429c-80cf-6c8ed997733a@8.32:1/College_Physics` I'm seeing the following link for both the book and page author: `<a class="list-comma" href="mailto:info@openstaxcollege.org?subject=College%20Physics">OpenStax College</a>`.

@amberwebb Can you provide a link or more details as to where you're seeing this issue?

**Comment by amberwebb** [comment]
This is happening on dev.

http://dev.cnx.org/contents/031da8d3-b525-429c-80cf-6c8ed997733a@8.9:1/College_Physics

**Comment by dak** [comment]
@amberwebb @reedstrm Hmm... it appears that the login server for dev is down.  Are we seeing this error because login/accounts is down on dev?

**Comment by amberwebb** [comment]
@dak @reedstrm I don't think so. If I stop authoring locally, the author's email address is populated in the email, unless I am missing something or need to clear my cache.

**Comment by amberwebb** [comment]
The problem is that the JSON from devarchive.cnx.org is returning 'emails' instead of 'email'. Archive.cnx.org JSON returns 'email'. @pumazi @reedstrm @dak

**Comment by pumazi** [comment]
Use 'emails' (plural). archive.cnx.org is not using the accounts database connection yet. It's still working off the legacy 'persons' table, which only contains a single email address.

**Comment by dak** [comment]
@pumazi authoring is returning:

```json
authors: [{
assignmentDate: "2015-02-11T09:54:50.063955-05:00",
email: "rings@example.com",
firstname: "Test",
fullname: "Test User",
hasAccepted: true,
id: "rings",
requester: "rings",
surname: "User",
type: "cnx-id" }]
```

while archive is returning:
```json
authors: [{
assignmentDate: "2015-02-11T09:54:50.063955-05:00",
emails: ["rings@example.com"],
firstname: "Test",
fullname: "Test User",
hasAccepted: true,
id: "rings",
requester: "rings",
surname: "User",
type: "cnx-id" }]
```

(As Amber noted).  I imagine we still need to support the `email` format from authoring as well, and handling both is a little awkward as it requires going through every `authors` array and doing something like `authors.email = authors.emails[0]` or writing a template helper to do the same.

Would it be easier for archive to do this transform before sending the data?

**Comment by pumazi** [comment]
@dak This is going to change in the near future anyhow. The email will no longer be part of the response in both authoring and archive. This was due to a change in the accounts api, which rightfully no longer exposes the email address.

**Comment by dak** [comment]
@pumazi So you're saying the e-mail won't be exposed to webview at all, so we might as well remove the `mailto` link entirely?

**Comment by pumazi** [comment]
For now, yes.

I imagine we will need to come up with an action that allows a user to email other users, but it will be part of our interface rather than opening the user's email client directly. In other words it will proxy the message through accounts.
