### ISSUE TITLE
Cannot edit math without clicking elsewhere on the page

### ISSUE THREAD

**Issue by amberwebb** [Connexions/webview#849]
Steps to reproduce:

1. Create math in editor.
2. Click math to edit. No math editor.
3. Click anywhere on the page.
4. Click math again. Now the math editor appears.

This is happening in all browsers except for Safari. https://github.com/Connexions/webview/issues/838

**Comment by dak** [comment]
I think this may be an example of the larger issue related to the edit bar/aloha gaining focus of the correct editable element.

**Comment by amberwebb** [comment]
I have found the code for this in the overlay plugin, the Aloha.bind() function. I am reviewing it to make sure there are no problems there. 

But yes, that may be the issue. What would be the best way to test your theory?
