### ISSUE TITLE
Publishing - Cannot publish book, but not given a reason

### ISSUE THREAD

**Issue by edwoodward** [Connexions/webview#858]
I tried to publish a book on demo that contained only one previously published Page.  I got a popup when I clicked publish.

![screenshot from 2015-01-14 08 07 45](https://cloud.githubusercontent.com/assets/1394695/5739979/b7c8cb36-9bc4-11e4-8441-82a6cb6d119d.png)

 The user needs the reason to correct the problem, but I don't think there is a reason to prevent publishing.  The URL is http://demo.cnx.org/contents/484853c4-92a8-468a-ae33-ceee8989b0df@draft:1/Test_Book_1-13

**Comment by reedstrm** [comment]
Pretty sure this was fixed by #866

**Comment by edwoodward** [comment]
I will retest and verify.

**Comment by edwoodward** [comment]
This is fixed on dev.cnx.org
