### ISSUE TITLE
Problem with Save Draft button

### ISSUE THREAD

**Issue by edwoodward** [Connexions/webview#869]
Derek Ford reported

When I edit a page in a book or create a new page in a book the Publish button appears before the Save Draft button. Once I publish, the save draft button appears. 

I will follow up for more information.

**Comment by amberwebb** [comment]
@edwoodward I tested this and do not have this problem. I've asked Derek Ford to retest when he gets a chance. This may have already been fixed.

**Comment by InconceivableVizzini** [comment]
The Save Draft button is appearing first when I create a new page in a book.

When I edit a page the Publish buttons turns into a Save Draft button as soon as I edit the content.

Seems to be resolved.
