### ISSUE TITLE
Publishing - Could not get serveral Pages to Publish

### ISSUE THREAD

**Issue by edwoodward** [Connexions/webview#871]
Alina Slavik reported

Could not get content to publish after editing multiple pages.  (Publish worked when I had only edited one page.)

I will verify that she was trying to edit a Book.

**Comment by reedstrm** [comment]
piblsihing shows two instances of:

**Comment by amberwebb** [comment]
@edwoodward Do we know what content she had problems with?

**Comment by edwoodward** [comment]
I do not and it is probably long gone.  I am closing this since we are not seeing it.
