### ISSUE TITLE
How do I add a link to another page in my book?

### ISSUE THREAD

**Issue by pumazi** [Connexions/webview#873]
I expected to be able to click the link UI button to add a link to an internal page. No such internal link interface exists.

My next best option was to copy and paste (c&p) the link. But this only works if you have previously published the content or know to remove the 'draft' version indicator from the url. (possibly needs work elsewhere)

I don't mind the c&p procedure, webview will need to rewrite the url into a **version agnostic url** or **use the draft** (may need work in cnx-publishing) or **pin to a specific version**.

Also, any urls that point to _a page within a book_ should use the `/contents/{ident-hash}:{ident-hash}/{name}` syntax rather than the `/contents/{ident-hash}:{page-num}/{name}`syntax.

**Comment by amberwebb** [comment]
Per the DMAs - also need the ability to link to part of another page.

**Comment by pumazi** [comment]
What's a DMA?

**Comment by amberwebb** [comment]
Digital media assistant.
