### ISSUE TITLE
Editor - Image not removed on publish

### ISSUE THREAD

**Issue by edwoodward** [Connexions/webview#876]
This was reported by more than one team tester

Edit a Page by adding an image, remove the image and publish.  The image is still in the published content.

**Comment by reedstrm** [comment]
This does not involve publish - images cannot be deleted at all. Save, reload from workspace, image returns.

**Comment by edwoodward** [comment]
This problem exists for all blockish draggable items in the editor,

**Comment by amberwebb** [comment]
@dak This is definitely because of blur
