### ISSUE TITLE
Version part of URL is duplicated in Attribution area

### ISSUE THREAD

**Issue by philschatz** [Connexions/webview#879]
for both Book and Page. It seems one of those images will be used in the 10th Anniversary edition of http://www.amazon.com/Taking-Charge-Fertility-Anniversary-Edition/dp/0060881909 (# 1 Best Seller in Women's Sexual Health)

<http://cnx.org/contents/185cbf87-c72e-48f5-b51e-f14f21b5eabd@9.17:229/Biology>

![image](https://cloud.githubusercontent.com/assets/253202/5884031/0fb59a46-a326-11e4-9e29-2b9794b0e942.png)

**Comment by amberwebb** [comment]
This was fixed. https://github.com/Connexions/webview/issues/702
