### ISSUE TITLE
TOC does not open when editing a new Book

### ISSUE THREAD

**Issue by edwoodward** [Connexions/webview#894]
This worked yesterday so it is a regression. A new book opens in the Editor, but does not open the TOC.

**Comment by amberwebb** [comment]
@edwoodward  Are you testing on dev? I cannot login to accounts on dev for some reason so I can't test there. I get a blank screen. But testing locally with the latest merges, the TOC is open when I create a new book and the Add button is visible.

**Comment by dak** [comment]
This is working for me locally as well.  Is it possible some changes haven't been deployed to dev yet?

**Comment by reedstrm** [comment]
it happens if you use a book totle with spaces (or at least, just did for me)

**Comment by edwoodward** [comment]
Not sure what you mean by "it happens". Does the TOC open or not open? I 
created a book titled "Test Book 1-29" and it does not open.

**Comment by reedstrm** [comment]
Sorry about the imprecise pronoun the bug (failure of toc to open) happens when there's spaces in the title. This has to do w/ the title being rewritten w/ underscores, and the tab= part of the url being lost.
