### ISSUE TITLE
Metadata - Add drop down for selecting Print Style

### ISSUE THREAD

**Issue by edwoodward** [Connexions/webview#909]
We need to add a dropdown for selecting print styles for OSC books.  It should be on the metadata page. Values are:

Latex (the default)
CCAP Physics
CCAP Sociology
CCAP Biology
CCAP Anatomy
CCAP Statistics
CCAP Precalculus
CCAP Psychology
CCAP Economics
CCAP History
CCAP Chemistry

**Comment by dak** [comment]
Saved on the `printStyle` property.
