### ISSUE TITLE
Search - Add the same content multiple times

### ISSUE THREAD

**Issue by pumazi** [Connexions/webview#913]
@edwoodward wrote "On demo, I added an already published Page to a Book. I then tried to add the same Page again to the same Book and was able to. Search should block content already in a Book from the search results."

Copied from Connexions/cnx-authoring#180. See the notes in the comments. This filtering apparently needs to happen in webview, because authoring can't filter the search that is coming from archive.

**Comment by amberwebb** [comment]
A problem I see with filtering in webview is that webview doesn't know what pages have been added to the book until the user saves.

**Comment by pumazi** [comment]
I talked this over with @amberwebb. It appears that the table-of-contents (aka the tree data structure) is only available on save. I'm guessing we'll need to change the add a page item to the table-of-contents event to also insert into the tree. We then use the tree to filter the (archive) search results.
