### ISSUE TITLE
Get This Book download list wrapping

### ISSUE THREAD

**Issue by edwoodward** [Connexions/webview#918]
The list of options to download is wrapping.  Offline ZIp is on a second line which does not look good. Either the font needs to be smaller or the box enlarged slightly.

Screenshot
![screenshot from 2015-02-23 09 00 45](https://cloud.githubusercontent.com/assets/1394695/6330000/7fe244b4-bb3a-11e4-975a-f50cd97c36a4.png)

**Comment by amberwebb** [comment]
@edwoodward I don't see this. Checked in FF, Chrome and Safari.

![image](https://cloud.githubusercontent.com/assets/8335640/6334896/32946f3e-bb5d-11e4-9755-99eb04bd0f69.png)
