### ISSUE TITLE
Incorrect labeling used on Note and possibly others

### ISSUE THREAD

**Issue by pumazi** [Connexions/webview#919]
I'm noticing that `@class='title'` is being used when adding a title to a **Note**. The correct label to put on this should be `@data-type='title'`.

I have a feeling it is happening for other blockish components as well.

**Comment by pumazi** [comment]
This:
```
<div class="note">
  <span class="title">Optional title on note</span>
  <p>Hiya.</p>
</div>
```
...should be:
```
<div data-type="note">
  <span data-type="title">Optional title on note</span>
  <p>Hiya.</p>
</div>
```

**Comment by pumazi** [comment]
I'm also noticing that ``@class='note'`` is incorrect. It should be using ``@data-type='note'``.

**Comment by amberwebb** [comment]
@pumazi Is this still a bug?

**Comment by pumazi** [comment]
Yes. See a recently published example at http://devarchive.cnx.org/contents/bb5370a9-10e7-4ca0-8fe1-a9115f3320a0@2.json This contains both an example and a note. Both elements use class, when they should be using data-type.

**Comment by dak** [comment]
Titles are being added by [note.coffee](https://github.com/oerpub/Aloha-Editor/blob/d97ad37ecdeda5c7a15ff02bd00ea492cc19b08a/src/plugins/oer/note/lib/note-plugin.coffee#L192) as classes.  It looks like part of the issue *may* be fixable with changes to 4-5 lines of code in that plugin.

**Comment by RoyEJohnson** [comment]
Is this the same problem?
/webview/src/scripts/modules/media/editbar/editbar-template.html
