### ISSUE TITLE
Publishing - Derived Page in Derived Book is listed in Workspace

### ISSUE THREAD

**Issue by edwoodward** [Connexions/webview#923]
On beta, I derived a copy of "Understanding Basic Music Theory". I then derived the first Page and added some text.  I published the Book and it was successful.  However, the derived Page is now listed in my Workspace as if I deleted the Book without publishing. I'm not sure where the problem is so I'm placing this here as a starting point.

**Comment by amberwebb** [comment]
@edwoodward  I cannot reproduce this. I followed the steps and My derived page is not in my workspace. Maybe this was already fixed. Can you please test again?

**Comment by amberwebb** [comment]
@edwoodward  Have you been able to test this again?

**Comment by amberwebb** [comment]
I have tested this issue on dev with the latest code and bug fixes. This seems to no longer be an issue.
