### ISSUE TITLE
Zendesk - Submit button not working

### ISSUE THREAD

**Issue by edwoodward** [Connexions/webview#935]
If you open the Zendesk widget (Ask Us button), enter a question and hit Enter, the Zendesk search happens as expected.  if you click the Submit button instead of hitting Enter, the search fails. I was able to reproduce this on dev and production.

**Comment by amberwebb** [comment]
@edwoodward Consulted @dak about the Zendesk form. We do not have control over it. The submit button is submitting the form and not the search. It is not ideal and not very user friendly

**Comment by edwoodward** [comment]
I'll check Zendesk to see if they have an issue for this.

**Comment by edwoodward** [comment]
Went to Zendesk and reconfigured the "Feedback tab" The code is below.  
You will need to compare with what we have and modify so we do not lose 
the styling of the button.

<script type="text/javascript" 
src="//assets.zendesk.com/external/zenbox/v2.6/zenbox.js"></script>
<style type="text/css" media="screen, projection">
   @import url(//assets.zendesk.com/external/zenbox/v2.6/zenbox.css);
</style>
<script type="text/javascript">
   if (typeof(Zenbox) !== "undefined") {
     Zenbox.init({
       dropboxID:   "20194334",
       url:         "https://openstaxcnx.zendesk.com",
       tabTooltip:  "Support",
       tabImageURL: 
"https://p2.zdassets.com/external/zenbox/images/tab_support.png",
       tabColor:    "black",
       tabPosition: "Left"
     });
   }
</script>
