### ISSUE TITLE
Precalculus WebView => General Note label is duplicated on new web view

### ISSUE THREAD

**Issue by nyxer95** [Connexions/webview#937]
As far as I know, this issue is limited to Precal and Precal-derived forthcoming titles (CAT, etc.)

![precalgeneralnote](https://cloud.githubusercontent.com/assets/7863733/5882223/193a936e-a30d-11e4-9fab-9696fe9a9518.png)

Here's the CNXML for the above screenshot:
![screen shot 2015-01-23 at 2 38 28 pm](https://cloud.githubusercontent.com/assets/7863733/5882273/899fd7d6-a30d-11e4-86f9-02d0804bc75d.png)

This issue appears to be specific to the new site.

(Derek Ford may need to provide more detail here.)

**Comment by nyxer95** [comment]
Below is a "How To" note, which does not have any duplication.  Please note, the How To HAS a class and does NOT have a title.  This may provide a clue.

![screen shot 2015-01-27 at 10 15 37 am](https://cloud.githubusercontent.com/assets/7863733/5921981/9ae3399a-a60d-11e4-9d0e-b56e38723ef2.png)
![screen shot 2015-01-27 at 10 16 32 am](https://cloud.githubusercontent.com/assets/7863733/5921986/9f084ec0-a60d-11e4-9044-2ebeeecfdc2b.png)

**Comment by nyxer95** [comment]
For more information, contact Alina Slavik.

**Comment by edwoodward** [comment]
I believe adding a title will force the word Note to show up.

**Comment by edwoodward** [comment]
This has been fixed and released to production
