### ISSUE TITLE
Psychology: Link to Learning features do not open in new window

### ISSUE THREAD

**Issue by nyxer95** [Connexions/webview#938]
The links in "Link to Learning" features do not open in a new window.  This appears to be global on all delivered chapters (and almost definitely exists on as-yet-undelivered chapters, too).

In other books, these features have the code [link window=“new”].

This problem only impacts webview and still exists in the updated module on naginata:

http://naginata.cnx.rice.edu:9999/content/m10087/latest/?collection=col10018/latest

It may be an issue with the code on Naginata; Derek and Alina had a conversation about default settings on the various servers a while back.  He may be a good resource in verifying whether this will be an issue on Production.

**Comment by nyxer95** [comment]
This issue was reported by Alina Slavik in oer.exports:

https://github.com/Connexions/oer.exports/issues/641

**Comment by edwoodward** [comment]
Is this a new requirement?  Does it open in another window in other books?

**Comment by amberwebb** [comment]
@nyxer95 Can this be closed in webview?

**Comment by amberwebb** [comment]
@nyxer95 @edwoodward Where can I find this in webview?

**Comment by edwoodward** [comment]
It is at 
http://cnx.org/contents/b5e7f2ec-4e9c-467d-82cc-e0a5f8a35487@5/What_Is_Consciousness?

**Comment by amberwebb** [comment]
@edwoodward @nyxer95 I've tested this module on beta. The Link to Learning features open in a new window.

**Comment by edwoodward** [comment]
But it fails on production?

**Comment by amberwebb** [comment]
@edwoodward Sorry I meant production
