### ISSUE TITLE
Incorrect user login

### ISSUE THREAD

**Issue by rich-hart** [Connexions/webview#955]
In beta.cnx.org, webview will automatically sign in under the wrong user name without a password.  For example, when visiting beta.cnx.org my browser will automatically sign into 'amwebb' without any prompt.   
![wrong_login](https://cloud.githubusercontent.com/assets/2857670/6628708/c99eedac-c8d5-11e4-92ad-232a50610e92.png)

@reedstrm suggests that this is a problem of incorrectly caching with varnish. Note: clearing my browser cache removes the 'amwebb' login.  This issue was first reported in Connexions/rhaptos.cnxmlutils/issues/120

**Comment by reedstrm** [comment]
likely a caching issue just presenting the page. Not sure anyone actually tried say the workspace link to see if you got Amber's stuff.

**Comment by amberwebb** [comment]
@reedstrm I believe @karenc said she could see my workspace

**Comment by rich-hart** [comment]
I could access amber's content as well

**Comment by pumazi** [comment]
This is a devops issue, not webview. But it's here now...

I'll throw my question here, since I hadn't heard a response:
```
13:42:58 pumazi : It's likely that the resource is cached with the session info in the response.
...
13:56:42 pumazi : reedstrm: Is it possible for nginx to append a header (maybe something like x-no-cache) when falling back to a protected app?
13:57:52 pumazi : Just trying to figure this out now, rather than implement this cascading /contents/ only to find that we have auth leaks like the one karen just experienced.
```

The idea with the ``x-no-cache`` is to have the caching server see it and ignore it. But there is likely a few ways to achieve the same thing.

**Comment by amberwebb** [comment]
Closing this as a webview issue.

**Comment by reedstrm** [comment]
We need a header to tell varnish not to cache pages that  are authenticated. Ideally, the app itself should add them, making this an authoring issue.
