### ISSUE TITLE
Cannot publish new module with images on dev or beta

### ISSUE THREAD

**Issue by amberwebb** [Connexions/webview#957]
1. Create new page
2. Add image
3. Publish.

This is referring to the page itself:
![image](https://cloud.githubusercontent.com/assets/8335640/6644225/39565d92-c980-11e4-81bb-241b0619cf52.png)

**Comment by reedstrm** [comment]
Agree w/ Michael (as per scrum discussion) that this is an authoring issue, but only for the working: we don't want to publish pages with no textual content at all.

**Comment by pumazi** [comment]
The code that does the content validation can be found here: https://github.com/Connexions/cnx-authoring/blob/b9fab724d549603e8c52b41841273c3a60461487/cnxauthoring/utils.py#L662
As you can see, the xpath is written as ``/html/body//text()``. So even if this image had a caption text (which I believe is an attribute value???) it would still be considered empty.

**Comment by amberwebb** [comment]
Closing this as a bug in webview
