### ISSUE TITLE
Editor - math editing does not work in Firefox

### ISSUE THREAD

**Issue by edwoodward** [Connexions/webview#973]
I created a Page and tried to add math using the editor.  I entered the following Latex

\sqrt{36} + x^3 = y^2

The math was not displayed and did not appear as empty in the editor.

The same edit worked correctly in Chrome.

**Comment by amberwebb** [comment]
@edwoodward I entered the same math and it displayed in FF.

http://dev.cnx.org/contents/2b98e03e-06e2-4f79-8656-3bcfa04da6ba/math_test

Am I not testing this correctly?

**Comment by edwoodward** [comment]
I'm on Firefox 36.0.1 on Ubuntu.  I'll test again on my Mac when I test 
safari.  Could be a Linux issue.

**Comment by edwoodward** [comment]
I tested again on Ubuntu by adding a Page to a Book, adding math, saving and reopening the book.  The math is there and the display blinks the math briefly. When I clicked where the math is I got this popup:

![screenshot from 2015-03-19 14 30 32](https://cloud.githubusercontent.com/assets/1394695/6739106/8f8c0cd4-ce44-11e4-900a-0cef6fbdf4a2.png)

The MathML option does not display when you first enter the math.

**Comment by amberwebb** [comment]
@dak @reedstrm @dak  There is MathML in the DOM. Look at the screenshot. Only the xmlns is showing only once. I do not know much about LaTex or MathML. If I entered math as LaTex like Ed's example, should MathML be in the DOM?

![image](https://cloud.githubusercontent.com/assets/8335640/6815077/5596305a-d253-11e4-8773-fd3411c816e1.png)

**Comment by reedstrm** [comment]
Yup, that looks correct. If you expand the mrow, the rest of the MathML is hidden in there. Once we save it to the database (authoring)  all the tags below <math> get decorated w/ the namespace, and <math> itself gets doubled.

**Comment by dak** [comment]
@reedstrm Are you saying the backend is doing the doubling?

**Comment by dak** [comment]
Note: Issue reportedly occurred when Ed was added as an author to a piece of content.  The content had been edited and published previously, then derived and added more math and that's when the issue occurred.

**Comment by amberwebb** [comment]
@edwoodward Please test this again. This may have been fixed.

**Comment by edwoodward** [comment]
Tested this on dev. It is working
