### ISSUE TITLE
Logging out of Accounts does not log you out of CNX

### ISSUE THREAD

**Issue by edwoodward** [Connexions/webview#975]
I logged into dev.cnx.org, went to Accounts to edit my profile and logged out on the Accounts screen. I then used the browser back button to get back to the Book I was editing.  I edited it some more and published it while logged out of accounts. I'm not sure if this is a really bad thing since I had to know my id and password to log in the first time, but it is not the expected behavior.

**Comment by pumazi** [comment]
I don't think this is a bug. I believe you are conceptualizing accounts as a single signon service, rather than an oauth provider that happens to provide authentication facilities for us.

**Comment by edwoodward** [comment]
I'm not sure it is a bug either, but I wanted to document it since it is 
not the expected behavior.  What you describe makes sense to us 
developers, but will it make sense to a user?  The likelihood of them 
logging out of accounts in very small, so probably not an issue.
