### ISSUE TITLE
Role Acceptance - link in workspace displays empty page

### ISSUE THREAD

**Issue by edwoodward** [Connexions/webview#976]
I was not receiving emails from qa accounts, so I logged in as my user and clicked on the content's awaiting acceptance link and was shown this page
![screenshot from 2015-03-19 15 14 37](https://cloud.githubusercontent.com/assets/1394695/6739989/b48c22a2-ce4a-11e4-9328-63e26fdbbde3.png)

No errors on the page in dev tools.

**Comment by amberwebb** [comment]
@edwoodward I got the same blank page on dev. Thought maybe there was a problem with the json returned, but I checked locally and I can see the role requests. Not sure why this is happening on dev.

**Comment by amberwebb** [comment]
@dak @edwoodward @reedstrm 

Possibly an nginx problem. From sprint chat:

I'm seeing an html response for the request at /contents/{ident_hash}/acceptance
7:50 Are you seeing the same?
7:51 If that's the case, I can limit it to an nginx issue?

**Comment by pumazi** [comment]
I'm guessing something like the following would work:

```
  location ~ ^/contents/.*@draft\.json {
      proxy_pass http://localhost:8900;
  }

  location ~ ^/contents/.*@draft/users/me {
      proxy_pass http://localhost:8900;
  }

  location ~ ^/contents/.*@draft/acceptance {
      proxy_pass http://localhost:8900;
  }
```
OR (maybe greedy?):
```
  location ~ ^/contents/.*@draft.* {
      proxy_pass http://localhost:8900;
  }
```

**Comment by edwoodward** [comment]
This is working now on dev.  Closing.
