### ISSUE TITLE
Editor - user needs to be able to edit type attribute

### ISSUE THREAD

**Issue by edwoodward** [Connexions/webview#978]
The Biology OSC book uses the type attribute on Notes that are Art Connection features.  We need to at least add editing of type to Notes.  It should work in the same way that the class attribute editor works.

Tagging Legand for Biology: https://rice.box.com/s/2m8ysm0mg3a5bvzwu55djfqw0myxc4sf

Example of Note using type in Biology: http://legacy.cnx.org/content/m44418/latest/

Screenshot of CNXML with type.
![screen shot 2015-03-11 at 4 59 30 pm](https://cloud.githubusercontent.com/assets/1394695/6750678/d6684e66-ceca-11e4-9cb4-50c0f1054601.png)

**Comment by edwoodward** [comment]
Editing exists and it is retrieved when you save the type and reopen the editor.  However, if you return to the workspace, reopen the Page, reopen the type editor, the type you saved is not displayed.

**Comment by amberwebb** [comment]
The custom type attribute is working as expected, but the problem seems to be with triggering a change event on the semantic block plugin without making a change inside the plugin or directly to the editor. Looking for a solution to this.
