### ISSUE TITLE
Publishing - As an added author, the publish button won't work for me

### ISSUE THREAD

**Issue by pumazi** [Connexions/webview#982]
As an author added to the content by the content creator, the publish button is visible (blue) and allows me to fill in the publishing modal, but never publishes.

### Recreate
1. Create a page as 'billy'.
2. Add 'grim' to the authors list.
3. Sign out
4. Sign in as 'grim'
5. Accept the author role.
6. Click the publish button on the page.

### Issue
'grim' was never given permission to publish. So I'm not sure why, as 'grim', I have the ability to click the button.

I experienced this locally and have not tried to reproduce it on dev or beta.

**Comment by amberwebb** [comment]
@pumazi add me as an author on dev

**Comment by pumazi** [comment]
I added 'amberwebb' hopefully that's the correct one.

**Comment by amberwebb** [comment]
@pumazi Can you add amwebb? I cannot login with amberwebb on dev.

**Comment by amberwebb** [comment]
@pumazi Followed steps got error message in console. http://dev.cnx.org/publish 403 Forbidden

**Comment by pumazi** [comment]
Right, I'm seeing the 403 as well. I don't get anything in the UI telling me this didn't work or that I'm not allowed to do this action.

**Comment by amberwebb** [comment]
http://dev.cnx.org/contents/4ae7d91c-bf89-4a32-a1f0-c0f8fdfa52d6@draft/acceptance Should have amwebb as an author but it doesn't.

**Comment by amberwebb** [comment]
I only have edit and view permissions on that content.

**Comment by pumazi** [comment]
Indeed. You should have permission to publish as an author. Ok, that means this is an authoring issue.

**Comment by edwoodward** [comment]
Moved to https://github.com/Connexions/cnx-authoring/issues/216
