### ISSUE TITLE
Editor - adding an image causes editor to disappear

### ISSUE THREAD

**Issue by edwoodward** [Connexions/webview#983]
On dev.cnx.org, I added an image to a new page.  I filled out the alt text and clicked next. The yellow background of the editor went away when the image was added to the page and I could not click save, only cancel on the image popup.

If I select Preview and then back to edit, the editor returns, but the image has been removed. I'm hoping this is an install issue.

http://dev.cnx.org/contents/6979f63b-a2f1-4a0f-b7c0-ee97dc98bccf@draft/Test_3-22

**Comment by edwoodward** [comment]
FYI, there is no network error in dev tools when this happens.

**Comment by amberwebb** [comment]
@edwoodward I'm looking into this.

**Comment by amberwebb** [comment]
I can reproduce this on dev, but not on local. Going to dig into this further.

**Comment by amberwebb** [comment]
@edwoodward  So this was an installation part on my end when testing locally. I did not update Aloha correctly on my localhost. I made changes to the figure plugin to fix the duplicate text issue, but was not testing the correct version of Aloha. I have found the error in my code and have fixed it. I am testing it now.

**Comment by edwoodward** [comment]
This is fixed on dev.
